(mes
 (meta (engine 'ADV) (charset "english") (extraop #t))
 (seg*
  (if (</>
       (//
        (? (= K 1))
        ((cmd 209) 0 5)
        (image-file "gpc¥waku.gpc")
        (image-mem 0 3)
        ((cmd 209) 1 5)
        (nop@)
        (set-var K 0))
       (// (nop@))))
  (branch-reg 56 (</> (/) (/ (mes-jump "mes¥ma_a03.mes"))))
  (exec-mem 14080 2 24 4 135 71 80 34 80 34 0 30)
  (image-file "gpc¥b13_01.gpc")
  (image-mem 0 3)
  (proc 3)
  (if (</>
       (//
        (? (= P 5))
        (nop@))
       (//
        (if (</>
             (//
              (? (= O 0))
              (sound '|| 0)
              (sound '|| "uso¥xg_05.uso")
              (sound '|| 1)
              (nop@)
              (set-var P 5))
             (//
              (? (= O 1))
              (sound '|| 0)
              (sound '|| "uso¥xg_05v.uso")
              (sound '|| 1)
              (nop@)
              (set-var P 5)))))
       (// (nop@))))
  (load-mem "clm¥b13_01.clm" 32768)
  (text-frame 10 312 70 383)
  (text-delay 2)
  (if (</>
       (//
        (? (= 900 #t))
        (text "I'm back at my room again. The air here is stale...... I'd   rather wander the city than stay in a place like this.")
        (wait)
        (text-reset 14))
       (//
        (? (= 900 #f))
		(text "I'm back in my room at Intelligence. Even though I got" 'br)
		(text "information about the two fugitives at Ichigaya, I still" 'br)
		(text "haven't been able to capture a single prisoner.")
        (wait)
        (text-reset 14)
        (text "Not that I can be blamed for that, but it's really getting" 'br)
		(text "under my skin.")
        (wait)
        (text-reset 14))))
  (nop@)
  (set-reg 900 #t)
  (exec-mem 3968 102 500 360)
  (exec-mem 3072 1)
  (loop (set-var S 0) (exec-mem 3072 1020 1021 "S" 32768) (seg-call)))
 (seg (? (= 1020 #f) (= 1021 #f)) (exec-mem 3072 1))
 (seg (? (= 1021 #t))
   (nop@)
   (set-var K 0)
   (exec-mem 3072 0)
   (exec-mem 3968 103)
   (exec-mem 256 "A 0 S 0")
   (exec-mem 256 "G 1 4 64 12 48")
   (exec-mem 4768 4 8 12 6 1 0 0 4480 4480 1 0)
   (menu1 5 72 5 88 (</> (/ (text "   Save   ")) (/ (str "  Travel  "))))
   (if (</>
        (//
         (? (= S 0))
         (exec-mem 256 "A 0 S 0")
         (exec-mem 256 "G 9 5 72 16 96")
         (exec-mem 4768 5 9 16 12 1 0 0 4480 4480 1 0)
         (menu1
          6
          80
          6
          96
          6
          112
          6
          128
          6
          144
          (</>
           (/ (text "    File 1    "))
           (/ (text "    File 2    "))
           (/ (text "    File 3    "))
           (/ (text "    File 4    "))
           (/ (text "    File 5    "))
           (/)))
         (exec-mem 256 "P 9 5 72")
         (exec-mem 256 "P 1 4 64")
         (nop@)
         (set-var J P)
         (nop@)
         (set-var P 0)
         (if (</>
              (//
               (? (= S 0))
               (nop@)
               (set-var K 1)
               (flag-save 0)
               (nop@)
               (set-var K 0)
               (text "Successfully saved to File 1.")
               (wait)
               (text-reset 14))
              (//
               (? (= S 1))
               (nop@)
               (set-var K 1)
               (flag-save 1)
               (nop@)
               (set-var K 0)
               (text "Successfully saved to File 2.")
               (wait)
               (text-reset 14))
              (//
               (? (= S 2))
               (nop@)
               (set-var K 1)
               (flag-save 2)
               (nop@)
               (set-var K 0)
               (text "Successfully saved to File 3.")
               (wait)
               (text-reset 14))
              (//
               (? (= S 3))
               (nop@)
               (set-var K 1)
               (flag-save 3)
               (nop@)
               (set-var K 0)
               (text "Successfully saved to File 4.")
               (wait)
               (text-reset 14))
              (//
               (? (= S 4))
               (nop@)
               (set-var K 1)
               (flag-save 4)
               (nop@)
               (set-var K 0)
               (text "Successfully saved to File 5.")
               (wait)
               (text-reset 14))
              (// (? (= S 255)))))
         (nop@)
         (set-var P J))
        (//
         (? (= S 1))
         (exec-mem 256 "A 0 S 0")
         (exec-mem 256 "G 9 5 72 22 64")
         (exec-mem 4768 5 9 22 8 1 0 0 4480 4480 1 0)
         (menu1
          6
          80
          6
          96
          6
          112
          (</>
           (/ (text "   Anna's Office   "))
           (/ (text "    Anna's Room    "))
           (/ (text "      Outside      "))
           (/)))
         (exec-mem 256 "P 9 5 72")
         (exec-mem 256 "P 1 4 64")
         (if (</>
              (//
               (? (= S 0))
               (branch-reg
                55
                (</>
                 (/ (mes-jump "mes¥MA_B02.MES"))
                 (/ (mes-jump "mes¥MA_B03.MES")))))
              (// (? (= S 1)) (mes-jump "mes¥MA_C02.MES"))
              (//
               (? (= S 2))
               (branch-reg
                55
                (</>
                 (/ (mes-jump "mes¥MB_A01.MES"))
                 (/ (nop@) (set-reg 56 #t) (mes-jump "mes¥MB_A02.MES")))))
              (// (? (= S 255))))))
        (// (? (= S 255)) (exec-mem 256 "P 1 4 64"))))
   (exec-mem 3968 104)
   (exec-mem 3072 2)
   (exec-mem 3072 1))
 (seg (? (= S 1) (= 288 #f))
   (proc 0)
   (text "This room has desks and chairs to keep up appearances, but" 'br)
   (text "I barely ever use them.")
   (wait)
   (text-reset 14)
   (text "I never really had a reason to. Desk work doesn't suit me," 'br)
   (text "and I hardly consider it my job.")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 288 #t)
   (proc 1))
 (seg (? (= S 1) (= 289 #f))
   (proc 0)
   (text "My room differs somewhat from what a typical Intelligence" 'br)
   (text "member has.")
   (wait)
   (text-reset 14)
   (text "While desks and chairs are essential for most agents, to me" 'br)
   (text "they're just a space-wasting obstacle. I use the bed far" 'br)
   (text "more often.")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 289 #t)
   (proc 1))
 (seg (? (= S 1) (= 289 #t))
   (proc 0)
   (text "This room has desks and chairs to keep up appearances, but" 'br)
   (text "I barely ever use them.")
   (wait)
   (text-reset 14)
   (proc 1))
 (seg (? (= S 2) (= 290 #f))
   (proc 0)
   (text "The shelves are filled with tools used to torture prisoners. Whips, vibrators, enemas, and even more exotic things...")
   (wait)
   (text-reset 14)
   (text "The only reason they keep me in Intelligence is because" 'br)
   (text "I can use these tools better than anyone else.")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 290 #t)
   (proc 1))
 (seg (? (= S 2) (= 291 #f))
   (proc 0)
   (text "It contains various torture implements. Every one personally" 'br)
   (text "selected by me to inflict maximum pain and humiliation on" 'br)
   (text "my subjects.")
   (wait)
   (text-reset 14)
   (text "But without any prisoners to use them on, they're pointless." 'br)
   (text "I'll have to finish this pain-in-the-ass mission before I can")
   (text "have any fun.")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 291 #t)
   (proc 1))
 (seg (? (= S 2) (= 291 #t))
   (proc 0)
   (text "I don't need to open this until I catch one of the" 'br)
  (text "prisoners.")
   (wait)
   (text-reset 14)
   (proc 1))
 (seg (? (= S 3) (= 292 #f))
   (proc 0)
   (text "Outside the window is a small park. This Intelligence office" 'br)
   (text "is in the true city center - the waste of land here is often" 'br)
   (text "criticized.")
   (wait)
   (text-reset 14)
   (text "This area used to be a military garrison, apparently. Before" 'br)
   (text "the large base at Ichigaya was built, this was responsible" 'br)
   (text "for the capital's security.")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 292 #t)
   (proc 1))
 (seg (? (= S 3) (= 293 #f))
   (proc 0)
   (text "Outside the window is a war memorial. The pillar stands at" 'br)
   (text "least three stories tall, covered in the names of soldiers" 'br)
   (text "who've died for our nation.")
   (wait)
   (text-reset 14)
   (text "The tower has gotten larger and fuller since I last saw it." 'br)
   (text "It's amazing how much the view has changed after just a" 'br)
   (text "couple months of not using this room.")
   (wait)
   (text-reset 14)
   (text "It's clear evidence this country won't last much longer. No" 'br)
   (text "wonder crime is increasing and order breaking down. Everyone" 'br)
   (text "has given up on the future......")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 293 #t)
   (proc 1))
 (seg (? (= S 3) (= 293 #t))
   (proc 0)
   (text "Outside the window is a small park. This Intelligence office" 'br)
   (text "is in the true city center - the waste of land here is often" 'br)
   (text "criticized.")
   (wait)
   (text-reset 14)
   (proc 1))
 (seg (? (= S 4) (= 253 #f) (= 287 #t))
   (proc 0)
   (text "That woman I met at Akihabara's black market - Colonel Karl" 'br)
   (text "said she was April's friend.")
   (wait)
   (text-reset 14)
   (text "But how can I be sure she wasn't April herself? I don't even" 'br)
   (text "know what the escaped prisoners look like.")
   (wait)
   (text-reset 14)
   (text "Even if I found April and Lei-Fa, what could I do" 'br)
   (text "about it......")
   (wait)
   (text-reset 14)
   (proc 1))
 (seg (? (= S 4) (= 253 #t) (= 287 #f))
   (proc 0)
   (text "I searched Chinatown like Colonel Karl suggested, but" 'br)
   (text "couldn't find Lei-Fa......")
   (wait)
   (text-reset 14)
   (text "That district has countless places to hide, and even if I was" 'br)
   (text "in the same room as her, she'd probably spot me first.")
   (wait)
   (text-reset 14)
   (text "She's ex-Special Forces - far stronger than me, and killing" 'br)
   (text "is second nature to her. I need to figure out how to" 'br)
   (text "beat Lei-Fa.")
   (wait)
   (text-reset 14)
   (proc 1))
 (seg (? (= S 4) (= 253 #t) (= 287 #t))
   (proc 0)
   (text "I couldn't find the two prisoners in Akihabara or Chinatown," 'br)
   (text "where Colonel Karl told me to look......")
   (wait)
   (text-reset 14)
   (text "Even if they were there, with their special training, there's")
   (text "no guarantee I'd be able to catch them.")
   (wait)
   (text-reset 14)
   (proc 1))
 (seg (? (= S 4) (= 55 #t))
   (proc 0)
   (text "Katou must have deliberately withheld information about the" 'br)
   (text "marks carved on the prisoners and the specialized goggles.")
   (wait)
   (text-reset 14)
   (text "Is he just screwing with me, or would it be inconvenient for" 'br)
   (text "him if I actually found the prisoners?")
   (wait)
   (text-reset 14)
   (proc 1))
 (seg (? (= S 4) (= 294 #f))
   (proc 0)
   (text "I have ideas about where April and Lei-Fa might be, but" 'br)
   (text "searching Akihabara or Chinatown doesn't guarantee I'll" 'br)
   (text "find them......")
   (wait)
   (text-reset 14)
   (text "If they stole secrets and escaped on someone's orders," 'br)
   (text "they've probably been \"removed\" by now to destroy evidence.")
   (wait)
   (text-reset 14)
   (text "But even so, I won't be allowed to just give up. I need to at")
   (text "least show I tried to complete the mission.")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 294 #t)
   (proc 1))
 (seg (? (= S 4) (= 294 #t))
   (proc 0)
   (text "Even if they're already dead, I have to search for them. I" 'br)
   (text "need to prove I at least tried......")
   (wait)
   (text-reset 14)
   (proc 1))
 (seg*))