(mes
 (meta (engine 'ADV) (charset "english") (extraop #t))
 (seg*
  (if (</>
       (//
        (? (= K 1))
        ((cmd 209) 0 5)
        (image-file "gpc¥waku.gpc")
        (image-mem 0 3)
        ((cmd 209) 1 5)
        (nop@)
        (set-var K 0))
       (// (nop@))))
  (branch-reg 56 (</> (/) (/ (mes-jump "mes¥ma_a03.mes"))))
  (exec-mem 14080 2 24 4 135 71 80 34 80 34 0 30)
  (image-file "gpc¥b13_01.gpc")
  (image-mem 0 3)
  (proc 3)
  (if (</>
       (//
        (? (= P 5))
        (if (</>
             (//
              (? (= O 0))
              (sound '|| 0)
              (sound '|| "uso¥xg_05.uso")
              (sound '|| 1)
              (nop@)
              (set-var P 5))
             (//
              (? (= O 1))
              (sound '|| 0)
              (sound '|| "uso¥xg_05v.uso")
              (sound '|| 1)
              (nop@)
              (set-var P 5)))))
       (// (nop@))))
  (load-mem "clm¥b13_01.clm" 32768)
  (text-frame 10 312 70 383)
  (if (</>
       (//
        (? (= 900 #t))
        (text "I'm back at my room again. The air here is stale...... I'd   rather wander the city than stay in a place like this.")
        (wait)
        (text-reset 14))
       (//
        (? (= 900 #f))
        (text "I'm back at my room in the Intelligence Division.We had received information about two prisoners in Ichigaya, but we still had not been able to capture a single prisoner.")
        (wait)
        (text-reset 14)
        (text "I understand their reasons, but the pressure is simply overwhelming for me")
        (wait)
        (text-reset 14))))
  (nop@)
  (set-reg 900 #t)
  (exec-mem 3968 102 500 360)
  (exec-mem 3072 1)
  (loop (set-var S 0) (exec-mem 3072 1020 1021 "S" 32768) (seg-call)))
 (seg (? (= 1020 #f) (= 1021 #f)) (exec-mem 3072 1))
 (seg (? (= 1021 #t))
   (nop@)
   (set-var K 0)
   (exec-mem 3072 0)
   (exec-mem 3968 103)
   (exec-mem 256 "A 0 S 0")
   (exec-mem 256 "G 1 4 64 12 48")
   (exec-mem 4768 4 8 12 6 1 0 0 4480 4480 1 0)
   (menu1 5 72 5 88 (</> (/ (text "   Save   ")) (/ (str "  Travel  "))))
   (if (</>
        (//
         (? (= S 0))
         (exec-mem 256 "A 0 S 0")
         (exec-mem 256 "G 9 5 72 16 96")
         (exec-mem 4768 5 9 16 12 1 0 0 4480 4480 1 0)
         (menu1
          6
          80
          6
          96
          6
          112
          6
          128
          6
          144
          (</>
           (/ (text "    File 1    "))
           (/ (text "    File 2    "))
           (/ (text "    File 3    "))
           (/ (text "    File 4    "))
           (/ (text "    File 5    "))
           (/)))
         (exec-mem 256 "P 9 5 72")
         (exec-mem 256 "P 1 4 64")
         (nop@)
         (set-var J P)
         (nop@)
         (set-var P 0)
         (if (</>
              (//
               (? (= S 0))
               (nop@)
               (set-var K 1)
               (flag-save 0)
               (nop@)
               (set-var K 0)
               (text "Successfully saved to File 1.")
               (wait)
               (text-reset 14))
              (//
               (? (= S 1))
               (nop@)
               (set-var K 1)
               (flag-save 1)
               (nop@)
               (set-var K 0)
               (text "Successfully saved to File 2.")
               (wait)
               (text-reset 14))
              (//
               (? (= S 2))
               (nop@)
               (set-var K 1)
               (flag-save 2)
               (nop@)
               (set-var K 0)
               (text "Successfully saved to File 3.")
               (wait)
               (text-reset 14))
              (//
               (? (= S 3))
               (nop@)
               (set-var K 1)
               (flag-save 3)
               (nop@)
               (set-var K 0)
               (text "Successfully saved to File 4.")
               (wait)
               (text-reset 14))
              (//
               (? (= S 4))
               (nop@)
               (set-var K 1)
               (flag-save 4)
               (nop@)
               (set-var K 0)
               (text "Successfully saved to File 5.")
               (wait)
               (text-reset 14))
              (// (? (= S 255)))))
         (nop@)
         (set-var P J))
        (//
         (? (= S 1))
         (exec-mem 256 "A 0 S 0")
         (exec-mem 256 "G 9 5 72 22 64")
         (exec-mem 4768 5 9 22 8 1 0 0 4480 4480 1 0)
         (menu1
          6
          80
          6
          96
          6
          112
          (</>
           (/ (text "   Anna's Office   "))
           (/ (text "    Anna's Room    "))
           (/ (text "      Outside      "))
           (/)))
         (exec-mem 256 "P 9 5 72")
         (exec-mem 256 "P 1 4 64")
         (if (</>
              (//
               (? (= S 0))
               (branch-reg
                55
                (</>
                 (/ (mes-jump "mes¥MA_B02.MES"))
                 (/ (mes-jump "mes¥MA_B03.MES")))))
              (// (? (= S 1)) (mes-jump "mes¥MA_C02.MES"))
              (//
               (? (= S 2))
               (branch-reg
                55
                (</>
                 (/ (mes-jump "mes¥MB_A01.MES"))
                 (/ (nop@) (set-reg 56 #t) (mes-jump "mes¥MB_A02.MES")))))
              (// (? (= S 255))))))
        (// (? (= S 255)) (exec-mem 256 "P 1 4 64"))))
   (exec-mem 3968 104)
   (exec-mem 3072 2)
   (exec-mem 3072 1))
 (seg (? (= S 1) (= 288 #f))
   (proc 0)
   (text "There are desks and chairs that are just as old as the room itself. I barely ever use them.but I guess to keep up appearances.")
   (wait)
   (text-reset 14)
   (text "I never really had a reason to. Desk work doesn't suit me,   and I don't consider it my job.")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 288 #t)
   (proc 1))
 (seg (? (= S 1) (= 289 #f))
   (proc 0)
   (text "My room is slighly different from other typical intelligence officer.")
   (wait)
   (text-reset 14)
   (text "The standard desk and chair of an intelligence officer are more of a nuisance than a necessity to me. I use my bed more often.")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 289 #t)
   (proc 1))
 (seg (? (= S 1) (= 289 #t))
   (proc 0)
   (text "There is a desk and chair as old as the room itself. I barely ever use them, but I guess it is there to keep up appearances.")
   (wait)
   (text-reset 14)
   (proc 1))
 (seg (? (= S 2) (= 290 #f))
   (proc 0)
   (text "The shelves are filled with tools used to torture prisoners. Whips, vibrators, enemas, and other tools")
   (wait)
   (text-reset 14)
   (text "I am allowed to be a member of the Intelligence Division simply because I could use these tools better than anyone else.")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 290 #t)
   (proc 1))
 (seg (? (= S 2) (= 291 #f))
   (proc 0)
   (text "It contains various tools used in torture. all personally selected by me to inflict the greatest pain and humiliation on the prisoners.")
   (wait)
   (text-reset 14)
   (text "However, since all the prisoners are gone, I can't use those tools. I have to finish the difficult task before the fun time.")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 291 #t)
   (proc 1))
 (seg (? (= S 2) (= 291 #t))
   (proc 0)
   (text "I don't need to open this until I catch one of the prisoners.")
   (wait)
   (text-reset 14)
   (proc 1))
 (seg (? (= S 3) (= 292 #f))
   (proc 0)
   (text "Outside the window is a small park. The area where the intelligence office is located is right in the city center. The wasteful use of land has come under criticism.")
   (wait)
   (text-reset 14)
   (text "Apparently, this area was originally a military garrison. Until a large-scale base was built in Ichigaya, it was charged for protecting the security of the Imperial Capital.")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 292 #t)
   (proc 1))
 (seg (? (= S 3) (= 293 #f))
   (proc 0)
   (text "Outside the window is a war memorial. The pillar stands at   least three stories tall, covered in the names of soldiers   who've died for our nation.")
   (wait)
   (text-reset 14)
   (text "The tower has gotten larger and fuller since I last saw it.  It's amazing how much the view has changed after just a      couple months of not using this room.")
   (wait)
   (text-reset 14)
   (text "This is clear evidence that this country will not last much longer. No wonder that crime is rising and public order is in disarray. Everyone is despairing about the future...")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 293 #t)
   (proc 1))
 (seg (? (= S 3) (= 293 #t))
   (proc 0)
   (text "Outside the window is a small park. The area where the intelligence office is located is right in the city center. The wasteful use of land has come under criticism.")
   (wait)
   (text-reset 14)
   (proc 1))
 (seg (? (= S 4) (= 253 #f) (= 287 #t))
   (proc 0)
   (text "The woman I met at the black market in Akihabara said she was a friend of April that the Colonel had mentioned.")
   (wait)
   (text-reset 14)
   (text "But how can I be sure that woman isn't April? I don't even know the face of the escaped prisoner.")
   (wait)
   (text-reset 14)
   (text "Even if we find April and Leifa, there is nothing we can do.....")
   (wait)
   (text-reset 14)
   (proc 1))
 (seg (? (= S 4) (= 253 #t) (= 287 #f))
   (proc 0)
   (text "I searched Chinatown as told by Colonel Carl at the Ichigaya base, but could not find Lei-fa...")
   (wait)
   (text-reset 14)
   (text "There are plenty of places to hide in that area, and even if she were in the same room, there is a good chance that she would find me before I did.")
   (wait)
   (text-reset 14)
   (text "My opponent is a former special forces. She's much stronger than me, and killing people is probably easy for her. I have to think of a way to beat Lei-fa.")
   (wait)
   (text-reset 14)
   (proc 1))
 (seg (? (= S 4) (= 253 #t) (= 287 #t))
   (proc 0)
   (text "Colonel Carl from Ichigaya Base had told me that they could not find the two prisoners in Akihabara or Chinatown...")
   (wait)
   (text-reset 14)
   (text "No, even if they were there, it would be difficult to catch them with their special abilities.")
   (wait)
   (text-reset 14)
   (proc 1))
 (seg (? (= S 4) (= 55 #t))
   (proc 0)
   (text "Katou must have deliberately not informed me about the engraved markings on the prisoners and the special goggles.")
   (wait)
   (text-reset 14)
   (text "Is this just harassment, or is it inconvenient for them to find the prisoner?")
   (wait)
   (text-reset 14)
   (proc 1))
 (seg (? (= S 4) (= 294 #f))
   (proc 0)
   (text "I have an idea where April and Lei-fa might be, but even if I search in Akihabara or Chinatown, there is no guarantee that I will find them....")
   (wait)
   (text-reset 14)
   (text "If the two had stolen the secrets and escaped on someone else's orders, wouldn't they have been eliminated by now to destroy the evidence?")
   (wait)
   (text-reset 14)
   (text "But even if I did, I can't afford not to look for the two of them. At any rate, I need to let them know that I tried to complete the mission.")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 294 #t)
   (proc 1))
 (seg (? (= S 4) (= 294 #t))
   (proc 0)
   (text "Even if they are no longer alive, I have no choice but to search for them. I have to show that I made an effort...")
   (wait)
   (text-reset 14)
   (proc 1))
 (seg*))
