(mes
 (meta (engine 'ADV) (charset "pc98") (extraop #t))
 (seg*
  (if (</>
       (//
        (? (= K 1))
        ((cmd 209) 0 5)
        (image-file "gpc¥waku.gpc")
        (image-mem 0 3)
        ((cmd 209) 1 5)
        (nop@)
        (set-var K 0))
       (// (nop@))))
  (if (</> (// (? (= 58 #t) (= 60 #t)) (mes-jump "mes¥ma_a04.mes")) (//)))
  (exec-mem 14080 2 24 4 135 71 80 34 80 34 0 30)
  (image-file "gpc¥b13_01.gpc")
  (image-mem 0 3)
  (proc 3)
  (if (</>
       (//
        (? (!= P 5))
        (if (</>
             (//
              (? (= O 0))
              (sound '|| 0)
              (sound '|| "uso¥xg_05.uso")
              (sound '|| 1)
              (nop@)
              (set-var P 5))
             (//
              (? (= O 1))
              (sound '|| 0)
              (sound '|| "uso¥xg_05v.uso")
              (sound '|| 1)
              (nop@)
              (set-var P 5)))))
       (// (nop@))))
  (load-mem "clm¥b13_01.clm" 32768)
  (text-frame 10 312 70 383)
  (text-delay 2)
  (if (</>
       (//
        (? (= 938 #t))
        (str "I made it back from that dungeon of an interrogation" 'br)
        (str "room. Exhaustion is clinging to every part of" 'br)
        (str "my body......")
        (wait)
        (text-reset 14)
        (nop@)
        (set-reg 938 #f))
       (//
        (? (= 935 #t))
        (str "I'm back in my room at Intelligence. My prisoner is in" 'br)
        (str "the interrogation room - I should get started before she" 'br)
        (str "finds a way to escape again.")
        (wait)
        (text-reset 14)
        (nop@)
        (set-reg 935 #f))
       (//
        (? (= 901 #t))
        (str "I'm back in my room at Intelligence. For a while, it'll" 'br)
        (str "just be back and forth between here and the city.")
        (wait)
        (text-reset 14))
       (//
        (? (= 901 #f))
        (str "I've returned to my room at Intelligence. For a while, it'll" 'br)
        (str "just be back and forth between here and the city.")
        (wait)
        (text-reset 14)
        (str "I can't go anywhere else until every prisoner is" 'br)
        (str "arrested and interrogated. If I tried to run," 'br)
        (str "I'd be the one getting hunted down.")
        (wait)
        (text-reset 14)
        (str "When the military's involved, a nobody like me doesn't even" 'br)
        (str "get to complain. Now then, what should I do from here......")
        (wait)
        (text-reset 14)
        (nop@)
        (set-reg 901 #t))))
  (exec-mem 3968 102 500 360)
  (exec-mem 3072 1)
  (loop (set-var S 0) (exec-mem 3072 1020 1021 "S" 32768) (seg-call)))
 (seg (? (= 1020 #f) (= 1021 #f)) (exec-mem 3072 1))
 (seg (? (= 1021 #t))
   (exec-mem 3072 0)
   (nop@)
   (set-var K 0)
   (exec-mem 3968 103)
   (exec-mem 256 "A 0 S 0")
   (exec-mem 256 "G 1 4 64 12 48")
   (exec-mem 4768 4 8 12 6 1 0 0 4480 4480 1 0)
   (menu1 5 72 5 88 (</> (/ (str "   Save   ")) (/ (str "  Travel  "))))
   (if (</>
        (//
         (? (= S 0))
         (exec-mem 256 "A 0 S 0")
         (exec-mem 256 "G 9 5 72 16 96")
         (exec-mem 4768 5 9 16 12 1 0 0 4480 4480 1 0)
         (menu1
          6
          80
          6
          96
          6
          112
          6
          128
          6
          144
          (</>
           (/ (str "    File 1    "))
           (/ (str "    File 2    "))
           (/ (str "    File 3    "))
           (/ (str "    File 4    "))
           (/ (str "    File 5    "))
           (/)))
         (exec-mem 256 "P 9 5 72")
         (exec-mem 256 "P 1 4 64")
         (nop@)
         (set-var J P)
         (nop@)
         (set-var P 0)
         (if (</>
              (//
               (? (= S 0))
               (nop@)
               (set-var K 1)
               (flag-save 0)
               (nop@)
               (set-var K 0)
               (str "Successfully saved to File 1.")
               (wait)
               (text-reset 14))
              (//
               (? (= S 1))
               (nop@)
               (set-var K 1)
               (flag-save 1)
               (nop@)
               (set-var K 0)
               (str "Successfully saved to File 2.")
               (wait)
               (text-reset 14))
              (//
               (? (= S 2))
               (nop@)
               (set-var K 1)
               (flag-save 2)
               (nop@)
               (set-var K 0)
               (str "Successfully saved to File 3.")
               (wait)
               (text-reset 14))
              (//
               (? (= S 3))
               (nop@)
               (set-var K 1)
               (flag-save 3)
               (nop@)
               (set-var K 0)
               (str "Successfully saved to File 4.")
               (wait)
               (text-reset 14))
              (//
               (? (= S 4))
               (nop@)
               (set-var K 1)
               (flag-save 4)
               (nop@)
               (set-var K 0)
               (str "Successfully saved to File 5.")
               (wait)
               (text-reset 14))
              (// (? (= S 255)))))
         (nop@)
         (set-var P J))
        (//
         (? (= S 1))
         (exec-mem 256 "A 0 S 0")
         (exec-mem 256 "G 9 5 72 22 64")
         (exec-mem 4768 5 9 22 8 1 0 0 4480 4480 1 0)
         (menu1
          6
          80
          6
          96
          6
          112
          (</>
           (/ (str "   Anna's Office   "))
           (/ (str "    Anna's Room    "))
           (/ (str "      Outside      "))
           (/)))
         (exec-mem 256 "P 9 5 72")
         (exec-mem 256 "P 1 4 64")
         (if (</>
              (// (? (= S 0)) (mes-jump "mes¥MA_B03.MES"))
              (// (? (= S 1)) (mes-jump "mes¥MA_C02.MES"))
              (// (? (= S 2)) (mes-jump "mes¥MB_A02.MES"))
              (// (? (= S 255))))))
        (// (? (= S 255)) (exec-mem 256 "P 1 4 64"))))
   (exec-mem 3968 104)
   (exec-mem 3072 2)
   (exec-mem 3072 1))
 (seg (? (= S 1) (= 318 #f))
   (proc 0)
   (str "My room differs somewhat from what a typical Intelligence" 'br)
   (str "member has.")
   (wait)
   (text-reset 14)
   (str "While desks and chairs are essential for most agents, to me" 'br)
   (str "they're just a space-wasting obstacle.")
   (wait)
   (text-reset 14)
   (str "The terminal on the desk is no different. It's definitely" 'br)
   (str "being monitored. Using it would be the same as handing" 'br)
   (str "information straight to the enemy.")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 318 #t)
   (proc 1))
 (seg (? (= S 1) (= 319 #f))
   (proc 0)
   (str "This room has desks and chairs to keep up appearances, but" 'br)
   (str "I barely ever use them.")
   (wait)
   (text-reset 14)
   (str "Desk work doesn't suit me, and I hardly consider it my job.")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 319 #t)
   (proc 1))
 (seg (? (= S 1) (= 319 #t))
   (proc 0)
   (str "Desk work doesn't suit me, and I hardly consider it my job.")
   (wait)
   (text-reset 14)
   (proc 1))
 (seg (? (= S 2) (= 57 #f) (= 58 #f) (= 59 #f) (= 60 #f))
   (proc 0)
   (str "It contains various torture implements. Every one personally" 'br)
   (str "selected by me to inflict maximum pain and humiliation on" 'br)
   (str "my subjects.")
   (wait)
   (text-reset 14)
   (str "But without any prisoners to use them on, they're pointless." 'br)
   (str "I'll have to finish this pain-in-the-ass mission before I" 'br)
   (str "can have any fun.")
   (wait)
   (text-reset 14)
   (proc 1))
 (seg (? (= S 2))
   (proc 0)
   (str "Time to start the interrogation. I've been looking forward" 'br)
   (str "to this. Now then, who should I start with......")
   (wait)
   (text-reset 14)
   (exec-mem 256 "A 0 S 0")
   (exec-mem 256 "G 1 4 64 22 64")
   (set-var X 1)
   (when (</>
          (// (? (= 57 #t)) (nop@) (inc-var X 1))
          (// (? (= 59 #t)) (nop@) (inc-var X 1))))
   (if (</>
        (// (? (= X 3)) (exec-mem 4768 4 8 22 8 1 0 0 4480 4480 1 0))
        (// (? (= X 2)) (exec-mem 4768 4 8 22 6 1 0 0 4480 4480 1 0))
        (// (? (= X 1)) (exec-mem 4768 4 8 22 4 1 0 0 4480 4480 1 0))))
   (menu1
    5
    72
    5
    88
    5
    104
    (</>
     (/ (set-reg 57 #t) (nop@) (str "       April        "))
     (/ (set-reg 59 #t) (nop@) (str "       Lei-Fa       "))
     (/ (str "       Cancel       "))))
   (exec-mem 256 "P 1 4 64")
   (if (</>
        (//
         (? (= S 0))
         (branch-reg
          58
          (</>
           (/
            (str "I think I'll interrogate April. As a former Special Forces" 'br)
            (str "soldier, she won't break easily.")
            (wait)
            (text-reset 14)
            (str "She's probably built up a tolerance for pain. All the more" 'br)
            (str "satisfying when I make her understand who's in charge......")
            (wait)
            (text-reset 14)
            (exec-mem 3072 0)
            (mes-jump "mes¥MD_A01.MES"))
           (/
            (str "I've already interrogated April plenty. She's done talking," 'br)
            (str "and pushing further will just break what's left of her" 'br)
            (str "mind.")
            (wait)
            (text-reset 14)))))
        (//
         (? (= S 1))
         (branch-reg
          60
          (</>
           (/
            (str "Time to interrogate Lei-Fa. Imagining that cocky Chinese" 'br)
            (str "girl screaming in pain is already making my blood run" 'br)
            (str "hot......")
            (wait)
            (text-reset 14)
            (str "Will she keep me entertained, I wonder...... I'll torment" 'br)
            (str "Lei-Fa until she's crying and begging from the humiliation.")
            (wait)
            (text-reset 14)
            (exec-mem 3072 0)
            (mes-jump "mes¥MD_B01.MES"))
           (/
            (str "I've already interrogated Lei-Fa. She's not going to say" 'br)
            (str "anything more.")
            (wait)
            (text-reset 14)))))))
   (proc 1))
 (seg (? (= S 3) (= 320 #f))
   (proc 0)
   (str "Outside the window, it's the same overcast sky as before -" 'br)
   (str "looks like it could start raining any second. The damp air" 'br)
   (str "is already creeping into the room.")
   (wait)
   (text-reset 14)
   (str "Not a soul in the park below. The dead winter grass gives" 'br)
   (str "the whole place a desolate feel. What a depressing" 'br)
   (str "view......")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 320 #t)
   (proc 1))
 (seg (? (= S 3) (= 321 #f))
   (proc 0)
   (str "Outside the window is a small park. This Intelligence office" 'br)
   (str "is in the true city center - the waste of land here is often" 'br)
   (str "criticized.")
   (wait)
   (text-reset 14)
   (str "This area used to be a military garrison, apparently. Before" 'br)
   (str "the large base at Ichigaya was built, this was responsible" 'br)
   (str "for the capital's security.")
   (wait)
   (text-reset 14)
   (str "If you dug up the ground around here, you'd probably find a" 'br)
   (str "dud or two, or maybe even a human corpse......")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 321 #t)
   (proc 1))
 (seg (? (= S 3) (= 321 #t))
   (proc 0)
   (str "Outside the window, it's the same overcast sky as before -" 'br)
   (str "looks like it could start raining any second. The damp air" 'br)
   (str "is already creeping into the room.")
   (wait)
   (text-reset 14)
   (proc 1))
 (seg (? (= S 4))
   (proc 0)
   (if (</>
        (//
         (? (= 57 #t) (= 58 #f) (= 59 #f) (= 60 #f))
         (nop@)
         (str "First I should interrogate April. She might hold the key to" 'br)
         (str "solving this whole case.")
         (wait)
         (text-reset 14)
         (str "If that doesn't work, at least I might get a hint for" 'br)
         (str "capturing Lei-Fa or finding the third prisoner.")
         (wait)
         (text-reset 14))
        (//
         (? (= 57 #t) (= 58 #t) (= 59 #f) (= 60 #f))
         (nop@)
         (str "I hate to think April could withstand my torture. Did she" 'br)
         (str "really know nothing?")
         (wait)
         (text-reset 14))
        (//
         (? (= 57 #t) (= 58 #t) (= 59 #t) (= 60 #f))
         (nop@)
         (str "I've captured the second prisoner, Lei-Fa. Interrogating her" 'br)
         (str "might give me more information.")
         (wait)
         (text-reset 14))
        (//
         (? (= 57 #t) (= 58 #f) (= 59 #t) (= 60 #f))
         (nop@)
         (str "I've arrested both prisoners. Interrogating them should give" 'br)
         (str "me info about the classified material I'm looking for.")
         (wait)
         (text-reset 14))
        (//
         (? (= 57 #f) (= 58 #f) (= 59 #t) (= 60 #f))
         (nop@)
         (str "I've arrested Lei-Fa. Interrogating her might provide the" 'br)
         (str "key to solving this whole case.")
         (wait)
         (text-reset 14))
        (//
         (? (= 57 #f) (= 58 #f) (= 59 #t) (= 60 #t))
         (nop@)
         (str "I hate to think Lei-Fa could withstand my torture. Did she" 'br)
         (str "really know nothing?")
         (wait)
         (text-reset 14))
        (//
         (? (= 57 #t) (= 58 #f) (= 59 #t) (= 60 #t))
         (nop@)
         (str "Lei-Fa didn't talk. I have to do something about April." 'br)
         (str "Anything - I have to make something work......")
         (wait)
         (text-reset 14))
        (//
         (str "First I need to arrest April or Lei-Fa. Fighting someone" 'br)
         (str "clearly stronger than me makes me nervous......")
         (wait)
         (text-reset 14)
         (str "My only advantage is the marks on the prisoners and the" 'br)
         (str "goggles that let me see them. I'll have to take them down" 'br)
         (str "before they can react.")
         (wait)
         (text-reset 14))))
   (proc 1)))