(mes
 (meta (engine 'ADV) (charset "english") (extraop #t))
 (seg*
  (branch-reg 55 (</> (/) (/ (mes-jump "mes¥ma_b03.mes"))))
  (exec-mem 14080 2 24 4 135 71 80 34 80 34 0 30)
  (image-file "gpc¥b01_01.gpc")
  (image-mem 0 3)
  (image-file "gpc¥b01_01a.gpc")
  (image-mem 1 0)
  (proc 3)
  (if (</>
       (//
        (? (= P 5))
        (if (</>
             (//
              (? (= O 0))
              (sound '|| 0)
              (sound '|| "uso¥xg_05.uso")
              (sound '|| 1)
              (nop@)
              (set-var P 5))
             (//
              (? (= O 1))
              (sound '|| 0)
              (sound '|| "uso¥xg_05v.uso")
              (sound '|| 1)
              (nop@)
              (set-var P 5)))))
       (// (nop@))))
  (load-mem "clm¥b01_01a.clm" 32768)
  (text-frame 10 312 70 383)
  (if (</>
       (//
        (? (= 913 #t))
		(text-delay 0)
        (text "「Anna」" 'br)
		(text-delay 2)
        (text "Kiyomi...... Have you found any leads on the prisoners?")
        (wait)
        (text-reset 14))
       (//
        (? (= 913 #f))
		(text-delay 0)
        (text "「Anna」" 'br)
		(text-delay 2)
        (text "Kiyomi...... What's wrong?")
        (wait)
        (text-reset 14)
		(text-delay 0)
        (text "「Kiyomi」" 'br)
		(text-delay 2)
        (text "What's wrong? I've hit a dead end, that's what.")
        (wait)
        (text-reset 14)
		(text-delay 0)
        (text "「Anna」" 'br)
		(text-delay 2)
        (text "Did you go to Ichigaya Base?")
        (wait)
        (text-reset 14)
		(text-delay 0)
        (text "「Kiyomi」" 'br)
		(text-delay 2)
        (text "Of course I did. You think I'm not doing my job?")
        (wait)
        (text-reset 14)
		(text-delay 0)
        (text "「Katou」" 'br)
		(text-delay 2)
        (text "Not at all. We have high expectations for you.")
        (wait)
        (text-reset 14)
		(text-delay 0)
        (text "「Kiyomi」" 'br)
        (text-delay 2)
        (text "Thanks, I guess...... I appreciate it, but it's also a pain" 'br)
        (text "in the ass.")
        (wait)
        (text-reset 14)
		(text-delay 0)
        (text "「Katou」" 'br)
        (text-delay 2)
        (text "It's not for no reason. You're aware of the risk, aren't you?")
        (text "We've already lost three agents on this case.")
        (wait)
        (text-reset 14)
		(text-delay 0)
        (text "「Kiyomi」" 'br)
        (text-delay 2)
        (text "I never heard about that. You deliberately kept it from me...... Why?")
        (wait)
        (text-reset 14)
		(text-delay 0)
        (text "「Anna」" 'br)
		(text-delay 2)
        (text "..................")
        (wait)
        (text-reset 14))))
  (nop@)
  (set-reg 913 #t)
  (exec-mem 3968 102 500 360)
  (exec-mem 3072 1)
  (loop (set-var S 0) (exec-mem 3072 1020 1021 "S" 32768) (seg-call)))
 (seg (? (= 1020 #f) (= 1021 #f)) (exec-mem 3072 1))
 (seg (? (= 1021 #t) (= 253 #t) (= 287 #t) (= 55 #t))
   (exec-mem 3072 0)
   (exec-mem 3968 103)
   (exec-mem 256 "A 0 S 0")
   (exec-mem 256 "G 1 4 64 12 48")
   (exec-mem 4768 4 8 12 4 1 0 0 4480 4480 1 0)
   (menu1 5 72 (</> (/ (str "  Travel  "))))
   (if (</>
        (//
         (? (= S 0))
         (exec-mem 256 "A 0 S 0")
         (exec-mem 256 "G 9 5 72 22 64")
         (exec-mem 4768 5 9 22 4 1 0 0 4480 4480 1 0)
         (menu1 6 80 (</> (/ (str "   Kiyomi's Room    "))))
         (exec-mem 256 "P 9 5 72")
         (exec-mem 256 "P 1 4 64")
         (if (</>
              (//
               (? (= S 0))
               (proc 0)
               (branch-reg
                55
                (</>
                 (/
				  (text-delay 0)
                  (text "「Katou」" 'br)
				  (text-delay 2)
                  (text "Next time you come back, I expect some good news.")
                  (wait)
                  (text-reset 14)
				  (text-delay 0)
                  (text "「Kiyomi」" 'br)
				  (text-delay 2)
                  (text ".................."))
                 (/
				  (text-delay 0)
                  (text "「Katou」" 'br)
				  (text-delay 2)
                  (text "You're leaving? Don't forget what I told you. Check for the marks on the prisoners, understood?")
                  (wait)
                  (text-reset 14)
				  (text-delay 0)
                  (text "「Kiyomi」" 'br)
				  (text-delay 2)
                  (text "I'll do that without being told. And I won't forget how you hid those marks from me......"))))
               (wait)
               (text-reset 14)
               (mes-jump "mes¥MA_A02.MES"))
              (// (? (= S 255))))))
        (// (? (= S 255)) (exec-mem 256 "P 1 4 64"))))
   (exec-mem 3968 104)
   (exec-mem 3072 2)
   (exec-mem 3072 1))
 (seg (? (= 1021 #t) (= 287 #f))
   (exec-mem 3072 0)
   (exec-mem 3968 103)
   (exec-mem 256 "A 0 S 0")
   (exec-mem 256 "G 1 4 64 12 48")
   (exec-mem 4768 4 8 12 4 1 0 0 4480 4480 1 0)
   (menu1 5 72 (</> (/ (str "  Travel  "))))
   (if (</>
        (//
         (? (= S 0))
         (exec-mem 256 "A 0 S 0")
         (exec-mem 256 "G 9 5 72 22 64")
         (exec-mem 4768 5 9 22 4 1 0 0 4480 4480 1 0)
         (menu1 6 80 (</> (/ (str " 　　自分の部屋　　 "))))
         (exec-mem 256 "P 9 5 72")
         (exec-mem 256 "P 1 4 64")
         (if (</>
              (//
               (? (= S 0))
               (proc 0)
               (branch-reg
                55
                (</>
                 (/
                  (text-delay 0)
				  (text "「Katou」" 'br)
				  (text-delay 2)
                  (text "Next time you come back, I expect some good news.")
                  (wait)
                  (text-reset 14)
                  (text-delay 0)
				  (text "「Kiyomi」" 'br)
				  (text-delay 2)
                  (text ".................."))
                 (/
                  (text-delay 0)
				  (text "「Katou」" 'br)
				  (text-delay 2)
                  (text "You're leaving? Don't forget what I told you. Check for the marks on the prisoners, understood?")
                  (wait)
                  (text-reset 14)
				  (text-delay 0)
                  (text "「Kiyomi」" 'br)
				  (text-delay 2)
                  (text "I'll do that without being told. And I won't forget how you hid those marks from me......"))))
               (wait)
               (text-reset 14)
               (mes-jump "mes¥MA_A02.MES"))
              (// (? (= S 255))))))
        (// (? (= S 255)) (exec-mem 256 "P 1 4 64"))))
   (exec-mem 3968 104)
   (exec-mem 3072 2)
   (exec-mem 3072 1))
 (seg (? (= 1021 #t) (= 253 #f))
   (exec-mem 3072 0)
   (exec-mem 3968 103)
   (exec-mem 256 "A 0 S 0")
   (exec-mem 256 "G 1 4 64 12 48")
   (exec-mem 4768 4 8 12 4 1 0 0 4480 4480 1 0)
   (menu1 5 72 (</> (/ (str "  Travel  "))))
   (if (</>
        (//
         (? (= S 0))
         (exec-mem 256 "A 0 S 0")
         (exec-mem 256 "G 9 5 72 22 64")
         (exec-mem 4768 5 9 22 4 1 0 0 4480 4480 1 0)
         (menu1 6 80 (</> (/ (str " 　　自分の部屋　　 "))))
         (exec-mem 256 "P 9 5 72")
         (exec-mem 256 "P 1 4 64")
         (if (</>
              (//
               (? (= S 0))
               (proc 0)
               (branch-reg
                55
                (</>
                 (/
                  (text-delay 0)
				  (text "「Katou」" 'br)
				  (text-delay 2)
                  (text "Next time you come back, I expect some good news.")
                  (wait)
                  (text-reset 14)
				  (text-delay 0)
                  (text "「Kiyomi」" 'br)
				  (text-delay 2)
                  (text ".................."))
                 (/
                  (text-delay 0)
				  (text "「Katou」" 'br)
				  (text-delay 2)
                  (text "You're leaving? Don't forget what I told you. Check for the marks on the prisoners, understood?")
                  (wait)
                  (text-reset 14)
				  (text-delay 0)
                  (text "「Kiyomi」" 'br)
				  (text-delay 2)
                  (text "I'll do that without being told. And I won't forget how you hid those marks from me......"))))
               (wait)
               (text-reset 14)
               (mes-jump "mes¥MA_A02.MES"))
              (// (? (= S 255))))))
        (// (? (= S 255)) (exec-mem 256 "P 1 4 64"))))
   (exec-mem 3968 104)
   (exec-mem 3072 2)
   (exec-mem 3072 1))
 (seg (? (= 1021 #t)) (exec-mem 3072 1))
 (seg (? (= S 1) (= 55 #t))
   (proc 0)
   (text-delay 0)
   (text "「Anna」" 'br)
   (text-delay 2)
   (text "Kiyomi, please be careful......")
   (wait)
   (text-reset 14)
   (proc 1))
 (seg (? (= S 1) (= 296 #t))
   (proc 0)
   (text-delay 0)
   (text "「Anna」" 'br)
   (text-delay 2)
   (text "We have to capture them, no matter what......")
   (wait)
   (text-reset 14)
   (proc 1))
 (seg (? (= S 1) (= 253 #t) (= 287 #t))
   (proc 0)
   (text-delay 0)
   (text "「Kiyomi」" 'br)
   (text-delay 2)
   (text "At this rate, it's impossible. I could spend my whole life" 'br)
   (text "searching and never find those two.")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (text "「Anna」" 'br)
   (text-delay 2)
   (text "I see...... I was really counting on you.")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (text "「Kiyomi」" 'br)
   (text-delay 2)
   (text "Don't look at me like that, Anna. It breaks my heart. There" 'br)
   (text "are things even I can't do.")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (text "「Anna」" 'br)
   (text-delay 2)
   (text "But Kiyomi...... I have no one else I can rely on......")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (text "「Kiyomi」" 'br)
   (text-delay 2)
   (text "I hear you, but I've got nothing to go on. Having their" 'br)
   (text "profiles erased was the fatal blow.")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (text "「Anna」" 'br)
   (text-delay 2)
   (text "I know...... I understand that. But we still can't stop" 'br)
   (text "searching.")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (text "「Anna」" 'br)
   (text-delay 2)
   (text "We must capture them no matter what......")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (text "「Kiyomi」" 'br)
   (text-delay 2)
   (text "You keep saying that...... but impossible is impossible." 'br)
   (text "Unless you lend me about a hundred agents, that is.")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (text "「Anna」" 'br)
   (text-delay 2)
   (text "That's not happening. If we got that many people involved," 'br)
   (text "we wouldn't be able to keep the mission confidential.")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (text "「Anna」" 'br)
   (text-delay 2)
   (text "Not with this massive security breach we have in" 'br)
   (text "Intelligence.")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (text "「Kiyomi」" 'br)
   (text-delay 2)
   (text "Then what the hell do you expect me to do?")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (text "「Anna」" 'br)
   (text-delay 2)
   (text "............")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 296 #t)
   (proc 1))
 (seg (? (= S 1) (= 295 #f))
   (proc 0)
   (text-delay 0)
   (text "「Kiyomi」" 'br)
   (text-delay 2)
   (text "I met Colonel Karl at Ichigaya Base - he was April and" 'br)
   (text "Lei-Fa's former commander.")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (text "「Anna」" 'br)
   (text-delay 2)
   (text "And...... did he know where they went?")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (text "「Kiyomi」" 'br)
   (text-delay 2)
   (text "Nothing concrete. But apparently April talked about a friend")
   (text "of hers in Akihabara's black market before her discharge.")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (text "「Kiyomi」" 'br)
   (text-delay 2)
   (text "And Lei-Fa's supposedly hiding out in Chinatown. But I'm not")
   (text "sure we can even believe anything the Colonel says.")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (text "「Anna」" 'br)
   (text-delay 2)
   (text "We have to believe it - we don't have any other leads." 'br)
   (text "Have you searched there?")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (text "「Kiyomi」" 'br)
   (text-delay 2)
   (text "Not yet, but...... is it true? That three agents were killed")
   (text "before you sent me in?")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (text "「Anna」" 'br)
   (text-delay 2)
   (text "............It's true. I'm sorry for keeping it from you.")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (text "「Kiyomi」" 'br)
   (text-delay 2)
   (text "Damn right you should be. Three agents dead, and you thought" 'br)
   (text "I didn't need a heads-up......")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (text "「Anna」" 'br)
   (text-delay 2)
   (text "Would you have accepted the mission if I had told you?")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (text "「Kiyomi」" 'br)
   (text-delay 2)
   (text "............")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 295 #t)
   (proc 1))
 (seg (? (= S 1) (= 296 #f))
   (proc 0)
   (text-delay 0)
   (text "「Anna」" 'br)
   (text-delay 2)
   (text "Why don't you search Akihabara and Chinatown like the" 'br)
   (text "Colonel suggested?")
   (wait)
   (text-reset 14)
   (proc 1))
 (seg (? (= S 2) (= 299 #t))
   (proc 0)
   (text-delay 0)
   (text "「Katou」" 'br)
   (text-delay 2)
   (text "Get going. Go catch the prisoners.")
   (wait)
   (text-reset 14)
   (proc 1))
 (seg (? (= S 2) (= 55 #t))
   (proc 0)
   (text-delay 0)
   (text "「Kiyomi」" 'br)
   (text-delay 2)
   (text "Why didn't you tell me the prisoners were marked? If I'd" 'br)
   (text "known that, I wouldn't have wasted so much time!")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (text "「Katou」" 'br)
   (text-delay 2)
   (text "Again, I told you I forgot.")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (text "「Kiyomi」" 'br)
   (text-delay 2)
   (text "Hah. Like hell you did. You want to know what I think?" 'br)
   (text "I think you're the leak in Intelligence.")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (text "「Katou」" 'br)
   (text-delay 2)
   (text "What are you saying......")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (text "「Kiyomi」" 'br)
   (text-delay 2)
   (text "Think about it. Who benefits from slowing down my" 'br)
   (text "investigation?")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (text "「Kiyomi」" 'br)
   (text-delay 2)
   (text "You'd have time to eliminate the prisoners or destroy the" 'br)
   (text "evidence. Maybe you're the mastermind behind all this!")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (text "「Anna」" 'br)
   (text-delay 2)
   (text "Kiyomi! Stop it...... What are you saying?")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (text "「Katou」" 'br)
   (text-delay 2)
   (text "I'd advise you to watch your tongue. For your own sake.")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (text "「Anna」" 'br)
   (text-delay 2)
   (text "Kiyomi...... Control yourself.")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (text "「Kiyomi」" 'br)
   (text-delay 2)
   (text "I can't wait for the day I get to torture you.")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (text "「Katou」" 'br)
   (text-delay 2)
   (text "............")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (text "「Katou」" 'br)
   (text-delay 2)
   (text "Enough. Go catch those prisoners......")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 299 #t)
   (proc 1))
 (seg (? (= S 2) (= 298 #t))
   (proc 0)
   (text-delay 0)
   (text "「Kiyomi」" 'br)
   (text-delay 2)
   (text "So what am I supposed to do? Please, enlighten me.")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (text "「Katou」" 'br)
   (text-delay 2)
   (text "If it were me, identifying the prisoners would be trivial.")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (text "「Katou」" 'br)
   (text-delay 2)
   (text "They're marked with a tattoo only visible through a special" 'br)
   (text "filter.")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (text "「Kiyomi」" 'br)
   (text-delay 2)
   (text "What?")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (text "「Katou」" 'br)
   (text-delay 2)
   (text "The filter is built into the goggles issued to some of our" 'br)
   (text "agents.")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (text "「Kiyomi」" 'br)
   (text-delay 2)
   (text "What the hell? Why didn't you tell me this earlier?! I could" 'br)
   (text "have avoided wasting all that time!")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (text "「Katou」" 'br)
   (text-delay 2)
   (text "Didn't I mention that? My apologies. You always carry your" 'br)
   (text "goggles with you, don't you? How ironic......")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (text "「Katou」" 'br)
   (text-delay 2)
   (text "All you had to do was look through them and you would've seen")
   (text "the swastika mark branded on the prisoners. But you didn't.")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (text "「Kiyomi」" 'br)
   (text-delay 2)
   (text "......You kept that from me on purpose. What's your game?" 'br)
   (text "Are you just messing with me?")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (text "「Katou」" 'br)
   (text-delay 2)
   (text "I told you, I forgot. Everyone makes mistakes.")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (text "「Kiyomi」" 'br)
   (text-delay 2)
   (text "You're rotten to the core, you bastard......")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (text "「Katou」" 'br)
   (text-delay 2)
   (text "Don't get so upset. You just need to search again.")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (text "「Katou」" 'br)
   (text-delay 2)
   (text "Akihabara and Chinatown, right? Go back there and use your" 'br)
   (text "goggles this time.")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (text "「Kiyomi」" 'br)
   (text-delay 2)
   (text "........................")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 55 #t)
   (proc 1))
 (seg (? (= S 2) (= 253 #t) (= 287 #t))
   (proc 0)
   (text-delay 0)
   (text "「Kiyomi」" 'br)
   (text-delay 2)
   (text "I've figured out where two of the four might be," 'br)
   (text "roughly anyway.")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (text "「Katou」" 'br)
   (text-delay 2)
   (text "Then go arrest them. What are you waiting for? At this rate," 'br)
   (text "you'll be charged with negligence.")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (text "「Kiyomi」" 'br)
   (text-delay 2)
   (text "I need to know what they look like. I've got zero intel to" 'br)
   (text "go on. Without holos or profiles, there's nothing I can do.")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (text "「Katou」" 'br)
   (text-delay 2)
   (text "Is that so? How interesting.")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (text "「Kiyomi」" 'br)
   (text-delay 2)
   (text "I searched Akihabara and Chinatown, but it was a waste of" 'br)
   (text "time. You want me to keep wasting my time?")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (text "「Katou」" 'br)
   (text-delay 2)
   (text "Not at all. I have no intention of wasting the valuable" 'br)
   (text "resources given to Intelligence on chasing shadows.")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (text "「Kiyomi」" 'br)
   (text-delay 2)
   (text "Then I'm at a dead end here. There's nowhere left to go.")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (text "「Katou」" 'br)
   (text-delay 2)
   (text "I don't agree.")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (text "「Kiyomi」" 'br)
   (text-delay 2)
   (text "I don't care what you think. If I say it's impossible, then" 'br)
   (text "it's impossible.")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (text "「Katou」" 'br)
   (text-delay 2)
   (text "Well, what you say doesn't matter. Neither do faces or" 'br)
   (text "profiles......")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (text "「Kiyomi」" 'br)
   (text-delay 2)
   (text "What are you talking about?")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 298 #t)
   (proc 1))
 (seg (? (= S 2) (= 297 #f))
   (proc 0)
   (text-delay 0)
   (text "「Katou」" 'br)
   (text-delay 2)
   (text "What's this? Have you come to beg for mercy already?")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (text "「Kiyomi」" 'br)
   (text-delay 2)
   (text "You're a scumbag through and through. If you hate me so much," 'br)
   (text "why don't you use your own damn men?")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (text "「Kiyomi」" 'br)
   (text-delay 2)
   (text "Oh wait, they're useless. That's why this got dumped on me," 'br)
   (text "isn't it?")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (text "「Katou」" 'br)
   (text-delay 2)
   (text "Don't be so emotional. Just finish your mission and get this" 'br)
   (text "over with. It'll be easier for both of us.")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (text "「Kiyomi」" 'br)
   (text-delay 2)
   (text "I would if I could.")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (text "「Katou」" 'br)
   (text-delay 2)
   (text "Exactly. When you must walk through filth, it's best to hold" 'br)
   (text "your breath and get through it quickly.")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (text "「Kiyomi」" 'br)
   (text-delay 2)
   (text "..................")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (text "「Katou」" 'br)
   (text-delay 2)
   (text "I have high expectations for you. Hurry up and catch those prisoners.")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 297 #t)
   (proc 1))
 (seg (? (= S 2) (= 297 #t))
   (proc 0)
   (text-delay 0)
   (text "「Katou」" 'br)
   (text-delay 2)
   (text "I have high expectations for you. Hurry up and catch those prisoners.")
   (wait)
   (text-reset 14)
   (proc 1))
 (seg (? (= S 3) (= 300 #f))
   (proc 0)
   (text-delay 2)
   (text "Anna's office faces the opposite direction from my room," 'br)
   (text "looking straight down at the cluttered streets below.")
   (wait)
   (text-reset 14)
   (text "Being on a higher floor gives it a better view. But when all" 'br)
   (text "you have to look at is this dark cityscape, you can't really" 'br)
   (text "call it scenic.")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 300 #t)
   (proc 1))
 (seg (? (= S 3) (= 301 #f))
   (proc 0)
   (text "The large, ornate window facing the front of the building" 'br)
   (text "must be clearly visible from the street. Someone could shoot" 'br)
   (text "through it at any moment.")
   (wait)
   (text-reset 14)
   (text "Despite her high rank in Intelligence, Anna's gotten stuck" 'br)
   (text "with this terrible room. There are some powerful people who" 'br)
   (text "resent her success, and this is their way of showing it.")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 301 #t)
   (proc 1))
 (seg (? (= S 3) (= 301 #t))
   (proc 0)
   (text "Anna's office faces the opposite direction from my room," 'br)
   (text "overlooking the trash-filled streets below.")
   (wait)
   (text-reset 14)
   (proc 1))
 (seg (? (= S 4) (= 55 #t))
   (proc 0)
   (text "The markings on the prisoners, and the fact that my goggles" 'br)
   (text "can detect them......")
   (wait)
   (text-reset 14)
   (text "Katou definitely kept quiet about it on purpose. Why? Did" 'br)
   (text "he just want to see me struggle, or is there something more" 'br)
   (text "to it?")
   (wait)
   (text-reset 14)
   (proc 1))
 (seg (? (= S 4) (= 253 #t) (= 287 #t))
   (proc 0)
   (text-delay 2)
   (text "Even if I know where April and Lei-Fa might be, finding them" 'br)
   (text "is still going to be nearly impossible.")
   (wait)
   (text-reset 14)
   (text-delay 2)
   (text "I need to let Anna and Katou know I'm stuck - and that it's" 'br)
   (text "not my fault!")
   (wait)
   (text-reset 14)
   (proc 1))
 (seg (? (= S 4) (= 302 #f))
   (proc 0)
   (text-delay 2)
   (text "Anna and Katou don't seem happy to see me. They must" 'br)
   (text "think I came here to complain mid-mission......")
   (wait)
   (text-reset 14)
   (text-delay 2)
   (text "I don't want to look pathetic either, but I need to make them" 'br)
   (text "understand this mission really is impossible without more data.")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 302 #t)
   (proc 1))
 (seg (? (= S 4) (= 302 #t))
   (proc 0)
   (text-delay 2)
   (text "Anna and Katou don't seem happy to see me. They must" 'br)
   (text "think I came here to complain mid-mission......")
   (wait)
   (text-reset 14)
   (proc 1))
 (seg*))