; X-Girl - Cyberpunk Adventure (PC-98) - MA_C01A.MES
; Translation by Fuzion
; Script Editing by Tan2000
; Content Revision by OldCorpo
; Chapter 1 - April and Lei-Fa
; Section 1.1 - Anna's consolation
; -----Location:-----
; Anna's Room
; -----Scene:-----
; Kiyomi offers "consolation" to Anna (Part 2).
; --Progression:--
; Play and talk with Anna until the scene finished.
(mes
 (meta (engine 'ADV) (charset "pc98") (extraop #t))
 (seg*
  (exec-mem 14080 2 24 4 135 71 80 34 80 34 0 30)
  (image-file "gpc¥b02_02.gpc")
  (image-mem 0 3)
  (if (</>
       (//
        (? (!= P 7))
        (if (</>
             (//
              (? (= O 0))
              (sound '|| 0)
              (sound '|| "uso¥xg_07.uso")
              (sound '|| 1)
              (nop@)
              (set-var P 7))
             (//
              (? (= O 1))
              (sound '|| 0)
              (sound '|| "uso¥xg_07v.uso")
              (sound '|| 1)
              (nop@)
              (set-var P 7)))))
       (// (nop@))))
  (proc 3)
  (text-frame 10 312 70 383)
  (text-delay 0)
  (str "「Anna」" 'br)
  (text-delay 2)
  (str "Haa......")
  (wait)
  (text-reset 14)
  (text-delay 0)
  (str "「Kiyomi」" 'br)
  (text-delay 2)
  (str "It's been so long since I've played with you. You really are" 'br)
  (str "a bad girl, seducing me in the middle of a mission.")
  (wait)
  (text-reset 14)
  (text-delay 0)
  (str "「Anna」" 'br)
  (text-delay 2)
  (str "Don't call me that... And please, turn off the lights!")
  (wait)
  (text-reset 14)
  (text-delay 0)
  (str "「Kiyomi」" 'br)
  (text-delay 2)
  (str "You know I prefer it like this. I think I'll leave them on so")
  (str "I can see you squirm in pleasure.")
  (wait)
  (text-reset 14)
  (text-delay 0)
  (str "「Anna」" 'br)
  (text-delay 2)
  (str "But what if someone sees us, Kiyomi? What if there are hidden")
  (str "cameras?")
  (wait)
  (text-reset 14)
  (text-delay 0)
  (str "「Kiyomi」" 'br)
  (text-delay 2)
  (str "Let them watch, Anna. What if someone's jerking off to the" 'br)
  (str "sight of your pussy right now?")
  (wait)
  (text-reset 14)
  (text-delay 0)
  (str "「Anna」" 'br)
  (text-delay 2)
  (str "Don't say things like that...... just thinking about it makes")
  (str "me sick!")
  (wait)
  (text-reset 14)
  (text-delay 0)
  (str "「Kiyomi」" 'br)
  (text-delay 2)
  (str "You hate Japanese people, right? Especially military ones." 'br)
  (str "Imagine one of them is monitoring us right now.")
  (wait)
  (text-reset 14)
  (text-delay 0)
  (str "「Anna」" 'br)
  (text-delay 2)
  (str "Mnnh! Please... stop talking... I can't focus...")
  (wait)
  (text-reset 14)
  (str "Anna's skin is like ice; smooth and cold to the touch." 'br)
  (str "It doesn't feel any warmer than room temperature.")
  (wait)
  (text-reset 14)
  (text-delay 0)
  (str "「Kiyomi」" 'br)
  (text-delay 2)
  (str "You're so pale, Anna. They say women from cold countries" 'br)
  (str "have skin like yours......")
  (wait)
  (text-reset 14)
  (text-delay 0)
  (str "「Anna」" 'br)
  (text-delay 2)
  (str "Don't look at me so closely. It's... It's embarrassing.")
  (wait)
  (text-reset 14)
  (text-delay 0)
  (str "「Kiyomi」" 'br)
  (text-delay 2)
  (str "Who are you talking to, Anna? Me? Or the guy behind the" 'br)
  (str "screen, jerking off to you?")
  (wait)
  (text-reset 14)
  (text-delay 0)
  (str "「Anna」" 'br)
  (text-delay 7)
  (str "..................")
  (wait)
  (text-reset 14)
  (text-delay 2)
  (str "I lean down and lick Anna's sensitive nipple, making her" 'br)
  (str "gasp. I trail my tongue up her side to her armpit and" 'br)
  (str "suck out her sweat.")
  (wait)
  (text-reset 14)
  (str "Her shy look changed into a pained one as I leaned over her.")
  (wait)
  (text-reset 14)
  (text-delay 0)
  (str "「Anna」" 'br)
  (text-delay 2)
  (str "Kiyomi, you're so heavy... it feels like I'm being crushed.")
  (wait)
  (text-reset 14)
  (text-delay 0)
  (str "「Kiyomi」" 'br)
  (text-delay 2)
  (str "Of course I'm heavier than you, Anna. But you can still" 'br)
  (str "breathe, right?")
  (wait)
  (text-reset 14)
  (str "I lean down, taking Anna's nipple into my mouth, sucking" 'br)
  (str "gently. I can feel her body tense beneath me, her breath" 'br)
  (str "hitching as she responds to my touch.")
  (wait)
  (text-reset 14)
  (str "I trace my fingers along her sides, her hips, her thighs," 'br)
  (str "using her heightened sensitivity to my advantage.")
  (wait)
  (text-reset 14)
  (text-delay 0)
  (str "「Anna」" 'br)
  (text-delay 2)
  (str "Ah... it tickles there!")
  (wait)
  (text-reset 14)
  (text-delay 0)
  (str "「Kiyomi」" 'br)
  (text-delay 2)
  (str "But does it feel good?")
  (wait)
  (text-reset 14)
  (text-delay 0)
  (str "「Anna」" 'br)
  (text-delay 2)
  (str "Mmh...... yes, it feels really good.........")
  (wait)
  (text-reset 14)
  (str "Anna's body is a pod-mod, and as close to white as possible." 'br)
  (str "Even though my touch is making her twitch and tremble," 'br)
  (str "there's only a slight red flush on her skin.")
  (wait)
  (text-reset 14)
  (text-delay 0)
  (str "「Kiyomi」" 'br)
  (text-delay 2)
  (str "You seem to be enjoying this quite a bit.")
  (wait)
  (text-reset 14)
  (text-delay 0)
  (str "「Anna」" 'br)
  (text-delay 2)
  (str "That's because...... you haven't come to see me in so long...")
  (wait)
  (text-reset 14)
  (text-delay 0)
  (str "「Kiyomi」" 'br)
  (text-delay 2)
  (str "It's not that I dislike you, Anna. I just... I can't stand" 'br)
  (str "this room, or the building it's in. You know that.")
  (wait)
  (text-reset 14)
  (text-delay 0)
  (str "「Anna」" 'br)
  (text-delay 2)
  (str "..................")
  (wait)
  (text-reset 14)
  (text-delay 0)
  (str "「Kiyomi」" 'br)
  (text-delay 2)
  (str "I'll give you plenty of service to make up for lost time.")
  (wait)
  (text-reset 14)
  (text-delay 0)
  (str "「Anna」" 'br)
  (text-delay 2)
  (str "Nnh......Ahn!")
  (wait)
  (text-reset 14)
  (str "I slide my fingers down Anna's body, finding her center." 'br)
  (str "I press against her, feeling the wetness that's already" 'br)
  (str "gathered soak my fingers.")
  (wait)
  (text-reset 14)
  (text-delay 0)
  (str "「Kiyomi」" 'br)
  (text-delay 2)
  (str "I can feel you... it's getting hot down here.")
  (wait)
  (text-reset 14)
  (text-delay 0)
  (str "「Anna」" 'br)
  (text-delay 2)
  (str "Yes, I feel it, it's so good... ahh, Kiyomi!")
  (wait)
  (text-reset 14)
  (text-delay 0)
  (str "「Kiyomi」" 'br)
  (text-delay 2)
  (str "What a lovely smell. The smell of Anna's juices...")
  (wait)
  (text-reset 14)
  (text-delay 0)
  (str "「Kiyomi」" 'br)
  (text-delay 2)
  (str "Only this place is colored any differently. It's a beautiful pink...")
  (wait)
  (text-reset 14)
  (text-delay 0)
  (str "「Anna」" 'br)
  (text-delay 2)
  (str "..................")
  (wait)
  (text-reset 14)
  (text-delay 0)
  (str "「Anna」" 'br)
  (text-delay 2)
  (str "Kiyomi...... Please keep me safe. Please protect me.")
  (wait)
  (text-reset 14)
  (text-delay 0)
  (str "「Kiyomi」" 'br)
  (text-delay 2)
  (str "I'll always protect you, Anna.")
  (wait)
  (text-reset 14)
  (text-delay 0)
  (str "「Kiyomi」" 'br)
  (text-delay 2)
  (str "Why are you bringing this up?")
  (wait)
  (text-reset 14)
  (text-delay 0)
  (str "「Anna」" 'br)
  (text-delay 2)
  (str "......It's fine, don't worry about it.")
  (wait)
  (text-reset 14)
  (text-delay 0)
  (str "「Kiyomi」" 'br)
  (text-delay 2)
  (str "Then, I'll make you feel so good you won't be able to think" 'br)
  (str "of anything else.")
  (wait)
  (text-reset 14)
  (str "I squeeze Anna's breasts hard enough to leave marks on them," 'br)
  (str "and slowly rub my crotch against hers.")
  (wait)
  (text-reset 14)
  (text-delay 0)
  (str "「Anna」" 'br)
  (text-delay 2)
  (str "Ah! Aah...Kiyomi, ah〜n!")
  (wait)
  (text-reset 14)
  (str "The sound of our bodies sliding together fills the room," 'br)
  (str "a wet, slick sound that echoes in the silence.")
  (wait)
  (text-reset 14)
  (str "My own clit brushes against Anna's, filling me with" 'br)
  (str "unexpected electricity. The sweet, numbing stimulation" 'br)
  (str "paralyzes my brain, and I sink into an abyss of pleasure.")
  (wait)
  (text-reset 14)
  (text-delay 0)
  (str "「Kiyomi」" 'br)
  (text-delay 2)
  (str "Anna, move your hips more!")
  (wait)
  (text-reset 14)
  (text-delay 0)
  (str "「Anna」" 'br)
  (text-delay 2)
  (str "Mmm...... Kiyomi, ah...... I can't hold it...... Oh, God!")
  (wait)
  (text-reset 14)
  (text-delay 0)
  (str "「Kiyomi」" 'br)
  (text-delay 2)
  (str "Together... Anna!")
  (wait)
  (text-reset 14)
  (text-delay 0)
  (str "「Anna」" 'br)
  (text-delay 2)
  (str "Ah! Ahhhhhhh〜!!")
  (wait)
  (text-reset 14)
  ((cmd 209) 0 5)
  (nop@)
  (set-reg 920 #t)
  (sound '|| 2)
  (delay 50)
  (sound '|| 0)
  (nop@)
  (set-var P 0)
  (exec-mem 3072 0)
  (mes-jump "mes¥MA_C01.MES"))) ; Back to Anna's room again
