; X-Girl - Cyberpunk Adventure (PC-98) - MA_C01.MES
; Translation by Fuzion
; Script Editing by Tan2000
; Content Revision by OldCorpo
; Chapter 1 - April and Lei-Fa
; Section 1.1 - Anna's consolation
; -----Location:-----
; Anna's Room
; -----Scene:-----
; Meet with Anna.
; --Progression:--
; Talk with Anna, inspect her body & the bedroom, offer "consolation" to Anna.
(mes
 (meta (engine 'ADV) (charset "pc98") (extraop #t))
 (seg*
  (branch-reg 54 (</> (/) (/ (mes-jump "mes¥ma_c02.mes"))))
  (if (</>
       (//
        (? (= 920 #t)) ; Lead-in from "consolation" MA_C01A.MES script (one time only)
        (image-file "gpc¥waku.gpc")
        (image-mem 0 3)
        ((cmd 209) 1 5)
        (exec-mem 14080 2 24 4 135 71 80 34 80 34 0 30)
        (image-file "gpc¥b02_01.gpc")
        (image-mem 0 3)
        (image-file "gpc¥b02_01a.gpc")
        (image-mem 0 3)
        (proc 3)
        (if (</>
             (//
              (? (!= P 5))
              (if (</>
                   (//
                    (? (= O 0))
                    (sound '|| 0)
                    (sound '|| "uso¥xg_05.uso")
                    (sound '|| 1)
                    (nop@)
                    (set-var P 5))
                   (//
                    (? (= O 1))
                    (sound '|| 0)
                    (sound '|| "uso¥xg_05v.uso")
                    (sound '|| 1)
                    (nop@)
                    (set-var P 5)))))
             (// (nop@))))
        (load-mem "clm¥b02_01a.clm" 32768)
        (text-frame 10 312 70 383)
        (set-reg 219 #t)
        (nop@)
        (text-delay 0)
        (str "「Anna」" 'br)
        (text-delay 2)
        (str "............")
        (wait)
        (text-reset 14)
        (text-delay 0)
        (str "「Kiyomi」" 'br)
        (text-delay 2)
        (str "So, are you still cold?")
        (wait)
        (text-reset 14)
        (text-delay 0)
        (str "「Anna」" 'br)
        (text-delay 2)
        (str "I'm fine now...... But I can't shake this feeling of guilt." 'br)
        (str "I may have dragged you into something terrible, Kiyomi.")
        (wait)
        (text-reset 14)
        (text-delay 0)
        (str "「Kiyomi」" 'br)
        (text-delay 2)
        (str "Don't worry, we'll get through this together. Just like we" 'br)
        (str "always have before.")
        (wait)
        (text-reset 14)
        (text-delay 0)
        (str "「Anna」" 'br)
        (text-delay 5)
        (str "............")
        (text-delay 2)
        (wait)
        (text-reset 14)
        (nop@)
        (set-reg 920 #f))
       (//
        (? (= 919 #t)) ; Lead-in from previous MES script, repeated line
        (exec-mem 14080 2 24 4 135 71 80 34 80 34 0 30)
        (image-file "gpc¥b02_01.gpc")
        (image-mem 0 3)
        (image-file "gpc¥b02_01a.gpc")
        (image-mem 0 3)
        (proc 3)
        (load-mem "clm¥b02_01a.clm" 32768)
        (text-frame 10 312 70 383)
        (text-delay 0)
        (str "「Anna」" 'br)
        (text-delay 2)
        (str "Kiyomi...... Have you found any leads?")
        (wait)
        (text-reset 14)
        (set-reg 52 #t)
        (nop@))
       (//
        (? (= 919 #f)) ; Lead-in from previous MA_A01.MES script, 1st conversation with Anna (one time only)
        (exec-mem 14080 2 24 4 135 71 80 34 80 34 0 30)
        (image-file "gpc¥b02_01.gpc")
        (image-mem 0 3)
        (image-file "gpc¥b02_01a.gpc")
        (image-mem 0 3)
        (proc 3)
        (load-mem "clm¥b02_01a.clm" 32768)
        (text-frame 10 312 70 383)
        (text-delay 2)
        (str "「Anna」" 'br)
        (str "Kiyomi......")
        (wait)
        (text-reset 14)
        (text-delay 0)
        (str "「Kiyomi」" 'br)
        (text-delay 2)
        (str "I came, just like you asked.")
        (wait)
        (text-reset 14)
        (text-delay 0)
        (str "「Anna」" 'br)
        (text-delay 2)
        (str "I'm sorry about earlier, I had to act that way in front of" 'br)
        (str "Katou. Making an enemy of him would be stupid.")
        (wait)
        (text-reset 14)
        (text-delay 0)
        (str "「Kiyomi」" 'br)
        (text-delay 2)
        (str "I get that. But you're going to explain why you got me into" 'br)
        (str "this mess in the first place, right?")
        (wait)
        (text-reset 14)
        (text-delay 0)
        (str "「Anna」" 'br)
        (text-delay 2)
        (str "I can't explain it. I had no choice.")
        (wait)
        (text-reset 14)
        (text-delay 0)
        (str "「Anna」" 'br)
        (text-delay 2)
        (str "There's no one I can rely on but you......")
        (wait)
        (text-reset 14))))
  (nop@)
  (set-reg 919 #t)
  (exec-mem 3968 102 500 360)
  (exec-mem 3072 1)
  (loop (set-var S 0) (exec-mem 3072 1020 1021 "S" 32768) (seg-call)))
 (seg (? (= 1020 #f) (= 1021 #f)) (exec-mem 3072 1))
 (seg (? (= 1021 #t) (= 52 #t))
   (exec-mem 3072 0)
   (exec-mem 3968 103)
   (exec-mem 256 "A 0 S 0")
   (exec-mem 256 "G 1 4 64 12 48")
   (exec-mem 4768 4 8 12 4 1 0 0 4480 4480 1 0)
   (menu1 5 72 (</> (/ (str "  Travel  "))))
   (if (</>
        (//
         (? (= S 0))
         (exec-mem 256 "A 0 S 0")
         (exec-mem 256 "G 9 5 72 22 64")
         (exec-mem 4768 5 9 22 6 1 0 0 4480 4480 1 0)
         (menu1
          6
          80
          6
          96
          (</> (/ (str "   Kiyomi's Room    ")) (/ (str "   Anna's Office    "))))
         (exec-mem 256 "P 9 5 72")
         (exec-mem 256 "P 1 4 64")
         (if (</>
              (// (? (= S 0)) (mes-jump "mes¥MA_A01.MES")) ; Go to Kiyomi's room
              (// (? (= S 1)) (mes-jump "mes¥MA_B01.MES")) ; Go to Anna's office
              (// (? (= S 255))))))
        (// (? (= S 255)) (exec-mem 256 "P 1 4 64"))))
   (exec-mem 3968 104)
   (exec-mem 3072 2)
   (exec-mem 3072 1))
 (seg (? (= 1021 #t)) (exec-mem 3072 1))
 (seg (? (= S 1) (= 219 #t) (= 52 #t)) ; lines after "consolation" session (repeat line)
   (proc 0)
   (text-delay 0)
   (str "「Anna」" 'br)
   (text-delay 2)
   (str "April and Lei-Fa's former commander is stationed" 'br)
   (str "at Ichigaya Base.")
   (wait)
   (text-reset 14)
   (proc 1))
 (seg (? (= S 1) (= 219 #t) (= 52 #f)) ; lines after "consolation" session (1st time)
   (proc 0)
   (text-delay 0)
   (str "「Kiyomi」" 'br)
   (text-delay 2)
   (str "I suppose it was too much to hope that I could ignore this." 'br)
   (str "Alright, Anna, what do you need me to do?")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (str "「Anna」" 'br)
   (text-delay 2)
   (str "Two of the prisoners...... April and Lei-Fa, their commander" 'br)
   (str "is over at Ichigaya Base.")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (str "「Kiyomi」" 'br)
   (text-delay 2)
   (str "Ichigaya Base, huh. How long were those two in the military?")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (str "「Anna」" 'br)
   (text-delay 2)
   (str "Until a year ago. They completed their mandatory 3 years of" 'br)
   (str "service to earn citizenship, and are now in the reserves.")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (str "「Kiyomi」" 'br)
   (text-delay 2)
   (str "You did say they were Special Forces. Three years on the" 'br)
   (str "front lines is impressive, especially for immigrants.")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (str "「Anna」" 'br)
   (text-delay 2)
   (str "Yes, it is. They're no ordinary soldiers.")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (str "「Kiyomi」" 'br)
   (text-delay 2)
   (str "These days, you can't throw a rock without hitting a former" 'br)
   (str "*something*. Hackers, hitmen... they're everywhere.")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (str "「Kiyomi」" 'br)
   (text-delay 2)
   (str "The world has become a difficult place to live in for us.")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (str "「Anna」" 'br)
   (text-delay 2)
   (str "............Be careful out there.")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (str "「Kiyomi」" 'br)
   (text-delay 2)
   (str "Yeah, I've got to be careful. These women are real" 'br)
   (str "professionals......")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 52 #t)
   (proc 1))
 (seg (? (= S 1) (= 218 #t) (= 221 #t) (= 225 #t)) ; Kiyomi offers "consolation" to Anna
   (proc 0)
   (text-delay 0)
   (str "「Anna」" 'br)
   (text-delay 2)
   (str "Kiyomi")
   (text-delay 15)
   (str "...... ")
   (delay 30)
   (text-delay 5)
   (str "I'm scared.")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (str "「Kiyomi」" 'br)
   (text-delay 2)
   (str "What's wrong, Anna? Does Katou have dirt on you or something?")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (str "「Anna」" 'br)
   (text-delay 2)
   (str "If this gets much worse, the military will start looking for" 'br)
   (str "a scapegoat. And immigrants like me are the perfect target.")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (str "「Kiyomi」" 'br)
   (text-delay 2)
   (str "Don't be ridiculous, Anna. The military can't afford to" 'br)
   (str "ignore such a huge vulnerability in their organization.")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (str "「Kiyomi」" 'br)
   (text-delay 2)
   (str "I'll do whatever it takes to find the traitor. It could be" 'br)
   (str "a sleeper agent, sent by some foreign country.")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (str "「Anna」" 'br)
   (text-delay 2)
   (str "From a foreign country, like me? That only makes things" 'br)
   (str "worse!")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (str "「Kiyomi」" 'br)
   (text-delay 2)
   (str "Whoa, Anna, calm down. You're overreacting.")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (str "「Anna」" 'br)
   (text-delay 2)
   (str "Easy for you to say...... You're full Japanese, after all.")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (str "「Kiyomi」" 'br)
   (text-delay 2)
   (str "..................")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (str "「Anna」" 'br)
   (text-delay 2)
   (str "I'm cold...")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (str "「Kiyomi」" 'br)
   (text-delay 2)
   (str "It's been cold outside, too. I think they're diverting the" 'br)
   (str "power meant for heating the city to somewhere else.")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (str "「Anna」" 'br)
   (text-delay 2)
   (str "No, that's not it......")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (str "「Anna」" 'br)
   (text-delay 2)
   (str "Kiyomi, I need you to hold me tight.")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (str "「Kiyomi」" 'br)
   (text-delay 2)
   (str "You're being quite demanding today, Anna. It's no surprise" 'br)
   (str "after you had to deal with Katou for so long.")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (str "「Kiyomi」" 'br)
   (text-delay 2)
   (str "He really is a bastard.")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (str "「Anna」" 'br)
   (text-delay 2)
   (str "Please, just hold me!")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (str "「Kiyomi」" 'br)
   (text-delay 2)
   (str "......Ahh, fine. If that's what you really need.")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 219 #t)
   (sound '|| 2)
   (delay 50)
   ; This track song #6 doesn't play, it skipped and move to next scene
   (if (</>
        (//
         (? (!= P 6))
         (if (</>
              (//
               (? (= O 0))
               (sound '|| 0)
               (sound '|| "uso¥xg_06.uso")
               (sound '|| 3)
               (nop@)
               (set-var P 6))
              (//
               (? (= O 1))
               (sound '|| 0)
               (sound '|| "uso¥xg_06v.uso")
               (sound '|| 3)
               (nop@)
               (set-var P 6)))))
        (// (nop@))))
   (exec-mem 3072 0)
   (mes-jump "mes¥MA_C01A.MES")) ; Move to next scene
 (seg (? (= S 1) (= 217 #f)) ; Talk to Anna (1st time conversation)
   (proc 0)
   (text-delay 0)
   (str "「Kiyomi」" 'br)
   (text-delay 2)
   (str "I need you to break the situation down for me. How did the" 'br)
   (str "leak happen? And what's the relation between the 4 escapees?")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (str "「Anna」" 'br)
   (text-delay 2)
   (str "I can't tell you anything about the classified information." 'br)
   (str "I don't even have clearance to view it myself.")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (str "「Anna」" 'br)
   (text-delay 2)
   (str "However, it seems to be about a system being developed in" 'br)
   (str "partnership between the military and a private corporation.")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (str "「Kiyomi」" 'br)
   (text-delay 2)
   (str "You're being pretty vague......")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (str "「Anna」" 'br)
   (text-delay 2)
   (str "I'm telling you all the details I know.")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (str "「Kiyomi」" 'br)
   (text-delay 2)
   (str "So how did the prisoners get their hands on that information?")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (str "「Anna」" 'br)
   (text-delay 2)
   (str "We suspect it was leaked by Mitsuko, who used to be the" 'br)
   (str "secretary of a top military officer.")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (str "「Anna」" 'br)
   (text-delay 2)
   (str "Of course, by now that officer has been dealt with.")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (str "「Anna」" 'br)
   (text-delay 2)
   (str "We don't know how the prisoners are connected. I don't think" 'br)
   (str "they knew each other at all before they were captured.")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (str "「Kiyomi」" 'br)
   (text-delay 2)
   (str "It's likely that someone arranged their meeting. And that" 'br)
   (str "\"someone\" is probably in intel or the military.")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (str "「Kiyomi」" 'br)
   (text-delay 2)
   (str "Otherwise, it would be nearly impossible for four prisoners" 'br)
   (str "to escape at once.")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (str "「Anna」" 'br)
   (text-delay 2)
   (str "Yes, that's what we think too......")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 217 #t)
   (proc 1))
 (seg (? (= S 1) (= 218 #f)) ; Talk to Anna (1st time conversation)
   (proc 0)
   (text-delay 0)
   (str "「Kiyomi」" 'br)
   (text-delay 2)
   (str "Tell me more about the contents of the stolen classified" 'br)
   (str "information. I don't know enough to get the full picture.")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (str "「Anna」" 'br)
   (text-delay 2)
   (str "It started with the military and its private business partner")
   (str "working together to build some kind of system.")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (str "「Kiyomi」" 'br)
   (text-delay 2)
   (str "Someone, somewhere, found out about it and decided to hire" 'br)
   (str "former professionals to steal info about the secret tech...")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (str "「Anna」" 'br)
   (text-delay 2)
   (str "Right...... The team successfully stole the information and" 'br)
   (str "passed it on to the mastermind who hired them.")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (str "「Kiyomi」" 'br)
   (text-delay 2)
   (str "But you don't know if they delivered the stolen intel or not,")
   (str "right? Since the culprit was caught shortly afterwards.")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (str "「Kiyomi」" 'br)
   (text-delay 2)
   (str "It's hard to believe that a \"professional\" would make such" 'br)
   (str "a simple mistake.")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (str "「Anna」" 'br)
   (text-delay 2)
   (str "That's true......")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (str "「Anna」" 'br)
   (text-delay 2)
   (str "However, the captured team member was broken out and" 'br)
   (str "disappeared before we could interrogate them.")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (str "「Anna」" 'br)
   (text-delay 2)
   (str "It appears someone within the military helped them escape." 'br)
   (str "Or at least, someone with serious inside connections.")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (str "「Kiyomi」" 'br)
   (text-delay 2)
   (str "Yeah, the situation is pretty bad. If this gets out," 'br)
   (str "the Intel director's head will roll.")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (str "「Anna」" 'br)
   (text-delay 2)
   (str "Even that wouldn't fix things.")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 218 #t)
   (proc 1))
 (seg (? (= S 1) (= 218 #t)) ; Repeat line
   (proc 0)
   (text-delay 0)
   (str "「Anna」" 'br)
   (text-delay 2)
   (str "There's still a leak in our organization that hasn't been" 'br)
   (str "found.")
   (wait)
   (text-reset 14)
   (proc 1))
 (seg (? (= S 2) (= 220 #f)) ; Look at Anna's body (1st time)
   (proc 0)
   (str "Her slender body looks like it would break if you touched it.")
   (str "For a pod-mod, her skin is unusually pale. No matter how" 'br)
   (str "I look at her, she doesn't seem tough at all.")
   (wait)
   (text-reset 14)
   (str "Climbing the ranks to her current position in Intel must have")
   (str "been a difficult battle.")
   (wait)
   (text-reset 14)
   (str "I know she has a socket, though it's not visible from this" 'br)
   (str "angle. It was probably essential for her to get this far.")
   (wait)
   (text-reset 14)
   (str "To survive in this world, you either have to be tough as" 'br)
   (str "nails or sharp as a razor.")
   (wait)
   (text-reset 14)
   (str "I doubt anyone would blame her for enhancing her body to" 'br)
   (str "compensate for her weakness.")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 220 #t)
   (proc 1))
 (seg (? (= S 2) (= 221 #f)) ; Look at Anna's body (2nd time - repeat line) before talk to Anna
   (proc 0)
   (branch-reg
    218
    (</>
     (/
      (str "I've never heard anyone mention it before, but I wonder how" 'br)
      (str "old Anna is. If she's ex-KGB like the rumours say, then she'd")
      (str "have to be much older than me.")
      (wait)
      (text-reset 14)
      (str "This city is full of people like Anna with unknown pasts. Not")
      (str "just immigrants, either. It's like they're all frozen in" 'br)
      (str "time."))
     (/
      (str "Anna seems to have lost her usual calm demeanor. Her slender" 'br)
      (str "fingers are clasped in front of her, trembling slightly.")
      (wait)
      (text-reset 14)
      (str "Anna's trendy, intricate, and flamboyant dress is carefully" 'br)
      (str "designed to make her body appear larger than she really is.")
      (wait)
      (text-reset 14)
      (str "But thanks to her anxious look and posture, the tailor's hard")
      (str "work is undone and she looks like a helpless child in adult" 'br)
      (str "clothes.")
      (wait)
      (text-reset 14)
      (str "What could have Anna so worried?")
      (nop@)
      (set-reg 221 #t))))
   (wait)
   (text-reset 14)
   (proc 1))
 (seg (? (= S 2) (= 221 #t)) ; Repeat line after talk to Anna
   (proc 0)
   (text-delay 2)
   (str "Anna's shaking has gotten more intense, her arms wrapped" 'br)
   (str "tightly around her body as though she's freezing.")
   (wait)
   (text-reset 14)
   (proc 1))
 (seg (? (= S 3) (= 222 #f))
   (proc 0)
   (str "Anna's private room is lower than mine, and the view isn't" 'br)
   (str "quite as good.")
   (wait)
   (text-reset 14)
   (str "The view is blocked by overgrown tree branches, and the sound")
   (str "from outside is muffled as well.")
   (wait)
   (text-reset 14)
   (str "However, in this city, the higher a room is, the lower it is.")
   (str "The whole building is located more than a hundred meters" 'br)
   (str "underground.")
   (wait)
   (text-reset 14)
   (str "The real important people live further underground in the" 'br)
   (str "city. If a disaster were to happen and the roof caved in, all")
   (str "these exposed buildings would be obliterated.")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 222 #t)
   (proc 1))
 (seg (? (= S 3) (= 223 #f))
   (proc 0)
   (str "The heat emitting from people's bodies and the moisture" 'br)
   (str "drifting up from the ground combine to create a thick mist" 'br)
   (str "that lingers outside the window.")
   (wait)
   (text-reset 14)
   (str "Soon, that mist will condense into rain. The city planners" 'br)
   (str "stopped trying to manage the weather long ago.")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 223 #t)
   (proc 1))
 (seg (? (= S 3) (= 223 #t))
   (proc 0)
   (text-delay 2)
   (str "Outside the window, it's as dark as night because of the" 'br)
   (str "drifting fog. But day and night look practically the same" 'br)
   (str "here, save for the brightness of the sky-lights.")
   (wait)
   (text-reset 14)
   (proc 1))
 (seg (? (= S 4) (= 224 #f))
   (proc 0)
   (str "Anna's room is full of furniture from her homeland, making it")
   (str "one of the most unique rooms in the division.")
   (wait)
   (text-reset 14)
   (str "Though, if you consider that it's her only home, it seems" 'br)
   (str "very sterile. If Anna wasn't here, I'd think this was" 'br)
   (str "a storage room.")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 224 #t)
   (proc 1))
 (seg (? (= S 4) (= 225 #f))
   (proc 0)
   (str "With her high rank, there's no reason Anna should be required")
   (str "to stay in the Intelligence building.")
   (wait)
   (text-reset 14)
   (str "The reason she's still here is probably for her own safety." 'br)
   (str "There are people all over the city who are bitter about" 'br)
   (str "people like Anna succeeding.")
   (wait)
   (text-reset 14)
   (str "How can a single woman, especially someone delicate like" 'br)
   (str "Anna, possibly live alone safely?")
   (wait)
   (text-reset 14)
   (str "It's practically impossible for her to move out of this" 'br)
   (str "building.")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 225 #t)
   (proc 1))
 (seg (? (= S 4) (= 225 #t))
   (proc 0)
   (text-delay 2)
   (str "This place may be lonely and empty, but it's Anna's only" 'br)
   (str "place to live. Better this than living on the street......")
   (wait)
   (text-reset 14)
   (proc 1))
 (seg*))
