(mes
 (meta (engine 'ADV) (charset "english") (extraop #t))
 (seg*
  (if (</> (// (? (= 58 #t) (= 60 #t)) (mes-jump "mes¥ma_c03.mes")) (//)))
  (exec-mem 14080 2 24 4 135 71 80 34 80 34 0 30)
  (if (</>
       (// (? (= 55 #f)) (image-file "gpc¥b02_01.gpc") (image-mem 0 3))
       (//
        (image-file "gpc¥b02_01.gpc")
        (image-mem 0 3)
        (image-file "gpc¥b02_01a.gpc")
        (image-mem 0 3)
        (load-mem "clm¥b02_01a.clm" 32768))))
  (proc 3)
  (text-frame 10 312 70 383)
  (if (</>
       (//
        (? (!= P 5))
        (if (</>
             (//
              (? (= O 0))
              (sound '|| 0)
              (sound '|| "uso¥xg_05.uso")
              (sound '|| 1)
              (nop@)
              (set-var P 5))
             (//
              (? (= O 1))
              (sound '|| 0)
              (sound '|| "uso¥xg_05v.uso")
              (sound '|| 1)
              (nop@)
              (set-var P 5)))))
       (// (nop@))))
  (if (</>
       (//
        (? (= 55 #f))
        (text "Anna isn't here. She's probably in her office......")
        (wait)
        (text-reset 14)
        (mes-jump "mes¥MA_A02.MES"))
       (//
        (? (= 921 #t))
        (text-delay 0)
        (text "「Anna」" 'br)
        (text-delay 2)
        (text "Kiyomi...... What is it?")
        (wait)
        (text-reset 14))
       (//
        (? (= 921 #f))
        (text-delay 0)
        (text "「Kiyomi」" 'br)
        (text-delay 2)
        (text "Anna, I need to ask you something......")
        (wait)
        (text-reset 14)
        (text-delay 0)
        (text "「Anna」" 'br)
        (text-delay 2)
        (text "What is it? Have you found April and Lei-Fa?")
        (wait)
        (text-reset 14)
        (text-delay 0)
        (text "「Kiyomi」" 'br)
        (text-delay 2)
        (text "That's not important right now.")
        (wait)
        (text-reset 14)
        (text-delay 0)
        (text "「Anna」" 'br)
        (text-delay 2)
        (text "It's not unimportant...... Are you angry with me?")
        (wait)
        (text-reset 14)
        (text-delay 0)
        (text "「Kiyomi」" 'br)
        (text-delay 2)
        (text "..................")
        (wait)
        (text-reset 14)
        (text-delay 0)
        (text "「Anna」" 'br)
        (text-delay 2)
        (text "You're frightening me. Don't look at me like that.")
        (wait)
        (text-reset 14)
        (text-delay 0)
        (text "「Kiyomi」" 'br)
        (text-delay 2)
        (text "........................")
        (wait)
        (text-reset 14))))
  (nop@)
  (set-reg 921 #t)
  (exec-mem 3968 102 500 360)
  (exec-mem 3072 1)
  (loop (set-var S 0) (exec-mem 3072 1020 1021 "S" 32768) (seg-call)))
 (seg (? (= 1020 #f) (= 1021 #f)) (exec-mem 3072 1))
 (seg (? (= 1021 #t) (= 52 #t))
   (exec-mem 3072 0)
   (exec-mem 3968 103)
   (exec-mem 256 "A 0 S 0")
   (exec-mem 256 "G 1 4 64 12 48")
   (exec-mem 4768 4 8 12 4 1 0 0 4480 4480 1 0)
   (menu1 5 72 (</> (/ (str "  Travel  "))))
   (if (</>
        (//
         (? (= S 0))
         (exec-mem 256 "A 0 S 0")
         (exec-mem 256 "G 9 5 72 22 64")
         (exec-mem 4768 5 9 22 6 1 0 0 4480 4480 1 0)
         (menu1
          6
          80
          6
          96
          (</> (/ (str "   Kiyomi's Room    ")) (/ (text "   Anna's Office   "))))
         (exec-mem 256 "P 9 5 72")
         (exec-mem 256 "P 1 4 64")
         (if (</>
              (//
               (? (= S 0))
               (branch-reg
                56
                (</>
                 (/ (mes-jump "mes¥MA_A02.MES"))
                 (/ (mes-jump "mes¥MA_A03.MES")))))
              (//
               (? (= S 1))
               (branch-reg
                55
                (</>
                 (/ (mes-jump "mes¥MA_B02.MES"))
                 (/ (mes-jump "mes¥MA_B03.MES")))))
              (// (? (= S 255))))))
        (// (? (= S 255)) (exec-mem 256 "P 1 4 64"))))
   (exec-mem 3968 104)
   (exec-mem 3072 2)
   (exec-mem 3072 1))
 (seg (? (= 1021 #t)) (exec-mem 3072 1))
 (seg (? (= S 1) (= 56 #t))
   (proc 0)
   (if (</>
        (//
         (? (= 57 #t) (= 58 #f) (= 59 #f) (= 60 #f))
         (nop@)
         (branch-reg
          308
          (</>
           (/
            (text-delay 0)
            (text "「Kiyomi」" 'br)
            (text-delay 2)
            (text "I've arrested April.")
            (wait)
            (text-reset 14)
            (text-delay 0)
            (text "「Anna」" 'br)
            (text-delay 2)
            (text "I see...... So she was in Akihabara after all?")
            (wait)
            (text-reset 14)
			;; line too long, had to split
            (text-delay 0)
            (text "「Kiyomi」" 'br)
            (text-delay 2)
            (text "She was disguised as a military surplus store clerk. Must" 'br)
            (text "have been planning that cover since before discharge.")
            (wait)
			(text-reset 14)
			(text-delay 0)
            (text "「Kiyomi」" 'br)
            (text-delay 2)
            (text "I'll be interrogating her soon.")
			(wait)
            (text-reset 14)
            (text-delay 0)
            (text "「Anna」" 'br)
            (text-delay 2)
            (text "I understand. I hope she'll talk......")
            (wait)
            (text-reset 14)
            (nop@)
            (set-reg 308 #t))
           (/
            (text-delay 0)
            (text "「Anna」" 'br)
            (text-delay 2)
            (text "Go interrogate April...... Don't forget to report back to me" 'br)
            (text "if you learn anything.")
            (wait)
            (text-reset 14)))))
        (//
         (? (= 57 #t) (= 58 #t) (= 59 #f) (= 60 #f))
         (nop@)
         (branch-reg
          309
          (</>
           (/
            (text-delay 0)
            (text "「Kiyomi」" 'br)
            (text-delay 2)
            (text "April didn't have much useful information.")
            (wait)
            (text-reset 14)
            (text-delay 0)
            (text "「Anna」" 'br)
            (text-delay 2)
            (text "Isn't it possible your torture simply didn't break her?")
            (wait)
            (text-reset 14)
            (text-delay 0)
            (text "「Kiyomi」" 'br)
            (text-delay 2)
            (text "She probably built up pain tolerance in Special Forces, but I" 'br)
            (text "can't believe she held out against my interrogation.")
            (wait)
            (text-reset 14)
            (text-delay 0)
            (text "「Kiyomi」" 'br)
            (text-delay 2)
            (text "I think April really doesn't know anything. Our only bet is" 'br)
            (text "Lei-Fa now.")
            (wait)
            (text-reset 14)
            (nop@)
            (set-reg 309 #t))
           (/
            (text-delay 0)
            (text "「Anna」" 'br)
            (text-delay 2)
            (text "Capture Lei-Fa quickly, before she realizes April's been" 'br)
            (text "arrested and flees.")
            (wait)
            (text-reset 14)))))
        (//
         (? (= 57 #t) (= 58 #t) (= 59 #t) (= 60 #f))
         (nop@)
         (branch-reg
          310
          (</>
           (/
            (text-delay 0)
            (text "「Kiyomi」" 'br)
            (text-delay 2)
            (text "I caught Lei-Fa. She was in Chinatown, just like I" 'br)
            (text "expected......")
            (wait)
            (text-reset 14)
            (text-delay 0)
            (text "「Anna」" 'br)
            (text-delay 2)
            (text "I see...... Start interrogating her right away.")
            (wait)
            (text-reset 14)
            (text-delay 0)
            (text "「Kiyomi」" 'br)
            (text-delay 2)
            (text "I will...... But why did Lei-Fa hide out in Chinatown of all" 'br)
            (text "places? It's way too obvious.")
            (wait)
            (text-reset 14)
            (text-delay 0)
            (text "「Anna」" 'br)
            (text-delay 2)
            (text "Maybe she wanted to be with her own people, even knowing the" 'br)
            (text "danger. Or perhaps she truly believed she could escape......")
            (wait)
            (text-reset 14)
            (text-delay 0)
            (text "「Kiyomi」" 'br)
            (text-delay 2)
            (text "If that's the case, then Lei-Fa's either really overconfident")
            (text "or just an idiot.")
            (wait)
            (text-reset 14)
            (set-reg 310 #t))
           (/
            (text-delay 0)
            (text "「Anna」" 'br)
            (text-delay 2)
            (text "Hopefully Lei-Fa will talk. If nothing else, we need to get" 'br)
            (text "a lead on the third prisoner......")
            (wait)
            (text-reset 14)))))
        (//
         (? (= 57 #t) (= 58 #f) (= 59 #t) (= 60 #f))
         (nop@)
         (branch-reg
          311
          (</>
           (/
            (text-delay 0)
            (text "「Kiyomi」" 'br)
            (text-delay 2)
            (text "I've arrested both April and Lei-Fa. Haven't interrogated" 'br)
            (text "them yet, though.")
            (wait)
            (text-reset 14)
            (text-delay 0)
            (text "「Anna」" 'br)
            (text-delay 2)
            (text "Saving the fun for later? I didn't think you were capable of" 'br)
            (text "that much restraint.")
            (wait)
            (text-reset 14)
            (text-delay 0)
            (text "「Kiyomi」" 'br)
            (text-delay 2)
            (text "You know prisoner psychology?")
            (wait)
            (text-reset 14)
            (text-delay 0)
            (text "「Kiyomi」" 'br)
            (text-delay 2)
            (text "Tell two prisoners that whoever sells out their partner" 'br)
            (text "goes free, but if they don't talk, they both die.")
            (wait)
            (text-reset 14)
            (text-delay 0)
            (text "「Kiyomi」" 'br)
            (text-delay 2)
            (text "They'll crack every time. They get paranoid their partner" 'br)
			(text "will betray them first, so they decide to do it themselves.")
            (wait)
            (text-reset 14)
            (text-delay 0)
            (text "「Anna」" 'br)
            (text-delay 2)
            (text "You're going to use that on April and Lei-Fa?")
            (wait)
            (text-reset 14)
            (text-delay 0)
            (text "「Kiyomi」" 'br)
            (text-delay 2)
            (text "Might not even need to. Though I'd like them to entertain me" 'br)
            (text "a little first.")
            (wait)
            (text-reset 14)
            (text-delay 0)
            (text "「Anna」" 'br)
            (text-delay 2)
            (text "Interrogation is your specialty. Do it however you want," 'br)
            (text "but don't let your guard down.")
            (wait)
            (text-reset 14)
            (text-delay 0)
            (text "「Anna」" 'br)
            (text-delay 2)
            (text "Remember, they're ex-Special Forces. Trained professionals" 'br)
            (text "just like you.")
            (wait)
            (text-reset 14)
            (nop@)
            (set-reg 311 #t))
           (/
            (text-delay 0)
            (text "「Anna」" 'br)
            (text-delay 2)
            (text "Interrogation is your specialty - do it however you want." 'br)
            (text "Just make sure you get them talking.")
            (wait)
            (text-reset 14)))))
        (//
         (? (= 57 #f) (= 58 #f) (= 59 #t) (= 60 #f))
         (nop@)
         (branch-reg
          311
          (</>
           (/
            (text-delay 0)
            (text "「Kiyomi」" 'br)
            (text-delay 2)
            (text "I caught Lei-Fa. She was in Chinatown, just like I" 'br)
            (text "expected......")
            (wait)
            (text-reset 14)
            (text-delay 0)
            (text "「Anna」" 'br)
            (text-delay 2)
            (text "I see...... Start interrogating her as soon as possible.")
            (wait)
            (text-reset 14)
            (text-delay 0)
            (text "「Kiyomi」" 'br)
            (text-delay 2)
            (text "I will...... But why did Lei-Fa hide out in Chinatown of all" 'br)
            (text "places? It's way too obvious.")
            (wait)
            (text-reset 14)
            (text-delay 0)
            (text "「Anna」" 'br)
            (text-delay 2)
            (text "Maybe she wanted to be with her own people, even knowing the" 'br)
            (text "danger. Or maybe she truly believed she could escape......")
            (wait)
            (text-reset 14)
            (text-delay 0)
            (text "「Anna」" 'br)
            (text-delay 2)
            (text "So you'll question Lei-Fa now? Or are you planning to find" 'br)
            (text "April first?")
            (wait)
            (text-reset 14)
            (text-delay 0)
            (text "「Kiyomi」" 'br)
            (text-delay 2)
            (text "Haven't decided yet. I'd like to save the fun for later, but" 'br)
            (text "Lei-Fa might tell me where April is.")
            (wait)
            (text-reset 14)
            (nop@)
            (set-reg 311 #t))
           (/
            (text-delay 0)
            (text "「Anna」" 'br)
            (text-delay 2)
            (text "What do you plan to do first, interrogate Lei-Fa or find" 'br)
            (text "April?")
            (wait)
            (text-reset 14)))))
        (//
         (? (= 57 #f) (= 58 #f) (= 59 #t) (= 60 #t))
         (nop@)
         (branch-reg
          312
          (</>
           (/
            (text-delay 0)
            (text "「Kiyomi」" 'br)
            (text-delay 2)
            (text "I've thoroughly interrogated Lei-Fa. There's no point doing" 'br)
            (text "anything more to her.")
            (wait)
            (text-reset 14)
            (text-delay 0)
            (text "「Anna」" 'br)
            (text-delay 2)
            (text "..................")
            (wait)
            (text-reset 14)
            (text-delay 0)
            (text "「Kiyomi」" 'br)
            (text-delay 2)
            (text "You want to know what I think? I'm starting to doubt you" 'br)
            (text "too, Anna.")
            (wait)
            (text-reset 14)
            (text-delay 0)
            (text "「Anna」" 'br)
            (text-delay 2)
            (text "What do you mean?")
            (wait)
            (text-reset 14)
            (text-delay 0)
            (text "「Kiyomi」" 'br)
            (text-delay 2)
            (text "Maybe this whole story about the classified information is" 'br)
            (text "made up. Lei-Fa genuinely knew nothing.")
            (wait)
            (text-reset 14)
            (text-delay 0)
            (text "「Anna」" 'br)
            (text-delay 2)
            (text "Then she cooperated without knowing anything. Capture April," 'br)
            (text "and find out what she knows.")
            (wait)
            (text-reset 14)
            (text-delay 0)
            (text "「Kiyomi」" 'br)
            (text-delay 2)
            (text "........................")
            (wait)
            (text-reset 14)
            (text-delay 0)
            (text "「Anna」" 'br)
            (text-delay 2)
            (text "Kiyomi. You're free not to trust me and Katou, but you will" 'br)
            (text "continue this mission.")
            (wait)
            (text-reset 14)
            (nop@)
            (set-reg 312 #t))
           (/
            (text-delay 0)
            (text "「Anna」" 'br)
            (text-delay 2)
            (text "Capture April quickly, before she realizes Lei-Fa's been" 'br)
            (text "arrested and flees.")
            (wait)
            (text-reset 14)))))
        (//
         (? (= 57 #t) (= 58 #f) (= 59 #t) (= 60 #t))
         (nop@)
         (text-delay 0)
         (text "「Kiyomi」" 'br)
         (text-delay 2)
         (text "Lei-Fa didn't talk...... If I can't get something out of" 'br)
         (text "April, we're finished.")
         (wait)
         (text-reset 14)
         (text-delay 0)
         (text "「Anna」" 'br)
         (text-delay 2)
         (text "Why are you doubting yourself already? You're good at" 'br)
         (text "interrogation, and you enjoy it too.")
         (wait)
         (text-reset 14)
         (text-delay 0)
         (text "「Anna」" 'br)
         (text-delay 2)
         (text "Everything will work out...... It has to.")
         (wait)
         (text-reset 14)
         (text-delay 0)
         (text "「Kiyomi」" 'br)
         (text-delay 2)
         (text "..................")
         (wait)
         (text-reset 14))
        (//
         (text-delay 0)
         (text "「Anna」" 'br)
         (text-delay 2)
         (text "We need to arrest at least one of them before we can make any" 'br)
         (text "progress. Whether it's April or Lei-Fa doesn't matter.")
         (wait)
         (text-reset 14))))
   (proc 1))
 (seg (? (= S 1) (= 305 #f))
   (proc 0)
   (text-delay 0)
   (text "「Kiyomi」" 'br)
   (text-delay 2)
   (text "Anna...... did you know about them?")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (text "「Anna」" 'br)
   (text-delay 2)
   (text "What are you talking about?")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (text "「Kiyomi」" 'br)
   (text-delay 2)
   (text "What do you think? The markings on the prisoners!")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (text "「Kiyomi」" 'br)
   (text-delay 2)
   (text "If I'd known about those, I could have arrested them both by" 'br)
   (text "now. I'm asking if you knew.")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (text "「Anna」" 'br)
   (text-delay 2)
   (text "Kiyomi, why are you asking me that? Surely you don't" 'br)
   (text "think I......")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (text "「Kiyomi」" 'br)
   (text-delay 2)
   (text "Just answer the question.")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (text "「Anna」" 'br)
   (text-delay 2)
   (text "I-I didn't know. I swear, that was my first time hearing" 'br)
   (text "about it too.")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (text "「Kiyomi」" 'br)
   (text-delay 2)
   (text "That better be the truth.")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (text "「Anna」" 'br)
   (text-delay 2)
   (text "What would I gain from lying, Kiyomi? Think about it.")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (text "「Anna」" 'br)
   (text-delay 2)
   (text "I have no grudge against you, and there's no reason I'd want" 'br)
   (text "the prisoners to stay free.")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (text "「Kiyomi」" 'br)
   (text-delay 2)
   (text "Then, do you think it's true?")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (text "「Kiyomi」" 'br)
   (text-delay 2)
   (text "That Katou didn't tell us about the goggles and marks because")
   (text "he doesn't want the prisoners caught.")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (text "「Anna」" 'br)
   (text-delay 2)
   (text "......That's possible.")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (text "「Kiyomi」" 'br)
   (text-delay 2)
   (text "And what if Katou's the one who actually leaked the" 'br)
   (text "classified info?")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (text "「Anna」" 'br)
   (text-delay 2)
   (text "Keep your voice down...... Someone might be listening!")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (text "「Anna」" 'br)
   (text-delay 2)
   (text "It's not safe to talk like that here.")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 305 #t)
   (proc 1))
 (seg (? (= S 1) (= 305 #t))
   (proc 0)
   (text-delay 0)
   (text "「Anna」" 'br)
   (text-delay 2)
   (text "For now, just focus on catching them as soon as possible." 'br)
   (text "Then we'll have our answers.")
   (wait)
   (text-reset 14)
   (proc 1))
 (seg (? (= S 2) (= 306 #f))
   (proc 0)
   (text "Her slender body looks like it would break if you touched it.")
   (text "For a pod-mod, her skin is unusually pale. No matter how I" 'br)
   (text "look at her, she doesn't seem tough at all.")
   (wait)
   (text-reset 14)
   (text "Climbing the ranks to her current position in Intel must have")
   (text "been a difficult battle.")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 306 #t)
   (proc 1))
 (seg (? (= S 2) (= 307 #f))
   (proc 0)
   (text "I've never heard anyone mention it before, but I wonder how" 'br)
   (text "old Anna is. If she's ex-KGB like the rumours say, then she'd")
   (text "have to be much older than me.")
   (wait)
   (text-reset 14)
   (text "This city is full of people like Anna with unknown pasts. Not")
   (text "just immigrants, either. It's like they're all" 'br)
   (text "frozen in time.")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 307 #t)
   (proc 1))
 (seg (? (= S 2) (= 307 #t))
   (proc 0)
   (text "Her slender body looks like it would break if you touched it.")
   (text "For a pod-mod, her skin is unusually pale. No matter how I" 'br)
   (text "look at her, she doesn't seem tough at all.")
   (wait)
   (text-reset 14)
   (proc 1))
 (seg (? (= S 3) (= 303 #f))
   (proc 0)
   (text "The heat emitting from people's bodies and the moisture" 'br)
   (text "drifting up from the ground combine to create a thick mist" 'br)
   (text "that lingers outside the window.")
   (wait)
   (text-reset 14)
   (text "Soon, that mist will condense into rain. The city planners" 'br)
   (text "stopped trying to manage the weather long ago.")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 303 #t)
   (proc 1))
 (seg (? (= S 3) (= 304 #f))
   (proc 0)
   (text "Anna's private room is lower than mine, and the view" 'br)
   (text "isn't quite as good.")
   (wait)
   (text-reset 14)
   (text "The view is blocked by overgrown tree branches, and the" 'br)
   (text "sound from outside is muffled as well.")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 304 #t)
   (proc 1))
 (seg (? (= S 3) (= 304 #t))
   (proc 0)
   (text "The heat emitting from people's bodies and the moisture" 'br)
   (text "drifting up from the ground combine to create a thick mist" 'br)
   (text "that lingers outside the window.")
   (wait)
   (text-reset 14)
   (proc 1))
 (seg (? (= S 4) (= 56 #t))
   (proc 0)
   (if (</>
        (//
         (? (= 57 #t) (= 58 #f) (= 59 #f) (= 60 #f))
         (nop@)
         (text "First I should interrogate April. She might hold the key to" 'br)
         (text "solving this whole case.")
         (wait)
         (text-reset 14)
         (text "If that doesn't work, at least I might get a hint for" 'br)
         (text "capturing Lei-Fa or finding the third prisoner.")
         (wait)
         (text-reset 14))
        (//
         (? (= 57 #t) (= 58 #t) (= 59 #f) (= 60 #f))
         (nop@)
         (text "I hate to think April could withstand my torture. Did she" 'br)
         (text "really know nothing?")
         (wait)
         (text-reset 14))
        (//
         (? (= 57 #t) (= 58 #t) (= 59 #t) (= 60 #f))
         (nop@)
         (text "I've captured the second prisoner, Lei-Fa. Interrogating her" 'br)
         (text "might give me more information.")
         (wait)
         (text-reset 14))
        (//
         (? (= 57 #t) (= 58 #f) (= 59 #t) (= 60 #f))
         (nop@)
         (text "I've arrested both prisoners. Interrogating them should give" 'br)
         (text "me info about the classified material I'm looking for.")
         (wait)
         (text-reset 14))
        (//
         (? (= 57 #f) (= 58 #f) (= 59 #t) (= 60 #f))
         (nop@)
         (text "I've arrested Lei-Fa. Interrogating her might provide the key")
         (text "to solving this whole case.")
         (wait)
         (text-reset 14))
        (//
         (? (= 57 #f) (= 58 #f) (= 59 #t) (= 60 #t))
         (nop@)
         (text "I hate to think Lei-Fa could withstand my torture. Did she" 'br)
         (text "really know nothing?")
         (wait)
         (text-reset 14))
        (//
         (? (= 57 #t) (= 58 #f) (= 59 #t) (= 60 #t))
         (nop@)
         (text "Lei-Fa didn't talk. I have to do something about April." 'br)
         (text "Anything - I have to make something work......")
         (wait)
         (text-reset 14))
        (//
         (text "First I need to arrest April or Lei-Fa. Fighting someone" 'br)
         (text "clearly stronger than me makes me nervous......")
         (wait)
         (text-reset 14))))
   (proc 1))
 (seg (? (= S 4) (= 313 #f))
   (proc 0)
   (text "Why did Katou keep quiet about the goggles and prisoner" 'br)
   (text "markings?")
   (wait)
   (text-reset 14)
   (text "If I'd known about that, I could have arrested the prisoners" 'br)
   (text "much sooner. Katou's definitely up to something.")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 313 #t)
   (proc 1))
 (seg (? (= S 4) (= 313 #t))
   (proc 0)
   (text "Why did Katou keep quiet about the goggles and prisoner" 'br)
   (text "markings? He's definitely up to something......")
   (wait)
   (text-reset 14)
   (proc 1))
 (seg*))