(mes
 (meta (engine 'ADV) (charset "pc98") (extraop #t))
 (seg*
  (branch-reg 56 (</> (/) (/ (mes-jump "mes¥mb_a02.mes"))))
  (exec-mem 14080 2 24 4 135 71 80 34 80 34 0 30)
  (image-file "gpc¥b15_01.gpc")
  (image-mem 0 3)
  (if (</>
       (//
        (? (= P 3))
		(nop@))
	   (//
        (if (</>
             (//
              (? (= O 0))
              (sound '|| 0)
              (sound '|| "uso¥xg_03.uso")
              (sound '|| 1)
              (nop@)
              (set-var P 3))
             (//
              (? (= O 1))
              (sound '|| 0)
              (sound '|| "uso¥xg_03v.uso")
              (sound '|| 1)
              (nop@)
              (set-var P 3)))))))
  (load-mem "clm¥b15_01.clm" 32768)
  (proc 3)
  (text-frame 10 312 70 383)
  (if (</>
       (//
        (? (= 54 #t))
        (str "I have an idea where April and Lei-Fa are, but......")
        (wait)
        (text-reset 14)
        (str "I don't even know what they look like, so how am I supposed" 'br)
        (str "to recognise them?")
        (wait)
        (text-reset 14))
       (//
        (? (= 922 #t) (= 53 #t))
        (nop@)
        (str "I walk out of the Intelligence Division building.")
        (wait)
        (text-reset 14)
        (branch-reg
         52
         (</>
          (/ (str "Although, I still don't even know where to start......"))
          (/
           (str "I should go meet April and Lei-Fa's old boss. Even if he" 'br)
		   (str "doesn't have much information, it's worth going to Ichigaya" 'br)
		   (str "Base anyway."))))
        (wait)
        (text-reset 14))
       (//
        (? (= 922 #f))
        (str "I exit the intelligence office and step into the streets." 'br)
		(str "This area is well patrolled by the military, so it's" 'br)
		(str "relatively safe.")
        (wait)
        (text-reset 14)
        (str "Intelligence has offices all over the city, usually" 'br)
		(str "disguised as companies that work with the military. This one" 'br)
		(str "doesn't try to hide itself, though.")
        (wait)
        (text-reset 14)
        (str "That means the office is an easy target for would-be" 'br)
		(str "terrorists, which is why there are so many plainclothes" 'br)
		(str "agents walking the streets and keeping this district safe.")
        (wait)
        (text-reset 14)
        (branch-reg
         52
         (</>
          (/
           (str "I doubt any escaped prisoners would be here. They'd be far" 'br)
		   (str "better off hiding in Chinatown or the maze that is" 'br)
		   (str "Chiba City.")
           (wait)
           (text-reset 14)
           (str "There are a lot of criminals and seedy types in those parts." 'br)
		   (str "If I were them, I'd just go to ground and lie low until" 'br)
		   (str "things cool down......"))
          (/
           (str "No escaped prisoner would come to a place like this. If they" 'br)
		   (str "were smart, they wouldn't set foot anywhere in Ichigaya," 'br)
		   (str "either.")
           (wait)
           (text-reset 14)
           (str "Because of that, I really doubt April and Lei-Fa's old CO" 'br)
		   (str "would know where they are.")
           (wait)
           (text-reset 14)
           (str "Well, unless the \"old CO\" is the mastermind behind" 'br)
		   (str "all this......"))))
        (nop@)
        (set-reg 53 #t)
        (wait)
        (text-reset 14))))
  (nop@)
  (set-reg 922 #t)
  (exec-mem 3968 102 500 360)
  (exec-mem 3072 1)
  (loop (set-var S 0) (exec-mem 3072 1020 1021 "S" 32768) (seg-call)))
 (seg (? (= 1020 #f) (= 1021 #f)) (exec-mem 3072 1))
 (seg (? (= 1021 #t))
   (exec-mem 3072 0)
   (exec-mem 3968 103)
   (exec-mem 256 "A 0 S 0")
   (exec-mem 256 "G 1 4 64 12 48")
   (exec-mem 4768 4 8 12 4 1 0 0 4480 4480 1 0)
   (menu1 5 72 (</> (/ (str "  Travel  "))))
   (if (</>
        (//
         (? (= S 0))
         (exec-mem 256 "A 0 S 0")
         (exec-mem 256 "G 9 5 72 22 96")
         (set-var X 3)
         (when (</>
                (// (? (= 52 #t)) (nop@) (inc-var X 1))
                (// (? (= 54 #t)) (nop@) (inc-var X 1))))
         (if (</>
              (// (? (= X 3)) (exec-mem 4768 5 9 22 8 1 0 0 4480 4480 1 0))
              (// (? (= X 4)) (exec-mem 4768 5 9 22 10 1 0 0 4480 4480 1 0))
              (// (? (= X 5)) (exec-mem 4768 5 9 22 12 1 0 0 4480 4480 1 0))))
         (menu1
          6
          80
          6
          96
          6
          112
          6
          128
          6
          144
          (</>
           (/ (str "  Intel Dept. Bldg  "))
           (/ (str "     Chinatown      "))
           (/ (str "     Chiba City     "))
           (/ (set-reg 52 #t) (nop@) (str "   Ichigaya Base   "))
           (/ (set-reg 54 #t) (nop@) (str "     Akihabara     "))))
         (exec-mem 256 "P 9 5 72")
         (exec-mem 256 "P 1 4 64")
         (if (</>
              (//
               (? (= S 0))
               (if (</>
                    (// (? (= 54 #t)) (nop@) (mes-jump "mes¥MA_A02.MES"))
                    (// (mes-jump "mes¥MA_A01.MES")))))
              (// (? (= S 1)) (mes-jump "mes¥MB_C01.MES"))
              (// (? (= S 2)) (mes-jump "mes¥MB_E01.MES"))
              (// (? (= S 3)) (mes-jump "mes¥MB_B01.MES"))
              (// (? (= S 4)) (mes-jump "mes¥MB_D01.MES"))
              (// (? (= S 255))))))
        (// (? (= S 255)) (exec-mem 256 "P 1 4 64"))))
   (exec-mem 3968 104)
   (exec-mem 3072 2)
   (exec-mem 3072 1))
 (seg (? (= 1021 #t)) (exec-mem 3072 1))
 (seg (? (= S 1) (= 226 #f))
   (proc 0)
   (str "This area is safe because of all the military presence" 'br)
   (str "nearby. The housing is relatively nice, and all the best" 'br)
   (str "hotels are here.")
   (wait)
   (text-reset 14)
   (str "But for me, and I'm sure for many in the military, this world")
   (str "has no appeal to me.")
   (wait)
   (text-reset 14)
   (str "If you're surrounded by this rich lifestyle every day, maybe" 'br)
   (str "it's inevitable you'd turn into a petty, disgusting" 'br)
   (str "bureaucrat......")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 226 #t)
   (proc 1))
 (seg (? (= S 1) (= 227 #f))
   (proc 0)
   (str "Huge skyscrapers stretch high into the distance. All over the")
   (str "city, there are buildings like this one that look like" 'br)
   (str "massive pillars holding up the sky.")
   (wait)
   (text-reset 14)
   (str "The buildings here are well-maintained and often renovated," 'br)
   (str "but that goes away quickly as you get near the slums.")
   (wait)
   (text-reset 14)
   (str "But many of those distant towers look like they could fall" 'br)
   (str "down at any moment. If they really were supporting the crust" 'br)
   (str "above us, I'd be scared for my life.")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 227 #t)
   (proc 1))
 (seg (? (= S 1) (= 227 #t))
   (proc 0)
   (str "Huge skyscrapers stretch high into the distance, like massive")
   (str "pillars holding up the sky. Buildings like this are scattered")
   (str "all over the city.")
   (wait)
   (text-reset 14)
   (proc 1))
 (seg (? (= S 2) (= 228 #f))
   (proc 0)
   (str "The heat wafting off people's bodies and the humidity" 'br)
   (str "drifting up from the ground combine to form a light mist that")
   (str "floats through the air like fog.")
   (wait)
   (text-reset 14)
   (str "It might sound like a strange sight, but down here it happens" 'br)
   (str "every day. Soon, the rain will start.")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 228 #t)
   (proc 1))
 (seg (? (= S 2) (= 229 #f))
   (proc 0)
   (str "Far above me, the concrete and chrome sky is barely visible" 'br)
   (str "through the mist.")
   (wait)
   (text-reset 14)
   (str "It's the same sky I've looked at for decades, but the sight" 'br)
   (str "still makes me uneasy.")
   (wait)
   (text-reset 14)
   (str "I don't think my fear of the city crumbling above me" 'br)
   (str "will ever go away.")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 229 #t)
   (proc 1))
 (seg (? (= S 2) (= 229 #t))
   (proc 0)
   (str "Far above me, the concrete and chrome sky is barely visible" 'br)
   (str "through the mist.")
   (wait)
   (text-reset 14)
   (proc 1))
 (seg (? (= S 3) (= 230 #f))
   (proc 0)
   (str "The streets are nearly empty, but that's not surprising. This")
   (str "part of the city is full of rich Japanese people who wouldn't")
   (str "dare walk around unguarded.")
   (wait)
   (text-reset 14)
   (str "The constant dim lighting means crime can happen at any time" 'br)
   (str "of day here.")
   (wait)
   (text-reset 14)
   (str "Why would anyone leave their home if they didn't have to," 'br)
   (str "especially if they have money?")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 230 #t)
   (proc 1))
 (seg (? (= S 3) (= 231 #f))
   (proc 0)
   (str "The chill I felt in the helicopter on the way to the" 'br)
   (str "Intelligence department is still in the air. Combined with" 'br)
   (str "the sparse crowd, it's a terribly bleak atmosphere.")
   (wait)
   (text-reset 14)
   (str "But if this cold is the only thing from the outside world" 'br)
   (str "that makes it down here, then maybe I should be" 'br)
   (str "happy to feel it.")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 231 #t)
   (proc 1))
 (seg (? (= S 3) (= 231 #t))
   (proc 0)
   (str "I still feel chilled from that helicopter ride. And these" 'br)
   (str "empty streets don't make me any warmer.")
   (wait)
   (text-reset 14)
   (proc 1))
 (seg (? (= S 4) (= 232 #t))
   (proc 0)
   (str "I have some ideas about where the first two prisoners might" 'br)
   (str "be. But how can I find them if I don't even know what they" 'br)
   (str "look like?")
   (wait)
   (text-reset 14)
   (proc 1))
 (seg (? (= S 4) (= 54 #t))
   (proc 0)
   (str "I have some ideas about where the first two prisoners might" 'br)
   (str "be. But how can I find them if I don't even know what they" 'br)
   (str "look like?")
   (wait)
   (text-reset 14)
   (str "Maybe I should talk to Anna or Katou......")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 232 #t)
   (proc 1))
 (seg (? (= S 4) (= 52 #t))
   (proc 0)
   (str "First, I should head to Ichigaya Base. Even if their" 'br)
   (str "former commander doesn't have much information, at least" 'br)
   (str "it's a start.")
   (wait)
   (text-reset 14)
   (proc 1))
 (seg (? (= S 4))
   (proc 0)
   (str "At the very least, I don't think they're foolish enough to be" 'br)
   (str "in this part of town. I don't have any leads on where to go," 'br)
   (str "though, so where do I go from here......")
   (wait)
   (text-reset 14)
   (proc 1))
 (seg*))