; X-Girl - Cyberpunk Adventure (PC-98) - MB_A02.MES
; Translation by Fuzion
; Script Editing by Tan2000
; Content Revision by OldCorpo
; Chapter 1 - April and Lei-Fa
; Section 1.3 - April's arrest
; Section 1.4 - Lei-Fa's arrest
; -----Location:-----
; Infront of Intelligence Division Building
; -----Scene:-----
; Kiyomi going to arrest April and Lei-Fa.
; --Progression:--
; 1. Fight and arrest April at Akihabara
; 2. Fight and arrest Lei-Fa at Chinatown.
(mes
 (meta (engine 'ADV) (charset "pc98") (extraop #t))
 (seg*
  (if (</> (// (? (= 58 #t) (= 60 #t)) (mes-jump "mes¥mb_a03.mes"))))
  (exec-mem 14080 2 24 4 135 71 80 34 80 34 0 30)
  (image-file "gpc¥b15_01.gpc")
  (image-mem 0 3)
  (proc 3)
  (if (</>
       (//
        (? (!= P 3))
        (if (</>
             (//
              (? (= O 0))
              (sound '|| 0)
              (sound '|| "uso¥xg_03.uso")
              (sound '|| 1)
              (nop@)
              (set-var P 3))
             (//
              (? (= O 1))
              (sound '|| 0)
              (sound '|| "uso¥xg_03v.uso")
              (sound '|| 1)
              (nop@)
              (set-var P 3)))))
       (// (nop@))))
  (load-mem "clm¥b15_01.clm" 32768)
  (text-frame 10 312 70 383)
  (text-delay 2)
  (if (</>
       (//
        (? (= 923 #t))
        (str "I'm back outside Intelligence headquarters. The thought of" 'br)
        (str "having to clean up this mess is really weighing on me......")
        (wait)
        (text-reset 14))
       (//
        (? (= 923 #f))
        (str "I left Intelligence and stepped out into the city. This time" 'br)
        (str "I have goggles to spot the swastika marks carved on the" 'br)
        (str "prisoners' bodies, and a gun full of tranquilizer rounds.")
        (wait)
        (text-reset 14)
        (str "My destinations are Akihabara and Chinatown. This probably" 'br)
        (str "won't be a waste of time anymore, but the thought of finally" 'br)
        (str "having to face the prisoners is weighing on me.")
        (wait)
        (text-reset 14)
        (str "After all, they're ex-Special Forces - real professionals." 'br)
        (str "And all I have is this unreliable tranquilizer gun. Can I" 'br)
        (str "really win?")
        (wait)
        (text-reset 14))))
  (nop@)
  (set-reg 923 #t)
  (exec-mem 3968 102 500 360)
  (exec-mem 3072 1)
  (loop (set-var S 0) (exec-mem 3072 1020 1021 "S" 32768) (seg-call)))
 (seg (? (= 1020 #f) (= 1021 #f)) (exec-mem 3072 1))
 (seg (? (= 1021 #t))
   (exec-mem 3072 0)
   (exec-mem 3968 103)
   (exec-mem 256 "A 0 S 0")
   (exec-mem 256 "G 1 4 64 12 48")
   (exec-mem 4768 4 8 12 4 1 0 0 4480 4480 1 0)
   (menu1 5 72 (</> (/ (str "  Travel  "))))
   (if (</>
        (//
         (? (= S 0))
         (exec-mem 256 "A 0 S 0")
         (exec-mem 256 "G 9 5 72 22 96")
         (exec-mem 4768 5 9 22 12 1 0 0 4480 4480 1 0)
         (menu1
          6
          80
          6
          96
          6
          112
          6
          128
          6
          144
          (</>
           (/ (str "  Intel Div. Bldg   "))
           (/ (str "     Chinatown      "))
           (/ (str "     Chiba City     "))
           (/ (str "   Ichigaya Base    "))
           (/ (str "     Akihabara      "))))
         (exec-mem 256 "P 9 5 72")
         (exec-mem 256 "P 1 4 64")
         (if (</>
              (// (? (= S 0)) (mes-jump "mes¥MA_A02.MES"))
              (// (? (= S 1)) (mes-jump "mes¥MB_C02.MES"))
              (// (? (= S 2)) (mes-jump "mes¥MB_E01.MES"))
              (// (? (= S 3)) (mes-jump "mes¥MB_B02.MES"))
              (// (? (= S 4)) (mes-jump "mes¥MB_D02.MES"))
              (// (? (= S 255))))))
        (// (? (= S 255)) (exec-mem 256 "P 1 4 64"))))
   (exec-mem 3968 104)
   (exec-mem 3072 2)
   (exec-mem 3072 1))
 (seg (? (= 1021 #t)) (exec-mem 3072 1))
 (seg (? (= S 1) (= 322 #f))
   (proc 0)
   (str "Huge skyscrapers stretch high into the distance. All over the")
   (str "city, there are buildings like this one that look like" 'br)
   (str "massive pillars holding up the sky.")
   (wait)
   (text-reset 14)
   (str "The buildings here are well-maintained and often renovated," 'br)
   (str "but that goes away quickly as you get near the slums.")
   (wait)
   (text-reset 14)
   (str "But many of those distant towers look like they could fall" 'br)
   (str "down at any moment. If they really were supporting the crust" 'br)
   (str "above us, I'd be scared for my life.")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 322 #t)
   (proc 1))
 (seg (? (= S 1) (= 323 #f))
   (proc 0)
   (str "This area is safe because of all the military presence" 'br)
   (str "nearby. The housing is relatively nice, and all the best" 'br)
   (str "hotels are here.")
   (wait)
   (text-reset 14)
   (str "But for me, and I'm sure for many in the military, this world")
   (str "has no appeal to me.")
   (wait)
   (text-reset 14)
   (str "If you're surrounded by this rich lifestyle every day, maybe" 'br)
   (str "it's inevitable you'd turn into a petty, disgusting" 'br)
   (str "bureaucrat......")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 323 #t)
   (proc 1))
 (seg (? (= S 1) (= 323 #t))
   (proc 0)
   (str "This area is prime real estate where plenty of rich Japanese" 'br)
   (str "people built houses. Some of them probably live in this" 'br)
   (str "building.")
   (wait)
   (text-reset 14)
   (proc 1))
 (seg (? (= S 2) (= 324 #f))
   (proc 0)
   (str "Same cloudy sky as always. Far above me, vapor floating up" 'br)
   (str "from the earth's crust has formed thick clouds.")
   (wait)
   (text-reset 14)
   (str "Soon, the rain will start. The city planners" 'br)
   (str "stopped trying to manage the weather long ago.")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 324 #t)
   (proc 1))
 (seg (? (= S 2) (= 325 #f))
   (proc 0)
   (str "Far above me, the concrete and chrome sky is barely visible" 'br)
   (str "through the mist.")
   (wait)
   (text-reset 14)
   (str "I don't think my fear of the city crumbling above me" 'br)
   (str "will ever go away.")
   (wait)
   (text-reset 14)
   (str "The stress of living underground is enough to break most" 'br)
   (str "people. Anyone still sane down here probably wasn't normal" 'br)
   (str "to begin with.")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 325 #t)
   (proc 1))
 (seg (? (= S 2) (= 325 #t))
   (proc 0)
   (str "Same dark sky as always. Far above me, vapor floating up" 'br)
   (str "from the earth's crust has formed thick clouds.")
   (wait)
   (text-reset 14)
   (proc 1))
 (seg (? (= S 3) (= 326 #f))
   (proc 0)
   (str "The chill I felt in the helicopter on the way to the" 'br)
   (str "Intelligence Division is still in the air. Combined with" 'br)
   (str "the sparse crowd, it's a terribly bleak atmosphere.")
   (wait)
   (text-reset 14)
   (str "But if this cold is the only thing from the outside world" 'br)
   (str "that makes it down here, then maybe I should be happy to" 'br)
   (str "feel it.")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 326 #t)
   (proc 1))
 (seg (? (= S 3) (= 327 #f))
   (proc 0)
   (str "The sky is threatening rain, and the streets are nearly" 'br)
   (str "deserted. If I didn't live here, I'd think it was abandoned.")
   (wait)
   (text-reset 14)
   (str "In this city, for some reason, the slums and rough areas are" 'br)
   (str "always pulsing with life. Only this district where the upper" 'br)
   (str "class live is so terribly lonely.")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 327 #t)
   (proc 1))
 (seg (? (= S 3) (= 327 #t))
   (proc 0)
   (str "The sky is threatening rain, and the streets are nearly" 'br)
   (str "deserted. If I didn't live here, I'd think it was abandoned.")
   (wait)
   (text-reset 14)
   (proc 1))
 (seg (? (= S 4))
   (proc 0)
   (if (</>
        (//
         (? (= 57 #t) (= 58 #f) (= 59 #f) (= 60 #f))
         (nop@)
         (str "First I should interrogate April. She might hold the key to" 'br)
         (str "solving this whole case.")
         (wait)
         (text-reset 14)
         (str "If that doesn't work, at least I might get a hint for" 'br)
         (str "capturing Lei-Fa or finding the third prisoner.")
         (wait)
         (text-reset 14))
        (//
         (? (= 57 #t) (= 58 #t) (= 59 #f) (= 60 #f))
         (nop@)
         (str "I hate to think April could withstand my torture. Did she" 'br)
         (str "really know nothing?")
         (wait)
         (text-reset 14))
        (//
         (? (= 57 #t) (= 58 #t) (= 59 #t) (= 60 #f))
         (nop@)
         (str "I've captured the second prisoner, Lei-Fa. Interrogating her" 'br)
         (str "might give me more information.")
         (wait)
         (text-reset 14))
        (//
         (? (= 57 #t) (= 58 #f) (= 59 #t) (= 60 #f))
         (nop@)
         (str "I've arrested both prisoners. Interrogating them should give" 'br)
         (str "me info about the classified material I'm looking for.")
         (wait)
         (text-reset 14))
        (//
         (? (= 57 #f) (= 58 #f) (= 59 #t) (= 60 #f))
         (nop@)
         (str "I've arrested Lei-Fa. Interrogating her might provide the key")
         (str "to solving this whole case.")
         (wait)
         (text-reset 14))
        (//
         (? (= 57 #f) (= 58 #f) (= 59 #t) (= 60 #t))
         (nop@)
         (str "I hate to think Lei-Fa could withstand my torture. Did she" 'br)
         (str "really know nothing?")
         (wait)
         (text-reset 14))
        (//
         (? (= 57 #t) (= 58 #f) (= 59 #t) (= 60 #t))
         (nop@)
         (str "Lei-Fa didn't talk. I have to do something about April." 'br)
         (str "Anything - I have to make something work......")
         (wait)
         (text-reset 14))
        (//
         (str "First I need to arrest April or Lei-Fa. Fighting someone" 'br)
         (str "clearly stronger than me makes me nervous......")
         (wait)
         (text-reset 14))))
   (proc 1))
 (seg*))
