; X-Girl - Cyberpunk Adventure (PC-98) - MB_B01.MES
; Translation by Fuzion
; Script Editing by Tan2000
; Content Revision by OldCorpo
; Chapter 1 - April and Lei-Fa
; Section 1.2 - April and Lei-Fa's search
; -----Scene:-----
; At Ichigaya Base to talk with April & Lei-Fa's ex-Commander.
; --Progression:--
; Talk to Colonel Karl after inspecting everything in the room.
(mes
 (meta (engine 'ADV) (charset "pc98") (extraop #t))
 (seg*
  (branch-reg 56 (</> (/) (/ (mes-jump "mes¥mb_b02.mes"))))
  (exec-mem 14080 2 24 4 135 71 80 34 80 34 0 30)
  (image-file "gpc¥b03_01.gpc")
  (image-mem 0 3)
  (if (</> (// (? (= 926 #t)) (image-file "gpc¥b03_01a.gpc") (image-mem 1 0))))
  (proc 3)
  (if (</>
       (//
        (? (!= P 5))
        (if (</>
             (//
              (? (= O 0))
              (sound '|| 0)
              (sound '|| "uso¥xg_05.uso")
              (sound '|| 1)
              (nop@)
              (set-var P 5))
             (//
              (? (= O 1))
              (sound '|| 0)
              (sound '|| "uso¥xg_05v.uso")
              (sound '|| 1)
              (nop@)
              (set-var P 5)))))
       (// (nop@))))
  (load-mem "clm¥b03_01a.clm" 32768)
  (text-frame 10 312 70 383)
  (if (</>
       (//
        (? (= 926 #t))
        (text-delay 0)
        (str "「Karl」" 'br)
        (text-delay 2)
        (str "How can I help you?")
        (wait)
        (text-reset 14))
       (//
        (? (= 926 #f))
        (str "When I arrived at Ichigaya Base, I was led inside by a" 'br)
        (str "soldier who clearly thought I was suspicious and kept giving" 'br)
		(str "me side glances.")
        (wait)
        (text-reset 14)
        (str "The soldier took me to an old part of the base. I was led to" 'br)
		(str "a damp, gloomy office that smells of ammonia.")
        (wait)
        (text-reset 14)
        (str "As I step into the office, it was immediately clear that they")
		(str "don't think very highly of the officer who works here.")
        (wait)
        (text-reset 14)
        (str "In the corner hangs a faded Foreign Legion flag - a famous" 'br)
		(str "symbol that even I recognize.")
        (wait)
        (text-reset 14)
        (image-file "gpc¥b03_01a.gpc")
        (image-mem 1 0)
        (text-delay 0)
        (str "「Uniformed Man」" 'br)
        (text-delay 2)
        (str "Sorry to keep you waiting.")
        (wait)
        (text-reset 14)
        (str "The man in front of me is built like a seasoned veteran, with")
		(str "a muscular body and a deep voice to match.")
        (wait)
        (text-reset 14)
        (text-delay 0)
        (str "「Kiyomi」" 'br)
        (text-delay 2)
        (str "Are you...... April and Lei-Fa's old commander?")
        (wait)
        (text-reset 14)
        (text-delay 0)
        (str "「Uniformed Man」" 'br)
        (text-delay 2)
        (str "I'm Colonel Karl. I've heard about you, Kiyomi. You wanted to")
		(str "ask me some questions about former agents of mine?")
        (wait)
        (text-reset 14)
        (str "Karl, huh......What a generic name. He looks European, but" 'br)
		(str "I can never tell with guys like him.")
        (wait)
        (text-reset 14)
        (text-delay 0)
        (str "「Karl」" 'br)
        (text-delay 2)
        (str "Sure, I'll hear you out and answer what I can. Don't think" 'br)
		(str "it'll help you much though.")
        (wait)
        (text-reset 14)
        (text-delay 0)
        (str "「Kiyomi」" 'br)
        (text-delay 2)
        (str "I'd like you to tell me about the two women who served" 'br)
		(str "under you.")
        (wait)
        (text-reset 14)
		;; Too long! Needs shortening.
        (text-delay 0)
        (str "「Karl」" 'br)
        (text-delay 2)
        (str "......Before we start, I want you to understand that I'm" 'br)
		(str "taking a big risk by sharing this with someone who isn't part")
		(str "of the military.")
        (wait)
        (text-reset 14))))
  (nop@)
  (set-reg 926 #t)
  (exec-mem 3968 102 500 360)
  (exec-mem 3072 1)
  (loop (set-var S 0) (exec-mem 3072 1020 1021 "S" 32768) (seg-call)))
 (seg (? (= 1020 #f) (= 1021 #f)) (exec-mem 3072 1))
 (seg (? (= 1021 #t) (= 54 #t))
   (exec-mem 3072 0)
   (exec-mem 3968 103)
   (exec-mem 256 "A 0 S 0")
   (exec-mem 256 "G 1 4 64 12 48")
   (exec-mem 4768 4 8 12 4 1 0 0 4480 4480 1 0)
   (menu1 5 72 (</> (/ (str "  Travel  "))))
   (if (</>
        (//
         (? (= S 0))
         (exec-mem 256 "A 0 S 0")
         (exec-mem 256 "G 9 5 72 22 64")
         (exec-mem 4768 5 9 22 4 1 0 0 4480 4480 1 0)
         (menu1 6 80 (</> (/ (str "  Intel Div. Bldg   "))))
         (exec-mem 256 "P 9 5 72")
         (exec-mem 256 "P 1 4 64")
         (if (</>
              (//
               (? (= S 0))
               (if (</>
                    (//
                     (? (= 55 #t))
                     (nop@)
                     (text-delay 0)
                     (str "「Kiyomi」" 'br)
                     (text-delay 2)
                     (str "I probably won't be bothering you again......")
                     (wait)
                     (text-reset 14)
                     (text-delay 0)
                     (str "「Karl」" 'br)
                     (text-delay 2)
                     (str "I certainly hope not. Now, if you'll excuse me.")
                     (wait)
                     (text-reset 14)
                     (mes-jump "mes¥MB_A02.MES"))
                    (//
                     (? (= 240 #t))
                     (nop@)
                     (text-delay 0)
                     (str "「Karl」" 'br)
                     (text-delay 2)
                     (str "Be careful around those two. This mission is much harder than")
					 (str "you think.")
                     (wait)
                     (text-reset 14)
                     (mes-jump "mes¥MB_A01.MES"))
                    (//
                     (nop@)
                     (set-reg 240 #t)
                     (text-delay 0)
                     (str "「Karl」" 'br)
                     (text-delay 2)
                     (str "Leaving already?")
                     (wait)
                     (text-reset 14)
                     (text-delay 0)
                     (str "「Kiyomi」" 'br)
                     (text-delay 2)
                     (str "Yeah. I doubt you know anything else that could help me.")
                     (wait)
                     (text-reset 14)
                     (text-delay 0)
                     (str "「Karl」" 'br)
                     (text-delay 2)
                     (str "I see. I'd wish you luck...... but I can't. Those two being" 'br)
					 (str "involved might ruin my reputation.")
                     (wait)
                     (text-reset 14)
                     (text-delay 0)
                     (str "「Kiyomi」" 'br)
                     (text-delay 2)
                     (str "Right......")
                     (wait)
                     (text-reset 14)
                     (text-delay 0)
                     (str "「Karl」" 'br)
                     (text-delay 2)
                     (str "Good luck out there. And be warned - those two were among the")
					 (str "best in my unit. They won't go down easily.")
                     (wait)
                     (text-reset 14)
                     (text-delay 0)
                     (str "「Kiyomi」" 'br)
                     (text-delay 2)
                     (str "..................Thank you for your cooperation.")
                     (wait)
                     (text-reset 14)
                     (mes-jump "mes¥MB_A01.MES")))))
              (// (? (= S 255))))))
        (// (? (= S 255)) (exec-mem 256 "P 1 4 64"))))
   (exec-mem 3968 104)
   (exec-mem 3072 2)
   (exec-mem 3072 1))
 (seg (? (= 1021 #t)) (exec-mem 3072 1))
 (seg (? (= S 1) (= 54 #t))
   (proc 0)
   (text-delay 0)
   (str "「Karl」" 'br)
   (text-delay 2)
   (str "Intelligence probably suspects me too. They probably think I" 'br)
   (str "was involved in planning whatever those two did......")
   (wait)
   (text-reset 14)
   (proc 1))
 (seg (? (= S 1) (= 234 #t))
   (proc 0)
   (text-delay 0)
   (str "「Kiyomi」" 'br)
   (text-delay 2)
   (str "So, what else do you know about them?")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (str "「Karl」" 'br)
   (text-delay 2)
   (str "Nothing else that I can think of......")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (str "「Kiyomi」" 'br)
   (text-delay 2)
   (str "You don't sound very sure. Are you hiding something from me," 'br)
   (str "Colonel?")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (str "「Karl」" 'br)
   (text-delay 2)
   (str "I have no reason to hide anything. You know the kind of" 'br)
   (str "situation this puts me in.")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (str "「Karl」" 'br)
   (text-delay 2)
   (str "I appreciate that you're respecting my position.")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (str "「Kiyomi」" 'br)
   (text-delay 2)
   (str "Feels like you're trying to warn me away from asking more.")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (str "「Karl」" 'br)
   (text-delay 2)
   (str "Your reputation precedes you, Major. The name Kiyomi from" 'br)
   (str "Intelligence is well-known among soldiers.")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (str "「Karl」" 'br)
   (text-delay 2)
   (str "There's a saying that \"if you're tortured by her, it's only a")
   (str "matter of time until you talk\".")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (str "「Kiyomi」" 'br)
   (text-delay 2)
   (str "If you think that...... 
   (wait)
   (text-reset 14)
   (text-delay 0)
   (str "「Kiyomi」" 'br)
   (text-delay 2)
   (str "If you really think I'm a professional, then tell me where" 'br)
   (str "they could be hiding so I can clear your name.")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (str "「Karl」" 'br)
   (text-delay 2)
   (str "......April has a friend in Akihabara, in the black market" 'br)
   (str "district. You know where that is?")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (str "「Kiyomi」" 'br)
   (text-delay 2)
   (str "I do. You think April is hiding there with her friend? What" 'br)
   (str "about Lei-Fa?")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (str "「Karl」" 'br)
   (text-delay 2)
   (str "Lei-Fa didn't seem to have a place to stay...... But given" 'br)
   (str "she's Chinese, you can probably guess where she'd end up.")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (str "「Kiyomi」" 'br)
   (text-delay 2)
   (str "Chinatown. I thought of that too, but would she really hide" 'br)
   (str "somewhere so obvious?")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (str "「Karl」" 'br)
   (text-delay 2)
   (str "You don't understand their culture. For them, being with" 'br)
   (str "their own people is the safest option.")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (str "「Karl」" 'br)
   (text-delay 2)
   (str "No one will sell out their own. Many of them are fugitives or")
   (str "criminals themselves, after all.")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (str "「Kiyomi」" 'br)
   (text-delay 2)
   (str "That makes sense...... And Akihabara's black market is full" 'br)
   (str "of criminals too. It's the perfect place to disappear.")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (str "「Kiyomi」" 'br)
   (text-delay 2)
   (str "By the way, do you have any holopics of them? I'd also really")
   (str "like a detailed profile, if possible.")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (str "「Karl」" 'br)
   (text-delay 2)
   (str "There's nothing. All their data's been wiped. Intelligence" 'br)
   (str "doesn't have it either, right? That's why you're here.")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (str "「Kiyomi」" 'br)
   (text-delay 2)
   (str "Damn it all......")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (str "「Karl」" 'br)
   (text-delay 2)
   (str "To make things worse, without their data, there's no proof" 'br)
   (str "those two were ever in the military. Only my memory.")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (str "「Kiyomi」" 'br)
   (text-delay 2)
   (str "You think Intelligence would accept that? Those two" 'br)
   (str "definitely exist.")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (str "「Karl」" 'br)
   (text-delay 2)
   (str "I know, I know...... just saying.")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (str "「Kiyomi」" 'br)
   (text-delay 2)
   (str "......You don't have to be so worried. I never said I" 'br)
   (str "suspected you.")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (str "「Karl」" 'br)
   (text-delay 2)
   (str "You don't understand. If this case isn't solved, I'll be" 'br)
   (str "their first scapegoat.")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 54 #t)
   (proc 1))
 (seg (? (= S 1) (= 233 #t) (= 236 #t))
   (proc 0)
   (text-delay 0)
   (str "「Karl」" 'br)
   (text-delay 2)
   (str "Those two were real professionals. Everyone who worked with" 'br)
   (str "them knew it.")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (str "「Kiyomi」" 'br)
   (text-delay 2)
   (str "What kind of operations were they involved in?")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (str "「Karl」" 'br)
   (text-delay 2)
   (str "Several battlefields in Asia, plus a year in the Middle East.")
   (str "You won't find a better record for Special Forces soldiers.")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (str "「Kiyomi」" 'br)
   (text-delay 2)
   (str "But they didn't stay in the military. They must have had" 'br)
   (str "something lined up - some plan for making it on the outside.")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (str "「Karl」" 'br)
   (text-delay 2)
   (str "......Maybe. But I doubt they could find better work than the")
   (str "military. Especially as immigrants.")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (str "「Karl」" 'br)
   (text-delay 2)
   (str "Special Forces aren't like conscripts who joined reluctantly.")
   (str "When they told me they were quitting, I couldn't believe it.")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (str "「Kiyomi」" 'br)
   (text-delay 2)
   (str "Do either of them have family?")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (str "「Karl」" 'br)
   (text-delay 2)
   (str "April doesn't. Lost her family in a bombing, I think." 'br)
   (str "Lei-Fa's family should still be around.")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (str "「Kiyomi」" 'br)
   (text-delay 2)
   (str "Were those two close?")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (str "「Karl」" 'br)
   (text-delay 2)
   (str "Hard to say. They were in the same unit, so they knew each" 'br)
   (str "other well enough.")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (str "「Kiyomi」" 'br)
   (text-delay 2)
   (str "The fact that they left around the same time bothers me." 'br)
   (str "I can't believe that's just a coincidence.")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (str "「Karl」" 'br)
   (text-delay 2)
   (str "..................")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (str "「Kiyomi」" 'br)
   (text-delay 2)
   (str "They could even be together right now............")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 234 #t)
   (proc 1))
 (seg (? (= S 1) (= 233 #f))
   (proc 0)
   (text-delay 0)
   (str "「Kiyomi」" 'br)
   (text-delay 2)
   (str "So you want something from me. Is that right?")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (str "「Karl」" 'br)
   (text-delay 2)
   (str "I want to know why you're after these girls, and what they" 'br)
   (str "did to warrant this kind of attention.")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (str "「Kiyomi」" 'br)
   (text-delay 2)
   (str "Why should I tell you that? I could always just have my" 'br)
   (str "superiors in Intelligence put some pressure on you.")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (str "「Kiyomi」" 'br)
   (text-delay 2)
   (str "I can make you talk if I have to.")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (str "「Karl」" 'br)
   (text-delay 2)
   (str "But you don't want to, do you? You seem to have at least a" 'br)
   (str "measure of respect for me.")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (str "「Karl」" 'br)
   (text-delay 2)
   (str "You're not the brute-force type, despite how you look." 'br)
   (str "Even though Intelligence has plenty of those.")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (str "「Kiyomi」" 'br)
   (text-delay 2)
   (str "That's true...... But honestly, I hardly know any more than" 'br)
   (str "you.")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (str "「Karl」" 'br)
   (text-delay 2)
   (str "What did they do? I still haven't been told what crime" 'br)
   (str "they supposedly committed before they ran away.")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (str "「Kiyomi」" 'br)
   (text-delay 2)
   (str "All I know is they stole some kind of system the military" 'br)
   (str "and a private company were developing together.")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (str "「Karl」" 'br)
   (text-delay 2)
   (str "Stole? What did they steal, the actual system? Its" 'br)
   (str "blueprints? A replica of the system?")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (str "「Kiyomi」" 'br)
   (text-delay 2)
   (str "Well, that's all I was told......")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (str "「Karl」" 'br)
   (text-delay 2)
   (str "And you don't see anything wrong with that story? It makes" 'br)
   (str "no sense to me.")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (str "「Kiyomi」" 'br)
   (text-delay 2)
   (str "..................")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 233 #t)
   (proc 1))
 (seg (? (= S 1) (= 233 #t))
   (proc 0)
   (text-delay 0)
   (str "「Karl」" 'br)
   (text-delay 2)
   (str "You really don't see any problems with this mission? The" 'br)
   (str "whole thing smells fishy to me.")
   (wait)
   (text-reset 14)
   (proc 1))
 (seg (? (= S 2) (= 235 #f))
   (proc 0)
   (str "Karl has the build of a seasoned veteran, with the presence" 'br)
   (str "to match. His uniform is well-worn - like a second skin.")
   (wait)
   (text-reset 14)
   (str "He's seen real battle, unlike the Japanese officers who are" 'br)
   (str "so busy polishing their medals that they forget to" 'br)
   (str "actually fight.")
   (wait)
   (text-reset 14)
   (str "A man like him would have plenty of reasons to resent the" 'br)
   (str "military and the Japanese. Him directing those two......" 'br)
   (str "it's not out of the question.")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 235 #t)
   (proc 1))
 (seg (? (= S 2) (= 236 #f))
   (proc 0)
   (str "Looking at him, he seems to be in his late forties. He was" 'br)
   (str "probably a soldier in his home country too.")
   (wait)
   (text-reset 14)
   (str "Maybe he was recruited when the war started. But if that's" 'br)
   (str "the case, he should be treated better than this......")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 236 #t)
   (proc 1))
 (seg (? (= S 2) (= 236 #t))
   (proc 0)
   (str "Karl has the build of a seasoned veteran, with the presence" 'br)
   (str "to match. His uniform is well-worn - like a second skin.")
   (wait)
   (text-reset 14)
   (proc 1))
 (seg (? (= S 3) (= 54 #t))
   (proc 0)
   (str "Akihabara's black market and Chinatown. I can't say I'm" 'br)
   (str "surprised.")
   (wait)
   (text-reset 14)
   (str "But their faces, their backgrounds - I still have nothing." 'br)
   (str "Whoever this Nana is, she's one hell of a hacker.")
   (wait)
   (text-reset 14)
   (proc 1))
 (seg (? (= S 3) (= 234 #t))
   (proc 0)
   (str "I expected the Colonel to be cagey about them, but he's been" 'br)
   (str "surprisingly cooperative. Is it just a bluff to make himself" 'br)
   (str "look clean?")
   (wait)
   (text-reset 14)
   (str "Still, winning me over won't save him. The leak came from" 'br)
   (str "the military - they'll be the ones grilling him.")
   (wait)
   (text-reset 14)
   (proc 1))
 (seg (? (= S 3) (= 233 #t))
   (proc 0)
   (str "He does have a point. I can't shake the feeling there's" 'br)
   (str "something rotten about this mission. But what does it" 'br)
   (str "matter?")
   (wait)
   (text-reset 14)
   (str "It's not like I understand what's going on anyway. But" 'br)
   (str "abandoning this mission and getting shipped to Siberia? Not" 'br)
   (str "a chance.")
   (wait)
   (text-reset 14)
   (proc 1))
 (seg (? (= S 3) (= 239 #f))
   (proc 0)
   (str "I should've known that dealing with military types wouldn't" 'br)
   (str "be easy......")
   (wait)
   (text-reset 14)
   (str "When his former subordinates screw up and Intelligence comes" 'br)
   (str "knocking at the military base, can you blame him for" 'br)
   (str "covering his ass?")
   (wait)
   (text-reset 14)
   (str "Well, it's not like I know anything important anyway. Even" 'br)
   (str "if I tell him, it won't really matter......")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 239 #t)
   (proc 1))
 (seg (? (= S 3) (= 239 #t))
   (proc 0)
   (str "It's not like I know anything important anyway. Even" 'br)
   (str "if I tell him, it won't really matter......")
   (wait)
   (text-reset 14)
   (proc 1))
 (seg*))
