; X-Girl - Cyberpunk Adventure (PC-98) - MB_C01.MES
; Translation by Fuzion
; Script Editing by Tan2000
; Content Revision by OldCorpo
; Chapter 1 - April and Lei-Fa
; Section 1.2 - April and Lei-Fa's search
; -----Location:-----
; Chinatown
; -----Scene:-----
; Initial search for Lei-Fa location.
; --Progression:--
; 1. Talk to Vagrant after inspecting everything in the scene.
; 2. Go inside Ruined Building.
(mes
 (meta (engine 'ADV) (charset "pc98") (extraop #t))
 (seg*
  (branch-reg 55 (</> (/) (/ (mes-jump "mes¥mb_c02.mes"))))
  (exec-mem 14080 2 24 4 135 71 80 34 80 34 0 30)
  (image-file "gpc¥b05_01.gpc")
  (image-mem 0 3)
  (if (</>
       (//
        (? (!= P 3))
        (if (</>
             (//
              (? (= O 0))
              (sound '|| 0)
              (sound '|| "uso¥xg_03.uso")
              (sound '|| 1)
              (nop@)
              (set-var P 3))
             (//
              (? (= O 1))
              (sound '|| 0)
              (sound '|| "uso¥xg_03v.uso")
              (sound '|| 1)
              (nop@)
              (set-var P 3)))))
       (// (nop@))))
  (proc 3)
  (load-mem "clm¥b05_01.clm" 32768)
  (text-frame 10 312 70 383)
  (if (</>
       (//
        (? (= 906 #t))
        (str "I left the small building and stepped out onto Chinatown's" 'br)
        (str "streets.")
        (wait)
        (text-reset 14))
       (//
        (? (= 54 #t))
        (str "I've arrived at Chinatown. If Colonel Karl was right, Lei-Fa" 'br)
		(str "should be hiding somewhere around here.")
        (wait)
        (text-reset 14)
        (str "But searching every crumbling building would be a massive" 'br)
		(str "waste of time. I need to figure something out......")
        (wait)
        (text-reset 14))
       (//
        (? (= 905 #t))
		(str "I've come to a section of Chinatown. Derelict buildings line" 'br)
		(str "the streets, looking ready to collapse at any moment.")
        (wait)
        (text-reset 14))
       (//
        (? (= 905 #f))
        (str "This is Chinatown. Derelict buildings line the area, all" 'br)
		(str "looking ready to collapse.")
        (wait)    
        (text-reset 14)
        (str "This district is the well-known residential area for Chinese" 'br)
		(str "immigrants, but it's also notorious for the criminals who" 'br)
		(str "hang out here.")
        (wait)
        (text-reset 14)
        (str "Anyone being hunted by the military and Intelligence would" 'br)
		(str "naturally hide here. But how do I find them?")
        (nop@)
        (set-reg 241 #t)
        (wait)
        (text-reset 14))))
  (nop@)
  (set-reg 905 #t)
  (nop@)
  (set-reg 906 #f)
  (exec-mem 3968 102 500 360)
  (exec-mem 3072 1)
  (loop (set-var S 0) (exec-mem 3072 1020 1021 "S" 32768) (seg-call)))
 (seg (? (= 1020 #f) (= 1021 #f)) (exec-mem 3072 1))
 (seg (? (= 1021 #t) (= 54 #f))
   (exec-mem 3072 0)
   (exec-mem 3968 103)
   (exec-mem 256 "A 0 S 0")
   (exec-mem 256 "G 1 4 64 12 48")
   (exec-mem 4768 4 8 12 4 1 0 0 4480 4480 1 0)
   (menu1 5 72 (</> (/ (str "  Travel  "))))
   (if (</>
        (//
         (? (= S 0))
         (exec-mem 256 "A 0 S 0")
         (exec-mem 256 "G 9 5 72 22 64")
         (if (</>
              (// (? (= 54 #t)) (exec-mem 4768 5 9 22 6 1 0 0 4480 4480 1 0))
              (// (exec-mem 4768 5 9 22 4 1 0 0 4480 4480 1 0))))
         (menu1
          6
          80
          6
          96
          (</>
           (/ (str " Intel Div. Bldg.   "))
           (/ (set-reg 54 #t) (nop@) (str "  Ruined Building   "))))
         (exec-mem 256 "P 9 5 72")
         (exec-mem 256 "P 1 4 64")
         (if (</>
              (// (? (= S 0)) (mes-jump "mes¥MB_A01.MES")) ; Go to Intel Div. Building
              (// (? (= S 1)) (mes-jump "mes¥MB_C01A.MES")) ; Go to Ruined Building
              (// (? (= S 255))))))
        (// (? (= S 255)) (exec-mem 256 "P 1 4 64"))))
   (exec-mem 3968 104)
   (exec-mem 3072 2)
   (exec-mem 3072 1))
 (seg (? (= 1021 #t) (= 54 #t) (= 253 #t))
   (exec-mem 3072 0)
   (exec-mem 3968 103)
   (exec-mem 256 "A 0 S 0")
   (exec-mem 256 "G 1 4 64 12 48")
   (exec-mem 4768 4 8 12 4 1 0 0 4480 4480 1 0)
   (menu1 5 72 (</> (/ (str "  Travel  "))))
   (if (</>
        (//
         (? (= S 0))
         (exec-mem 256 "A 0 S 0")
         (exec-mem 256 "G 9 5 72 22 64")
         (if (</>
              (// (? (= 54 #t)) (exec-mem 4768 5 9 22 6 1 0 0 4480 4480 1 0))
              (// (exec-mem 4768 5 9 22 4 1 0 0 4480 4480 1 0))))
         (menu1
          6
          80
          6
          96
          (</>
           (/ (str " Intel Div. Bldg.   "))
           (/ (set-reg 54 #t) (nop@) (str "  Ruined Building   "))))
         (exec-mem 256 "P 9 5 72")
         (exec-mem 256 "P 1 4 64")
         (if (</>
              (// (? (= S 0)) (mes-jump "mes¥MB_A01.MES")) ; Go to Intel Div. Building
              (// (? (= S 1)) (mes-jump "mes¥MB_C01A.MES")) ; Go to Ruined Building
              (// (? (= S 255))))))
        (// (? (= S 255)) (exec-mem 256 "P 1 4 64"))))
   (exec-mem 3968 104)
   (exec-mem 3072 2)
   (exec-mem 3072 1))
 (seg (? (= 1021 #t)) (exec-mem 3072 1))
 (seg (? (= S 1) (= 250 #t))
   (proc 0)
   (str "This building could collapse at any moment, but the entrance" 'br)
   (str "is still accessible.")
   (wait)
   (text-reset 14)
   (proc 1))
 (seg (? (= S 1) (= 54 #t) (= 243 #t))
   (proc 0)
   (str "It's so run-down it's barely standing, but the entrance area" 'br)
   (str "is intact enough for people to get inside.")
   (wait)
   (text-reset 14)
   (str "Going inside a building like this, I'd be constantly worried" 'br)
   (str "about the ceiling caving in......")
   (wait)
   (text-reset 14)
   (str "However, that's exactly why criminals would be hiding there." 'br)
   (str "If Karl's telling the truth, Lei-Fa should be around here" 'br)
   (str "somewhere......")
   (wait)
   (text-reset 14)
   (str "Searching randomly would just waste time, but I won't get" 'br)
   (str "anywhere if I don't try something.")
   (wait)
   (text-reset 14)
   (str "Let's check it out......")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 250 #t)
   (proc 1)
   (exec-mem 3072 0)
   (mes-jump "mes¥MB_C01A.MES")) ; Go to ruined building (first time)
 (seg (? (= S 1) (= 242 #f))
   (proc 0)
   (str "What was this building used for originally? It's much shorter")
   (str "than everything around it.")
   (wait)
   (text-reset 14)
   (str "In this city, the higher up you are, the more dangerous it" 'br)
   (str "is. By that logic, this might have been pretty upscale" 'br)
   (str "housing.")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 242 #t)
   (proc 1))
 (seg (? (= S 1) (= 243 #f))
   (proc 0)
   (str "How long has it been since people lived here? The building's" 'br)
   (str "walls are covered with countless tiny cracks.")
   (wait)
   (text-reset 14)
   (str "Even the criminals and homeless people infesting this area" 'br)
   (str "probably wouldn't want to live in this building.")
   (wait)
   (text-reset 14)
   (str "In this condition, it could collapse any second. But that's" 'br)
   (str "exactly why someone might be hiding there......")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 243 #t)
   (proc 1))
 (seg (? (= S 1) (= 243 #t))
   (proc 0)
   (str "How long has it been since people lived here? The building's" 'br)
   (str "walls are covered with countless tiny cracks.")
   (wait)
   (text-reset 14)
   (proc 1))
 (seg (? (= S 2) (= 244 #f))
   (proc 0)
   (str "In the distance, a cluster of tall buildings pierce the fog." 'br)
   (str "From here, they look like giant pillars holding up the sky.")
   (wait)
   (text-reset 14)
   (str "The buildings that surround me are so run-down, they could" 'br)
   (str "collapse at any moment.")
   (wait)
   (text-reset 14)
   (str "This part of town looks like it's been abandoned for years." 'br)
   (str "Was it the terrorists and gangs that drove it to ruin?")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 244 #t)
   (proc 1))
 (seg (? (= S 2) (= 245 #f))
   (proc 0)
   (str "The towering skyscrapers loom oppressively over a city of" 'br)
   (str "nothing but rubble and crumbling buildings.")
   (wait)
   (text-reset 14)
   (str "The people here have to look up at those towers every single" 'br)
   (str "day. What humiliation. I couldn't stand it for three days.")
   (wait)
   (text-reset 14)
   (str "But the immigrants have to endure this existence. They can" 'br)
   (str "never escape from it......")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 245 #t)
   (proc 1))
 (seg (? (= S 2) (= 245 #t))
   (proc 0)
   (str "This part of town looks like it's been abandoned for years." 'br)
   (str "Was it the terrorists and gangs that drove it to ruin?")
   (wait)
   (text-reset 14)
   (proc 1))
 (seg (? (= S 3) (= 246 #f))
   (proc 0)
   (str "It looks like a massive multi-story parking garage connected" 'br)
   (str "to a shopping mall. It's a shadow of its former self now, but")
   (str "I can easily picture how busy it once was.")
   (wait)
   (text-reset 14)
   (str "Besides signs of destruction, I can see evidence of looting." 'br)
   (str "That must have been years ago.")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 246 #t)
   (proc 1))
 (seg (? (= S 3) (= 247 #f))
   (proc 0)
   (str "It should be packed with cars, but through the gaping windows")
   (str "I only see pitch-black emptiness.")
   (wait)
   (text-reset 14)
   (str "I don't know how it became ruins, but scavengers probably" 'br)
   (str "cleaned it out completely afterward.")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 247 #t)
   (proc 1))
 (seg (? (= S 3) (= 247 #t))
   (proc 0)
   (str "It looks like a massive multi-story parking garage connected" 'br)
   (str "to a shopping mall. It's a shadow of its former self now, but")
   (str "I can easily picture how busy it once was.")
   (wait)
   (text-reset 14)
   (proc 1))
 (seg (? (= S 4) (= 253 #t))
   (proc 0)
   (text-delay 0)
   (str "「Vagrant」" 'br)
   (text-delay 2)
   (str "Give me something, then maybe I'll remember......")
   (wait)
   (text-reset 14)
   (proc 1))
 (seg (? (= S 4) (= 252 #t))
   (proc 0)
   (text-delay 0)
   (str "「Vagrant」" 'br)
   (text-delay 2)
   (str "Who are you...... You're not from around here, are you?")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (str "「Kiyomi」" 'br)
   (text-delay 2)
   (str "I'm looking for someone, do you understand? You do speak" 'br)
   (str "Japanese, right?")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (str "「Vagrant」" 'br)
   (text-delay 2)
   (str "Don't mess with me...... Stay back!")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (str "「Kiyomi」" 'br)
   (text-delay 2)
   (str "Come on, it's hard to talk when you're so far away.")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (str "「Kiyomi」" 'br)
   (text-delay 2)
   (str "A woman I'm looking for apparently fled to this area. You've" 'br)
   (str "been sleeping around here for a while, haven't you?")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (str "「Vagrant」" 'br)
   (text-delay 2)
   (str "Give me something, then maybe I'll remember......")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (str "「Kiyomi」" 'br)
   (text-delay 2)
   (str "Even if you ask for something, I don't have anything you'd" 'br)
   (str "want.")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (str "「Vagrant」" 'br)
   (text-delay 2)
   (str "Then I don't know anything.")
   (wait)
   (text-reset 14)
   (str "He probably doesn't know anything anyway. Besides, I really" 'br)
   (str "don't have anything to spare for this guy.")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 253 #t)
   (proc 0))
 (seg (? (= S 4) (= 248 #f))
   (proc 0)
   (str "He's frozen, watching my every move. Is he scared of me," 'br)
   (str "or is he sizing me up to see if I'm worth robbing?")
   (wait)
   (text-reset 14)
   (str "Either way, doesn't really matter. Even if he tried" 'br)
   (str "something, he doesn't look stronger than me.")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 248 #t)
   (proc 1))
 (seg (? (= S 4) (= 249 #f))
   (proc 0)
   (str "Looking closer, he seems Japanese......")
   (wait)
   (text-reset 14)
   (str "Hard to believe someone would drop out of society when they" 'br)
   (str "get so many privileges in this world.")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (str "「Kiyomi」" 'br)
   (text-delay 2)
   (str "Hey you. Seen any suspicious women around here?")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (str "「Vagrant」" 'br)
   (text-delay 2)
   (str "..................")
   (wait)
   (text-reset 14)
   (str "What a stupid question. Nobody around here isn't suspicious," 'br)
   (str "and this guy's probably the most suspicious of all.")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (str "「Kiyomi」" 'br)
   (text-delay 2)
   (str "Come closer. I won't hurt you.")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (str "「Vagrant」" 'br)
   (text-delay 2)
   (str "...............")
   (wait)
   (text-reset 14)
   (str "He's not coming any closer.")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 249 #t)
   (proc 0))
 (seg (? (= S 4) (= 249 #t))
   (proc 0)
   (str "He's frozen, watching my every move. Is he scared of me," 'br)
   (str "or is he sizing me up to see if I'm worth robbing?")
   (wait)
   (text-reset 14)
   (proc 1))
 (seg (? (= S 5) (= 252 #t))
   (proc 0)
   (str "Is it really worth the risk to go searching inside these" 'br)
   (str "collapsing buildings?")
   (wait)
   (text-reset 14)
   (proc 1))
 (seg (? (= S 5) (= 54 #t))
   (proc 0)
   (str "If Colonel Karl was telling the truth, Lei-Fa's probably" 'br)
   (str "hiding somewhere around here. So I've got to search.")
   (wait)
   (text-reset 14)
   (str "Still, Chinatown is a maze of buildings. Searching them all" 'br)
   (str "would be impossible......")
   (wait)
   (text-reset 14)
   (str "Guess I'll start with the buildings nearby.")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 252 #t)
   (proc 1))
 (seg (? (= S 5) (= 251 #f))
   (proc 0)
   (str "Chinatown may be packed with places to hide, but there's no" 'br)
   (str "guarantee she's even here......")
   (wait)
   (text-reset 14)
   (str "Searching every building without any leads is a waste of" 'br)
   (str "time. Plus there's no guarantee those roofs won't suddenly" 'br)
   (str "cave in.")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 251 #t)
   (proc 1))
 (seg (? (= S 5) (= 251 #t))
   (proc 0)
   (str "No sign of the escaped prisoners I'm looking for. And this" 'br)
   (str "homeless guy in front of me definitely isn't who I'm" 'br)
   (str "after......")
   (wait)
   (text-reset 14)
   (proc 1))
 (seg*))
