; X-Girl - Cyberpunk Adventure (PC-98) - MB_C02.MES
; Translation by Fuzion
; Script Editing by Tan2000
; Content Revision by OldCorpo
; Chapter 1 - April and Lei-Fa
; Section 1.4 - Lei-Fa's arrest
; -----Location:-----
; Inside Ruined Building, Chinatown
; -----Scene:-----
; Fight and arrest Lei-Fa.
; --Progression:--
; Inspect anything, wait for Lei-Fa, enter the fight scene.
(mes
 (meta (engine 'ADV) (charset "pc98") (extraop #t))
 (seg*
  (exec-mem 14080 2 24 4 135 71 80 34 80 34 0 30)
  (branch-reg
   930
   (</>
    (/
     (image-file "gpc¥b05_02.gpc")
     (image-mem 0 3)
     (branch-reg
      355
      (</> (/ (nop@)) (/ (image-file "gpc¥b05_02a.gpc") (image-mem 1 0)))))
    (/ (image-file "gpc¥b05_02b.gpc") (image-mem 0 3))))
  (proc 3)
  (if (</>
       (//
        (? (!= P 6))
        (if (</>
             (//
              (? (= O 0))
              (sound '|| 0)
              (sound '|| "uso¥xg_06.uso")
              (sound '|| 1)
              (nop@)
              (set-var P 6))
             (//
              (? (= O 1))
              (sound '|| 0)
              (sound '|| "uso¥xg_06v.uso")
              (sound '|| 1)
              (nop@)
              (set-var P 6)))))
       (// (nop@))))
  (load-mem "clm¥b05_02b.clm" 32768)
  (text-frame 10 312 70 383)
  (str "I entered the building where the homeless man said Lei-Fa was")
  (str "hiding. It's one of the less damaged, more" 'br)
  (str "comfortable-looking buildings in the area.")
  (wait)
  (text-reset 14)
  (str "I can't sense anyone inside, but considering Lei-Fa is" 'br)
  (str "ex-Special Forces, that makes sense. There's no way she'd let")
  (str "me detect her presence.")
  (wait)
  (text-reset 14)
  (str "Now I'm relying on dumb luck and the swastika mark carved" 'br)
  (str "into Lei-Fa's body. If she's nearby, I should be able to tell")
  (str "even through walls.")
  (wait)
  (text-reset 14)
  (exec-mem 3968 102 500 360)
  (exec-mem 3072 1)
  (loop (set-var S 0) (exec-mem 3072 1020 1021 "S" 32768) (seg-call)))
 (seg (? (= 1020 #f) (= 1021 #f)) (exec-mem 3072 1))
 (seg (? (= 1021 #t) (= 354 #t) (= 930 #f))
   (exec-mem 3072 0)
   (exec-mem 3968 103)
   (exec-mem 256 "A 0 S 0")
   (exec-mem 256 "G 1 4 64 16 48")
   (exec-mem 4768 4 8 16 4 1 0 0 4480 4480 1 0)
   (menu1 5 72 (</> (/ (str "Put on goggles"))))
   (if (</>
        (//
         (? (= S 0))
         (exec-mem 256 "P 1 4 64")
         (if (</>
              (//
               (? (= 355 #f))
               (str "I put on the goggles.")
               (wait)
               (text-reset 14)
               (image-file "gpc¥b05_02b.gpc")
               (image-mem 0 3)
               (image-file "gpc¥shotwaku.gpc")
               (image-mem 1 0)
               (proc 3)
               (str "My vision turns completely green. This is what it looks like" 'br)
               (str "through the filter...... What's that? Is that Lei-Fa?")
               (wait)
               (text-reset 14)
               (text-delay 0)
               (str "「Lei-Fa」" 'br)
               (text-delay 2)
               (str "You, who are you? You're looking at me!")
               (wait)
               (text-reset 14)
               (str "Did she sense my gaze? Lei-Fa is looking this way. Is it her" 'br)
               (str "Special Forces heightened senses, or some kung fu technique?")
               (wait)
               (text-reset 14)
               (text-delay 0)
               (str "「Kiyomi」" 'br)
               (text-delay 2)
               (str "Don't move! My gun is trained on you.")
               (wait)
               (text-reset 14)
               (text-delay 0)
               (str "「Lei-Fa」" 'br)
               (text-delay 2)
               (str "......You're not military. You smell different. So why are" 'br)
               (str "you here to capture me?")
               (wait)
               (text-reset 14)
               (text-delay 0)
               (str "「Kiyomi」" 'br)
               (text-delay 2)
               (str "I said don't move. Listen to me, and I'll go easy on you.")
               (wait)
               (text-reset 14)
               (text-delay 0)
               (str "「Lei-Fa」" 'br)
               (text-delay 2)
               (str "You Japanese rat. Coming all the way here to find me - there" 'br)
               (str "must be a limit to your stupidity!")
               (wait)
               (text-reset 14)
               (nop@)
               (set-reg 355 #t)
               (nop@)
               (set-reg 930 #t))
              (//
               (? (= 355 #t))
               (str "I put on the goggles. My vision turns green......")
               (wait)
               (text-reset 14)
               (image-file "gpc¥b05_02b.gpc")
               (image-mem 0 3)
               (image-file "gpc¥shotwaku.gpc")
               (image-mem 1 0)
               (proc 3)
               (nop@)
               (set-reg 930 #t)))))
        (// (? (= S 255)) (exec-mem 256 "P 1 4 64"))))
   (exec-mem 3968 104)
   (exec-mem 3072 2)
   (exec-mem 3072 1))
 (seg (? (= 1021 #t) (= 930 #t))
   (exec-mem 3072 0)
   (exec-mem 3968 103)
   (exec-mem 256 "A 0 S 0")
   (exec-mem 256 "G 1 4 64 16 48")
   (exec-mem 4768 4 8 16 4 1 0 0 4480 4480 1 0)
   (menu1 5 72 (</> (/ (str "Remove goggles"))))
   (if (</>
        (//
         (? (= S 0))
         (exec-mem 256 "P 1 4 64")
         (str "I took off the goggles.")
         (wait)
         (text-reset 14)
         (nop@)
         (set-reg 930 #f)
         (image-file "gpc¥b05_02.gpc")
         (image-mem 0 3)
         (image-file "gpc¥b05_02a.gpc")
         (image-mem 1 0)
         (proc 3))
        (// (? (= S 255)) (exec-mem 256 "P 1 4 64"))))
   (exec-mem 3968 104)
   (exec-mem 3072 2)
   (exec-mem 3072 1))
 (seg (? (= 1021 #t)) (exec-mem 3072 1))
 (seg (? (= S 1) (= 346 #f))
   (proc 0)
   (str "Part of the roof is gone, exposing wires that should be in" 'br)
   (str "the attic.")
   (wait)
   (text-reset 14)
   (str "I don't know what all these colorful wires were used for, but")
   (str "there's no doubt they're dead.")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 346 #t)
   (proc 1))
 (seg (? (= S 1) (= 347 #f))
   (proc 0)
   (str "If I had to guess, there was probably some kind of electrical")
   (str "device connected here.")
   (wait)
   (text-reset 14)
   (str "Lighting fixtures, security systems, or maybe communication" 'br)
   (str "equipment. Either way, they clearly had value in the" 'br)
   (str "looters' eyes.")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 347 #t)
   (proc 1))
 (seg (? (= S 1) (= 347 #t))
   (proc 0)
   (str "I don't know what all these colorful wires were used for, but")
   (str "there's no doubt they're dead.")
   (wait)
   (text-reset 14)
   (proc 1))
 (seg (? (= S 2) (= 348 #f))
   (proc 0)
   (str "The back room, which was probably once separated by a door," 'br)
   (str "appears to be a bathroom. I can see the remains of a tattered")
   (str "curtain.")
   (wait)
   (text-reset 14)
   (str "The unexpectedly old-fashioned design is surprising. A" 'br)
   (str "Western-style bathtub with wood flooring wouldn't have been" 'br)
   (str "modern even back then.")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 348 #t)
   (proc 1))
 (seg (? (= S 2) (= 349 #f))
   (proc 0)
   (str "Years of rainwater have collected in the Western bathtub," 'br)
   (str "with something yellow-green floating on the surface - could" 'br)
   (str "be moss or mold.")
   (wait)
   (text-reset 14)
   (str "In this condition, it can never be used again. I wonder if" 'br)
   (str "Lei-Fa ever used the bath while hiding here?")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 349 #t)
   (proc 1))
 (seg (? (= S 2) (= 349 #t))
   (proc 0)
   (str "The back room, which was probably once separated by a door," 'br)
   (str "appears to be a bathroom. I can see the remains of a tattered")
   (str "curtain.")
   (wait)
   (text-reset 14)
   (proc 1))
 (seg (? (= S 3) (= 350 #f))
   (proc 0)
   (str "Debris that was probably once part of the walls, roof, or" 'br)
   (str "furniture is scattered around.")
   (wait)
   (text-reset 14)
   (str "Was this the work of looters, or someone trying to make this" 'br)
   (str "place livable again?" 'br)
   (str "......I can't tell.")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 350 #t)
   (proc 1))
 (seg (? (= S 3) (= 351 #f))
   (proc 0)
   (str "The carpet, half-turned back to earth, and accumulated dust" 'br)
   (str "cover the entire floor.")
   (wait)
   (text-reset 14)
   (str "I don't see anything like footprints, but Lei-Fa could" 'br)
   (str "probably move around without leaving tracks. She's a" 'br)
   (str "professional, after all......")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 351 #t)
   (proc 1))
 (seg (? (= S 3) (= 351 #t))
   (proc 0)
   (str "There are no footprints on the floor, but Lei-Fa could" 'br)
   (str "probably move around without leaving tracks.")
   (wait)
   (text-reset 14)
   (proc 1))
 (seg (? (= S 4) (= 352 #f))
   (proc 0)
   (str "The deep cracks running through these walls fuel my anxiety." 'br)
   (str "How long will they hold the ceiling's weight......")
   (wait)
   (text-reset 14)
   (str "But then again, we underground dwellers always live with that")
   (str "fear. If the crust collapses, we die all the same.")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 352 #t)
   (proc 1))
 (seg (? (= S 4) (= 353 #f))
   (proc 0)
   (str "Since they don't get sunlight, there's not much" 'br)
   (str "discoloration, but countless cracks run across the walls -" 'br)
   (str "hardly pristine condition.")
   (wait)
   (text-reset 14)
   (str "The bare wall showing through where the plaster has peeled" 'br)
   (str "off makes the room look even more wretched.")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 353 #t)
   (proc 1))
 (seg (? (= S 4) (= 353 #t))
   (proc 0)
   (str "The deep cracks running through these walls fuel my anxiety." 'br)
   (str "How long will they hold the ceiling's weight......")
   (wait)
   (text-reset 14)
   (proc 1))
 (seg (? (= S 5) (= 356 #t))
   (proc 0)
   (str "Lei-Fa intends to eliminate me and escape again. A fight is" 'br)
   (str "becoming unavoidable.")
   (wait)
   (text-reset 14)
   (str "But she's ex-Special Forces. Do I have any chance of winning?")
   (str "Maybe I can exploit her overconfidence......")
   (wait)
   (text-reset 14)
   (proc 1))
 (seg (? (= S 5) (= 355 #t))
   (proc 0)
   (str "I wanted to handle this before Lei-Fa knew I was here......" 'br)
   (str "Though I think it's impossible, I have to try persuasion.")
   (wait)
   (text-reset 14)
   (proc 1))
 (seg (? (= S 5) (= 349 #t) (= 353 #t))
   (proc 0)
   (str "Looking around, I can't find anything that confirms Lei-Fa is")
   (str "here. Maybe it's time to use those goggles.")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 354 #t)
   (proc 1))
 (seg (? (= S 5))
   (proc 0)
   (str "Is there anything in the room that reveals Lei-Fa's" 'br)
   (str "presence...... Should I search around?")
   (wait)
   (text-reset 14)
   (proc 1))
 (seg (? (= S 6) (= 356 #f) (= 355 #t))
   (proc 0)
   (text-delay 0)
   (str "「Lei-Fa」" 'br)
   (text-delay 2)
   (str "Who are you?")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (str "「Kiyomi」" 'br)
   (text-delay 2)
   (str "........................")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (str "「Lei-Fa」" 'br)
   (text-delay 2)
   (str "Why are you silent? I see...... You've come to capture me." 'br)
   (str "You don't look military, so what are you?")
   (wait)
   (text-reset 14)
   (str "Shit, I wanted to handle this before Lei-Fa caught on......" 'br)
   (str "Do I have any chance in a straight fight?")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (str "「Lei-Fa」" 'br)
   (text-delay 2)
   (str "Not going to say anything? That's fine, you'll die here" 'br)
   (str "either way.")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (str "「Kiyomi」" 'br)
   (text-delay 2)
   (str "Attacking me isn't smart. I'm with Intelligence - kill me and")
   (str "agents will tear this place apart to find you.")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (str "「Lei-Fa」" 'br)
   (text-delay 2)
   (str "If I don't kill you, I'll just be captured here and now. You" 'br)
   (str "think threats work on me?")
   (wait)
   (text-reset 14)
   (str "That didn't work. I'm out of ideas...... Do I have to fight?")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 356 #t)
   (proc 1))
 (seg (? (= S 6) (= 356 #t) (= 355 #t))
   (proc 0)
   (str "Lei-Fa won't listen to anything I say anymore...... Looks" 'br)
   (str "like I'll have to make her listen by force.")
   (wait)
   (text-reset 14)
   (str "But can I actually do it? I have no confidence at all." 'br)
   (str "No matter how lucky I am......")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (str "「Kiyomi」" 'br)
   (text-delay 2)
   (str "Why did you go after military secrets? You must have known" 'br)
   (str "what would happen.")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (str "「Lei-Fa」" 'br)
   (text-delay 2)
   (str "You think I'd tell you that? I didn't talk even under" 'br)
   (str "torture.")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (str "「Kiyomi」" 'br)
   (text-delay 2)
   (str "Tch...... Then there's no helping it. I was hoping to handle" 'br)
   (str "this peacefully.")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (str "「Lei-Fa」" 'br)
   (text-delay 2)
   (str "Come at me from anywhere. There's no way I'll lose!")
   (wait)
   (text-reset 14)
   (proc 1)
   (exec-mem 3072 0)
   (branch-reg
    930
    (</>
     (/ (nop@))
     (/
      (exec-mem 9504 "I")
      (exec-mem 9504 "M M128")
      (exec-mem 9504 "L gpc¥b05_02b0.gpc,KEEP")
      (exec-mem 9504 "L gpc¥b05_02b1.gpc,KEEP")
      (exec-mem 9504 "L gpc¥b05_02b2.gpc,KEEP")
      (exec-mem 9504 "L gpc¥b05_02b3.gpc,KEEP")
      (exec-mem 9504 "L gpc¥b05_02b4.gpc,KEEP")
      (exec-mem 9504 "L gpc¥b05_02b5.gpc,KEEP")
      (exec-mem 9504 "L gpc¥b05_02b6.gpc,KEEP")
      (exec-mem 9504 "L gpc¥b05_02b7.gpc,KEEP")
      (exec-mem 9504 "C gpc¥b05_02b0.gpc,GPC")
      (image-mem 1 0)
      (delay 3)
      (exec-mem 9504 "C gpc¥b05_02b1.gpc,GPC")
      (image-mem 1 0)
      (delay 3)
      (exec-mem 9504 "C gpc¥b05_02b2.gpc,GPC")
      (image-mem 1 0)
      (delay 3)
      (exec-mem 9504 "C gpc¥b05_02b3.gpc,GPC")
      (image-mem 1 0)
      (delay 3)
      (exec-mem 9504 "C gpc¥b05_02b4.gpc,GPC")
      (image-mem 1 0)
      (delay 3)
      (exec-mem 9504 "C gpc¥b05_02b5.gpc,GPC")
      (image-mem 1 0)
      (delay 3)
      (exec-mem 9504 "C gpc¥b05_02b6.gpc,GPC")
      (image-mem 1 0)
      (delay 3)
      (exec-mem 9504 "C gpc¥b05_02b7.gpc,GPC")
      (image-mem 1 0)
      (delay 3))))
   (exec-mem 9504 "E")
   (exec-mem 3072 0)
   (mes-jump "mes¥MC_B01.MES"))
 (seg (? (= S 6) (= 355 #t) (= 930 #f))
   (proc 0)
   (str "I wanted to handle this before Lei-Fa knew I was here......" 'br)
   (str "Though I think it's impossible, I have to try persuasion.")
   (wait)
   (text-reset 14)
   (proc 1))
 (seg (? (= S 6) (= 349 #t) (= 353 #t) (= 930 #f))
   (proc 0)
   (str "Looking around, I can't find anything that confirms Lei-Fa is")
   (str "here. Maybe it's time to use those goggles.")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 354 #t)
   (proc 1))
 (seg (? (= S 6) (= 930 #f))
   (proc 0)
   (str "Is there anything in the room that reveals Lei-Fa's" 'br)
   (str "presence...... Should I search around?")
   (wait)
   (text-reset 14)
   (proc 1))
 (seg*))
