(mes
 (meta (engine 'ADV) (charset "english") (extraop #t))
 (seg*
  (branch-reg 55 (</> (/) (/ (mes-jump "mes¥mb_c02a.mes"))))
  (exec-mem 14080 2 24 4 135 71 80 34 80 34 0 30)
  (image-file "gpc¥b05_02.gpc")
  (image-mem 0 3)
  (proc 3)
  (load-mem "clm¥b05_02.clm" 32768)
  (text-frame 10 312 70 383)
  (if (</>
       (//
        (? (= 254 #t))
        (text "I step inside the low building. This place where someone once")
        (text "lived is now devastated beyond recognition.")
        (wait)
        (text-reset 14))
       (//
        (? (= 54 #t))
        (text "I step inside the low building. This place where someone once")
        (text "lived is now devastated beyond recognition.")
        (wait)
        (text-reset 14)
        (text "I can't sense anyone around, but after hearing Colonel Karl's")
        (text "story, I won't let my guard down so easily.")
        (wait)
        (text-reset 14)
        (text "She's a professional. It would be trivial for her to get" 'br)
        (text "behind me without letting me sense her presence......")
        (wait)
        (text-reset 14)
        (nop@)
        (set-reg 254 #t))
       (//
        (? (= 928 #t))
        (text "I entered a room inside the building. Like I thought from" 'br)
        (text "outside, the spacious and decorated interior proves this was" 'br)
        (text "once upscale housing.")
        (wait)
        (text-reset 14))
       (//
        (? (= 928 #f))
        (text "I entered a room inside the building. Like I thought from" 'br)
        (text "outside, the spacious and decorated interior proves this was" 'br)
        (text "once upscale housing.")
        (wait)
        (text-reset 14)
        (text "The musty air filling the room and the carpet remnants" 'br)
        (text "half-turned to dirt make it hard to imagine anyone's lived" 'br)
        (text "here for a long time.")
        (wait)
        (text-reset 14)
        (text "But there's no guarantee there's a better room around here." 'br)
        (text "Can't rule this place out just yet......")
        (wait)
        (text-reset 14))))
  (nop@)
  (set-reg 928 #t)
  (exec-mem 3968 102 500 360)
  (exec-mem 3072 1)
  (loop (set-var S 0) (exec-mem 3072 1020 1021 "S" 32768) (seg-call)))
 (seg (? (= 1020 #f) (= 1021 #f)) (exec-mem 3072 1))
 (seg (? (= 1021 #t))
   (exec-mem 3072 0)
   (exec-mem 3968 103)
   (exec-mem 256 "A 0 S 0")
   (exec-mem 256 "G 1 4 64 12 48")
   (exec-mem 4768 4 8 12 4 1 0 0 4480 4480 1 0)
   (menu1 5 72 5 88 (</> (/ (str "  Travel  "))))
   (if (</>
        (//
         (? (= S 0))
         (exec-mem 256 "A 0 S 0")
         (exec-mem 256 "G 9 5 72 22 64")
         (exec-mem 4768 5 9 22 4 1 0 0 4480 4480 1 0)
         (menu1 6 80 (</> (/ (text "     Chinatown      "))))
         (exec-mem 256 "P 9 5 72")
         (exec-mem 256 "P 1 4 64")
         (if (</>
              (//
               (? (= S 0))
               (nop@)
               (set-reg 906 #t)
               (mes-jump "mes¥MB_C01.MES"))
              (// (? (= S 255))))))
        (// (? (= S 255)) (exec-mem 256 "P 1 4 64"))))
   (exec-mem 3968 104)
   (exec-mem 3072 2)
   (exec-mem 3072 1))
 (seg (? (= 1021 #t)) (exec-mem 3072 1))
 (seg (? (= S 1) (= 255 #f))
   (proc 0)
   (text "Part of the roof is gone, exposing wires that should be in" 'br)
   (text "the attic.")
   (wait)
   (text-reset 14)
   (text "I don't know what all these colorful wires were used for, but")
   (text "there's no doubt they're dead.")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 255 #t)
   (proc 1))
 (seg (? (= S 1) (= 256 #f))
   (proc 0)
   (text "If I had to guess, there was probably some kind of electrical")
   (text "device connected here.")
   (wait)
   (text-reset 14)
   (text "Lighting fixtures, security systems, or maybe communications" 'br)
   (text "equipment. Either way, they clearly had enough value to catch")
   (text "the looters' attention.")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 256 #t)
   (proc 1))
 (seg (? (= S 1) (= 256 #t))
   (proc 0)
   (text "Part of the roof is gone, exposing wires that should be in" 'br)
   (text "the attic.")
   (wait)
   (text-reset 14)
   (proc 1))
 (seg (? (= S 2) (= 257 #f))
   (proc 0)
   (text "The back room, which was probably once separated by a door," 'br)
   (text "appears to be a bathroom. I can see the remains of a tattered")
   (text "curtain.")
   (wait)
   (text-reset 14)
   (text "The unexpectedly old-fashioned design is surprising. A" 'br)
   (text "Western-style bathtub with wood flooring wouldn't have been" 'br)
   (text "modern even back then.")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 257 #t)
   (proc 1))
 (seg (? (= S 2) (= 258 #f))
   (proc 0)
   (text "Years of rainwater have collected in the bathtub, with" 'br)
   (text "something yellow-green floating on the surface - could be" 'br)
   (text "moss or mold.")
   (wait)
   (text-reset 14)
   (text "Just touching it would probably make me sick...... Surely" 'br)
   (text "no one would be hiding in there.")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 258 #t)
   (proc 1))
 (seg (? (= S 2) (= 258 #t))
   (proc 0)
   (text "The back room, which was probably once separated by a door," 'br)
   (text "appears to be a bathroom. I can see the remains of a tattered")
   (text "curtain.")
   (wait)
   (text-reset 14)
   (proc 1))
 (seg (? (= S 3) (= 259 #f))
   (proc 0)
   (text "The carpet, half-turned back to earth, and accumulated dust" 'br)
   (text "cover the entire floor.")
   (wait)
   (text-reset 14)
   (text "The puddles here and there must be from rain through holes in")
   (text "the roof. I don't see anything like footprints.")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 259 #t)
   (proc 1))
 (seg (? (= S 3) (= 260 #f))
   (proc 0)
   (text "Debris that was probably once part of the walls, roof, or" 'br)
   (text "furniture is scattered around.")
   (wait)
   (text-reset 14)
   (text "Was this the work of looters, or someone trying to make this" 'br)
   (text "place livable again?" 'br)
   (text "......I can't tell.")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 260 #t)
   (proc 1))
 (seg (? (= S 3) (= 260 #t))
   (proc 0)
   (text "The puddles here and there must be from rain through holes in")
   (text "the roof. I don't see anything like footprints.")
   (wait)
   (text-reset 14)
   (proc 1))
 (seg (? (= S 4) (= 261 #f))
   (proc 0)
   (text "Since they don't get sunlight, there's not much" 'br)
   (text "discoloration, but countless cracks run across the walls -" 'br)
   (text "hardly pristine condition.")
   (wait)
   (text-reset 14)
   (text "The bare wall showing through where the plaster has peeled" 'br)
   (text "off makes the room look even more wretched.")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 261 #t)
   (proc 1))
 (seg (? (= S 4) (= 262 #f))
   (proc 0)
   (text "The deep cracks running through these walls fuel my anxiety." 'br)
   (text "How long will they hold the ceiling's weight......")
   (wait)
   (text-reset 14)
   (text "But then again, we underground dwellers always live with that")
   (text "fear. If the crust collapses, we die all the same.")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 262 #t)
   (proc 1))
 (seg (? (= S 4) (= 262 #t))
   (proc 0)
   (text "Since they don't get sunlight, there's not much" 'br)
   (text "discoloration, but countless cracks run across the walls -" 'br)
   (text "hardly pristine condition.")
   (wait)
   (text-reset 14)
   (proc 1))
 (seg (? (= S 5) (= 54 #t))
   (proc 0)
   (text "Even if Lei-Fa grew up in the area, it's hard to imagine her" 'br)
   (text "hiding in this room.")
   (wait)
   (text-reset 14)
   (text "For one thing, she wouldn't get the help from her own people" 'br)
   (text "that she'd be counting on. Her secret might be safe," 'br)
   (text "but......")
   (wait)
   (text-reset 14)
   (proc 1))
 (seg (? (= S 5) (= 263 #f))
   (proc 0)
   (text "This room isn't exactly comfortable for living. The roof" 'br)
   (text "barely serves its purpose, and the floor is the same......")
   (wait)
   (text-reset 14)
   (text "Even if these women learned to endure all kinds of pain in" 'br)
   (text "the military, I can't imagine they could live in a place" 'br)
   (text "like this.")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 263 #t)
   (proc 1))
 (seg (? (= S 5) (= 263 #t))
   (proc 0)
   (text "Even if these women learned to endure all types of pain in" 'br)
   (text "the military, I can't imagine they could live in a place" 'br)
   (text "like this.")
   (wait)
   (text-reset 14)
   (proc 1))
 (seg*))