; X-Girl - Cyberpunk Adventure (PC-98) - MB_C02.MES
; Translation by Fuzion
; Script Editing by Tan2000
; Content Revision by OldCorpo
; Chapter 1 - April and Lei-Fa
; Section 1.4 Lei-Fa's arrest
; -----Location:-----
; Chinatown
; -----Scene:-----
; Search and arrest Lei-Fa.
; --Progression:--
; Inspect anything, talk to Vagrant, enter Ruined Building
(mes
 (meta (engine 'ADV) (charset "pc98") (extraop #t))
 (seg*
  (exec-mem 14080 2 24 4 135 71 80 34 80 34 0 30)
  (image-file "gpc¥b05_01.gpc")
  (image-mem 0 3)
  (proc 3)
  (if (</>
       (//
        (? (!= P 3))
        (if (</>
             (//
              (? (= O 0))
              (sound '|| 0)
              (sound '|| "uso¥xg_03.uso")
              (sound '|| 1)
              (nop@)
              (set-var P 3))
             (//
              (? (= O 1))
              (sound '|| 0)
              (sound '|| "uso¥xg_03v.uso")
              (sound '|| 1)
              (nop@)
              (set-var P 3)))))
       (// (nop@))))
  (load-mem "clm¥b05_01.clm" 32768)
  (text-frame 10 312 70 383)
  (if (</>
       (//
        (? (= 907 #t))
        (str "I've come to a section of Chinatown. Now that I've arrested" 'br)
        (str "Lei-Fa, there's no reason to be here......")
        (wait)
        (text-reset 14))
       (//
        (? (= 907 #f))
        (str "Chinatown. Derelict buildings everywhere, dark even at noon -")
        (str "feels like a criminal hideout.")
        (wait)
        (text-reset 14)
        (str "Last time I came here, I had no solid proof Lei-Fa was" 'br)
        (str "around, and I wasn't really motivated......")
        (wait)
        (text-reset 14)
        (str "This time I can't be so casual. I'm sure Lei-Fa is hiding in" 'br)
        (str "one of these buildings.")
        (wait)
        (text-reset 14))))
  (nop@)
  (set-reg 907 #t)
  (exec-mem 3968 102 500 360)
  (exec-mem 3072 1)
  (loop (set-var S 0) (exec-mem 3072 1020 1021 "S" 32768) (seg-call)))
 (seg (? (= 1020 #f) (= 1021 #f)) (exec-mem 3072 1))
 (seg (? (= 1021 #t) (= 59 #t))
   (exec-mem 3072 0)
   (exec-mem 3968 103)
   (exec-mem 256 "A 0 S 0")
   (exec-mem 256 "G 1 4 64 12 48")
   (exec-mem 4768 4 8 12 4 1 0 0 4480 4480 1 0)
   (menu1 5 72 (</> (/ (str "  Travel  "))))
   (if (</>
        (//
         (? (= S 0))
         (exec-mem 256 "A 0 S 0")
         (exec-mem 256 "G 9 5 72 22 64")
         (exec-mem 4768 5 9 22 4 1 0 0 4480 4480 1 0)
         (menu1 6 80 6 96 (</> (/ (str " Intel Div. Bldg.  "))))
         (exec-mem 256 "P 9 5 72")
         (exec-mem 256 "P 1 4 64")
         (if (</>
              (// (? (= S 0)) (mes-jump "mes¥MB_A02.MES"))
              (// (? (= S 255))))))
        (// (? (= S 255)) (exec-mem 256 "P 1 4 64"))))
   (exec-mem 3968 104)
   (exec-mem 3072 2)
   (exec-mem 3072 1))
 (seg (? (= 1021 #t) (= 59 #f) (= 339 #t))
   (exec-mem 3072 0)
   (exec-mem 3968 103)
   (exec-mem 256 "A 0 S 0")
   (exec-mem 256 "G 1 4 64 12 48")
   (exec-mem 4768 4 8 12 4 1 0 0 4480 4480 1 0)
   (menu1 5 72 (</> (/ (str "  Travel  "))))
   (if (</>
        (//
         (? (= S 0))
         (exec-mem 256 "A 0 S 0")
         (exec-mem 256 "G 9 5 72 22 64")
         (exec-mem 4768 5 9 22 4 1 0 0 4480 4480 1 0)
         (menu1 6 80 6 96 (</> (/ (str "  Ruined Building   "))))
         (exec-mem 256 "P 9 5 72")
         (exec-mem 256 "P 1 4 64")
         (if (</>
              (// (? (= S 0)) (mes-jump "mes¥MB_C02A.MES"))
              (// (? (= S 255))))))
        (// (? (= S 255)) (exec-mem 256 "P 1 4 64"))))
   (exec-mem 3968 104)
   (exec-mem 3072 2)
   (exec-mem 3072 1))
 (seg (? (= 1021 #t)) (exec-mem 3072 1))
 (seg (? (= S 1) (= 59 #t))
   (proc 0)
   (str "The run-down building where Lei-Fa was hiding. Even on the" 'br)
   (str "run, I'm amazed she could stand staying here when it could" 'br)
   (str "collapse any moment.")
   (wait)
   (text-reset 14)
   (proc 1))
 (seg (? (= S 1) (= 339 #t))
   (proc 0)
   (str "This crumbling building seems perfect for criminals trying to")
   (str "hide from pursuit......")
   (wait)
   (text-reset 14)
   (proc 1))
 (seg (? (= S 1) (= 338 #f))
   (proc 0)
   (str "A building about to collapse. Lower than the surrounding" 'br)
   (str "buildings - might have been upscale housing once.")
   (wait)
   (text-reset 14)
   (str "Despite nearly collapsing, the entrance has just enough space")
   (str "for someone to squeeze through. Looks like the perfect place" 'br)
   (str "to hide......")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 338 #t)
   (proc 1))
 (seg (? (= S 1) (= 338 #t) (= 345 #f))
   (proc 0)
   (str "Somewhat lower than the surrounding buildings, looks like it" 'br)
   (str "was once upscale housing. The entrance barely has enough" 'br)
   (str "space for one person to get through.")
   (wait)
   (text-reset 14)
   (proc 1))
 (seg (? (= S 1) (= 338 #t) (= 345 #t))
   (proc 0)
   (str "This crumbling building seems perfect for criminals trying to")
   (str "hide from pursuit......")
   (wait)
   (text-reset 14)
   (str "Even without the homeless man's tip, I would've guessed" 'br)
   (str "Lei-Fa would hide in a building just like this.")
   (wait)
   (text-reset 14)
   (str "Mission or not, it takes guts to go in there. If I wasn't so" 'br)
   (str "desperate, if my career wasn't on the line, I'd never set" 'br)
   (str "foot inside.")
   (wait)
   (text-reset 14)
   (str "But I don't have a choice now. I just hope Lei-Fa and that" 'br)
   (str "homeless guy aren't working together to lead me into a trap.")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 339 #t)
   (proc 1))
 (seg (? (= S 2) (= 340 #f))
   (proc 0)
   (str "The towering skyscrapers loom oppressively over a city of" 'br)
   (str "nothing but rubble and crumbling buildings.")
   (wait)
   (text-reset 14)
   (str "The people here have to look up at those towers every single" 'br)
   (str "day. What humiliation. I couldn't stand it for three days.")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 340 #t)
   (proc 1))
 (seg (? (= S 2) (= 341 #f))
   (proc 0)
   (str "In the distance, a cluster of tall buildings pierce the fog." 'br)
   (str "From here, they look like giant pillars holding up the sky.")
   (wait)
   (text-reset 14)
   (str "The buildings in this nearby district are so run-down they" 'br)
   (str "could collapse at any moment.")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 341 #t)
   (proc 1))
 (seg (? (= S 2) (= 341 #t))
   (proc 0)
   (str "The towering skyscrapers loom oppressively over a city of" 'br)
   (str "nothing but rubble and crumbling buildings.")
   (wait)
   (text-reset 14)
   (proc 1))
 (seg (? (= S 3) (= 342 #f))
   (proc 0)
   (str "It should be packed with cars, but through the gaping windows")
   (str "I only see pitch-black emptiness.")
   (wait)
   (text-reset 14)
   (str "I don't know how it became ruins, but scavengers probably" 'br)
   (str "cleaned it out completely afterward.")
   (wait)
   (text-reset 14)
   (str "Is this what it looks like when a country's time is running" 'br)
   (str "out?")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 342 #t)
   (proc 1))
 (seg (? (= S 3) (= 343 #f))
   (proc 0)
   (str "It looks like a massive multi-story parking garage connected" 'br)
   (str "to a shopping mall. It's a shadow of its former self now, but")
   (str "I can easily picture how busy it once was.")
   (wait)
   (text-reset 14)
   (str "Besides signs of destruction, I can see evidence of looting." 'br)
   (str "That must have happened years ago.")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 343 #t)
   (proc 1))
 (seg (? (= S 3) (= 343 #t))
   (proc 0)
   (str "Besides signs of destruction, I can see terrible looting" 'br)
   (str "damage. That must have happened years ago......")
   (wait)
   (text-reset 14)
   (proc 1))
 (seg (? (= S 4) (= 60 #t)) ; Line after Lei-Fa interrogation scene
   (proc 0)
   (text-delay 0)
   (str "「Vagrant」" 'br)
   (text-delay 2)
   (str "Thanks for earlier, lady. First woman I've had in five years!")
   (str "Though I feel bad for her......")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (str "「Kiyomi」" 'br)
   (text-delay 2)
   (str "No problem. If you need anything else, just ask.")
   (wait)
   (text-reset 14)
   (proc 1))
 (seg (? (= S 4) (= 59 #t))
   (proc 0)
   (text-delay 0)
   (str "「Vagrant」" 'br)
   (text-delay 2)
   (str "Hey, it's you again. Did you find that woman?")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (str "「Kiyomi」" 'br)
   (text-delay 2)
   (str "Yeah, thanks to you. Don't worry, I haven't forgotten my" 'br)
   (str "promise. I'll get you that reward soon.")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (str "「Vagrant」" 'br)
   (text-delay 2)
   (str "Looking forward to it.")
   (wait)
   (text-reset 14)
   (proc 1))
 (seg (? (= S 4) (= 344 #f))
   (proc 0)
   (str "He's frozen, watching my every move. Is he scared of me," 'br)
   (str "or is he sizing me up to see if I'm worth robbing?")
   (wait)
   (text-reset 14)
   (str "Either way, doesn't really matter. Even if he tried" 'br)
   (str "something, he doesn't look stronger than me......")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (str "「Kiyomi」" 'br)
   (text-delay 2)
   (str "Hey, we meet again. You always hanging around here?")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (str "「Vagrant」" 'br)
   (text-delay 2)
   (str ".........Oh, it's you from before.")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (str "「Kiyomi」" 'br)
   (text-delay 2)
   (str "So you remember me, buddy?")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (str "「Vagrant」" 'br)
   (text-delay 2)
   (str "Who's your buddy? You get a warm room and good food while" 'br)
   (str "I gotta walk all night to keep from freezing to death.")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (str "「Kiyomi」" 'br)
   (text-delay 2)
   (str "I'm just like you. Gotta walk my feet raw just to eat" 'br)
   (str "tomorrow. What a miserable world.")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (str "「Vagrant」" 'br)
   (text-delay 2)
   (str "Doesn't look that way to me.............")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (str "「Kiyomi」" 'br)
   (text-delay 2)
   (str "Help ease my suffering and tell me something. There's a woman")
   (str "hiding around here somewhere.")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (str "「Kiyomi」" 'br)
   (text-delay 2)
   (str "She's being hunted by the military, really desperate." 'br)
   (str "Ex-Special Forces, so she's probably armed.")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (str "「Vagrant」" 'br)
   (text-delay 2)
   (str "............Lady, what are you exactly?")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (str "「Kiyomi」" 'br)
   (text-delay 2)
   (str "If you've been hanging around here, you should know something")
   (str "about the woman I'm looking for......")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (str "「Vagrant」" 'br)
   (text-delay 2)
   (str "Being hunted doesn't narrow it down much.")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (str "「Kiyomi」" 'br)
   (text-delay 2)
   (str "So you do know something?")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (str "「Vagrant」" 'br)
   (text-delay 2)
   (str "What's she like? Race, face, build?")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (str "「Kiyomi」" 'br)
   (text-delay 2)
   (str "Chinese. Her face...... can't say since I've never seen her." 'br)
   (str "Military background, so probably pretty fit and muscular.")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (str "「Vagrant」" 'br)
   (text-delay 2)
   (str "There's plenty of Chinese around here. But, I might know" 'br)
   (str "something about that woman.")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 344 #t)
   (proc 1))
 (seg (? (= S 4) (= 345 #f))
   (proc 0)
   (text-delay 0)
   (str "「Kiyomi」" 'br)
   (text-delay 2)
   (str "You saw her, didn't you? Tell me already!")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (str "「Vagrant」" 'br)
   (text-delay 2)
   (str "What's in it for me? You walking your feet off doesn't fill" 'br)
   (str "my stomach.")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (str "「Kiyomi」" 'br)
   (text-delay 2)
   (str ".........Fair point.")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (str "「Vagrant」" 'br)
   (text-delay 2)
   (str "Lady, how much you getting for finding this woman? Share some")
   (str "with me and I'll talk.")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (str "「Kiyomi」" 'br)
   (text-delay 2)
   (str "Greed like that will bite you in the ass someday.")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (str "「Vagrant」" 'br)
   (text-delay 2)
   (str "Your threats don't work on me. I face death every day anyway.")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (str "「Kiyomi」" 'br)
   (text-delay 2)
   (str "Fine, fine. I'm with Intelligence. When you're dying," 'br)
   (str "I'll make sure Intelligence takes care of you.")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (str "「Vagrant」" 'br)
   (text-delay 2)
   (str "...............")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (str "「Kiyomi」" 'br)
   (text-delay 2)
   (str "How's that sound?")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (str "「Vagrant」" 'br)
   (text-delay 2)
   (str "Can I trust you?")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (str "「Kiyomi」" 'br)
   (text-delay 2)
   (str "However far we've fallen, we're still the same people, right?")
   (str "Like siblings. It'd be sad if you couldn't trust me.")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (str "「Vagrant」" 'br)
   (text-delay 2)
   (str "Alright. There's been an unfamiliar woman going in and out of")
   (str "that low building over there.")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (str "「Kiyomi」" 'br)
   (text-delay 2)
   (str "What makes you think she's the one I'm looking for?")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (str "「Vagrant」" 'br)
   (text-delay 2)
   (str "She's Chinese, but doesn't seem to know the locals. Acts" 'br)
   (str "scared, moves all wrong......")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (str "「Kiyomi」" 'br)
   (text-delay 2)
   (str "I see. That's some sharp observation. Got it, I'll check that")
   (str "building.")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (str "「Vagrant」" 'br)
   (text-delay 2)
   (str "If she's the one you're looking for, make sure I get" 'br)
   (str "something good out of it.")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 345 #t)
   (proc 1))
 (seg (? (= S 4) (= 345 #t))
   (proc 0)
   (text-delay 0)
   (str "「Vagrant」" 'br)
   (text-delay 2)
   (str "If she's the one you're looking for, make sure I get" 'br)
   (str "something good out of it.")
   (wait)
   (text-reset 14)
   (proc 1))
 (seg (? (= S 5))
   (proc 0)
   (if (</>
        (//
         (? (= 63 #t)) ; Line after Mitsuko arrested
         (nop@)
         (branch-index
          (</>
           (/
            (str "From the three prisoners' testimony, I know Mitsuko was the" 'br)
            (str "one who suggested stealing military secrets.")
            (wait)
            (text-reset 14)
            (str "But it's also clear someone was pulling the strings from" 'br)
            (str "behind. Mitsuko should know who.")
            (wait)
            (text-reset 14)
            (str "I'm finally starting to understand the rhythm and color of" 'br)
            (str "this whole case. At this rate, the mission should be over" 'br)
            (str "soon.")
            (wait)
            (text-reset 14))
           (/
            (str "If I interrogate Mitsuko, I should learn about the mastermind")
            (str "pulling their strings.")
            (wait)
            (text-reset 14)))))
        (//
         (? (= 62 #t)) ; Line after Nana interrogation
         (nop@)
         (str "Nana's supposed to meet Mitsuko on the subway between Tokyo" 'br)
         (str "and Chiba. If I go there, I should be able to capture" 'br)
         (str "Mitsuko.")
         (wait)
         (text-reset 14))
        (//
         (? (= 61 #t))
         (nop@)
         (str "Unlike April and Lei-Fa, Nana's just a regular ex-soldier." 'br)
         (str "She should break easily under torture......")
         (wait)
         (text-reset 14))
        (//
         (? (= 66 #t))
         (nop@)
         (str "Anna knows Morii? She told me to go to Morii's shop......")
         (wait)
         (text-reset 14))
        (//
         (? (= 65 #t))
         (nop@)
         (branch-index
          (</>
           (/
            (str "That woman I met at the shady shop in Chiba, Morii......" 'br)
            (str "She seems pretty well-known in Chiba's underworld.")
            (wait)
            (text-reset 14)
            (str "And she seemed to know something about those two. But" 'br)
            (str "military and Intelligence authority means nothing in Chiba.")
            (wait)
            (text-reset 14)
            (str "Force doesn't seem like a good idea with her...... How can I" 'br)
            (str "get Morii to talk?")
            (wait)
            (text-reset 14))
           (/
            (str "Morii seems to know something about Nana and Mitsuko. Even if")
            (str "not, she has information connections in Chiba. I need to get" 'br)
            (str "her on my side somehow.")
            (wait)
            (text-reset 14)))))
        (//
         (? (= 58 #t) (= 60 #t))
         (branch-index
          (</>
           (/
            (str "From what I got out of April and Lei-Fa, they were recruited" 'br)
            (str "by Mitsuko, a former secretary to a military official.")
            (wait)
            (text-reset 14)
            (str "And Mitsuko and Nana were lovers. The story about them hiding")
            (str "together in Chiba might actually be true.")
            (wait)
            (text-reset 14))
           (/
            (str "My next task is to capture Nana and Mitsuko. They apparently" 'br)
            (str "fled to Chiba City. But......")
            (wait)
            (text-reset 14)
            (str "Chiba is a lawless zone abandoned by the government and" 'br)
            (str "military - a place where even Intelligence's authority" 'br)
            (str "doesn't reach.")
            (wait)
            (text-reset 14)
            (str "Forget finding them, I'll be glad to get out with" 'br)
            (str "my life......")
            (wait)
            (text-reset 14))
           (/
            (str "My next task is to capture Nana and Mitsuko. They apparently" 'br)
            (str "fled to Chiba City. But......")
            (wait)
            (text-reset 14)))))
        (//
         (? (= 57 #t) (= 58 #f) (= 59 #f) (= 60 #f))
         (nop@)
         (str "First I should interrogate April. She might hold the key to" 'br)
         (str "solving this whole case.")
         (wait)
         (text-reset 14)
         (str "If that doesn't work, at least I might get a hint for" 'br)
         (str "capturing Lei-Fa or finding the third prisoner.")
         (wait)
         (text-reset 14))
        (//
         (? (= 57 #t) (= 58 #t) (= 59 #f) (= 60 #f))
         (nop@)
         (str "I hate to think April could withstand my torture. Did she" 'br)
         (str "really know nothing?")
         (wait)
         (text-reset 14))
        (//
         (? (= 57 #t) (= 58 #t) (= 59 #t) (= 60 #f))
         (nop@)
         (str "I've captured the second prisoner, Lei-Fa. Interrogating her" 'br)
         (str "might give me more information.")
         (wait)
         (text-reset 14))
        (//
         (? (= 57 #t) (= 58 #f) (= 59 #t) (= 60 #f))
         (nop@)
         (str "I've arrested both prisoners. Interrogating them should give" 'br)
         (str "me info about the classified material I'm looking for.")
         (wait)
         (text-reset 14))
        (//
         (? (= 57 #f) (= 58 #f) (= 59 #t) (= 60 #f))
         (nop@)
         (str "I've arrested Lei-Fa. Interrogating her might provide the key")
         (str "to solving this whole case.")
         (wait)
         (text-reset 14))
        (//
         (? (= 57 #f) (= 58 #f) (= 59 #t) (= 60 #t))
         (nop@)
         (str "I hate to think Lei-Fa could withstand my torture. Did she" 'br)
         (str "really know nothing?")
         (wait)
         (text-reset 14))
        (//
         (? (= 57 #t) (= 58 #f) (= 59 #t) (= 60 #t))
         (nop@)
         (str "Lei-Fa didn't talk. I have to do something about April." 'br)
         (str "Anything - I have to make something work......")
         (wait)
         (text-reset 14))
        (//
         (str "First I need to arrest April or Lei-Fa. Fighting someone" 'br)
         (str "clearly stronger than me makes me nervous......")
         (wait)
         (text-reset 14))))
   (proc 1)))
