(mes
 (meta (engine 'ADV) (charset "english") (extraop #t))
 (seg*
  (load-mem "clm¥b04_01.clm" 32768)
  (exec-mem 14080 2 24 4 135 71 80 34 80 34 0 30)
  (image-file "gpc¥b04_01.gpc")
  (image-mem 0 3)
  (if (</>
       (//
        (? (= P 6))
        (if (</>
             (//
              (? (= O 0))
              (sound '|| 0)
              (sound '|| "uso¥xg_06.uso")
              (sound '|| 1)
              (nop@)
              (set-var P 6))
             (//
              (? (= O 1))
              (sound '|| 0)
              (sound '|| "uso¥xg_06v.uso")
              (sound '|| 1)
              (nop@)
              (set-var P 6)))))
       (// (nop@))))
  (if (</>
       (//
        (? (= 57 #t))
        (proc 3)
        (text-frame 10 312 70 383)
        (text "April's \(former\) shop in Akihabara's black market. Now that" 'br)
        (text "the owner's been arrested, there's nothing to do here......")
        (wait)
        (text-reset 14)
        (nop@)
        (set-reg 932 #t)
        (mes-jump "mes¥mb_a02.mes"))
       (//
        (? (= 57 #f))
        (image-file "gpc¥b04_01a.gpc")
        (image-mem 1 0)
        (load-mem "clm¥b04_01.clm" 32768)
        (proc 3)
        (text-frame 10 312 70 383)
        (text-delay 0)
        (text "「Counter Girl」" 'br)
        (text-delay 2)
        (text "Welcome...... Oh, it's you again.")
        (wait)
        (text-reset 14)
        (text-delay 0)
        (text "「Kiyomi」" 'br)
        (text-delay 2)
        (text "Well, well. I'm surprised you're still here. Thought" 'br)
        (text "you'd have disappeared ages ago.")
        (wait)
        (text-reset 14)
        (text-delay 0)
        (text "「Counter Girl」" 'br)
        (text-delay 2)
        (text "Huh...... W-what are you talking about?")
        (wait)
        (text-reset 14)
        (text-delay 0)
        (text "「Kiyomi」" 'br)
        (text-delay 2)
        (text "I'm talking about you. I really hate being taken for a fool." 'br)
        (text "Can't stand being treated like one.")
        (wait)
        (text-reset 14)
        (text-delay 0)
        (text "「Counter Girl」" 'br)
        (text-delay 2)
        (text "..................")
        (wait)
        (text-reset 14)
        (text-delay 0)
        (text "「Kiyomi」" 'br)
        (text-delay 2)
        (text "Or what, are you that confident?")
        (wait)
        (text-reset 14)
        (text-delay 0)
        (text "「Counter Girl」" 'br)
        (text-delay 2)
        (text "I-I really don't understand what you're saying.")
        (wait)
        (text-reset 14)
        (text-delay 0)
        (text "「Kiyomi」" 'br)
        (text-delay 2)
        (text "Fine. Then I'll make sure you understand, whether you like it")
        (text "or not.")
        (wait)
        (text-reset 14))))
  (nop@)
  (set-reg 932 #f)
  (exec-mem 3968 102 500 360)
  (exec-mem 3072 1)
  (loop (set-var S 0) (exec-mem 3072 1020 1021 "S" 32768) (seg-call)))
 (seg (? (= 1020 #f) (= 1021 #f)) (exec-mem 3072 1))
 (seg (? (= 1021 #t) (= 57 #t))
   (exec-mem 3072 0)
   (exec-mem 3968 103)
   (exec-mem 256 "A 0 S 0")
   (exec-mem 256 "G 1 4 64 12 48")
   (exec-mem 4768 4 8 12 4 1 0 0 4480 4480 1 0)
   (menu1 5 72 (</> (/ (str "  Travel  "))))
   (if (</>
        (//
         (? (= S 0))
         (exec-mem 256 "A 0 S 0")
         (exec-mem 256 "G 9 5 72 22 64")
         (exec-mem 4768 5 9 22 4 1 0 0 4480 4480 1 0)
         (menu1 6 80 (</> (/ (text " Intel Dept. Bldg.  "))))
         (exec-mem 256 "P 9 5 72")
         (exec-mem 256 "P 1 4 64")
         (if (</>
              (// (? (= S 0)) (mes-jump "mes¥MB_A02.MES"))
              (// (? (= S 255))))))
        (// (? (= S 255)) (exec-mem 256 "P 1 4 64"))))
   (exec-mem 3968 104)
   (exec-mem 3072 2)
   (exec-mem 3072 1))
 (seg (? (= 1021 #t) (= 57 #f) (= 368 #t) (= 931 #f))
   (exec-mem 3072 0)
   (exec-mem 3968 103)
   (exec-mem 256 "A 0 S 0")
   (exec-mem 256 "G 1 4 64 16 48")
   (exec-mem 4768 4 8 16 4 1 0 0 4480 4480 1 0)
   (menu1 5 72 (</> (/ (str "Put on goggles"))))
   (if (</>
        (//
         (? (= S 0))
         (exec-mem 256 "P 1 4 64")
         (if (</>
              (//
               (? (= 369 #f))
               (text "I put on the goggles.")
               (wait)
               (text-reset 14)
               (image-file "gpc¥b04_01b.gpc")
               (image-mem 0 3)
               (image-file "gpc¥shotwaku.gpc")
               (image-mem 1 0)
               (proc 3)
               (text "My vision turns completely green. This is what the world" 'br)
               (text "looks like through the filter...... And there, floating" 'br)
               (text "undeniably in the goggles' display, is a swastika mark.")
               (wait)
               (text-reset 14)
               (text-delay 0)
               (text "「Counter Girl」" 'br)
               (text-delay 2)
               (text "That's...... Those goggles, I've seen them before.")
               (wait)
               (text-reset 14)
               (text-delay 0)
               (text "「Kiyomi」" 'br)
               (text-delay 2)
               (text "Is that so? Well, then you should know what I see......")
               (wait)
               (text-reset 14)
               (text-delay 0)
               (text "「Counter Girl」" 'br)
               (text-delay 2)
               (text "Don't tell me, on my body...... Shit!")
               (wait)
               (text-reset 14)
               (text-delay 0)
               (text "「Kiyomi」" 'br)
               (text-delay 2)
               (text "Nice to meet you, April. Though I've suspected you for quite" 'br)
               (text "a while now!")
               (wait)
               (text-reset 14)
               (text-delay 0)
               (text "「April」" 'br)
               (text-delay 2)
               (text "Damn it! I should have gotten out when I had the chance.")
               (wait)
               (text-reset 14)
               (text-delay 0)
               (text "「Kiyomi」" 'br)
               (text-delay 2)
               (text "Too late. You held onto your cover too tightly. Was life as a")
               (text "surplus dealer that enjoyable?")
               (wait)
               (text-reset 14)
               (text-delay 0)
               (text "「April」" 'br)
               (text-delay 2)
               (text "You wouldn't understand!")
               (wait)
               (text-reset 14)
               (text-delay 0)
               (text "「April」" 'br)
               (text-delay 2)
               (text "I survived hellish battlefields in the Foreign Legion, but" 'br)
               (text "after discharge I'm just another immigrant!")
               (wait)
               (text-reset 14)
               (text-delay 0)
               (text "「April」" 'br)
               (text-delay 2)
               (text "And now I'm the bad guy here......")
               (wait)
               (text-reset 14)
               (text-delay 0)
               (text "「Kiyomi」" 'br)
               (text-delay 2)
               (text "April, you're under arrest.")
               (wait)
               (text-reset 14)
               (nop@)
               (set-reg 369 #t))
              (//
               (? (= 369 #t))
               (text "I put on the goggles. My vision turns green......")
               (wait)
               (text-reset 14)
               (image-file "gpc¥b04_01b.gpc")
               (image-mem 0 3)
               (image-file "gpc¥shotwaku.gpc")
               (image-mem 1 0)
               (proc 3))))
         (nop@)
         (set-reg 931 #t))
        (// (? (= S 255)) (exec-mem 256 "P 1 4 64"))))
   (exec-mem 3968 104)
   (exec-mem 3072 2)
   (exec-mem 3072 1))
 (seg (? (= 1021 #t) (= 57 #f) (= 368 #f) (= 931 #f)) (exec-mem 3072 1))
 (seg (? (= 1021 #t) (= 57 #f) (= 931 #t))
   (exec-mem 3072 0)
   (exec-mem 3968 103)
   (exec-mem 256 "A 0 S 0")
   (exec-mem 256 "G 1 4 64 16 48")
   (exec-mem 4768 4 8 16 4 1 0 0 4480 4480 1 0)
   (menu1 5 72 (</> (/ (str "Remove goggles"))))
   (if (</>
        (//
         (? (= S 0))
         (exec-mem 256 "P 1 4 64")
         (text "I took off the goggles.")
         (wait)
         (text-reset 14)
         (image-file "gpc¥b04_01.gpc")
         (image-mem 0 3)
         (image-file "gpc¥b04_01a.gpc")
         (image-mem 1 0)
         (proc 3)
         (nop@)
         (set-reg 931 #f))
        (// (? (= S 255)) (exec-mem 256 "P 1 4 64"))))
   (exec-mem 3968 104)
   (exec-mem 3072 2)
   (exec-mem 3072 1))
 (seg (? (= 1021 #t)) (exec-mem 3072 1))
 (seg (? (= S 3) (= 361 #f))
   (proc 0)
   (text "Most of the guns in the case are secondhand, military issue." 'br)
   (text "The military must be really desperate, to trash their own" 'br)
   (text "laws like this.")
   (wait)
   (text-reset 14)
   (text "Though now that guns have spread throughout the city," 'br)
   (text "gun control is pretty meaningless anyway......")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 361 #t)
   (proc 1))
 (seg (? (= S 3) (= 362 #f))
   (proc 0)
   (text "The glass case displays old-model light machine guns and" 'br)
   (text "various handguns.")
   (wait)
   (text-reset 14)
   (text "Even knowing most of these guns will end up in criminals'" 'br)
   (text "hands, there's nothing we can do about it.")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 362 #t)
   (proc 1))
 (seg (? (= S 3) (= 362 #t))
   (proc 0)
   (text "Most of the guns in the case are secondhand, military issue." 'br)
   (text "The military must be really desperate, to trash their own" 'br)
   (text "laws like this.")
   (wait)
   (text-reset 14)
   (proc 1))
 (seg (? (= S 4) (= 363 #f))
   (proc 0)
   (text "Old gas masks are carelessly heaped on the wall. Probably" 'br)
   (text "used on some front line, but who would buy them?")
   (wait)
   (text-reset 14)
   (text "If we really needed gas masks, I don't think these cheap" 'br)
   (text "secondhand ones would protect anyone.")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 363 #t)
   (proc 1))
 (seg (? (= S 4) (= 363 #t))
   (proc 0)
   (text "Old gas masks are carelessly heaped on the wall. Probably" 'br)
   (text "used on some front line, but who would buy them now?")
   (wait)
   (text-reset 14)
   (proc 1))
 (seg (? (= S 5) (= 365 #f))
   (proc 0)
   (text "Military boots and packs are piled up like mountains. Both" 'br)
   (text "look like they were actually used in combat.")
   (wait)
   (text-reset 14)
   (text "They'd still work fine, but thinking about how many were" 'br)
   (text "stripped from dead soldiers, I couldn't bring myself to" 'br)
   (text "buy one......")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 365 #t)
   (proc 1))
 (seg (? (= S 5) (= 365 #t))
   (proc 0)
   (text "Military boots and packs are piled up like mountains. Both" 'br)
   (text "look like they were actually used in combat.")
   (wait)
   (text-reset 14)
   (proc 1))
 (seg (? (>= S 6) (= 57 #t))
   (proc 0)
   (text "April's not here anymore. The shop she risked her freedom to" 'br)
   (text "protect will probably belong to looters soon.")
   (wait)
   (text-reset 14)
   (proc 1))
 (seg (? (= S 6) (= 368 #t))
   (proc 0)
   (text "Fighting April will be unavoidable. But it's not like I have" 'br)
   (text "no chance of winning.")
   (wait)
   (text-reset 14)
   (text "She's been immersed in her cover life too long - she no" 'br)
   (text "longer has the sharpness and cruelty from her Special Forces" 'br)
   (text "days......")
   (wait)
   (text-reset 14)
   (proc 1))
 (seg (? (= S 6) (= 359 #t) (= 360 #t))
   (proc 0)
   (text "Yeah, this woman is definitely April. Time to use those" 'br)
   (text "special goggles......")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 368 #t)
   (proc 1))
 (seg (? (= S 6))
   (proc 0)
   (branch-reg
    81
    (</>
     (/
      (text "The counter girl is nervously watching me. Not surprising" 'br)
      (text "after how much I threatened her last time......")
      (wait)
      (text-reset 14)
      (text "If this woman was April, normally she'd have disappeared" 'br)
      (text "right after my last visit.")
      (wait)
      (text-reset 14)
      (text "But my instincts are telling me I've found her, and I don't" 'br)
      (text "think they're wrong.")
      (wait)
      (text-reset 14))
     (/
      (text "It's obvious this woman is April from Lei-Fa's testimony." 'br)
      (text "No matter how good her act is, she can't escape now.")
      (wait)
      (text-reset 14)
      (text "She never imagined her fellow fugitive would get captured and")
      (text "rat her out......")
      (wait)
      (text-reset 14)
      (text "No matter how this plays out, April has no chance of winning.")
      (text "I'd prefer if she just gave up without causing trouble.")
      (wait)
      (text-reset 14))))
   (nop@)
   (set-reg 367 #t)
   (proc 1))
 (seg (? (= S 1) (= 370 #t))
   (proc 0)
   (text-delay 0)
   (text "「Kiyomi」" 'br)
   (text-delay 2)
   (text "Didn't you hear me? Put your hands on the counter!")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (text "「April」" 'br)
   (text-delay 2)
   (text "............")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (text "「Kiyomi」" 'br)
   (text-delay 2)
   (text "Think you can beat me now? You've gotten soft living under" 'br)
   (text "cover.")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (text "「Kiyomi」" 'br)
   (text-delay 2)
   (text "April, you're not Special Forces elite anymore. The smart" 'br)
   (text "move would be not to struggle.")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (text "「April」" 'br)
   (text-delay 2)
   (text "T-that's...... You don't know that! Come at me!")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (text "「Kiyomi」" 'br)
   (text-delay 2)
   (text "Damn. Can't be helped......")
   (wait)
   (text-reset 14)
   (proc 1)
   (exec-mem 3072 0)
   (mes-jump "mes¥MC_A01.MES"))
 (seg (? (= S 1) (= 369 #t))
   (proc 0)
   (text-delay 0)
   (text "「Kiyomi」" 'br)
   (text-delay 2)
   (text "Not that I don't sympathize, but stealing military intel was" 'br)
   (text "a mistake. Did you really think you could get away with it?")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (text "「April」" 'br)
   (text-delay 2)
   (text "............")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (text "「Kiyomi」" 'br)
   (text-delay 2)
   (text "I don't know who put you up to this, but they had no" 'br)
   (text "intention of protecting you.")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (text "「April」" 'br)
   (text-delay 2)
   (text "That's not it! I didn't...... I didn't want money or glory.")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (text "「April」" 'br)
   (text-delay 2)
   (text "I'm just an immigrant after all. In this country, I'm not" 'br)
   (text "much different from garbage. But......")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (text "「April」" 'br)
   (text-delay 2)
   (text "They said they needed someone like me......")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (text "「Kiyomi」" 'br)
   (text-delay 2)
   (text "I'll hear the details at Intelligence.")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (text "「April」" 'br)
   (text-delay 2)
   (text "............Who's just going to let you capture them?")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (text "「Kiyomi」" 'br)
   (text-delay 2)
   (text "Put your hands on the counter, now!")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 370 #t)
   (proc 1))
 (seg (? (= S 1) (= 358 #f))
   (proc 0)
   (text-delay 0)
   (text "「Kiyomi」" 'br)
   (text-delay 2)
   (text "I asked you to contact me last time, but I never heard" 'br)
   (text "anything about April showing up at your shop.")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (text "「Counter Girl」" 'br)
   (text-delay 2)
   (text "Oh, well...... that's because April never showed up.")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (text "「Kiyomi」" 'br)
   (text-delay 2)
   (text "I see...... I wonder what April's doing. No job after leaving")
   (text "the military, probably struggling just to eat.")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (text "「Counter Girl」" 'br)
   (text-delay 2)
   (text "..................Maybe so.")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (text "「Kiyomi」" 'br)
   (text-delay 2)
   (text "Aren't you worried? Your friend might be suffering all by" 'br)
   (text "herself out there.")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (text "「Counter Girl」" 'br)
   (text-delay 2)
   (text "........................")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (text "「Kiyomi」" 'br)
   (text-delay 2)
   (text "Are you scared of me? I can see it all over your face. Don't" 'br)
   (text "worry, I won't do anything. Unless you're April.")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 358 #t)
   (proc 1))
 (seg (? (= S 1) (= 359 #f))
   (proc 0)
   (text-delay 0)
   (text "「Counter Girl」" 'br)
   (text-delay 2)
   (text "Please, just go away...... I'll contact you if April comes!")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (text "「Kiyomi」" 'br)
   (text-delay 2)
   (text "No need to be so hostile. I'm not planning to do anything to" 'br)
   (text "you.")
   (wait)
   (text-reset 14)
   (branch-reg
    59
    (</>
     (/
      (text-delay 0)
      (text "「Kiyomi」" 'br)
      (text-delay 2)
      (text "By the way, did you know? April was captured by the military" 'br)
      (text "and interrogated.")
      (wait)
      (text-reset 14)
      (text-delay 0)
      (text "「Counter Girl」" 'br)
      (text-delay 2)
      (text "..................")
      (wait)
      (text-reset 14)
      (text-delay 0)
      (text "「Kiyomi」" 'br)
      (text-delay 2)
      (text "And back then, the bastard who did the interrogation put a" 'br)
      (text "mark on April's body.")
      (wait)
      (text-reset 14)
      (text-delay 0)
      (text "「Counter Girl」" 'br)
      (text-delay 2)
      (text "A mark, huh......")
      (wait)
      (text-reset 14)
      (text-delay 0)
      (text "「Kiyomi」" 'br)
      (text-delay 2)
      (text "Shouldn't the person who got marked know about it?")
      (wait)
      (text-reset 14)
      (text-delay 0)
      (text "「Counter Girl」" 'br)
      (text-delay 2)
      (text "I told you...... I don't know anything!")
      (wait)
      (text-reset 14)
      (text-delay 0)
      (text "「Kiyomi」" 'br)
      (text-delay 2)
      (text "Give it up. You can't escape anymore.")
      (wait)
      (text-reset 14))
     (/
      (text-delay 0)
      (text "「Kiyomi」" 'br)
      (text-delay 2)
      (text "By the way, I arrested your comrade Lei-Fa too.")
      (wait)
      (text-reset 14)
      (text-delay 0)
      (text "「Counter Girl」" 'br)
      (text-delay 2)
      (text "Wha.........")
      (wait)
      (text-reset 14)
      (text-delay 0)
      (text "「Kiyomi」" 'br)
      (text-delay 2)
      (text "That got a rise out of you, huh? Still going to claim you're" 'br)
      (text "not involved?")
      (wait)
      (text-reset 14)
      (text-delay 0)
      (text "「Counter Girl」" 'br)
      (text-delay 2)
      (text "I-I told you I don't know her!")
      (wait)
      (text-reset 14)
      (text-delay 0)
      (text "「Kiyomi」" 'br)
      (text-delay 2)
      (text "You're a stubborn woman. I heard about you from Lei-Fa.")
      (wait)
      (text-reset 14)
      (text-delay 0)
      (text "「Counter Girl」" 'br)
      (text-delay 2)
      (text "Don't make things up. That can't be true......")
      (wait)
      (text-reset 14))))
   (nop@)
   (set-reg 359 #t)
   (proc 1))
 (seg (? (= S 1) (= 359 #t))
   (proc 0)
   (text-delay 0)
   (text "「Kiyomi」" 'br)
   (text-delay 2)
   (text "Give it up. You can't escape anymore.")
   (wait)
   (text-reset 14)
   (proc 1))
 (seg (? (= S 2) (= 371 #t))
   (proc 0)
   (text "If this woman is April, she no longer has her Special Forces" 'br)
   (text "abilities. Trembling just at the sight of a gun.")
   (wait)
   (text-reset 14)
   (proc 1))
 (seg (? (= S 2) (= 369 #t))
   (proc 0)
   (text "The woman's face has gone pale after seeing me draw my" 'br)
   (text "weapon, and she can't even look me in the eye.")
   (wait)
   (text-reset 14)
   (text "A normal reaction......")
   (wait)
   (text-reset 14)
   (text "But if this woman is April, she no longer has her Special" 'br)
   (text "Forces abilities. Trembling just at the sight of a gun.")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 371 #t)
   (proc 1))
 (seg (? (= S 2) (= 360 #f))
   (proc 0)
   (text "She's watching me like I'm a suspicious customer. She's" 'br)
   (text "pretending to be an innocent surplus shop clerk, but she's" 'br)
   (text "clearly on edge.")
   (wait)
   (text-reset 14)
   (text "Her right arm is positioned under the counter, constantly" 'br)
   (text "scanning her surroundings. She's definitely not who she" 'br)
   (text "seems to be......")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 360 #t)
   (proc 1))
 (seg (? (= S 2) (= 360 #t))
   (proc 0)
   (text "Is she planning how to escape? She's restless, looking over" 'br)
   (text "at the back door of the shop......")
   (wait)
   (text-reset 14)
   (proc 1))
 (seg*))