; X-Girl - Cyberpunk Adventure (PC-98) - MB_D01.MES
; Translation by Fuzion
; Script Editing by Tan2000
; Content Revision by OldCorpo
; Chapter 1 - April & Lei-Fa
; Section 1.2 - Search for April and Lei-Fa
; -----Location:-----
; Akihabara Shop
; -----Scene:-----
; Initial search for April location.
; --Progression:--
; Talk to Counter Girl after inspecting everything in the scene.
(mes
 (meta (engine 'ADV) (charset "pc98") (extraop #t))
 (seg*
  (branch-reg 56 (</> (/) (/ (mes-jump "mes¥mb_d02.mes"))))
  (if (</>
       (//
        (? (!= P 6))
        (if (</>
             (//
              (? (= O 0))
              (sound '|| 0)
              (sound '|| "uso¥xg_06.uso")
              (sound '|| 1)
              (nop@)
              (set-var P 6))
             (//
              (? (= O 1))
              (sound '|| 0)
              (sound '|| "uso¥xg_06v.uso")
              (sound '|| 1)
              (nop@)
              (set-var P 6)))))
       (// (nop@))))
  (if (</>
       (//
        (? (= 908 #t))
        (exec-mem 14080 2 24 4 135 71 80 34 80 34 0 30)
        (image-file "gpc¥b04_01.gpc")
        (image-mem 0 3)
        (image-file "gpc¥b04_01a.gpc")
        (image-mem 1 0)
        (proc 3)
        (load-mem "clm¥b04_01.clm" 32768)
        (text-frame 10 312 70 383)
        (text-delay 0)
        (str "「Counter Girl」" 'br)
        (text-delay 2)
        (str "Oh, you're......")
        (wait)
        (text-reset 14)
        (text-delay 0)
        (str "「Kiyomi」" 'br)
        (text-delay 2)
        (str "You don't need to be so scared...... I'm just dropping by.")
        (wait)
        (text-reset 14))
       (//
        (? (= 908 #f)) ; Lead-in from previous MB_A01.MES script (1st time visit)
        (exec-mem 14080 2 24 4 135 71 80 34 80 34 0 30)
        (image-file "gpc¥b04_01.gpc")
        (image-mem 0 3)
        (load-mem "clm¥b04_01.clm" 32768)
        (proc 3)
        (text-frame 10 312 70 383)
        (str "I entered a shop in Akihabara's black market. Looks like this")
        (str "place sells military surplus.")
        (wait)
        (text-reset 14)
        (str "Military supplies fill every inch of the store. April was" 'br)
        (str "ex-Special Forces - she would have been familiar with these" 'br)
        (str "items.")
        (wait)
        (text-reset 14)
        (str "The story about her staying with a friend after being" 'br)
        (str "discharged...... If it was someone she knew from the" 'br)
        (str "military, then I could believe it.")
        (wait)
        (text-reset 14)
        (image-file "gpc¥b04_01a.gpc")
        (image-mem 1 0)
        (text-delay 0)
        (str "「Counter Girl」" 'br)
        (text-delay 2)
        (str "Welcome. What are you looking for?")
        (wait)
        (text-reset 14)
        (str "A friendly-looking woman emerged from the back of the store." 'br)
        (str "It's unusual to see a woman running this type of business.")
        (wait)
        (text-reset 14)
        (text-delay 0)
        (str "「Kiyomi」" 'br)
        (text-delay 2)
        (str "What if I was looking for something that isn't on display?")
        (wait)
        (text-reset 14)
        (text-delay 0)
        (str "「Counter Girl」" 'br)
        (text-delay 2)
        (str "If you're looking for items not on display...... are you" 'br)
        (str "military by any chance?")
        (wait)
        (text-reset 14)
        (text-delay 0)
        (str "「Kiyomi」" 'br)
        (text-delay 2)
        (str "Good guess. That's right.")
        (wait)
        (text-reset 14)
        (text-delay 0)
        (str "「Counter Girl」" 'br)
        (text-delay 2)
        (str "I-I'm not doing any illegal business! Everything in the" 'br)
        (str "store is military surplus...... I have permits!")
        (wait)
        (text-reset 14)
        (text-delay 0)
        (str "「Kiyomi」" 'br)
        (text-delay 2)
        (str "How about you show me what's in the back room.")
        (wait)
        (text-reset 14)
        (text-delay 0)
        (str "「Counter Girl」" 'br)
        (text-delay 2)
        (str "........................")
        (wait)
        (text-reset 14)
        (nop@)
        (set-reg 908 #t))))
  (exec-mem 3968 102 500 360)
  (exec-mem 3072 1)
  (loop (set-var S 0) (exec-mem 3072 1020 1021 "S" 32768) (seg-call)))
 (seg (? (= 1020 #f) (= 1021 #f)) (exec-mem 3072 1))
 (seg (? (= 1021 #t) (= 286 #t))
   (exec-mem 3072 0)
   (exec-mem 3968 103)
   (exec-mem 256 "A 0 S 0")
   (exec-mem 256 "G 1 4 64 12 48")
   (exec-mem 4768 4 8 12 4 1 0 0 4480 4480 1 0)
   (menu1 5 72 (</> (/ (str "  Travel  "))))
   (if (</>
        (//
         (? (= S 0))
         (exec-mem 256 "A 0 S 0")
         (exec-mem 256 "G 9 5 72 22 64")
         (exec-mem 4768 5 9 22 4 1 0 0 4480 4480 1 0)
         (menu1 6 80 (</> (/ (str " Intel Div. Bldg.   ")) (/)))
         (exec-mem 256 "P 9 5 72")
         (exec-mem 256 "P 1 4 64")
         (if (</>
              (//
               (? (= S 0))
               (branch-reg
                287
                (</>
                 (/
                  (text-delay 0)
                  (str "「Kiyomi」" 'br)
                  (text-delay 2)
                  (str "Thanks for your time.")
                  (wait)
                  (text-reset 14)
                  (text-delay 0)
                  (str "「Counter Girl」" 'br)
                  (text-delay 2)
                  (str "Y-yes... I'll definitely contact you if she shows up.")
                  (wait)
                  (text-reset 14)
                  (str "Even if this woman is lying, there's nothing I can do about" 'br)
                  (str "it right now.")
                  (wait)
                  (text-reset 14)
                  (str "Fine. If I find out she's lying, I'll make her pay for it.")
                  (wait)
                  (text-reset 14)
                  (nop@)
                  (set-reg 287 #t))
                 (/
                  (text-delay 0)
                  (str "「Kiyomi」" 'br)
                  (text-delay 2)
                  (str "Thanks for your time.........")
                  (wait)
                  (text-reset 14))))
               (mes-jump "mes¥MB_A01.MES"))
              (// (? (= S 255))))))
        (// (? (= S 255)) (exec-mem 256 "P 1 4 64"))))
   (exec-mem 3968 104)
   (exec-mem 3072 2)
   (exec-mem 3072 1))
 (seg (? (= 1021 #t)) (exec-mem 3072 1))
 (seg (? (= S 1) (= 276 #f)) ; Talk to April (1st time)
   (proc 0)
   (text-delay 0)
   (str "「Kiyomi」" 'br)
   (text-delay 2)
   (str "Don't be so tense. This isn't a raid.")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (str "「Counter Girl」" 'br)
   (text-delay 2)
   (str "..................")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (str "「Kiyomi」" 'br)
   (text-delay 2)
   (str "This is Akihabara, right? You need to stock dangerous stuff" 'br)
   (str "to make a living here. I'm not here to bust you for that.")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (str "「Counter Girl」" 'br)
   (text-delay 2)
   (str "Then...... what do you want?")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (str "「Kiyomi」" 'br)
   (text-delay 2)
   (str "How long have you been in this business?")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (str "「Counter Girl」" 'br)
   (text-delay 2)
   (str "Uh, about two years.")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (str "「Kiyomi」" 'br)
   (text-delay 2)
   (str "Impressive. Running a business alone as a woman in the black" 'br)
   (str "market can't be easy.")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (str "「Counter Girl」" 'br)
   (text-delay 2)
   (str "What do you really want? I'm just a surplus dealer.")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (str "「Kiyomi」" 'br)
   (text-delay 2)
   (str "I'm looking for an ex-military woman. Special Forces," 'br)
   (str "apparently.")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (str "「Kiyomi」" 'br)
   (text-delay 2)
   (str "She supposedly talked about having friends in Akihabara" 'br)
   (str "before her discharge.")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (str "「Counter Girl」" 'br)
   (text-delay 2)
   (str "There are tons of people like that in this city. Ex-military" 'br)
   (str "are everywhere......")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (str "「Kiyomi」" 'br)
   (text-delay 2)
   (str "I don't think so. Sure, regular ex-military are a dime a" 'br)
   (str "dozen. But ex-Special Forces... what do you think?")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (str "「Counter Girl」" 'br)
   (text-delay 5)
   (str "..................")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (str "「Kiyomi」" 'br)
   (text-delay 2)
   (str "Ring any bells? I have information saying she fled to this" 'br)
   (str "area.")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (str "「Counter Girl」" 'br)
   (text-delay 2)
   (str "......What's her name?")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (str "「Kiyomi」" 'br)
   (text-delay 2)
   (str "April. European immigrant. Ex-Special Forces...... Come to" 'br)
   (str "think of it, you're European too.")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (str "「Counter Girl」" 'br)
   (text-delay 5)
   (str "........................")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 276 #t)
   (proc 1))
 (seg (? (= S 1) (= 278 #t))
   (proc 0)
   (text-delay 0)
   (str "「Counter Girl」" 'br)
   (text-delay 2)
   (str "If April comes here, I'll contact you...... definitely.")
   (wait)
   (text-reset 14)
   (proc 1))
 (seg (? (= S 1) (= 276 #t) (= 280 #t))
   (proc 0)
   (text-delay 0)
   (str "「Kiyomi」" 'br)
   (text-delay 2)
   (str "I've seen plenty of soldiers. I can tell from the smallest" 'br)
   (str "movements. You're ex-military, aren't you?")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (str "「Counter Girl」" 'br)
   (text-delay 2)
   (str "Th-that's...!")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (str "「Kiyomi」" 'br)
   (text-delay 2)
   (str "Don't move! Try anything funny and you'll regret it.")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (str "「Counter Girl」" 'br)
   (text-delay 2)
   (str "N-no...... I'm not April!")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (str "「Kiyomi」" 'br)
   (text-delay 2)
   (str "\"I'm not April\"? Then where is April? You know something" 'br)
   (str "about her!")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (str "「Counter Girl」" 'br)
   (text-delay 2)
   (str "I-I'm April's friend. Her friend in Akihabara......")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (str "「Kiyomi」" 'br)
   (text-delay 2)
   (str "......That story better be true. For the record - my torture" 'br)
   (str "skills are unmatched. Lying won't do you any good.")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (str "「Counter Girl」" 'br)
   (text-delay 2)
   (str "It-it's true. Please, believe me......")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (str "「Kiyomi」" 'br)
   (text-delay 2)
   (str "Where is April?")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (str "「Counter Girl」" 'br)
   (text-delay 2)
   (str "I don't know...... I don't know anything. I haven't seen her" 'br)
   (str "in ages!")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (str "「Kiyomi」" 'br)
   (text-delay 2)
   (str "Your \"friend\" was discharged a year ago. She must have" 'br)
   (str "contacted you. Seems like she was counting on you.")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (str "「Counter Girl」" 'br)
   (text-delay 2)
   (str "She never contacted me. I didn't even know she left the" 'br)
   (str "military...... It's true.")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (str "「Kiyomi」" 'br)
   (text-delay 2)
   (str ".........You expect me to believe that?")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (str "「Counter Girl」" 'br)
   (text-delay 2)
   (str "It's the truth, so what else can I say?!")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (str "「Kiyomi」" 'br)
   (text-delay 2)
   (str "I'm not that gullible, April. I'm placing you under arrest.")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (str "「Counter Girl」" 'br)
   (text-delay 2)
   (str "I told you I'm not her! What proof do you have? Should I show")
   (str "you my ID card?")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (str "「Kiyomi」" 'br)
   (text-delay 2)
   (str "............I'll catch you eventually.")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (str "「Counter Girl」" 'br)
   (text-delay 2)
   (str "You're joking...... Leave me alone already.")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (str "「Kiyomi」" 'br)
   (text-delay 2)
   (str "If April shows up here, I want you to contact me. Major" 'br)
   (str "Kiyomi, Intelligence Division.")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (str "「Counter Girl」" 'br)
   (text-delay 3)
   (str "..................")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 278 #t)
   (proc 0))
 (seg (? (= S 1) (= 276 #t))
   (proc 0)
   (text-delay 0)
   (str "「Counter Girl」" 'br)
   (text-delay 2)
   (str "..................")
   (wait)
   (text-reset 14)
   (proc 1))
 (seg (? (= S 2) (= 279 #f)) ; Look at April's body
   (proc 0)
   (str "She's a white European-looking woman. A head taller than me," 'br)
   (str "with a well-toned, muscular build. Long hair tied back......")
   (wait)
   (text-reset 14)
   (str "I wasn't told her height, but she matches what I'd imagine" 'br)
   (str "April looks like. Her build is tough - I could believe" 'br)
   (str "she's ex-Special Forces.")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 279 #t)
   (proc 1))
 (seg (? (= S 2) (= 280 #f))
   (proc 0)
   (str "She's watching me like I'm a suspicious customer. She's" 'br)
   (str "pretending to be an innocent surplus shop clerk, but she's" 'br)
   (str "clearly on edge.")
   (wait)
   (text-reset 14)
   (str "Her right arm is positioned under the counter, constantly" 'br)
   (str "scanning her surroundings. She's definitely not who she" 'br)
   (str "seems to be......")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 280 #t)
   (proc 1))
 (seg (? (= S 2) (= 280 #t))
   (proc 0)
   (str "She's watching me like I'm a suspicious customer. She's" 'br)
   (str "pretending to be an innocent surplus shop clerk, but she's" 'br)
   (str "clearly on edge.")
   (wait)
   (text-reset 14)
   (proc 1))
 (seg (? (= S 3) (= 281 #f)) ; Look at gun display
   (proc 0)
   (str "The glass case displays old-model light machine guns and" 'br)
   (str "various handguns.")
   (wait)
   (text-reset 14)
   (str "Now that gun control laws are effectively dead, you see this" 'br)
   (str "stuff all over the city.")
   (wait)
   (text-reset 14)
   (str "Even knowing most of these guns will end up in criminals'" 'br)
   (str "hands, there's nothing we can do about it.")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 281 #t)
   (proc 1))
 (seg (? (= S 3) (= 282 #f)) 
   (proc 0)
   (str "Most of the guns in the case are secondhand, military issue." 'br)
   (str "The military must be really desperate, to trash their own" 'br)
   (str "laws like this.")
   (wait)
   (text-reset 14)
   (str "Though now that guns have spread throughout the city," 'br)
   (str "gun control is pretty meaningless anyway......")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 282 #t)
   (proc 1))
 (seg (? (= S 3) (= 282 #t))
   (proc 0)
   (str "The glass case displays old-model light machine guns and" 'br)
   (str "various handguns.")
   (wait)
   (text-reset 14)
   (proc 1))
 (seg (? (= S 4) (= 283 #f)) ; Look at gas masks
   (proc 0)
   (str "Old gas masks are carelessly heaped on the wall. Probably" 'br)
   (str "used on some front line, but who would buy them?")
   (wait)
   (text-reset 14)
   (str "If we really needed gas masks, I don't think these cheap" 'br)
   (str "secondhand ones would protect anyone.")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 283 #t)
   (proc 1))
 (seg (? (= S 4) (= 283 #t))
   (proc 0)
   (str "Old gas masks are carelessly heaped on the wall. Probably" 'br)
   (str "used on some front line, but who would buy them now?")
   (wait)
   (text-reset 14)
   (proc 1))
 (seg (? (= S 5) (= 284 #f))
   (proc 0)
   (str "Military boots and packs are piled up like mountains. Both" 'br)
   (str "look like they were actually used in combat.")
   (wait)
   (text-reset 14)
   (str "They'd still work fine, but thinking about how many were" 'br)
   (str "stripped from dead soldiers, I couldn't bring myself to" 'br)
   (str "buy one......")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 284 #t)
   (proc 1))
 (seg (? (= S 5) (= 284 #t))
   (proc 0)
   (str "Military boots and packs are piled up like mountains. Both" 'br)
   (str "look like they were actually used in combat.")
   (wait)
   (text-reset 14)
   (proc 1))
 (seg (? (= S 6) (= 286 #t))
   (proc 0)
   (str "The woman doesn't seem to know where April is. There goes" 'br)
   (str "my lead......")
   (wait)
   (text-reset 14)
   (proc 1))
 (seg (? (= S 6) (= 278 #t))
   (proc 0)
   (str "The woman doesn't seem to know where April is. There goes" 'br)
   (str "my lead......")
   (wait)
   (text-reset 14)
   (str "Even if this woman's lying and April's hiding nearby, I" 'br)
   (str "don't even know what she looks like.")
   (wait)
   (text-reset 14)
   (str "Maybe I should come back later......")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 286 #t)
   (proc 1))
 (seg (? (= S 6) (= 285 #f))
   (proc 0)
   (str "The woman's a European immigrant like April. Her age and" 'br)
   (str "build match what I imagined too......")
   (wait)
   (text-reset 14)
   (str "Plus, this is Akihabara - just like Colonel Karl said. Is" 'br)
   (str "there any reason this woman couldn't be April? Hmm......")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 285 #t)
   (proc 1))
 (seg (? (= S 6) (= 285 #t))
   (proc 0)
   (str "The woman's a European immigrant like April. Her age and" 'br)
   (str "build match what I imagined too.")
   (wait)
   (text-reset 14)
   (proc 1))
 (seg*))
