; X-Girl - Cyberpunk Adventure (PC-98) - MB_E01.MES
; Translation by Fuzion
; Script Editing by Tan2000
; Content Revision by OldCorpo
; Chapter 1 - April & Lei-Fa
; Section 1.2 - Search for April and Lei-Fa
; -----Location:-----
; Chiba City
; -----Scene:-----
; Initial search for April & Lei-Fa location.
; --Progression:--
; Inspect everything in the scene.
(mes
 (meta (engine 'ADV) (charset "pc98") (extraop #t))
 (seg*
  (if (</>
       (// (? (= 58 #t) (= 60 #t)) (mes-jump "mes¥mb_e02.mes"))
       (// (nop@))))
  (exec-mem 14080 2 24 4 135 71 80 34 80 34 0 30)
  (image-file "gpc¥b06_01.gpc")
  (image-mem 0 3)
  (proc 3)
  (if (</>
       (//
        (? (!= P 3))
        (if (</>
             (//
              (? (= O 0))
              (sound '|| 0)
              (sound '|| "uso¥xg_03.uso")
              (sound '|| 1)
              (nop@)
              (set-var P 3))
             (//
              (? (= O 1))
              (sound '|| 0)
              (sound '|| "uso¥xg_03v.uso")
              (sound '|| 1)
              (nop@)
              (set-var P 3)))))
       (// (nop@))))
  (load-mem "clm¥b06_01.clm" 32768)
  (text-frame 10 312 70 383)
  (if (</>
       (//
        (? (= 909 #t))
        (str "This is Chiba City. People who don't belong anywhere else" 'br)
        (str "roam these streets.")
        (wait)
        (text-reset 14))
       (//
        (? (= 909 #f))
        (str "I've arrived at Chiba City. This is a back street, a little" 'br)
        (str "off Chiba's main drag.")
        (wait)
        (text-reset 14)
        (str "There are almost no tourists wandering around here for fun." 'br)
        (str "Anyone unlucky enough to stumble down the wrong street is" 'br)
        (str "going to have a bad time......")
        (wait)
        (text-reset 14)
        (str "In other words, the most dangerous part of Chiba. Everyone" 'br)
        (str "walking around here is basically a criminal, and outsiders" 'br)
        (str "are never welcome.")
        (wait)
        (text-reset 14))))
  (nop@)
  (set-reg 909 #t)
  (exec-mem 3968 102 500 360)
  (exec-mem 3072 1)
  (loop (set-var S 0) (exec-mem 3072 1020 1021 "S" 32768) (seg-call)))
 (seg (? (= 1020 #f) (= 1021 #f)) (exec-mem 3072 1))
 (seg (? (= 1021 #t) (= 202 #t) (= 204 #t) (= 206 #t) (= 208 #t))
   (exec-mem 3072 0)
   (exec-mem 3968 103)
   (exec-mem 256 "A 0 S 0")
   (exec-mem 256 "G 1 4 64 12 48")
   (exec-mem 4768 4 8 12 4 1 0 0 4480 4480 1 0)
   (menu1 5 72 (</> (/ (str "  Travel  "))))
   (if (</>
        (//
         (? (= S 0))
         (exec-mem 256 "A 0 S 0")
         (exec-mem 256 "G 9 5 72 22 64")
         (exec-mem 4768 5 9 22 4 1 0 0 4480 4480 1 0)
         (menu1 6 80 (</> (/ (str " Intel Div. Bldg.   "))))
         (exec-mem 256 "P 9 5 72")
         (exec-mem 256 "P 1 4 64")
         (if (</>
              (//
               (? (= S 0))
               (branch-reg
                56
                (</>
                 (/ (mes-jump "mes¥MB_A01.MES"))
                 (/ (mes-jump "mes¥MB_A02.MES")))))
              (// (? (= S 255))))))
        (// (? (= S 255)) (exec-mem 256 "P 1 4 64"))))
   (exec-mem 3968 104)
   (exec-mem 3072 2)
   (exec-mem 3072 1))
 (seg (? (= 1021 #t)) (exec-mem 3072 1))
 (seg (? (= S 1) (= 264 #f))
   (proc 0)
   (str "The building in back has a hotel sign. No tourists would stay")
   (str "in a place like this, so it must be a love hotel.")
   (wait)
   (text-reset 14)
   (str "Dirty sheets, bugs crawling across the floor...... it's easy" 'br)
   (str "to picture. A hotel for the women who pick up clients on the" 'br)
   (str "street.")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 264 #t)
   (proc 1))
 (seg (? (= S 1) (= 265 #f))
   (proc 0)
   (str "I can see stairs leading down to the subway at the edge of" 'br)
   (str "the street. If it's this dangerous above ground, even a child")
   (str "could guess what happens down below.")
   (wait)
   (text-reset 14)
   (str "I wouldn't want to ride it either. Apparently there are still")
   (str "illegal squatters living in the subway tunnels. Can't imagine")
   (str "it's very comfortable.")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 265 #t)
   (proc 1))
 (seg (? (= S 1) (= 265 #t))
   (proc 0)
   (str "The building in back has a hotel sign. No tourists would stay")
   (str "in a place like this, so it must be a love hotel.")
   (wait)
   (text-reset 14)
   (proc 1))
 (seg (? (= S 2) (= 266 #f))
   (proc 0)
   (str "I can see a narrow alley squeezed between buildings. Does it" 'br)
   (str "dead-end, or connect to another street?")
   (wait)
   (text-reset 14)
   (str "Either way, if I went down that kind of alley...... hell, I" 'br)
   (str "might not make it back alive.")
   (wait)
   (text-reset 14)
   (str "Even if I wasn't carrying anything valuable, the scavengers" 'br)
   (str "wouldn't let me go. They'd examine my brain and send my" 'br)
   (str "organs to the organ banks.")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 266 #t)
   (proc 1))
 (seg (? (= S 2) (= 267 #f))
   (proc 0)
   (str "The shadiest street in all of Chiba, and an even more" 'br)
   (str "mysterious alley beyond that. I can't imagine what goes on" 'br)
   (str "back there.")
   (wait)
   (text-reset 14)
   (str "But everything that is Chiba City can be found in there." 'br)
   (str "Cutting-edge cybernetics, black-market body-mod doctors," 'br)
   (str "gruesome murders......")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 267 #t)
   (proc 1))
 (seg (? (= S 2) (= 267 #t))
   (proc 0)
   (str "I can see a narrow alley squeezed between buildings. Does it" 'br)
   (str "dead-end, or connect to another street?")
   (wait)
   (text-reset 14)
   (proc 1))
 (seg (? (= S 3) (= 268 #f))
   (proc 0)
   (str "This street dead-ends in front of some low warehouse-like" 'br)
   (str "buildings, with passages stretching left and right.")
   (wait)
   (text-reset 14)
   (str "One way probably leads back to the main street, but take the" 'br)
   (str "other path and you'll go deeper, disappearing into the" 'br)
   (str "darkness of Chiba.")
   (wait)
   (text-reset 14)
   (str "That's a place where outsiders like me absolutely cannot set" 'br)
   (str "foot. Intelligence Division authority is worth less than" 'br)
   (str "garbage there.")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 268 #t)
   (proc 1))
 (seg (? (= S 3) (= 269 #f))
   (proc 0)
   (str "There are narrow passages leading to the depths of Chiba" 'br)
   (str "City. A breeding ground for crime that outsiders like me can" 'br)
   (str "barely even enter.")
   (wait)
   (text-reset 14)
   (str "It's definitely one of those places I never want to go unless")
   (str "absolutely forced to. But lately, I've been made to do" 'br)
   (str "nothing but things I don't want to do.")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 269 #t)
   (proc 1))
 (seg (? (= S 3) (= 269 #t))
   (proc 0)
   (str "This street dead-ends in front of some low warehouse-like" 'br)
   (str "buildings, with passages stretching left and right.")
   (wait)
   (text-reset 14)
   (proc 1))
 (seg (? (= S 4) (= 270 #f))
   (proc 0)
   (str "Probably one of those tourist-trap bars common in Chiba. Any" 'br)
   (str "customers unlucky enough to wander off the beaten path and" 'br)
   (str "stumble in here are going to get ripped off.")
   (wait)
   (text-reset 14)
   (str "If they came looking for women, it's even worse. About half" 'br)
   (str "the working girls in Chiba are transsexuals. But if that's" 'br)
   (str "what they like, I won't stop them......")
   (wait)
   (text-reset 14)
   (str "These former guys who used top-tier tech and big money to" 'br)
   (str "become women are like hyenas to their customers. Though I" 'br)
   (str "hear their skills are supposedly incredible.")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 270 #t)
   (proc 1))
 (seg (? (= S 4) (= 271 #f))
   (proc 0)
   (str "Looks like the first floor is a bar and the second floor is a")
   (str "brothel. The woman standing on the balcony must be a hooker" 'br)
   (str "who couldn't find a customer.")
   (wait)
   (text-reset 14)
   (str "The sign that says \"parking\" must be left over from the past.")
   (str "The locals don't use cars, and neither do the tourists.")
   (wait)
   (text-reset 14)
   (str "For the record, prostitution's obviously illegal. They only" 'br)
   (str "get away with running it in the open because both the police" 'br)
   (str "and the government have abandoned Chiba.")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 271 #t)
   (proc 1))
 (seg (? (= S 4) (= 271 #t))
   (proc 0)
   (str "Probably one of those tourist-trap bars common in Chiba. Any" 'br)
   (str "customers unlucky enough to wander off the beaten path and" 'br)
   (str "stumble in here are going to get ripped off.")
   (wait)
   (text-reset 14)
   (proc 1))
 (seg (? (= S 5) (= 272 #f))
   (proc 0)
   (str "For Chiba residents, they're dressed relatively normally. But")
   (str "what's inside their bodies is anyone's guess.")
   (wait)
   (text-reset 14)
   (str "I'm sure they're neuro-enhanced, but some people are walking" 'br)
   (str "around with drug tanks connected to their bloodstream or" 'br)
   (str "plastic explosives in their guts.")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 272 #t)
   (proc 1))
 (seg (? (= S 5) (= 273 #f))
   (proc 0)
   (text-delay 0)
   (str "「Right Man」" 'br)
   (text-delay 2)
   (str "Hey lady, you look lost. Need something?")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (str "「Kiyomi」" 'br)
   (text-delay 2)
   (str "Not really. You'd better not mess with me.")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (str "「Left Man」" 'br)
   (text-delay 2)
   (str "Don't get involved with weird types, man. Look at that coat -")
   (str "she's military.")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (str "「Right Man」" 'br)
   (text-delay 2)
   (str "Well, shit! What do you do in the military, make tea?")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (str "「Kiyomi」" 'br)
   (text-delay 2)
   (str "............")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (str "「Right Man」" 'br)
   (text-delay 2)
   (str "The military's going downhill these days. How about dancing" 'br)
   (str "at my place instead?")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (str "「Right Man」" 'br)
   (text-delay 2)
   (str "You could make good money!")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (str "「Kiyomi」" 'br)
   (text-delay 2)
   (str "I'll think about it. Might take you up on that if I lose" 'br)
   (str "my job.")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (str "「Right Man」" 'br)
   (text-delay 2)
   (str "Sounds good. Change your hair and eye color by then, yeah?" 'br)
   (str "Black is too gloomy.")
   (wait)
   (text-reset 14)
   (text-delay 0)
   (str "「Kiyomi」" 'br)
   (text-delay 2)
   (str "............")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 273 #t)
   (proc 1))
 (seg (? (= S 5) (= 273 #t))
   (proc 0)
   (str "They seem interested in me. Better not to get involved.")
   (wait)
   (text-reset 14)
   (proc 1))
 (seg (? (= S 6) (= 274 #f))
   (proc 0)
   (str "Maybe because it's still early, there aren't many really" 'br)
   (str "dangerous types around. The streetwalkers are all young women")
   (str "who won't have trouble finding customers.")
   (wait)
   (text-reset 14)
   (str "The older prostitutes can't work until there are more drunk" 'br)
   (str "customers around. Their flaws show too much when dealing with")
   (str "sober people.")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 274 #t)
   (proc 1))
 (seg (? (= S 6) (= 274 #t))
   (proc 0)
   (str "Maybe because it's still early, there aren't many really" 'br)
   (str "dangerous types around. If I wanted to experience the true" 'br)
   (str "essence of Chiba, I'd have to wait another 5 hours.")
   (wait)
   (text-reset 14)
   (proc 1))
 (seg (? (= S 7) (= 275 #f))
   (proc 0)
   (str "Chiba would definitely be perfect for fugitives on the run." 'br)
   (str "But anyone with half a brain would be lurking deeper in the" 'br)
   (str "city, away from prying eyes.")
   (wait)
   (text-reset 14)
   (str "And trying to get into those neighborhoods is a whole" 'br)
   (str "different problem. There's barely any Japanese in those" 'br)
   (str "parts......")
   (wait)
   (text-reset 14)
   (nop@)
   (set-reg 275 #t)
   (proc 1))
 (seg (? (= S 7) (= 275 #t))
   (proc 0)
   (str "Chiba would definitely be perfect for fugitives on the run." 'br)
   (str "But anyone with half a brain would be lurking deeper in the" 'br)
   (str "city, away from prying eyes.")
   (wait)
   (text-reset 14)
   (proc 1))
 (seg (? (= S 7) (= 54 #t))
   (proc 0)
   (if (</>
        (//
         (? (= 57 #t) (= 58 #f) (= 59 #f) (= 60 #f)) ; April arrested, not interrogated yet, Lei-Fa not arrested yet
         (nop@)
         (str "First I should interrogate April. She might hold the key to" 'br)
         (str "solving this whole case.")
         (wait)
         (text-reset 14)
         (str "If that doesn't work, at least I might get a hint for" 'br)
         (str "capturing Lei-Fa or finding the third prisoner.")
         (wait)
         (text-reset 14))
        (//
         (? (= 57 #t) (= 58 #t) (= 59 #f) (= 60 #f)) ; April arrested and interrogated, Lei-Fa not arrested yet
         (nop@)
         (str "I hate to think April could withstand my torture. Did she" 'br)
         (str "really know nothing?")
         (wait)
         (text-reset 14))
        (//
         (? (= 57 #t) (= 58 #t) (= 59 #t) (= 60 #f)) ; April arrested and interrogated, Lei-Fa arrested, not interrogated yet
         (nop@)
         (str "I've captured the second prisoner, Lei-Fa. Interrogating her" 'br)
         (str "might give me more information.")
         (wait)
         (text-reset 14))
        (//
         (? (= 57 #t) (= 58 #f) (= 59 #t) (= 60 #f)) ; April & Lei-Fa arrested, both are not interrogated yet
         (nop@)
         (str "I've arrested both prisoners. Interrogating them should give" 'br)
         (str "me info about the classified material I'm looking for.")
         (wait)
         (text-reset 14))
        (//
         (? (= 57 #f) (= 58 #f) (= 59 #t) (= 60 #f)) ; April not arrested yet, Lei-Fa arrested, not interrogated yet
         (nop@)
         (str "I've arrested Lei-Fa. Interrogating her might provide the key")
         (str "to solving this whole case.")
         (wait)
         (text-reset 14))
        (//
         (? (= 57 #f) (= 58 #f) (= 59 #t) (= 60 #t)) ; April not arrested yet, Lei-Fa arrested and interrogated
         (nop@)
         (str "I hate to think Lei-Fa could withstand my torture. Did she" 'br)
         (str "really know nothing?")
         (wait)
         (text-reset 14))
        (//
         (? (= 57 #t) (= 58 #f) (= 59 #t) (= 60 #t)) ; April arrested. not interrogated yet, Lei-Fa arrested and interrogated
         (nop@)
         (str "Lei-Fa didn't talk. I have to do something about April." 'br)
         (str "Anything - I have to make something work......")
         (wait)
         (text-reset 14))
        (//
         (str "First I need to arrest April or Lei-Fa. Who should I hunt" 'br) ; April & Lei-Fa not arrested yet
         (str "down first......")
         (wait)
         (text-reset 14))))
   (proc 1))
 (seg*))
