(mes
 (meta (engine 'ADV) (charset "pc98") (extraop #t))
 (seg*
  (proc 10)
  (proc 14)
  (str "Please, no more...... I-I'll really die if you keep this up!")
  (wait)
  (text-reset 14)
  (proc 13)
  (str "Looks like you're finally starting to behave. But don't" 'br)
  (str "think I'm done with you.")
  (wait)
  (text-reset 14)
  (proc 14)
  (str "Hii.........")
  (wait)
  (text-reset 14)
  (proc 13)
  (str "I'm a professional when it comes to this sort of thing. I" 'br)
  (str "know exactly what hurts the most.")
  (wait)
  (text-reset 14)
  (proc 13)
  (str "You can spend the night like that and think about what" 'br)
  (str "you've done. I'll come back to play with you tomorrow.")
  (wait)
  (text-reset 14)
  (proc 14)
  (str "No, please don't...... Untie me!")
  (wait)
  (text-reset 14)
  (proc 13)
  (str "Your wounds should heal by tomorrow. But remember your" 'br)
  (str "place - you're nothing but a dirty pet!")
  (wait)
  (text-reset 14)
  (proc 14)
  (str "W-wait...... Don't leave me here!")
  (wait)
  (text-reset 14)
  (proc 14)
  (str "Please, no, please............")
  (wait)
  (text-reset 14)
  (proc 11)
  (exec-mem 18688 3)
  (exec-mem 18688 5 1 0)
  (exec-mem 3072 0)
  (cmd:209 0 5)
  (text-frame 0 0 79 399)
  (text-reset 14)
  (cmd:209 1 0)
  (define-proc 9
   (<>
    (exec-mem 12288 3 0 1 5 0)
    (exec-mem 11680 0)
    (exec-mem 27648 2 2)
    (exec-mem 3072 2)))
  (define-proc 8
   (<>
    (exec-mem 3968 104)
    (exec-mem 25984 2 1)
    (exec-mem 3072 2)
    (exec-mem 3072 1)))
  (mes-jump "mes¥MD_A03.MES")))