(mes
 (meta (engine 'ADV) (charset "pc98") (extraop #t))
 (seg (? (= 991 #f) (= Y 0))
      (mes-load? "mes¥md_a2pl1.mec" 0)
      (mes-load? 0)
      (mes-load? "mes¥icon_clf.mec" 4096)
      (mes-load? 4096)
      (mes-load? "mes¥icon_c2.mec" 4096)
      (mes-load? 4096)
      (mes-load? "mes¥md_a2pl2.mec" 0)
      (mes-load? 0)
      (mes-load? "mes¥md_a2pl3.mec" 0)
      (text-frame 10 312 70 370)
      (loop
       (set-var S 0)
       (exec-mem 3072 1020 1021 "S" 32768 "Z" 20480)
       (seg-call)))
 (seg (? (= Z 2) (= 991 #f) (= 1020 #f) (!= Q 2))
      (proc 0)
      (exec-mem 256 "P 6 9 16")
      (exec-mem 9504 "C icon¥name1.gpc,GPC")
      (image-mem 1 0 9 16)
      (proc 1)
      (set-var Q 2))
 (seg (? (= Z 3) (= 991 #f) (= 1020 #f) (!= Q 3))
      (proc 0)
      (exec-mem 256 "P 6 9 16")
      (exec-mem 9504 "C icon¥name2.gpc,GPC")
      (image-mem 1 0 9 40)
      (proc 1)
      (set-var Q 3))
 (seg (? (= Z 6) (= 991 #f) (= 1020 #f) (!= Q 6) (= 984 #t))
      (proc 0)
      (exec-mem 256 "P 6 9 16")
      (exec-mem 9504 "C icon¥name5.gpc,GPC")
      (image-mem 1 0 9 112)
      (proc 1)
      (set-var Q 6))
 (seg (? (= Z 2) (= 991 #t) (= 1020 #f) (!= Q 2))
      (proc 0)
      (exec-mem 256 "P 7 52 16")
      (exec-mem 9504 "C icon¥name1.gpc,GPC")
      (image-mem 1 0 52 16)
      (proc 1)
      (set-var Q 2))
 (seg (? (= Z 3) (= 991 #t) (= 1020 #f) (!= Q 3))
      (proc 0)
      (exec-mem 256 "P 7 52 16")
      (exec-mem 9504 "C icon¥name2.gpc,GPC")
      (image-mem 1 0 52 40)
      (proc 1)
      (set-var Q 3))
 (seg (? (= Z 6) (= 991 #t) (= 1020 #f) (!= Q 6) (= 984 #t))
      (proc 0)
      (exec-mem 256 "P 7 52 16")
      (exec-mem 9504 "C icon¥name5.gpc,GPC")
      (image-mem 1 0 52 112)
      (proc 1)
      (set-var Q 6))
 (seg (? (!= Z 2) (!= Z 3) (!= Z 6) (= 991 #f) (= 1020 #f) (>= Q 1) (= 984 #t))
      (proc 0)
      (exec-mem 256 "P 6 9 16")
      (proc 1)
      (nop@)
      (set-var Q 0))
 (seg (? (!= Z 2) (!= Z 3) (!= Z 6) (= 991 #t) (= 1020 #f) (>= Q 1) (= 984 #t))
      (proc 0)
      (exec-mem 256 "P 7 52 16")
      (proc 1)
      (nop@)
      (set-var Q 0))
 (seg (? (!= Z 2) (!= Z 3) (= 991 #f) (= 1020 #f) (>= Q 1) (= 984 #f))
      (proc 0)
      (exec-mem 256 "P 6 9 16")
      (proc 1)
      (nop@)
      (set-var Q 0))
 (seg (? (!= Z 2) (!= Z 3) (= 991 #t) (= 1020 #f) (>= Q 1) (= 984 #f))
      (proc 0)
      (exec-mem 256 "P 7 52 16")
      (proc 1)
      (nop@)
      (set-var Q 0))
 (seg (? (= 1020 #f) (= 1021 #f)) (exec-mem 3072 1))
 (seg (? (= 1021 #t)) (exec-mem 3072 1))
 (seg* (proc 4) (seg-call))
 (seg (? (= Z 1)) (mes-load? 0))
 (seg (? (= Z 2)) (mes-load? 0))
 (seg (? (= Z 3)) (mes-load? 0))
 (seg (? (= Z 6)) (mes-load? 0))
 (seg (? (= Y 1) (= S 1) (>= H 17)) (mes-jump "mes¥md_a2_r1.mes"))
 (seg (? (= Y 1) (= S 1) (<= H 5))
      (proc 10)
      (branch-index (</>
                     (/
                      (proc 13)
                      (str "Look at you. Stripped bare with everything on display. How" 'br)
                      (str "shameful.")
                      (proc 18)
                      (proc 14)
                      (str "I-I didn't do this to myself...... I've had enough, untie me!")
                      (proc 18)
                      (proc 13)
                      (str "Not a chance. That pathetic look suits a bitch like you" 'br)
                      (str "perfectly.")
                      (proc 18)
                      (proc 14)
                      (str "..................")
                      (proc 18)
                      (proc 13)
                      (str "How does the rope feel? Those knots must be digging in real" 'br)
                      (str "nice. I hope they're keeping your lower mouth satisfied.")
                      (proc 18)
                      (proc 14)
                      (str "A-as if...... It just hurts, that's all!")
                      (proc 18)
                      (proc 13)
                      (str "Then why is your body drooling down there? Go on, explain" 'br)
                      (str "what that filthy mess is.")
                      (proc 18)
                      (proc 14)
                      (str "T-that's a lie...... That's not happening!")
                      (proc 18)
                      (proc 13)
                      (str "I guess you can't see for yourself in that position." 'br)
                      (str "Trust me, that dirty slit of yours is crying tears of joy.")
                      (proc 18)
                      (proc 14)
                      (str "That's horrible...... You're lying...... You must be!")
                      (proc 18)
                      (nop@)
                      (inc-var H 1)
                      (proc 15))
                     (/
                      (proc 13)
                      (str "I've never seen anyone as depraved as you. And coming from" 'br)
                      (str "me, that's saying something.")
                      (proc 18))))
      (proc 11))
 (seg (? (= Y 1) (= S 1) (<= H 10))
      (proc 10)
      (branch-index (</>
                     (/
                      (proc 13)
                      (str "Have you learned to act and speak like a proper bitch yet?")
                      (proc 18)
                      (proc 14)
                      (str "P-please forgive me...... I'm begging you!")
                      (proc 18)
                      (proc 13)
                      (str "Then spill everything. Where are your accomplices? Where" 'br)
                      (str "are the stolen secrets!")
                      (proc 18)
                      (proc 14)
                      (str "T-that's......... I can't............")
                      (proc 18)
                      (proc 13)
                      (str "Clearly, you still don't understand your position." 'br)
                      (str "How disappointing.")
                      (proc 18)
                      (proc 14)
                      (str "I-I'm sorry...... B-but that's the one thing I can't......")
                      (proc 18)
                      (proc 13)
                      (str "I'll teach your body just how weak and powerless you" 'br)
                      (str "really are.")
                      (proc 18)
                      (proc 14)
                      (str "No, s-stop it!")
                      (proc 18))
                     (/
                      (proc 14)
                      (str "Aaah, please...... I-I can't take any more!")
                      (proc 18))))
      (proc 11))
 (seg (? (= Y 1) (= S 1) (<= H 16))
      (proc 10)
      (branch-index (</>
                     (/
                      (proc 13)
                      (str "You're really starting to feel it now...... Your lower" 'br)
                      (str "mouth is wide open, I can see every fold inside.")
                      (proc 18)
                      (proc 14)
                      (str "N-no...... Don't say that!")
                      (proc 18)
                      (proc 13)
                      (str "Getting off on torture? You're the real pervert here. If" 'br)
                      (str "only your upper mouth were as honest as the lower one.")
                      (proc 18)
                      (proc 14)
                      (str "This is...... This is just too cruel............")
                      (proc 18)
                      (proc 13)
                      (str "If only it were, you could have been spared all this" 'br)
                      (str "humiliation!")
                      (proc 18)
                      (proc 14)
                      (str "Ugh, uugh............")
                      (proc 18))
                     (/
                      (proc 13)
                      (str "I'm not stopping until your upper mouth is as honest as" 'br)
                      (str "the lower one.")
                      (proc 18))))
      (proc 11))
 (seg (? (= Y 1) (= S 2))
      (sound 'se 1)
      (branch-reg 550
       (</>
        (/
         (nop@)
         (inc-var H 1)
         (proc 0)
         (proc 5)
         (proc 19)
         (branch-reg 569
          (</>
           (/)
           (/ (image-file "gpc¥a1_01bk.gpc") (image-mem 1 0) (proc 12))))
         (exec-mem 3072 0)
         (image-file "gpc¥a1_01ca.gpc")
         (image-mem 1 0)
         (proc 12)
         (proc 6)
         (branch-reg 991
          (</>
           (/ (exec-mem 9504 "C icon¥tool12.gpc,GPC") (image-mem 1 0 6 16))
           (/ (exec-mem 9504 "C icon¥tool12.gpc,GPC") (image-mem 1 0 71 16))))
         (proc 10)
         (proc 14)
         (str "Ah...... Aah!")
         (proc 18)
         (proc 13)
         (str "Looks like I left a mark on your pretty legs. But don't" 'br)
         (str "worry, it's not nearly as ugly as the rest of you right now.")
         (proc 18)
         (proc 14)
         (str "Untie me, I can't stand being like this......" 'br)
         (str "please............")
         (proc 18)
         (nop@)
         (set-reg 550 #t)
         (proc 15))
        (/
         (proc 10)
         (proc 14)
         (str "Ow............")
         (proc 18))))
      (proc 11))
 (seg (? (= Y 1) (= S 3))
      (branch-reg 559
       (</>
        (/
         (sound 'se 1)
         (branch-reg 551
          (</>
           (/
            (nop@)
            (inc-var H 1)
            (proc 0)
            (image-file "gpc¥a1_01cb.gpc")
            (image-mem 1 0)
            (proc 12)
            (proc 19)
            (branch-reg 569
             (</>
              (/)
              (/ (image-file "gpc¥a1_01bk.gpc") (image-mem 1 0) (proc 12))))
            (proc 10)
            (proc 14)
            (str "Augh! I-it hurts...... Stop it!")
            (proc 18)
            (proc 13)
            (str "Good sound. A bit more force and I'd snap a bone. It's all in")
            (str "how hard I swing. Do you see now just how helpless you are?")
            (proc 18)
            (proc 14)
            (str "Y-yes............")
            (proc 18)
            (nop@)
            (set-reg 551 #t)
            (proc 15)
            (proc 11))
           (/
            (proc 10)
            (proc 14)
            (str "Augh! I-it hurts...... Stop it!")
            (proc 18))))
         (proc 11))
        (/))))
 (seg (? (= Y 1) (= S 4))
      (branch-reg 560
       (</>
        (/
         (sound 'se 1)
         (branch-reg 552
          (</>
           (/
            (nop@)
            (inc-var H 1)
            (proc 0)
            (image-file "gpc¥a1_01cc.gpc")
            (image-mem 1 0)
            (proc 12)
            (proc 19)
            (branch-reg 569
             (</>
              (/)
              (/ (image-file "gpc¥a1_01bk.gpc") (image-mem 1 0) (proc 12))))
            (proc 10)
            (proc 14)
            (str "Hii............")
            (proc 18)
            (proc 13)
            (str "Oops, almost crushed something precious down there.")
            (proc 18)
            (proc 14)
            (str "Ahh...... ugh......")
            (proc 18)
            (nop@)
            (set-reg 552 #t)
            (proc 15)
            (proc 11))
           (/ (proc 10) (proc 14) (str "Hih............") (proc 18))))
         (proc 11))
        (/))))
 (seg (? (= Y 1) (= S 5))
      (branch-reg 562
       (</>
        (/
         (sound 'se 1)
         (branch-reg 553
          (</>
           (/
            (nop@)
            (inc-var H 1)
            (proc 0)
            (image-file "gpc¥a1_01cd.gpc")
            (image-mem 1 0)
            (proc 12)
            (proc 19)
            (branch-reg 569
             (</>
              (/)
              (/ (image-file "gpc¥a1_01bk.gpc") (image-mem 1 0) (proc 12))))
            (proc 10)
            (proc 14)
            (str "Hauuu............")
            (proc 18)
            (proc 13)
            (str "Those welts really stand out against your white skin." 'br)
            (str "Beautiful, really - almost wasted on such a pathetic sight.")
            (proc 18)
            (proc 14)
            (str "Ugh, please stop......")
            (proc 18)
            (nop@)
            (set-reg 553 #t)
            (proc 15)
            (proc 11))
           (/
            (proc 10)
            (proc 14)
            (str "Ugh! P-please stop......")
            (proc 18))))
         (proc 11))
        (/))))
 (seg (? (= Y 1) (= S 6))
      (sound 'se 1)
      (branch-reg 554
       (</>
        (/
         (nop@)
         (inc-var H 1)
         (proc 0)
         (image-file "gpc¥a1_01ce.gpc")
         (image-mem 1 0)
         (proc 12)
         (proc 19)
         (branch-reg 569
          (</>
           (/)
           (/ (image-file "gpc¥a1_01bk.gpc") (image-mem 1 0) (proc 12))))
         (proc 10)
         (proc 14)
         (str "Hah, hahn!")
         (proc 18)
         (proc 13)
         (str "What kind of noise was that? You get off on having your tits" 'br)
         (str "slapped? You're a masochist! A real freak!")
         (proc 18)
         (proc 14)
         (str "Ugh.........")
         (proc 18)
         (nop@)
         (set-reg 554 #t)
         (proc 15))
        (/ (proc 10) (proc 14) (str "Hah...... hahn!") (proc 18))))
      (proc 11))
 (seg (? (= Y 1) (= S 7))
      (branch-reg 563
       (</>
        (/
         (sound 'se 1)
         (branch-reg 555
          (</>
           (/
            (nop@)
            (inc-var H 1)
            (nop@)
            (set-reg 555 #t)
            (proc 0)
            (image-file "gpc¥a1_01cf.gpc")
            (image-mem 1 0)
            (nop@)
            (set-reg 555 #t)
            (proc 12)
            (proc 19)
            (branch-reg 569
             (</>
              (/)
              (/ (image-file "gpc¥a1_01bk.gpc") (image-mem 1 0) (proc 12))))
            (proc 10)
            (proc 14)
            (str "Hah............ nnh!")
            (proc 18)
            (proc 13)
            (str "You held out well. But how long can you keep it up when your" 'br)
            (str "tits and *** are covered in welts?")
            (proc 18)
            (proc 14)
            (str "S-stop...... I-I can't take any more!")
            (proc 18)
            (nop@)
            (set-reg 555 #t)
            (proc 15)
            (proc 11))
           (/
            (proc 10)
            (proc 14)
            (str "Hah............ annh!")
            (proc 18))))
         (proc 11))
        (/))))
 (seg (? (= Y 1) (= S 8))
      (sound 'se 1)
      (branch-reg 556
       (</>
        (/
         (nop@)
         (inc-var H 1)
         (proc 0)
         (image-file "gpc¥a1_01cg.gpc")
         (image-mem 1 0)
         (proc 12)
         (proc 19)
         (branch-reg 569
          (</>
           (/)
           (/ (image-file "gpc¥a1_01bk.gpc") (image-mem 1 0) (proc 12))))
         (proc 10)
         (proc 14)
         (str "Ah, kuuh............")
         (proc 18)
         (proc 13)
         (str "You depraved slut, don't you dare enjoy being tormented!")
         (proc 18)
         (proc 14)
         (str "Ahhh, please have mercy on me......")
         (proc 18)
         (nop@)
         (set-reg 556 #t)
         (proc 15))
        (/
         (proc 10)
         (proc 14)
         (str "Ah, kuuh............")
         (proc 18))))
      (proc 11))
 (seg (? (= Y 1) (= S 9))
      (branch-reg 567
       (</>
        (/
         (sound 'se 1)
         (branch-reg 557
          (</>
           (/
            (nop@)
            (inc-var H 1)
            (proc 0)
            (image-file "gpc¥a1_01ch.gpc")
            (image-mem 1 0)
            (proc 12)
            (proc 19)
            (branch-reg 569
             (</>
              (/)
              (/ (image-file "gpc¥a1_01bk.gpc") (image-mem 1 0) (proc 12))))
            (proc 10)
            (proc 14)
            (str "Ah...... Aaaagh!")
            (proc 18)
            (proc 13)
            (str "Does getting your tits smashed feel that good? I'll keep" 'br)
            (str "going as many times as you like!")
            (proc 18)
            (proc 14)
            (str "Ahh, yes, i-it feels good...... Please, hit me more!")
            (proc 18)
            (nop@)
            (set-reg 557 #t)
            (proc 15)
            (proc 11))
           (/
            (proc 10)
            (proc 14)
            (str "Ah...... Aaaagh!")
            (proc 18))))
         (proc 11))
        (/))))
 (seg (? (= Y 1) (= S 10))
      (branch-reg 568
       (</>
        (/
         (sound 'se 1)
         (branch-reg 558
          (</>
           (/
            (nop@)
            (inc-var H 1)
            (proc 0)
            (image-file "gpc¥a1_01ci.gpc")
            (image-mem 1 0)
            (proc 12)
            (proc 19)
            (branch-reg 569
             (</>
              (/)
              (/ (image-file "gpc¥a1_01bk.gpc") (image-mem 1 0) (proc 12))))
            (proc 10)
            (proc 14)
            (str "Hii...... hiih!")
            (proc 18)
            (proc 13)
            (str "You're a depraved bitch who gets off on anything!")
            (proc 18)
            (proc 14)
            (str "Ugh, this is...... This is too cruel!")
            (proc 18)
            (nop@)
            (set-reg 558 #t)
            (proc 15)
            (proc 11))
           (/
            (proc 10)
            (proc 14)
            (str "Hii...... hiih!")
            (proc 18))))
         (proc 11))
        (/))))
 (seg (? (= Y 2) (= S 1) (>= H 17)) (mes-jump "mes¥md_a2_r2.mes"))
 (seg (? (= Y 2) (= S 1) (<= H 5))
      (proc 10)
      (branch-index (</>
                     (/
                      (proc 13)
                      (str "Ku ku ku...... The sight of you is hilarious. I can barely" 'br)
                      (str "keep from laughing.")
                      (proc 18)
                      (proc 14)
                      (str "Y-you're the one who did this to me...... That's so cruel!")
                      (proc 18)
                      (proc 13)
                      (str "Don't talk back to me! You're nothing but a lowly dog. You" 'br)
                      (str "think you can speak to your master like that?")
                      (proc 18)
                      (proc 14)
                      (str "I'm a human being...... I'll never do what you say!")
                      (proc 18)
                      (proc 13)
                      (str "You're still resisting? Perfect. I love it when you fight" 'br)
                      (str "back...... it'll make breaking you so much sweeter.")
                      (proc 18)
                      (proc 14)
                      (str "W-wait...... stop, I'll do anything, please!")
                      (proc 18))
                     (/
                      (proc 14)
                      (str "Please stop hurting me...... I'm begging you!")
                      (proc 18))))
      (proc 11))
 (seg (? (= Y 2) (= S 1) (<= H 10))
      (proc 10)
      (branch-index (</>
                     (/
                      (proc 14)
                      (str "Ugh, uugh............")
                      (proc 18)
                      (proc 13)
                      (str "That mouth was clamped shut like a clam at first, but it's" 'br)
                      (str "loosened up. Just like that soaking mess down below.")
                      (proc 18)
                      (proc 14)
                      (str "That's so mean...... Don't say things like that............")
                      (proc 18)
                      (proc 13)
                      (str "Just admit it already. You're a perverted, slutty" 'br)
                      (str "masochist. And stop getting your disgusting juices on me!")
                      (proc 18)
                      (proc 14)
                      (str "Please, forgive me. I'll do whatever you say......")
                      (proc 18)
                      (proc 13)
                      (str "Then talk. About your comrades and the data you stole from" 'br)
                      (str "the military. Tell me about the System.")
                      (proc 18)
                      (proc 14)
                      (str "N-no...... Anything but that!")
                      (proc 18)
                      (nop@)
                      (inc-var H 1)
                      (proc 15))
                     (/
                      (proc 14)
                      (str "..................")
                      (proc 18)
                      (proc 13)
                      (str "You're a hopelessly stupid bitch. If you want more pain that" 'br)
                      (str "badly, I'll give you exactly what you're asking for!")
                      (proc 18))
                     (/
                      (proc 14)
                      (str "Forgive me, I'll do whatever you say. I'll even become" 'br)
                      (str "your slave!")
                      (proc 18))))
      (proc 11))
 (seg (? (= Y 2) (= S 1) (<= H 16))
      (proc 10)
      (branch-index (</>
                     (/
                      (proc 14)
                      (str "Hah, hah, hah, hah............")
                      (proc 18)
                      (proc 13)
                      (str "What's with all the heavy breathing? Are you so worked up" 'br)
                      (str "you can't hold it in anymore?")
                      (proc 18)
                      (proc 14)
                      (str "N-no, that's not it. This is......")
                      (proc 18)
                      (proc 13)
                      (str "Save your excuses. That dirty slit of yours is overflowing" 'br)
                      (str "for all to see.")
                      (proc 18)
                      (proc 13)
                      (str "I've changed my mind about forcing you to talk. Breaking" 'br)
                      (str "you into my personal slave is so much more fun!")
                      (proc 18)
                      (proc 14)
                      (str "No, you can't......")
                      (proc 18)
                      (proc 13)
                      (str "Oh, we're far from done. This is just the beginning............")
                      (proc 18))
                     (/
                      (proc 13)
                      (str "I wonder what your comrades would say if they could see" 'br)
                      (str "what you've become. I can hardly wait to find out.")
                      (proc 18))))
      (proc 11))
 (seg (? (= Y 2) (= S 2))
      (sound 'se 1)
      (branch-reg 550
       (</>
        (/
         (nop@)
         (inc-var H 1)
         (proc 0)
         (proc 5)
         (proc 19)
         (branch-reg 569
          (</>
           (/)
           (/ (image-file "gpc¥a1_01bk.gpc") (image-mem 1 0) (proc 12))))
         (exec-mem 3072 0)
         (image-file "gpc¥a1_01ca.gpc")
         (image-mem 1 0)
         (proc 12)
         (proc 6)
         (branch-reg 991
          (</>
           (/ (exec-mem 9504 "C icon¥tool13.gpc,GPC") (image-mem 1 0 6 40))
           (/ (exec-mem 9504 "C icon¥tool13.gpc,GPC") (image-mem 1 0 71 40))))
         (proc 12)
         (proc 10)
         (proc 14)
         (str "Hauh...... It hurts!")
         (proc 18)
         (proc 13)
         (str "Oh, I'm far from done with you!")
         (proc 18)
         (proc 14)
         (str "No, I can't take any more............")
         (proc 18)
         (nop@)
         (set-reg 550 #t)
         (proc 15))
        (/
         (proc 10)
         (proc 14)
         (str "Hauh...... It hurts!")
         (proc 18))))
      (proc 11))
 (seg (? (= Y 2) (= S 3))
      (branch-reg 559
       (</>
        (/
         (sound 'se 1)
         (branch-reg 551
          (</>
           (/
            (nop@)
            (inc-var H 1)
            (proc 0)
            (image-file "gpc¥a1_01cb.gpc")
            (image-mem 1 0)
            (proc 12)
            (proc 19)
            (branch-reg 569
             (</>
              (/)
              (/ (image-file "gpc¥a1_01bk.gpc") (image-mem 1 0) (proc 12))))
            (proc 10)
            (proc 14)
            (str "Nguh! Mmh............")
            (proc 18)
            (proc 13)
            (str "Ku ku, you're starting to sound like a proper little bitch." 'br)
            (str "Are you starting to feel good?")
            (proc 18)
            (proc 14)
            (str "Uugh............")
            (proc 18)
            (nop@)
            (set-reg 551 #t)
            (proc 15)
            (proc 11))
           (/
            (proc 10)
            (proc 14)
            (str "Nguh! Mmh............")
            (proc 18))))
         (proc 11))
        (/))))
 (seg (? (= Y 2) (= S 4))
      (branch-reg 560
       (</>
        (/
         (sound 'se 1)
         (branch-reg 552
          (</>
           (/
            (nop@)
            (inc-var H 1)
            (proc 0)
            (image-file "gpc¥a1_01cc.gpc")
            (image-mem 1 0)
            (proc 12)
            (proc 19)
            (branch-reg 569
             (</>
              (/)
              (/ (image-file "gpc¥a1_01bk.gpc") (image-mem 1 0) (proc 12))))
            (proc 10)
            (proc 14)
            (str "Hiii!")
            (proc 18)
            (proc 13)
            (str "It's twitching down there, begging for the whip. But we" 'br)
            (str "can't have that... I'm going to torment you some more first.")
            (proc 18)
            (proc 14)
            (str "Ugh, uugh...... Please...... Let me go!")
            (proc 18)
            (nop@)
            (set-reg 552 #t)
            (proc 15)
            (proc 11))
           (/ (proc 10) (proc 14) (str "Hiii!") (proc 18))))
         (proc 11))
        (/))))
 (seg (? (= Y 2) (= S 5))
      (branch-reg 562
       (</>
        (/
         (sound 'se 1)
         (branch-reg 553
          (</>
           (/
            (nop@)
            (inc-var H 1)
            (proc 0)
            (image-file "gpc¥a1_01cd.gpc")
            (image-mem 1 0)
            (proc 12)
            (proc 19)
            (branch-reg 569
             (</>
              (/)
              (/ (image-file "gpc¥a1_01bk.gpc") (image-mem 1 0) (proc 12))))
            (proc 10)
            (proc 14)
            (str "Hah...... nnh, aaah!")
            (proc 18)
            (proc 13)
            (str "Scream louder! You're not getting off that easily!")
            (proc 18)
            (proc 14)
            (str "Nnh, nnnh......")
            (proc 18)
            (nop@)
            (set-reg 553 #t)
            (proc 15)
            (proc 11))
           (/
            (proc 10)
            (proc 14)
            (str "Hah...... nnh, aaah!")
            (proc 18))))
         (proc 11))
        (/))))
 (seg (? (= Y 2) (= S 6))
      (sound 'se 1)
      (branch-reg 554
       (</>
        (/
         (nop@)
         (inc-var H 1)
         (proc 0)
         (image-file "gpc¥a1_01ce.gpc")
         (image-mem 1 0)
         (proc 12)
         (proc 19)
         (branch-reg 569
          (</>
           (/)
           (/ (image-file "gpc¥a1_01bk.gpc") (image-mem 1 0) (proc 12))))
         (proc 10)
         (proc 14)
         (str "Hah, hahn!")
         (proc 18)
         (proc 13)
         (str "What kind of noise was that? You get off on having your tits" 'br)
         (str "whipped? You're a masochist! A real freak!")
         (proc 18)
         (proc 14)
         (str "Ugh.........")
         (proc 18)
         (nop@)
         (set-reg 554 #t)
         (proc 15))
        (/ (proc 10) (proc 14) (str "Hah, hahn!") (proc 18))))
      (proc 11))
 (seg (? (= Y 2) (= S 7))
      (branch-reg 563
       (</>
        (/
         (sound 'se 1)
         (branch-reg 555
          (</>
           (/
            (nop@)
            (set-reg 555 #t)
            (nop@)
            (inc-var H 1)
            (proc 0)
            (image-file "gpc¥a1_01cf.gpc")
            (image-mem 1 0)
            (nop@)
            (set-reg 555 #t)
            (proc 12)
            (proc 19)
            (branch-reg 569
             (</>
              (/)
              (/ (image-file "gpc¥a1_01bk.gpc") (image-mem 1 0) (proc 12))))
            (proc 10)
            (proc 14)
            (str "Hii, it hurts...... I'm going to die!")
            (proc 18)
            (proc 13)
            (str "A little more force and your skin will split open, leaving" 'br)
            (str "scars that will never fully heal. It's all in how I swing.")
            (proc 18)
            (proc 13)
            (str "Do you understand now how powerless you are?")
            (proc 18)
            (proc 14)
            (str "I-I'll do anything you say, so please......")
            (proc 18)
            (nop@)
            (set-reg 555 #t)
            (proc 15)
            (proc 11))
           (/
            (proc 10)
            (proc 14)
            (str "Hii, it hurts...... I'm going to die!")
            (proc 18))))
         (proc 11))
        (/))))
 (seg (? (= Y 2) (= S 8))
      (sound 'se 1)
      (branch-reg 556
       (</>
        (/
         (nop@)
         (inc-var H 1)
         (proc 0)
         (image-file "gpc¥a1_01cg.gpc")
         (image-mem 1 0)
         (proc 12)
         (proc 19)
         (branch-reg 569
          (</>
           (/)
           (/ (image-file "gpc¥a1_01bk.gpc") (image-mem 1 0) (proc 12))))
         (proc 10)
         (proc 14)
         (str "Ah, kuuh............")
         (proc 18)
         (proc 13)
         (str "Each strike is coming closer and closer down there. Want" 'br)
         (str "me to make that filthy hole of yours completely useless?")
         (proc 18)
         (proc 14)
         (str "Hah, hah, hah...... I don't care anymore, do whatever" 'br)
         (str "you want!")
         (proc 18)
         (nop@)
         (set-reg 556 #t)
         (proc 15))
        (/
         (proc 10)
         (proc 14)
         (str "Ah, kuuh............")
         (proc 18))))
      (proc 11))
 (seg (? (= Y 2) (= S 9))
      (branch-reg 567
       (</>
        (/
         (sound 'se 1)
         (branch-reg 557
          (</>
           (/
            (nop@)
            (inc-var H 1)
            (proc 0)
            (image-file "gpc¥a1_01ch.gpc")
            (image-mem 1 0)
            (proc 12)
            (proc 19)
            (branch-reg 569
             (</>
              (/)
              (/ (image-file "gpc¥a1_01bk.gpc") (image-mem 1 0) (proc 12))))
            (proc 10)
            (proc 13)
            (str "This depraved slut is actually enjoying being tormented!")
            (proc 18)
            (proc 14)
            (str "Ahhh, please have mercy on me......")
            (proc 18)
            (proc 13)
            (str "Spill everything you know, you bitch! Unless you want" 'br)
            (str "things to get much worse!")
            (proc 18)
            (nop@)
            (set-reg 557 #t)
            (proc 15)
            (proc 11))
           (/
            (proc 10)
            (proc 14)
            (str "Hauh, I'm a bitch...... A shameless, dirty bitch!")
            (proc 18))))
         (proc 11))
        (/))))
 (seg (? (= Y 2) (= S 10))
      (branch-reg 568
       (</>
        (/
         (sound 'se 1)
         (branch-reg 558
          (</>
           (/
            (nop@)
            (inc-var H 1)
            (proc 0)
            (image-file "gpc¥a1_01ci.gpc")
            (image-mem 1 0)
            (proc 12)
            (proc 19)
            (branch-reg 569
             (</>
              (/)
              (/ (image-file "gpc¥a1_01bk.gpc") (image-mem 1 0) (proc 12))))
            (proc 10)
            (proc 14)
            (str "Ow...... N-not there!")
            (proc 18)
            (proc 13)
            (str "You mean this filthy thing down here? Does that soaking wet" 'br)
            (str "lower mouth of yours want the whip?")
            (proc 18)
            (proc 14)
            (str "No, anything but that...... Please, forgive me!")
            (proc 18)
            (nop@)
            (set-reg 558 #t)
            (proc 15)
            (proc 11))
           (/
            (proc 10)
            (proc 14)
            (str "Ow...... N-not there!")
            (proc 18))))
         (proc 11))
        (/))))
 (seg (? (= Y 5) (<= H 16) (= S 1))
      (proc 10)
      (branch-index (</>
                     (/
                      (proc 14)
                      (str "Ah, it's hot...... Take it away, take the candle away!")
                      (proc 18)
                      (proc 13)
                      (str "Want me to burn that pretty face of yours? It'd be a" 'br)
                      (str "fitting brand for a slave like you!")
                      (proc 18)
                      (proc 14)
                      (str "No, anything but that!")
                      (proc 18)
                      (proc 13)
                      (str "Then beg like the slave you are!")
                      (proc 18)
                      (proc 14)
                      (str "Please...... Master, I'm begging you...... Take the" 'br)
                      (str "candle away.")
                      (proc 18)
                      (proc 13)
                      (str "Just take it away? If not on your face, then tell me where" 'br)
                      (str "you want me to drip the wax instead.")
                      (proc 18)
                      (proc 14)
                      (str "..................")
                      (proc 18)
                      (proc 13)
                      (str "Say it!")
                      (proc 18)
                      (proc 14)
                      (str "Ah, it's hot...... My breasts, please drip it on my breasts!")
                      (proc 18)
                      (proc 13)
                      (str "Oh? So you want the wax that badly? Then I'll give you" 'br)
                      (str "exactly what you asked for.")
                      (proc 18))
                     (/
                      (proc 14)
                      (str "Ah, it's hot...... Take it away, take the candle away!")
                      (proc 18))
                     (/
                      (proc 14)
                      (str "M-my hair is going to burn...... Please stop!")
                      (proc 18))))
      (proc 11))
 (seg (? (= Y 5) (>= H 17) (= S 1)) (mes-jump "mes¥md_a2_r3.mes"))
 (seg (? (= Y 5) (= S 2))
      (branch-reg 559
       (</>
        (/
         (nop@)
         (inc-var H 1)
         (proc 0)
         (image-file "gpc¥a1_01ba.gpc")
         (image-mem 1 0)
         (proc 12)
         (proc 19)
         (branch-reg 569
          (</>
           (/)
           (/ (image-file "gpc¥a1_01bk.gpc") (image-mem 1 0) (proc 12))))
         (proc 10)
         (proc 14)
         (str "Aah, that burns...... it burns!")
         (proc 18)
         (branch-reg 551
          (</>
           (/
            (proc 13)
            (str "The red wax looks just like blood on your skin. I think" 'br)
            (str "I'll cover you head to toe in it. What a sight that'll be......")
            (proc 18))
           (/
            (proc 13)
            (str "Oh, it landed right on a wound. Does that sting? Go ahead" 'br)
            (str "and scream if it does. You'll only be making me happier.")
            (proc 18))))
         (proc 14)
         (str "Ugh, uugh...... How did it come to this......")
         (proc 18)
         (nop@)
         (set-reg 559 #t))
        (/
         (proc 10)
         (proc 14)
         (str "Hauh...... It's so hot...... I can't stand it anymore!")
         (proc 18))))
      (proc 11))
 (seg (? (= Y 5) (= S 3))
      (branch-reg 560
       (</>
        (/
         (nop@)
         (inc-var H 1)
         (proc 0)
         (image-file "gpc¥a1_01bb.gpc")
         (image-mem 1 0)
         (proc 12)
         (proc 19)
         (branch-reg 569
          (</>
           (/)
           (/ (image-file "gpc¥a1_01bk.gpc") (image-mem 1 0) (proc 12))))
         (proc 10)
         (proc 14)
         (str "Hii...... hiii!")
         (proc 18)
         (proc 13)
         (str "Look at that red wax on your white thighs. Isn't it" 'br)
         (str "beautiful? You should be glad I'm making you look so pretty.")
         (proc 18)
         (proc 14)
         (str "I-I am grateful...... so please...... no more!")
         (proc 18)
         (nop@)
         (set-reg 560 #t))
        (/ (proc 10) (proc 14) (str "Hii...... hiii!") (proc 18))))
      (proc 11))
 (seg (? (= Y 5) (= S 4))
      (branch-reg 561
       (</>
        (/
         (nop@)
         (inc-var H 1)
         (proc 0)
         (image-file "gpc¥a1_01bc.gpc")
         (image-mem 1 0)
         (proc 12)
         (proc 19)
         (branch-reg 569
          (</>
           (/)
           (/ (image-file "gpc¥a1_01bk.gpc") (image-mem 1 0) (proc 12))))
         (proc 10)
         (proc 14)
         (str "Haahhn, not there!")
         (proc 18)
         (proc 13)
         (str "Your *** isn't saying that. It's crying, practically begging" 'br)
         (str "for me to pour the wax on it!")
         (proc 18)
         (proc 14)
         (str "No...... oh god, no......")
         (proc 18)
         (nop@)
         (set-reg 561 #t))
        (/
         (proc 10)
         (proc 14)
         (str "Haahhn, not there!")
         (proc 18))))
      (proc 11))
 (seg (? (= Y 5) (= S 5))
      (branch-reg 562
       (</>
        (/
         (nop@)
         (inc-var H 1)
         (proc 0)
         (image-file "gpc¥a1_01bd.gpc")
         (image-mem 1 0)
         (proc 12)
         (proc 19)
         (branch-reg 569
          (</>
           (/)
           (/ (image-file "gpc¥a1_01bk.gpc") (image-mem 1 0) (proc 12))))
         (proc 10)
         (proc 14)
         (str "Ahhh............")
         (proc 18)
         (proc 13)
         (str "The wax on your stomach looks like someone's seed sprayed" 'br)
         (str "all over you. How many men have you let do that, I wonder?")
         (proc 18)
         (proc 14)
         (str "I-I wouldn't know...... I don't do things like that!")
         (proc 18)
         (nop@)
         (set-reg 562 #t))
        (/ (proc 10) (proc 14) (str "Ahhh............") (proc 18))))
      (proc 11))
 (seg (? (= Y 5) (= S 6))
      (branch-reg 563
       (</>
        (/
         (nop@)
         (inc-var H 1)
         (nop@)
         (set-reg 563 #t)
         (proc 0)
         (image-file "gpc¥a1_01be.gpc")
         (image-mem 1 0)
         (proc 12)
         (proc 19)
         (branch-reg 569
          (</>
           (/)
           (/ (image-file "gpc¥a1_01bk.gpc") (image-mem 1 0) (proc 12))))
         (proc 10)
         (proc 14)
         (str "Hauh! Hah, hah, hah......")
         (proc 18)
         (proc 13)
         (str "So even the candle is starting to feel good now? You're well" 'br)
         (str "on your way to becoming a proper bitch.")
         (proc 18)
         (nop@)
         (set-reg 563 #t))
        (/
         (proc 10)
         (proc 14)
         (str "Hauh! Hah, hah, hah......")
         (proc 18))))
      (proc 11))
 (seg (? (= Y 5) (= S 7))
      (branch-reg 564
       (</>
        (/
         (nop@)
         (inc-var H 1)
         (proc 0)
         (image-file "gpc¥a1_01bf.gpc")
         (image-mem 1 0)
         (proc 12)
         (proc 19)
         (branch-reg 569
          (</>
           (/)
           (/ (image-file "gpc¥a1_01bk.gpc") (image-mem 1 0) (proc 12))))
         (proc 10)
         (proc 14)
         (str "Nfuh! No, it's too hot, I can't take it!")
         (proc 18)
         (proc 13)
         (str "Do you even hear yourself right now? Have I been too rough" 'br)
         (str "with you and you've finally lost your mind?")
         (proc 18)
         (proc 14)
         (str "It's hot...... so hot...... I hate it......")
         (proc 18)
         (nop@)
         (set-reg 564 #t))
        (/
         (proc 10)
         (proc 14)
         (str "Nfuh! No, it's too hot, I can't take it!")
         (proc 18))))
      (proc 11))
 (seg (? (= Y 5) (= S 8))
      (branch-reg 565
       (</>
        (/
         (nop@)
         (inc-var H 1)
         (proc 0)
         (image-file "gpc¥a1_01bg.gpc")
         (image-mem 1 0)
         (proc 12)
         (proc 19)
         (branch-reg 569
          (</>
           (/)
           (/ (image-file "gpc¥a1_01bk.gpc") (image-mem 1 0) (proc 12))))
         (proc 10)
         (proc 14)
         (str "Ugh...... hiiiiii!")
         (proc 18)
         (proc 13)
         (str "Hot, isn't it? Of course it is, you just got burned with wax" 'br)
         (str "down there. So why are you soaking wet like you pissed yourself?")
         (proc 18)
         (proc 14)
         (str "Ugh, uugh......")
         (proc 18)
         (nop@)
         (set-reg 565 #t))
        (/
         (proc 10)
         (proc 14)
         (str "N-not there! I-I'll die............")
         (proc 18))))
      (proc 11))
 (seg (? (= Y 5) (= S 9))
      (branch-reg 566
       (</>
        (/
         (nop@)
         (inc-var H 1)
         (nop@)
         (set-reg 566 #t)
         (proc 0)
         (proc 5)
         (proc 19)
         (branch-reg 569
          (</>
           (/)
           (/ (image-file "gpc¥a1_01bk.gpc") (image-mem 1 0) (proc 12))))
         (exec-mem 3072 0)
         (image-file "gpc¥a1_01bh.gpc")
         (image-mem 1 0)
         (proc 12)
         (proc 6)
         (branch-reg 991
          (</>
           (/ (exec-mem 9504 "C icon¥tool16.gpc,GPC") (image-mem 1 0 6 112))
           (/ (exec-mem 9504 "C icon¥tool16.gpc,GPC") (image-mem 1 0 71 112))))
         (proc 10)
         (proc 14)
         (str "Hahn............")
         (proc 18)
         (proc 13)
         (str "The heat of the candle feels good to you, doesn't it? You" 'br)
         (str "were born to be someone's pet. That's what you were made for.")
         (proc 18)
         (proc 14)
         (str "T-that's not true...... It's not like that, I-I'm not......!")
         (proc 18)
         (nop@)
         (set-reg 566 #t))
        (/ (proc 10) (proc 14) (str "Hahn............") (proc 18))))
      (proc 11))
 (seg (? (= Y 5) (= S 10))
      (branch-reg 567
       (</>
        (/
         (nop@)
         (inc-var H 1)
         (proc 0)
         (image-file "gpc¥a1_01bi.gpc")
         (image-mem 1 0)
         (proc 12)
         (proc 19)
         (branch-reg 569
          (</>
           (/)
           (/ (image-file "gpc¥a1_01bk.gpc") (image-mem 1 0) (proc 12))))
         (proc 10)
         (proc 14)
         (str "Augh, not there...... I'll die!")
         (proc 18)
         (proc 13)
         (str "Are you feeling so good it's killing you?")
         (proc 18)
         (proc 13)
         (str "You're looking more like a proper pet by the minute." 'br)
         (str "Look at how hard your nipples are......")
         (proc 18)
         (proc 14)
         (str "That's a lie, that isn't...... It's not what you think!")
         (proc 18)
         (nop@)
         (set-reg 567 #t))
        (/
         (proc 10)
         (proc 14)
         (str "Augh, not there...... I'll die!")
         (proc 18))))
      (proc 11))
 (seg (? (= Y 5) (= S 11))
      (branch-reg 568
       (</>
        (/
         (nop@)
         (inc-var H 1)
         (proc 0)
         (image-file "gpc¥a1_01bj.gpc")
         (image-mem 1 0)
         (proc 12)
         (proc 19)
         (branch-reg 569
          (</>
           (/)
           (/ (image-file "gpc¥a1_01bk.gpc") (image-mem 1 0) (proc 12))))
         (proc 10)
         (proc 14)
         (str "Hii...... ah, it burns!")
         (proc 18)
         (branch-reg 558
          (</>
           (/
            (proc 13)
            (str "Your master is going out of her way for you. Say thank you!")
            (proc 18)
            (proc 14)
            (str "M-Master...... Thank you.")
            (proc 18))
           (/
            (proc 13)
            (str "Doesn't the wax feel even better when I drip it on your" 'br)
            (str "wounds like this?")
            (proc 18)
            (proc 13)
            (str "It's a kind of pleasure only a naughty pet like you" 'br)
            (str "could appreciate.")
            (proc 18)
            (proc 14)
            (str "Y-yes...... It feels good...... I can't get enough!")
            (proc 18))))
         (nop@)
         (set-reg 568 #t))
        (/
         (proc 10)
         (proc 14)
         (str "Hii...... ah, it burns!")
         (proc 18))))
      (proc 11))
 (seg (? (= Y 5) (= S 12))
      (branch-reg 569
       (</>
        (/
         (nop@)
         (inc-var H 1)
         (nop@)
         (set-reg 569 #t)
         (proc 0)
         (image-file "gpc¥a1_01bk.gpc")
         (image-mem 1 0)
         (proc 12)
         (proc 19)
         (branch-reg 569
          (</>
           (/)
           (/ (image-file "gpc¥a1_01bk.gpc") (image-mem 1 0) (proc 12))))
         (proc 10)
         (proc 14)
         (str "Aaahhhhn............")
         (proc 18)
         (proc 13)
         (str "Getting off on the candle now, you bitch? Thank your master" 'br)
         (str "the way a dog should - bark for me!")
         (proc 18)
         (proc 14)
         (str "W...... Woof, woof, woof!")
         (proc 18)
         (nop@)
         (set-reg 569 #t))
        (/
         (proc 10)
         (proc 14)
         (str "Aaahhhh............")
         (proc 18))))
      (proc 11)))