(mes
 (meta (engine 'ADV) (charset "pc98") (extraop #t))
 (seg (? (= 991 #f) (= Y 0))
      (nop@)
      (set-reg 980 #t)
      (set-reg 981 #t)
      (set-reg 982 #f)
      (set-reg 983 #f)
      (set-reg 984 #f)
      (set-reg 985 #f)
      (set-reg 986 #f)
      (set-reg 987 #f)
      (set-reg 988 #f)
      (set-reg 989 #f)
      (set-reg 990 #f)
      (exec-mem 14080 2 0 0 159 99 80 34 80 34 0 30)
      (text-frame 0 0 79 399)
      (text-reset 14)
      (image-file "gpc¥a1_00.gpc")
      (image-mem 0 3)
      (exec-mem 14080 1 80 34 80 34 0 0 159 99 8 30)
      (if (</>
           (//
            (? (!= P 8))
            (if (</>
                 (//
                  (? (= O 0))
                  (sound ' 0)
                  (sound ' "uso¥xg_08.uso")
                  (sound ' 1)
                  (nop@)
                  (set-var P 8))
                 (//
                  (? (= O 1))
                  (sound ' 0)
                  (sound ' "uso¥xg_08v.uso")
                  (sound ' 1)
                  (nop@)
                  (set-var P 8)))))
           (// (nop@))))
      (exec-mem 256 "E")
      (load-mem "clm¥A1_00.clm" 32768)
      (load-mem "clm¥icon.clm" 20480)
      (mes-load? "mes¥icon_cl.mec" 0)
      (mes-load? 0)
      (mes-load? "mes¥icon_c2.mec" 0)
      (mes-load? 0)
      (define-proc 13 (<> (text-delay 0) (str "「Kiyomi」" 'br) (text-delay 2)))
      (define-proc 14 (<> (text-delay 0) (str "「April」" 'br) (text-delay 2)))
      (define-proc 18 (<> (wait) (text-reset 14)))
      (text-frame 10 312 70 370)
      (exec-mem 256 "A 0")
      (proc 12)
      (set-var H 0)
      (proc 10)
      (proc 13)
      (str "If you're going to confess, now's the time. No need to put" 'br)
      (str "yourself through unnecessary pain.")
      (proc 18)
      (proc 14)
      (text-delay 4)
      (str "............")
      (proc 18)
      (proc 13)
      (str "Or are you into that?")
      (proc 18)
      (proc 14)
      (str "H-hmph...... You just say whatever you want, don't you!")
      (proc 18)
      (proc 13)
      (str "Your voice is shaking, you know.")
      (proc 18)
      (proc 14)
      (str "Don't mess with me! I'm a professional - don't think I'll" 'br)
      (str "crack that easily!")
      (proc 18)
      (proc 13)
      (str "Big talk. Then I guess you'll have to entertain me......")
      (proc 18)
      (proc 13)
      (str "See, I love this kind of thing. Watching a cocky bitch like" 'br)
      (str "you squeal and cry - that's what gets me going!")
      (proc 18)
      (proc 14)
      (str "You're sick...... You're completely insane.")
      (proc 18)
      (proc 13)
      (str "Call me whatever you want. I had the courtesy to warn you.")
      (proc 18)
      (proc 14)
      (str "D-don't come any closer! Don't touch me!")
      (proc 18)
      (proc 13)
      (str "Now, what tool should I use first...... This whip is" 'br)
      (str "carefully tanned, oil-soaked leather. It cuts like a razor.")
      (proc 18)
      (proc 13)
      (str "This rod here is incredibly heavy. Get hit with this and it" 'br)
      (str "just might break a bone.")
      (proc 18)
      (proc 14)
      (text-delay 6)
      (str "..................")
      (proc 18)
      (proc 13)
      (str "Nothing to say? Well then, let's get started......")
      (proc 18)
      (proc 11)
      (exec-mem 3968 102 500 360)
      (exec-mem 3072 1)
      (exec-mem 256 "P 5 6 0")
      (loop
       (set-var S 0)
       (exec-mem 3072 1020 1021 "S" 32768 "Z" 20480)
       (seg-call)))
 (seg (? (= Z 2) (= 991 #f) (= 1020 #f) (!= Q 2))
      (proc 0)
      (exec-mem 256 "P 6 9 16")
      (exec-mem 9504 "C icon¥name1.gpc,GPC")
      (image-mem 1 0 9 16)
      (proc 1)
      (set-var Q 2))
 (seg (? (= Z 3) (= 991 #f) (= 1020 #f) (!= Q 3))
      (proc 0)
      (exec-mem 256 "P 6 9 16")
      (exec-mem 9504 "C icon¥name2.gpc,GPC")
      (image-mem 1 0 9 40)
      (proc 1)
      (set-var Q 3))
 (seg (? (= Z 2) (= 991 #t) (= 1020 #f) (!= Q 2))
      (proc 0)
      (exec-mem 256 "P 7 52 16")
      (exec-mem 9504 "C icon¥name1.gpc,GPC")
      (image-mem 1 0 52 16)
      (proc 1)
      (set-var Q 2))
 (seg (? (= Z 3) (= 991 #t) (= 1020 #f) (!= Q 3))
      (proc 0)
      (exec-mem 256 "P 7 52 16")
      (exec-mem 9504 "C icon¥name2.gpc,GPC")
      (image-mem 1 0 52 40)
      (proc 1)
      (set-var Q 3))
 (seg (? (!= Z 2) (!= Z 3) (= 991 #f) (= 1020 #f) (>= Q 1))
      (proc 0)
      (exec-mem 256 "P 6 9 16")
      (proc 1)
      (nop@)
      (set-var Q 0))
 (seg (? (!= Z 2) (!= Z 3) (= 991 #t) (= 1020 #f) (>= Q 1))
      (proc 0)
      (exec-mem 256 "P 7 52 16")
      (proc 1)
      (nop@)
      (set-var Q 0))
 (seg (? (= 1020 #f) (= 1021 #f)) (exec-mem 3072 1))
 (seg (? (= 1021 #t)) (exec-mem 3072 1))
 (seg* (proc 4) (seg-call))
 (seg (? (= Z 1) (= 991 #f))
      (proc 0)
      (exec-mem 256 "P 5 71 0")
      (nop@)
      (set-reg 991 #t)
      (exec-mem 256 "P 8 6 0")
      (if (</>
           (//
            (? (= Y 1))
            (exec-mem 9504 "C icon¥tool12.gpc,GPC")
            (image-mem 1 0 71 16))
           (//
            (? (= Y 2))
            (exec-mem 9504 "C icon¥tool13.gpc,GPC")
            (image-mem 1 0 71 40))))
      (load-mem "clm¥icon2.clm" 20480)
      (proc 1))
 (seg (? (= Z 1) (= 991 #t))
      (proc 0)
      (exec-mem 256 "P 5 6 0")
      (nop@)
      (set-reg 991 #f)
      (exec-mem 256 "P 9 71 0")
      (if (</>
           (//
            (? (= Y 1))
            (exec-mem 9504 "C icon¥tool12.gpc,GPC")
            (image-mem 1 0 6 16))
           (//
            (? (= Y 2))
            (exec-mem 9504 "C icon¥tool13.gpc,GPC")
            (image-mem 1 0 6 40))))
      (load-mem "clm¥icon.clm" 20480)
      (proc 1))
 (seg (? (= Z 2) (= 991 #f))
      (nop@)
      (set-var Y 1)
      (proc 0)
      (exec-mem 9504 "C icon¥tool12.gpc,GPC")
      (image-mem 1 0 6 16)
      (exec-mem 9504 "C icon¥tool24.gpc,GPC")
      (image-mem 1 0 6 40)
      (exec-mem 18688 5 1 1)
      (proc 1)
      (exec-mem 18688 2 2))
 (seg (? (= Z 3) (= 991 #f))
      (nop@)
      (set-var Y 2)
      (proc 0)
      (exec-mem 9504 "C icon¥tool13.gpc,GPC")
      (image-mem 1 0 6 40)
      (exec-mem 9504 "C icon¥tool23.gpc,GPC")
      (image-mem 1 0 6 16)
      (exec-mem 18688 5 3 1)
      (proc 1)
      (exec-mem 18688 2 3))
 (seg (? (= Z 2) (= 991 #t))
      (nop@)
      (set-var Y 1)
      (proc 0)
      (exec-mem 9504 "C icon¥tool12.gpc,GPC")
      (image-mem 1 0 71 16)
      (exec-mem 9504 "C icon¥tool24.gpc,GPC")
      (image-mem 1 0 71 40)
      (exec-mem 18688 5 1 1)
      (proc 1)
      (exec-mem 18688 2 2))
 (seg (? (= Z 3) (= 991 #t))
      (nop@)
      (set-var Y 2)
      (proc 0)
      (exec-mem 9504 "C icon¥tool13.gpc,GPC")
      (image-mem 1 0 71 40)
      (exec-mem 9504 "C icon¥tool23.gpc,GPC")
      (image-mem 1 0 71 16)
      (exec-mem 18688 5 3 1)
      (proc 1)
      (exec-mem 18688 2 3))
 (seg (? (= Y 1) (= S 1) (<= H 3))
      (proc 10)
      (branch-index (</>
                     (/
                      (proc 13)
                      (str "This is your last chance. Talk, before things get ugly" 'br)
                      (str "for you!")
                      (wait)
                      (text-reset 14)
                      (proc 14)
                      (str "A-as if...... I'd rather die than betray my comrades!")
                      (wait)
                      (text-reset 14)
                      (proc 13)
                      (str "Is that so? Then I'll beat you half to death with this" 'br)
                      (str "rod!")
                      (wait)
                      (text-reset 14)
                      (proc 14)
                      (str "Kuh...... Y-you sadist!")
                      (wait)
                      (text-reset 14)
                      (proc 13)
                      (str "That's the nicest thing you've said yet. Gives me chills.")
                      (wait)
                      (text-reset 14)
                      (proc 14)
                      (str "You're insane......")
                      (wait)
                      (text-reset 14)
                      (proc 13)
                      (str "The real fun is just getting started. You can't give up so" 'br)
                      (str "soon...... You'll keep entertaining me, won't you?")
                      (wait)
                      (text-reset 14))
                     (/
                      (proc 13)
                      (str "You can't give up so soon. You'll keep entertaining me," 'br)
                      (str "won't you?")
                      (wait)
                      (text-reset 14))))
      (proc 11))
 (seg (? (= Y 1) (= S 1) (<= H 6))
      (proc 10)
      (branch-index (</>
                     (/
                      (proc 13)
                      (str "Ku ku ku...... What a lovely voice you have.")
                      (wait)
                      (text-reset 14)
                      (proc 14)
                      (str "Ugh...... P-please, no more.")
                      (wait)
                      (text-reset 14)
                      (proc 13)
                      (str "If you want me to stop, then talk. Tell me about your" 'br)
                      (str "accomplices and what you did with those stolen files!" 'br)
                      (wait)
                      (text-reset 14)
                      (proc 14)
                      (str "I told you, I don't know...... I really don't know anything!")
                      (wait)
                      (text-reset 14)
                      (proc 13)
                      (str "You really like getting hit that much? If that's what you" 'br)
                      (str "want, I'll cover your whole body in bruises.")
                      (wait)
                      (text-reset 14)
                      (proc 14)
                      (str "Eek.............. N-no!")
                      (wait)
                      (text-reset 14)
                      (proc 13)
                      (str "I should torment you a bit more. When you betray them," 'br)
                      (str "it's easier to live with if you held out for a while, right?")
                      (wait)
                      (text-reset 14))
                     (/
                      (proc 13)
                      (str "I should torment you a bit more. When you betray them," 'br)
                      (str "it's easier to live with if you held out for a while, right?")
                      (wait)
                      (text-reset 14))))
      (proc 11))
 (seg (? (= Y 1) (= S 1) (>= H 7))
      (proc 10)
      (proc 13)
      (str "Ready to talk yet?")
      (proc 18)
      (proc 14)
      (str "Peh! Not a chance.")
      (proc 18)
      (proc 13)
      (str "Stupid woman...... The sooner you talk, the less you'll" 'br)
      (str "have to suffer. Though I'd hate to lose my fun.")
      (proc 18)
      (proc 14)
      (str "..................")
      (proc 18)
      (proc 13)
      (str "I'm glad you're such a stubborn fool.")
      (proc 18)
      (proc 14)
      (str "W-wait......")
      (proc 18)
      (proc 13)
      (str "It's too late for regrets. Just thinking about how to" 'br)
      (str "torment you gets me excited!")
      (proc 18)
      (proc 14)
      (str "W-what are you going to do? Stop it, don't touch me!")
      (proc 18)
      (proc 13)
      (str "First, I need to get those clothes off. The rod loses its" 'br)
      (str "edge through fabric, and that outfit is an eyesore.")
      (proc 18)
      (proc 14)
      (str "S-stop...... I said don't touch me!")
      (proc 18)
      (proc 11)
      (exec-mem 18688 3)
      (exec-mem 18688 5 1 0)
      (exec-mem 3072 0)
      (mes-jump "mes¥MD_A02.MES"))
 (seg (? (= Y 1) (= S 2))
      (sound 'se 1)
      (if (</>
           (//
            (? (>= H 5) (= 548 #f))
            (proc 0)
            (image-file "gpc¥a1_00a.gpc")
            (image-mem 1 0)
            (nop@)
            (set-reg 548 #t)
            (image-file "gpc¥a1_00ba.gpc")
            (image-mem 1 0)
            (proc 12))
           (//
            (proc 0)
            (image-file "gpc¥a1_00ba.gpc")
            (image-mem 1 0)
            (proc 12))))
      (proc 10)
      (branch-reg 541
       (</>
        (/
         (nop@)
         (inc-var H 1)
         (proc 14)
         (str "Hih.........")
         (wait)
         (text-reset 14)
         (proc 13)
         (str "Oops, almost left a mark on that cute face of yours.")
         (wait)
         (text-reset 14)
         (proc 14)
         (str "P-please...... not the face!")
         (wait)
         (text-reset 14)
         (proc 13)
         (str "What, a former Special Forces soldier can't even handle the" 'br)
         (str "thought of a scarred face?")
         (wait)
         (text-reset 14)
         (proc 14)
         (str ".........")
         (wait)
         (text-reset 14)
         (proc 13)
         (str "Relax, I'll spare your face. If I hit you with this rod," 'br)
         (str "you'd end up with a mug nobody could stand to look at!")
         (wait)
         (text-reset 14)
         (proc 14)
         (str "Y-you psycho...... There's something wrong with you!")
         (wait)
         (text-reset 14)
         (nop@)
         (set-reg 541 #t)
         (set-reg 548 #f))
        (/
         (proc 14)
         (str "N-no...... not the face!")
         (wait)
         (text-reset 14)
         (nop@)
         (set-reg 548 #f))))
      (proc 11))
 (seg (? (= Y 1) (= S 3))
      (sound 'se 1)
      (branch-reg 542
       (</>
        (/
         (nop@)
         (inc-var H 1)
         (if (</>
              (//
               (? (>= H 3) (= 548 #f))
               (proc 0)
               (image-file "gpc¥a1_00bb.gpc")
               (image-mem 1 0)
               (image-file "gpc¥a1_00a.gpc")
               (image-mem 1 0)
               (nop@)
               (set-reg 548 #t)
               (proc 12))
              (//
               (proc 0)
               (image-file "gpc¥a1_00bb.gpc")
               (image-mem 1 0)
               (proc 12))))
         (proc 10)
         (proc 14)
         (str "Ow............")
         (wait)
         (text-reset 14)
         (proc 13)
         (str "Tch, those clothes are too thick. The rod's losing half its" 'br)
         (str "effect like this.")
         (wait)
         (text-reset 14)
         (proc 14)
         (str "Y-you pervert...... Give it a rest already!")
         (wait)
         (text-reset 14)
         (proc 13)
         (str "Then again, if I swing any harder I might break a bone. My" 'br)
         (str "advice? Talk before that happens.")
         (wait)
         (text-reset 14)
         (nop@)
         (set-reg 542 #t))
        (/
         (proc 10)
         (proc 13)
         (str "I've hardly even started!")
         (wait)
         (text-reset 14))))
      (proc 11))
 (seg (? (= Y 1) (= S 4))
      (sound 'se 1)
      (branch-reg 543
       (</>
        (/
         (nop@)
         (inc-var H 1)
         (if (</>
              (//
               (? (>= H 3) (= 548 #f))
               (proc 0)
               (image-file "gpc¥a1_00bc.gpc")
               (image-mem 1 0)
               (image-file "gpc¥a1_00a.gpc")
               (image-mem 1 0)
               (nop@)
               (set-reg 548 #t)
               (proc 12))
              (//
               (proc 0)
               (image-file "gpc¥a1_00bc.gpc")
               (image-mem 1 0)
               (proc 12))))
         (proc 10)
         (proc 13)
         (str "What a sound. No matter how many times I hear it, it gets" 'br)
         (str "me going...... Ready to give up yet?")
         (wait)
         (text-reset 14)
         (proc 14)
         (str "As if...... I'll never give in to the likes of you!")
         (wait)
         (text-reset 14)
         (proc 13)
         (str "I like the spirit. We'll see how long it lasts......")
         (wait)
         (text-reset 14)
         (nop@)
         (set-reg 543 #t))
        (/
         (proc 10)
         (proc 13)
         (str "Try and dodge this one, huh!")
         (wait)
         (text-reset 14))))
      (proc 11))
 (seg (? (= Y 1) (= S 5))
      (sound 'se 1)
      (branch-reg 544
       (</>
        (/
         (nop@)
         (inc-var H 1)
         (if (</>
              (//
               (? (>= H 3) (= 548 #f))
               (proc 0)
               (image-file "gpc¥a1_00a.gpc")
               (image-mem 1 0)
               (nop@)
               (set-reg 548 #t)
               (image-file "gpc¥a1_00bd.gpc")
               (image-mem 1 0)
               (proc 12))
              (//
               (proc 0)
               (image-file "gpc¥a1_00bd.gpc")
               (image-mem 1 0)
               (proc 12))))
         (proc 10)
         (proc 13)
         (str "Doesn't look like that did much...... Does it hurt?")
         (wait)
         (text-reset 14)
         (proc 14)
         (str "O-of course it hurts...... Ugh!")
         (wait)
         (text-reset 14)
         (proc 13)
         (str "Want me to hit harder? I'm sure it'll start to feel" 'br)
         (str "good eventually.")
         (wait)
         (text-reset 14)
         (nop@)
         (set-reg 544 #t))
        (/
         (proc 10)
         (proc 14)
         (str "Hii.........")
         (wait)
         (text-reset 14))))
      (proc 11))
 (seg (? (= Y 1) (= S 6))
      (sound 'se 1)
      (branch-reg 545
       (</>
        (/
         (nop@)
         (inc-var H 1)
         (if (</>
              (//
               (? (>= H 3) (= 548 #f))
               (proc 0)
               (image-file "gpc¥a1_00a.gpc")
               (image-mem 1 0)
               (nop@)
               (set-reg 548 #t)
               (image-file "gpc¥a1_00be.gpc")
               (image-mem 1 0)
               (proc 12))
              (//
               (proc 0)
               (image-file "gpc¥a1_00be.gpc")
               (image-mem 1 0)
               (proc 12))))
         (proc 10)
         (proc 14)
         (str "Ugh...... W-why is this happening to me?")
         (wait)
         (text-reset 14)
         (proc 13)
         (str "You're still going on about that? Keep it up and I'll stop" 'br)
         (str "going easy on you!")
         (wait)
         (text-reset 14)
         (proc 14)
         (str "Damn you, I'll get you back for this...... I swear it!")
         (wait)
         (text-reset 14)
         (proc 13)
         (str "Sorry to disappoint, but that's not going to happen." 'br)
         (str "It's over for you.")
         (wait)
         (text-reset 14)
         (nop@)
         (set-reg 545 #t))
        (/
         (proc 10)
         (proc 14)
         (str "Oww............")
         (wait)
         (text-reset 14))))
      (proc 11))
 (seg (? (= Y 1) (= S 7))
      (sound 'se 1)
      (branch-reg 546
       (</>
        (/
         (nop@)
         (inc-var H 1)
         (if (</>
              (//
               (? (>= H 3) (= 548 #f))
               (proc 0)
               (image-file "gpc¥a1_00a.gpc")
               (image-mem 1 0)
               (nop@)
               (set-reg 548 #t)
               (image-file "gpc¥a1_00bf.gpc")
               (image-mem 1 0)
               (proc 12))
              (//
               (proc 0)
               (image-file "gpc¥a1_00bf.gpc")
               (image-mem 1 0)
               (proc 12))))
         (proc 10)
         (proc 14)
         (str "Ah...... Ow!")
         (wait)
         (text-reset 14)
         (proc 13)
         (str "Well, isn't that some cute underwear you've got on. Too bad" 'br)
         (str "it doesn't suit you at all.")
         (wait)
         (text-reset 14)
         (proc 14)
         (str "That's cruel...... This is too much!")
         (wait)
         (text-reset 14)
         (proc 13)
         (str "I'm not doing this just for fun, you know. I don't have the" 'br)
         (str "luxury of caring about your feelings.")
         (wait)
         (text-reset 14)
         (nop@)
         (set-reg 546 #t))
        (/
         (proc 10)
         (proc 14)
         (str "Augh............ It hurts.")
         (wait)
         (text-reset 14))))
      (proc 11))
 (seg (? (= S 8) (= Y 1))
      (sound 'se 1)
      (branch-reg 547
       (</>
        (/
         (nop@)
         (inc-var H 1)
         (if (</>
              (//
               (? (>= H 3) (= 548 #f))
               (proc 0)
               (image-file "gpc¥a1_00a.gpc")
               (image-mem 1 0)
               (nop@)
               (set-reg 548 #t)
               (image-file "gpc¥a1_00bg.gpc")
               (image-mem 1 0)
               (proc 12))
              (//
               (proc 0)
               (image-file "gpc¥a1_00bg.gpc")
               (image-mem 1 0)
               (proc 12))))
         (proc 10)
         (nop@)
         (set-reg 547 #t)
         (proc 14)
         (str "Ah...... Aaagh!")
         (wait)
         (text-reset 14)
         (proc 13)
         (str "Now that's what I like to hear. It's no fun otherwise.")
         (wait)
         (text-reset 14)
         (proc 14)
         (str "B-blood............")
         (wait)
         (text-reset 14)
         (proc 13)
         (str "A former Special Forces soldier, shocked at the sight of" 'br)
         (str "blood? Or is it different when it's your own?")
         (wait)
         (text-reset 14))
        (/
         (proc 10)
         (proc 13)
         (str "Keep screaming for me, it only makes me want to hit harder!")
         (wait)
         (text-reset 14))))
      (proc 11))
 (seg (? (= Y 2) (= S 1) (<= H 3))
      (proc 10)
      (branch-index (</>
                     (/
                      (proc 13)
                      (str "This whip is made from carefully tanned, oil-soaked" 'br)
                      (str "leather. It cuts sharper than any razor.")
                      (wait)
                      (text-reset 14)
                      (proc 14)
                      (str "Y-you think that scares me? I'm not afraid of you at all.....")
                      (wait)
                      (text-reset 14)
                      (proc 13)
                      (str "Funny, your voice seems to be shaking though.")
                      (wait)
                      (text-reset 14)
                      (proc 14)
                      (str "..................")
                      (wait)
                      (text-reset 14)
                      (proc 13)
                      (str "I'd hate for you to give in this early. We're just getting" 'br)
                      (str "to the good part.")
                      (wait)
                      (text-reset 14)
                      (proc 14)
                      (str "You sadist...... You're a maniac!")
                      (wait)
                      (text-reset 14))
                     (/
                      (proc 13)
                      (str "You really get my blood pumping, you know that?")
                      (wait)
                      (text-reset 14))))
      (proc 11))
 (seg (? (= Y 2) (= S 1) (<= H 6))
      (proc 10)
      (branch-index (</>
                     (/
                      (proc 14)
                      (str "Ugh.........")
                      (wait)
                      (text-reset 14)
                      (proc 13)
                      (str "I'm not done with you yet, but I'll ask anyway.")
                      (wait)
                      (text-reset 14)
                      (proc 13)
                      (str "Where are the rest of your accomplices hiding? Where did" 'br)
                      (str "you stash the stolen classified materials?")
                      (wait)
                      (text-reset 14)
                      (proc 14)
                      (str "I-I have no idea what you're talking about......")
                      (wait)
                      (text-reset 14)
                      (proc 13)
                      (str "That's more like it. I was hoping you'd say that.")
                      (wait)
                      (text-reset 14))
                     (/
                      (proc 14)
                      (str "I-I won't say a word...... Not ever!")
                      (wait)
                      (text-reset 14))))
      (proc 11))
 (seg (? (= Y 2) (= S 1) (>= H 7))
      (proc 10)
      (proc 13)
      (str "Ready to talk yet?")
      (proc 18)
      (proc 14)
      (str "Peh! Not a chance.")
      (proc 18)
      (proc 13)
      (str "Stupid woman...... The sooner you talk, the less you'll" 'br)
      (str "have to suffer. Though I'd hate to lose my fun.")
      (proc 18)
      (proc 14)
      (str "..................")
      (proc 18)
      (proc 13)
      (str "I'm glad you're such a stubborn fool.")
      (proc 18)
      (proc 14)
      (str "W-wait......")
      (proc 18)
      (proc 13)
      (str "First, I need to get those clothes off. The whip loses its" 'br)
      (str "bite through fabric, and that outfit is an eyesore.")
      (proc 18)
      (proc 14)
      (str "Kuh...... How much more of this until you're satisfied!")
      (proc 18)
      (proc 13)
      (str "Who knows? That's entirely up to you. Believe it or not," 'br)
      (str "I'm a gentle woman at heart.")
      (proc 18)
      (text-delay 0)
      (str "「Kiyomi」" 'br)
      (text-delay 3)
      (str "I never lay a hand on girls who behave......")
      (proc 18)
      (proc 11)
      (exec-mem 18688 3)
      (exec-mem 18688 5 1 0)
      (exec-mem 3072 0)
      (mes-jump "mes¥MD_A02.MES"))
 (seg (? (= S 2) (= Y 2))
      (sound 'se 1)
      (branch-reg 541
       (</>
        (/
         (nop@)
         (inc-var H 1)
         (if (</>
              (//
               (? (>= H 5) (= 548 #f))
               (proc 0)
               (image-file "gpc¥a1_00a.gpc")
               (image-mem 1 0)
               (nop@)
               (set-reg 548 #t)
               (image-file "gpc¥a1_00ba.gpc")
               (image-mem 1 0)
               (proc 12))
              (//
               (proc 0)
               (image-file "gpc¥a1_00ba.gpc")
               (image-mem 1 0)
               (proc 12))))
         (proc 10)
         (nop@)
         (set-reg 541 #t)
         (set-reg 548 #f)
         (proc 14)
         (str "Hih.........")
         (wait)
         (text-reset 14)
         (proc 13)
         (str "Careful there, that almost hit your face.")
         (wait)
         (text-reset 14)
         (proc 14)
         (str "..................")
         (wait)
         (text-reset 14)
         (proc 13)
         (str "Watch yourself. You wouldn't want that pretty face scarred," 'br)
         (str "would you?")
         (wait)
         (text-reset 14))
        (/
         (proc 0)
         (image-file "gpc¥a1_00ba.gpc")
         (image-mem 1 0)
         (proc 12)
         (proc 10)
         (proc 14)
         (str "P-please, spare my face......")
         (wait)
         (text-reset 14)
         (nop@)
         (set-reg 548 #f))))
      (proc 11))
 (seg (? (= Y 2) (= S 3))
      (sound 'se 1)
      (branch-reg 542
       (</>
        (/
         (nop@)
         (inc-var H 1)
         (if (</>
              (//
               (? (>= H 3) (= 548 #f))
               (proc 0)
               (image-file "gpc¥a1_00a.gpc")
               (image-mem 1 0)
               (nop@)
               (set-reg 548 #t)
               (image-file "gpc¥a1_00bb.gpc")
               (image-mem 1 0)
               (proc 12))
              (//
               (proc 0)
               (image-file "gpc¥a1_00bb.gpc")
               (image-mem 1 0)
               (proc 12))))
         (proc 10)
         (proc 14)
         (str "Kuh! T-that didn't hurt at all......")
         (wait)
         (text-reset 14)
         (proc 13)
         (str "If you want, I can make it hurt more.")
         (wait)
         (text-reset 14)
         (proc 14)
         (str "N-no, that's alright............")
         (wait)
         (text-reset 14)
         (nop@)
         (set-reg 542 #t))
        (/
         (proc 10)
         (proc 14)
         (str "Nnh............")
         (wait)
         (text-reset 14))))
      (proc 11))
 (seg (? (= Y 2) (= S 4))
      (sound 'se 1)
      (branch-reg 543
       (</>
        (/
         (nop@)
         (inc-var H 1)
         (if (</>
              (//
               (? (>= H 3) (= 548 #f))
               (proc 0)
               (image-file "gpc¥a1_00a.gpc")
               (image-mem 1 0)
               (nop@)
               (set-reg 548 #t)
               (image-file "gpc¥a1_00bc.gpc")
               (image-mem 1 0)
               (proc 12))
              (//
               (proc 0)
               (image-file "gpc¥a1_00bc.gpc")
               (image-mem 1 0)
               (proc 12))))
         (proc 10)
         (proc 14)
         (str "Kuhh............")
         (wait)
         (text-reset 14)
         (proc 13)
         (str "Still putting on a brave face, are you?")
         (wait)
         (text-reset 14)
         (proc 14)
         (str "D-don't hold back. Go ahead, give me your worst............")
         (wait)
         (text-reset 14)
         (nop@)
         (set-reg 543 #t))
        (/
         (proc 10)
         (proc 14)
         (str "Augh......")
         (wait)
         (text-reset 14))))
      (proc 11))
 (seg (? (= S 5) (= Y 2))
      (sound 'se 1)
      (branch-reg 544
       (</>
        (/
         (nop@)
         (inc-var H 1)
         (if (</>
              (//
               (? (>= H 3) (= 548 #f))
               (proc 0)
               (image-file "gpc¥a1_00a.gpc")
               (image-mem 1 0)
               (nop@)
               (set-reg 548 #t)
               (image-file "gpc¥a1_00bd.gpc")
               (image-mem 1 0)
               (proc 12))
              (//
               (proc 0)
               (image-file "gpc¥a1_00bd.gpc")
               (image-mem 1 0)
               (proc 12))))
         (proc 10)
         (proc 14)
         (str "Ugh...... T-that's nothing, you hear me!")
         (wait)
         (text-reset 14)
         (proc 13)
         (str "Such a tough act. I wonder how long you can keep it up.")
         (wait)
         (text-reset 14)
         (proc 14)
         (str "I'll never give in to the likes of you......")
         (wait)
         (text-reset 14)
         (nop@)
         (set-reg 544 #t))
        (/
         (proc 10)
         (proc 14)
         (str "I-it doesn't hurt at all......")
         (wait)
         (text-reset 14))))
      (proc 11))
 (seg (? (= S 6) (= Y 2))
      (sound 'se 1)
      (branch-reg 545
       (</>
        (/
         (nop@)
         (inc-var H 1)
         (if (</>
              (//
               (? (>= H 3) (= 548 #f))
               (proc 0)
               (image-file "gpc¥a1_00a.gpc")
               (image-mem 1 0)
               (nop@)
               (set-reg 548 #t)
               (image-file "gpc¥a1_00be.gpc")
               (image-mem 1 0)
               (proc 12))
              (//
               (proc 0)
               (image-file "gpc¥a1_00be.gpc")
               (image-mem 1 0)
               (proc 12))))
         (proc 10)
         (nop@)
         (set-reg 545 #t)
         (proc 13)
         (str "Tch, doesn't do much through the clothes............")
         (wait)
         (text-reset 14)
         (proc 14)
         (str "It doesn't matter what you do, I'll never talk!")
         (wait)
         (text-reset 14)
         (proc 13)
         (str "Hah, I can't wait to see how long that stubbornness" 'br)
         (str "holds up......")
         (wait)
         (text-reset 14)
         (nop@)
         (set-reg 545 #t))
        (/
         (proc 10)
         (proc 14)
         (str "Ah............")
         (wait)
         (text-reset 14))))
      (proc 11))
 (seg (? (= S 7) (= Y 2))
      (sound 'se 1)
      (branch-reg 546
       (</>
        (/
         (nop@)
         (inc-var H 1)
         (if (</>
              (//
               (? (>= H 3) (= 548 #f))
               (proc 0)
               (image-file "gpc¥a1_00a.gpc")
               (image-mem 1 0)
               (nop@)
               (set-reg 548 #t)
               (image-file "gpc¥a1_00bf.gpc")
               (image-mem 1 0)
               (proc 12))
              (//
               (proc 0)
               (image-file "gpc¥a1_00bf.gpc")
               (image-mem 1 0)
               (proc 12))))
         (proc 10)
         (proc 14)
         (str "Kyah!")
         (wait)
         (text-reset 14)
         (proc 13)
         (str "What a cute little yelp. Hard to believe you were Special" 'br)
         (str "Forces once.")
         (wait)
         (text-reset 14)
         (proc 14)
         (str "Mind your own business...... I'm not some exhibitionist" 'br)
         (str "like you!")
         (wait)
         (text-reset 14)
         (nop@)
         (set-reg 546 #t))
        (/
         (proc 10)
         (proc 13)
         (str "Maybe I should just rip all your clothes off and get it" 'br)
         (str "over with!")
         (wait)
         (text-reset 14))))
      (proc 11))
 (seg (? (= S 8) (= Y 2))
      (sound 'se 1)
      (branch-reg 547
       (</>
        (/
         (nop@)
         (inc-var H 1)
         (if (</>
              (//
               (? (>= H 3) (= 548 #f))
               (proc 0)
               (image-file "gpc¥a1_00bg.gpc")
               (image-mem 1 0)
               (image-file "gpc¥a1_00a.gpc")
               (image-mem 1 0)
               (nop@)
               (set-reg 548 #t)
               (proc 12))
              (//
               (proc 0)
               (image-file "gpc¥a1_00bg.gpc")
               (image-mem 1 0)
               (proc 12))))
         (proc 10)
         (proc 13)
         (str "What a sound...... I can hear the whip tearing into your" 'br)
         (str "skin!")
         (wait)
         (text-reset 14)
         (proc 14)
         (str "Y-you're insane...... What do you even enjoy about this?")
         (wait)
         (text-reset 14)
         (proc 13)
         (str "Scream louder. Come on...... Louder!")
         (wait)
         (text-reset 14)
         (nop@)
         (set-reg 547 #t))
        (/
         (proc 10)
         (proc 14)
         (str "Ah...... Augh!")
         (wait)
         (text-reset 14))))
      (proc 11))
 (seg*))
