(mes
 (meta (engine 'ADV) (charset "pc98") (extraop #t))
 (seg*
  (proc 5)
  (proc 10)
  (proc 14)
  (text "ううぅぅッ！　うう、うぐッ‥‥‥")
  (wait)
  (text-reset 14)
  (proc 13)
  (text "なに、バイブなんか嫌いだって？")
  (wait)
  (text-reset 14)
  (proc 14)
  (text "うう。ううッ、ふぅッ！")
  (wait)
  (text-reset 14)
  (proc 13)
  (text "贅沢な子猫ちゃんだね。でも、そう言うだろうと思って、もっといい物を用意してあるんだ。うれしいだろう？")
  (wait)
  (text-reset 14)
  (proc 11)
  (exec-mem 3072 0)
  (image-file "gpc¥a1_11a2.gpc")
  (image-mem 1 0)
  (proc 12)
  (proc 10)
  (proc 14)
  (text "うぅッ‥‥‥‥‥‥")
  (wait)
  (text-reset 14)
  (proc 13)
  (text "そんなにがっつくんじゃないよ、いくら可愛いペットだからって、行儀が悪いのは許せないね。")
  (wait)
  (text-reset 14)
  (proc 14)
  (text "うぐッ‥‥‥‥‥‥‥‥‥")
  (wait)
  (text-reset 14)
  (proc 13)
  (text "よしよし、いい子だ。それじゃわたしのプレゼントをあげようか。あんまり焦らしても何だしね。")
  (wait)
  (text-reset 14)
  (proc 13)
  (text "おい、出といで！")
  (wait)
  (text-reset 14)
  (proc 11)
  (exec-mem 3072 0)
  (image-file "gpc¥a1_11a1.gpc")
  (image-mem 1 0)
  (proc 12)
  (proc 10)
  (text "「Vagrant」" 'br)
  (str "Heh heh... much obliged.")
  (wait)
  (text-reset 14)
  (proc 14)
  (text "ううッ、ううぅぅぅッ！")
  (wait)
  (text-reset 14)
  (proc 13)
  (text "この間約束した、おいしい目ってのにあわせてやるよ。")
  (wait)
  (text-reset 14)
  (text "「Vagrant」" 'br)
  (str "Yeah, thanks. So what're you gonna do for me?")
  (wait)
  (text-reset 14)
  (proc 13)
  (text "目の前にあるだろう。その子猫ちゃんを好きにしていいって言ってるんだ。")
  (wait)
  (text-reset 14)
  (text "「Vagrant」" 'br)
  (str "For real? That sounds like a dream!")
  (wait)
  (text-reset 14)
  (proc 13)
  (text "最後に＊＊＊したのはいつだ？　もうビンビンになっちまってる" 'br)
  (text "じゃないか。")
  (wait)
  (text-reset 14)
  (text "「Vagrant」" 'br)
  (str "Heh heh heh... yeah. After seeing you like that, no way I could've held back.")
  (wait)
  (text-reset 14)
  (proc 13)
  (text "それじゃ好きにしな。あんまり焦らしてやるんじゃないよ。見ろ、子猫ちゃんが＊＊＊びちゃびちゃにして待ってるだろ。")
  (wait)
  (text-reset 14)
  (proc 14)
  (text "んんッ！　んん‥‥‥ううぅッ！")
  (wait)
  (text-reset 14)
  (proc 13)
  (text "この牝猫に、お前の汚い物を一発ご馳走してやんな！")
  (wait)
  (text-reset 14)
  (proc 11)
  (exec-mem 3072 0)
  (image-file "gpc¥a1_11b.gpc")
  (image-mem 0 3)
  (proc 12)
  (proc 10)
  (proc 14)
  (text "うぐッ、んふッ‥‥‥")
  (wait)
  (text-reset 14)
  (text "「Vagrant」" 'br)
  (str "D-damn... this *** is amazing. Super tight!")
  (wait)
  (text-reset 14)
  (proc 13)
  (text "そうかい、子猫ちゃんもお気に召したみたいだよ。")
  (wait)
  (text-reset 14)
  (proc 14)
  (text "ううぅぅ‥‥‥‥‥‥")
  (wait)
  (text-reset 14)
  (text "「Vagrant」" 'br)
  (str "Heh heh... little lady, feelin' good?")
  (wait)
  (text-reset 14)
  (proc 14)
  (text "んぐッ、んんッ‥‥‥ううぅぅッ！")
  (wait)
  (text-reset 14)
  (text "「Vagrant」" 'br)
  (str "Oh! Don't move so damn much. I'm about to come. Let's make the most of this.")
  (wait)
  (text-reset 14)
  (proc 13)
  (text "だらしのない男だね。その子を失望させるんじゃないよ。")
  (wait)
  (text-reset 14)
  (text "「Vagrant」" 'br)
  (str "Y-yeah, I get it... but damn, you've got some very sweet stuff!")
  (wait)
  (text-reset 14)
  (text "「Vagrant」" 'br)
  (str "And these boobs... amazing. I've never come across a woman this fine!")
  (wait)
  (text-reset 14)
  (proc 14)
  (text "ふぅッ、ふぅぅぅッ‥‥‥")
  (wait)
  (text-reset 14)
  (proc 13)
  (text "おい牝猫。わたしの話を聞いてるか？　わたしに逆らうとどんな目にあうかよくわかったろう。")
  (wait)
  (text-reset 14)
  (text "「Vagrant」" 'br)
  (str Heh... super tight, and it feels damn good. You like my dick that much?")
  (wait)
  (text-reset 14)
  (text "「Vagrant」" 'br)
  (str "All slippery and clingy... Sis, looks like this girl was starving for it!")
  (wait)
  (text-reset 14)
  (proc 14)
  (text "んふっ、んッ‥‥‥んんッ、ふぅぅぅッ！")
  (wait)
  (text-reset 14)
  (proc 13)
  (text "なんて姿だ。薄汚い下衆野郎のチ○ポを咥えて、ヒイヒイ言ってる自分をよく見てみろ。")
  (wait)
  (text-reset 14)
  (proc 13)
  (text "もしもこれ以上わたしに逆らうなら、もっと酷い目にあわせるぞ。最低の淫売にしてやってもいいんだ。聞いてるか？")
  (wait)
  (text-reset 14)
  (proc 14)
  (text "ううっ‥‥‥うう、んんんッ！")
  (wait)
  (text-reset 14)
  (proc 13)
  (text "臭いチ○ポに貫かれて、＊＊＊から汚い汁をたれ流す。そんな辛" 'br)
  (text "い目には、もう遭いたくないだろう？")
  (wait)
  (text-reset 14)
  (text "「Vagrant」" 'br)
  (str "Oh... oh man, it's like my dick is getting crushed in a clamp!")
  (wait)
  (text-reset 14)
  (text "「Vagrant」" 'br)
  (str "Ah man, one round ain't enough. With a *** like this, I could keep going all night...")
  (str "I want to keep at it...")
  (wait)
  (text-reset 14)
  (proc 14)
  (text "んふっ、ううッ‥‥‥ふぅぅぅン！")
  (wait)
  (text-reset 14)
  (proc 13)
  (text "お前さえいい子でいるなら、すぐに楽にしてやるんだ。")
  (wait)
  (text-reset 14)
  (proc 14)
  (text "ふぅぅんッ、ふぅぅッ‥‥‥ふぅぅぅッ‥‥‥")
  (wait)
  (text-reset 14)
  (text "「Vagrant」" 'br)
  (str "Oh man! Ah... I'm gonna cum!")
  (wait)
  (text-reset 14)
  (proc 13)
  (text "レイファ、牝猫。約束だぞ。この悪夢から覚めたら、お前は従順なペットになるんだ。わたしの可愛い牝猫になるんだ！")
  (wait)
  (text-reset 14)
  (proc 14)
  (text "ふッ、ふぅぅぅぅぅぅン！")
  (wait)
  (text-reset 14)
  (exec-mem 3072 0)
  ((cmd 209) 0 5)
  (text-frame 0 0 79 399)
  (text-reset 14)
  ((cmd 209) 1 0)
  (text-frame 10 312 70 380)
  (proc 12)
  (proc 10)
  (text "「Vagrant」" 'br)
  (str "Heh heh... Sis, that was one hell of an experience.")
  (wait)
  (text-reset 14)
  (proc 13)
  (text "もうお前に用はないよ。さっさと帰りな。")
  (wait)
  (text-reset 14)
  (text "「Vagrant」" 'br)
  (str "Man... that *** was the best...")
  (wait)
  (text-reset 14)
  (proc 13)
  (text "こんな事は二度とない。さっさと帰ってマスでもかいてな。")
  (wait)
  (text-reset 14)
  (text "「Vagrant」" 'br)
  (str "Hey, don't be so harsh. If I'm getting treats like this, I'll do anything for you, Sis.")
  (wait)
  (text-reset 14)
  (proc 13)
  (text "お前に用がある時はこちらから連絡する。さあ、帰れ！")
  (wait)
  (text-reset 14)
  (proc 13)
  (text "レイファ、目が覚めたら全部吐いてもらうよ。その時までに牝猫らしい態度を身につけときな。")
  (wait)
  (text-reset 14)
  (proc 11)
  (exec-mem 18688 3)
  (exec-mem 18688 5 1 0)
  (exec-mem 3072 0)
  (mes-jump "mes¥MD_B03.MES")))