; X-Girl - Cyberpunk Adventure (PC-98) - OP_02.MES
; Translation by Fuzion
; Script Editing by Tan2000
; Content Revision by OldCorpo
; --Description:--
; Opening introduction (Part 2).
(mes
 (meta (engine 'ADV) (charset "pc98") (extraop #t))
 (seg*
  ((cmd 209) 0 0)
  (image-file "gpc¥op_04.gpc")
  (image-mem 0 3)
  (text-frame 10 312 70 393)
  ((cmd 209) 1 0)
  (text-delay 5)
  (str "We were headed to the intelligence office in Akasaka. The" 'br)
  (str "uniformed man had been quiet since we got on the AV, his" 'br)
  (str "body buried in the synthetic leather seat.")
  (wait)
  (text-reset 14)
  (text-delay 5)
  (str "From way up here, the streets and neon lights" 'br)
  (str "look just like the wiring on a circuitboard.")
  (wait)
  (text-reset 14)
  (text-delay 5)
  (str "It's so tacky, like a cheap trinket an artist threw" 'br)
  (str "together in his spare time.")
  (wait)
  (text-reset 14)
  (text-delay 5)
  (str "This place is the Japanese Empire's new capital. Apparently," 'br)
  (str "it used to be just a huge bomb shelter when the war started.")
  (wait)
  (text-reset 14)
  (text-delay 5)
  (str "It turned into a major city after it became" 'br)
  (str "too dangerous to stay aboveground.")
  (wait)
  (text-reset 14)
  (text-delay 5)
  (str "The city was built so quickly and recklessly that it ended up")
  (str "becoming a strange, complex place unlike anywhere else" 'br)
  (str "in the world.")
  (wait)
  (text-reset 14)
  (text-delay 0)
  (str "「Pilot」" 'br)
  (text-delay 5)
  (str "Rough air ahead. ")
  (str "Buckle up.")
  (wait)
  (text-reset 14)
  (text-delay 5)
  (str "The irregular vibration of the helicopter jars my head" 'br)
  (str "and makes me feel sick. It certainly doesn't help that my" 'br)
  (str "balance is already dulled from the purple rock.")
  (wait)
  (text-reset 14)
  (text-delay 5)
  (str "It's nauseating......")
  (wait)
  (text-reset 14)
  (text-delay 5)
  (str "It would be a lot easier if I could just fall asleep," 'br)
  (str "but my brain keeps buzzing with stupid fantasies.")
  (wait)
  (text-reset 14)
  (text-delay 5)
  (str "Is this what it's like to look out on cyberspace?" 'br)
  (str "I have no idea, as a low-tech person.")
  (wait)
  (text-reset 14)
  (text-delay 5)
  (str "But I don't want to see that world. As far as I'm concerned," 'br)
  (str "the only \"reality\" is the one in front of me." 'br)
  (str "Everything else may as well be a mirage." 'br)
  (wait)
  (text-reset 14)
  (text-delay 5)
  (str "Even so, I feel cold......")
  (wait)
  (text-reset 14)
  (text-delay 5)
  (str "The power that's supposed to be heating this city has been" 'br)
  (str "getting diverted somewhere else by the military." 'br)
  (delay 50)
  (str "Maybe our country is on its last legs after all.")
  (wait)
  (text-reset 14)
  (text-delay 5)
  (str "Is it time to start making my exit strategy?")
  (wait)
  (text-reset 14)
  (text-delay 0)
  ((cmd 209) 0 5)
  (text-frame 0 0 79 399)
  (text-reset 14)
  (image-file "gpc¥op_05.gpc")
  (image-mem 0 3)
  ((cmd 209) 1 5)
  (text-frame 10 312 70 393)
  (str "「Kiyomi」" 'br)
  (text-delay 5)
  (str "Though, where would I even go from here?")
  (text-delay 0)
  (wait)
  (text-reset 14)
  (str "「Uniformed Man」" 'br)
  (text-delay 5)
  (str "To Colonel Anna's office.")
  (text-delay 0)
  (wait)
  (text-reset 14)
  (str "「Uniformed Man」" 'br)
  (text-delay 5)
  (str "Hurry up! You've already kept her waiting for far too long.")
  (text-delay 0)
  (wait)
  (text-reset 14)
  (str "「Kiyomi」" 'br)
  (text-delay 5)
  (str "What, so you're saying Anna was the fool who called me here?")
  (wait)
  (text-reset 14)
  ((cmd 209) 0 0)
  (image-file "gpc¥op_06.gpc")
  (image-mem 0 3)
  ((cmd 209) 1 0)
  (text-delay 0)
  (str "「Kiyomi」" 'br)
  (text-delay 5)
  (str "You should've told me earlier......")
  (wait)
  (text-reset 14)
  (text-delay 0)
  (str "「Kiyomi」" 'br)
  (text-delay 5)
  (str "Anna, huh......")
  (wait)
  (text-reset 14)
  (text-delay 0)
  (str "「Kiyomi」" 'br)
  (text-delay 5)
  (str "That woman gives out the worst missions......")
  (wait)
  (text-reset 14)
  ((cmd 209) 0 0)
  (text-frame 0 0 79 399)
  (text-reset 14)
  (image-file "gpc¥op_07u.gpc")
  (image-mem 0 3)
  (exec-mem 256 "I")
  (exec-mem 256 "A 1")
  (text-reset 14)
  (text-frame 10 312 70 393)
  (image-file "gpc¥op_07d.gpc")
  (image-mem 0 3)
  (exec-mem 256 "A 0")
  ((cmd 209) 1 0)
  (load-mem "tcm¥scrh.tcm" 7072)
  (exec-mem 7072 12 16 68 287 0 1 16 17)
  (load-mem "tcm¥palch.tcm" 7072)
  (load-mem "tcm¥gpcpalch.tcm" 7936)
  (load-mem "tcm¥mbuff.tcm" 9504)
  (text-delay 0)
  (str "「Anna」" 'br)
  (text-delay 5)
  (str "Kiyomi")
  (text-delay 15)
  (str "... ")
  (text-delay 5)
  (str "You are VERY late.")
  (wait)
  (text-reset 14)
  (text-delay 0)
  (str "「Kiyomi」" 'br)
  (text-delay 5)
  (str "For your information, I was on vacation when you called me.")
  (wait)
  (text-reset 14)
  (text-delay 0)
  (str "「Anna」" 'br)
  (text-delay 5)
  (str "But you weren't doing anything productive, right?")
  (wait)
  (text-reset 14)
  (text-delay 0)
  (str "「Anna」" 'br)
  (text-delay 5)
  (str "You reek of purple rock. Personally, I won't just stand by" 'br)
  (str "and let my agents become junkies.")
  (wait)
  (text-reset 14)
  (text-delay 0)
  (str "「Kiyomi」" 'br)
  (text-delay 5)
  (str "Work is work. Play is play." 'br)
  (str "Don't interfere with what I do in my free time." 'br)
  (wait)
  (text-reset 14)
  (text-delay 0)
  (str "「Kiyomi」" 'br)
  (text-delay 5)
  (str "You're not my mother, Anna. So don't act like it.")
  (wait)
  (text-reset 14)
  (text-delay 0)
  (str "「Anna」" 'br)
  (text-delay 5)
  (str "..................")
  (wait)
  (text-reset 14)
  (text-delay 0)
  (str "「Kiyomi」" 'br)
  (text-delay 5)
  (str "Let's get down to business and discuss the mission. That's" 'br)
  (str "what you called me here for, right?")
  (wait)
  (text-reset 14)
  (text-delay 0)
  (str "「Anna」" 'br)
  (text-delay 5)
  (str "Right. 4 high-security prisoners have escaped and stolen" 'br)
  (str "confidential intel. Your mission is to capture" 'br)
  (str "the prisoners and retrieve the intelligence.")
  (wait)
  (text-reset 14)
  (str "It looks like she aged 10 years since the last time" 'br)
  (str "I saw her. She never was very energetic, but this is" 'br)
  (str "a new low.")
  (wait)
  (text-reset 14)
  (str "Anna is my boss and current master." 'br)
  (str "Or mistress, I suppose.")
  (wait)
  (text-reset 14)
  (str "I've heard rumours that she's a White Russian and former" 'br)
  (str "KGB officer. Did she flee her country after the war started?")
  (wait)
  (text-reset 14)
  (str "She never talks about her past, but if those rumours are" 'br)
  (str "true")
  (text-delay 7)
  (str "...... ")
  (text-delay 5)
  (str "she'd have to be at least 20 years older" 'br)
  (str "than she looks to make the math add up.")
  (wait)
  (text-reset 14)
  (str "But in this city, appearances are often deceiving.")
  (wait)
  (text-reset 14)
  (str "These days, organs and skin can be replaced with" 'br)
  (str "cybernetic substitutes by any backstreet circuit-splicer.")
  (wait)
  (text-reset 14)
  (text-delay 0)
  (str "「Anna」" 'br)
  (text-delay 5)
  (str "Of the 4 prisoners, 2 are ex-special forces." 'br)
  (str "Real killers.")
  (wait)
  (text-reset 14)
  (text-delay 0)
  (str "「Anna」" 'br)
  (text-delay 5)
  (str "One is a former soldier, and the last was a secretary" 'br)
  (str "to a high-ranking government official.")
  (wait)
  (text-reset 14)
  (text-delay 0)
  (str "「Kiyomi」" 'br)
  (text-delay 5)
  (str "...and you want me to find them?")
  (wait)
  (text-reset 14)
  (text-delay 0)
  (str "「Anna」" 'br)
  (text-delay 5)
  (str "They aren't a simple target. I'll need your" 'br)
  (str "professional tracking skills.")
  (wait)
  (text-reset 14)
  (exec-mem 256 "E")
  (exec-mem 9504 "I")
  (exec-mem 9504 "M M128")
  (exec-mem 9504 "L gpc¥op_08.gpc,KEEP")
  (exec-mem 9504 "L gpc¥op_09.gpc,KEEP")
  (exec-mem 9504 "L gpc¥op_10.gpc,KEEP")
  ((cmd 209) 0 0)
  (exec-mem 9504 "C gpc¥op_10.gpc,GPC")
  (image-mem 0 3)
  ((cmd 209) 1 0)
  (text-delay 0)
  (str "「Kiyomi」" 'br)
  (text-delay 5)
  (str "Hold on a minute. I haven't even accepted the mission yet.")
  (wait)
  (text-reset 14)
  (text-delay 0)
  (str "「Kiyomi」" 'br)
  (text-delay 5)
  (str "Besides, catching criminals is *definitely* not part of" 'br)
  (str "my job. You know that.")
  (wait)
  (text-reset 14)
  (text-delay 0)
  (str "「Anna」" 'br)
  (text-delay 5)
  (str "......This mission is completely secret. There cannot be" 'br)
  (str "any official investigation or tribunal.")
  (wait)
  (text-reset 14)
  (text-delay 0)
  (str "「Kiyomi」" 'br)
  (text-delay 5)
  (str "I understand, it sounds like a pretty dire situation." 'br)
  (str "But that's your problem, not mine.")
  (wait)
  (text-reset 14)
  (text-delay 0)
  (str "「Anna」" 'br)
  (text-delay 5)
  (str "Kiyomi, this is an opportunity to do your favorite torture.")
  (wait)
  (text-reset 14)
  (text-delay 0)
  (str "「Kiyomi」" 'br)
  (text-delay 5)
  (str "In your dreams! I won't agree just for that.")
  (wait)
  (text-reset 14)
  (text-delay 0)
  (str "「Anna」" 'br)
  (text-delay 10)
  (str "............")
  (text-delay 5)
  (str "Don't say that.")
  (wait)
  (text-reset 14)
  (text-delay 0)
  (str "「Kiyomi」" 'br)
  (text-delay 5)
  (str "Wait... Could I be the only agent you have?")
  (wait)
  (text-reset 14)
  (text-delay 0)
  (str "「Anna」" 'br)
  (text-delay 5)
  (str "Irrelevant! Circumstances are what they are.")
  (wait)
  (text-reset 14)
  (text-delay 0)
  (str "「Kiyomi」" 'br)
  (text-delay 5)
  (str "All the more reason it's not my job. Rat hunting" 'br)
  (str "isn't my specialty.")
  (wait)
  (text-reset 14)
  ((cmd 209) 0 0)
  (exec-mem 9504 "C gpc¥op_08.gpc,GPC")
  (image-mem 0 3)
  ((cmd 209) 1 0)
  (text-delay 0)
  (str "「Anna」" 'br)
  (text-delay 5)
  (str "Kiyomi, I don't know who else I can trust for this")
  (text-delay 10)
  (str "...........")
  (wait)
  (text-reset 14)
  (text-delay 0)
  (str "「Anna」" 'br)
  (text-delay 5)
  (str "In the first place, isn't it quite odd that the prisoners" 'br)
  (str "were able to escape?")
  (wait)
  (text-reset 14)
  (text-delay 0)
  (str "「Kiyomi」" 'br)
  (text-delay 5)
  (str "Crazy things and \"miracles\" that happen in this world" 'br)
  (str "don't surprise me anymore.")
  (wait)
  (text-reset 14)
  (text-delay 0)
  (str "「Anna」" 'br)
  (text-delay 5)
  (str "Our experts think there was a mole. The security hole" 'br)
  (str "has not been closed yet.")
  (wait)
  (text-reset 14)
  (text-delay 0)
  (str "「Kiyomi」" 'br)
  (text-delay 5)
  (str "Sorry to hear that. But it's really not my problem.")
  (wait)
  (text-reset 14)
  (text-delay 0)
  (str "「Anna」" 'br)
  (text-delay 15)
  (str "..................")
  (wait)
  (text-reset 14)
  (text-delay 0)
  (str "「Kiyomi」" 'br)
  (text-delay 5)
  (str "Don't look at me like that. There are plenty of other people" 'br)
  (str "working for your boss whose job is to sniff people's butts!")
  (wait)
  (text-reset 14)
  (text-delay 0)
  (str "「Anna」" 'br)
  (text-delay 5)
  (str "Kiyomi!")
  (wait)
  (text-reset 14)
  (text-delay 0)
  (str "「???」" 'br)
  (text-delay 5)
  (str "How much longer will you spout this nonsense?")
  (wait)
  (text-reset 14)
  ((cmd 209) 0 0)
  (exec-mem 9504 "C gpc¥op_09.gpc,GPC")
  (image-mem 0 3)
  ((cmd 209) 1 0)
  (text-delay 0)
  (str "「Kiyomi」" 'br)
  (text-delay 5)
  (str "..................")
  (wait)
  (text-reset 14)
  (text-delay 0)
  (str "「Military Officer」" 'br)
  (text-delay 5)
  (str "You're not a special agent nor an important contractor." 'br)
  (str "You're just another member of the intelligence division," 'br)
  (str "nothing more.")
  (wait)
  (text-reset 14)
  (text-delay 0)
  (str "「Military Officer」" 'br)
  (text-delay 5)
  (str "You don't have the option to refuse this mission." 'br)
  (str "Is that clear?")
  (wait)
  (text-reset 14)
  (str "This asshole's name is Katou. He's a big shot in the" 'br)
  (str "military and an internal affairs inspector for" 'br)
  (str "the government.")
  (wait)
  (text-reset 14)
  (str "He's a real lowlife... the kind who sniffs other" 'br)
  (str "people's butts.")
  (wait)
  (text-reset 14)
  (str "Unlike Anna, an immigrant, or me, a dropout," 'br)
  (str "he's a proper elite.")
  (wait)
  (text-reset 14)
  (str "However, Katou and I share some qualities. Those sadistic" 'br)
  (str "eyes that sometimes shine out from under his hat remind me" 'br)
  (str "of my own.")
  (wait)
  (text-reset 14)
  (str "Plus, Katou has also avoided getting neuro-mods."'br)
  (str "But I don't think his reasons are the same as mine......")
  (wait)
  (text-reset 14)
  (text-delay 0)
  (str "「Katou」" 'br)
  (text-delay 5)
  (str "Generally, people aren't allowed to be an intelligence" 'br)
  (str "officer specializing in torture. The military doesn't" 'br)
  (str "pay you to satisfy your own desires.")
  (wait)
  (text-reset 14)
  (text-delay 0)
  (str "「Kiyomi」" 'br)
  (text-delay 5)
  (str "Well, I happen to have quite the reputation for my technique" 'br)
  (str "in that field, thank you very much.")
  (wait)
  (text-reset 14)
  (text-delay 0)
  (str "「Anna」" 'br)
  (text-delay 5)
  (str "Kiyomi! Just shut up and listen.")
  (wait)
  (text-reset 14)
  (text-delay 0)
  (str "「Katou」" 'br)
  (text-delay 5)
  (str "The prisoners' names are April, Lei-Fa, Nana, and Mitsuko.")
  (wait)
  (text-reset 14)
  (text-delay 0)
  (str "「Katou」" 'br)
  (text-delay 5)
  (str "April was a former Special Forces member and" 'br)
  (str "European immigrant. Lei-Fa was also in the same unit," 'br)
  (str "and she's Chinese.")
  (wait)
  (text-reset 14)
  (text-delay 0)
  (str "「Katou」" 'br)
  (text-delay 5)
  (str "Nana is half-Japanese and used to be a soldier" 'br)
  (str "in cyberwarfare. She was a great hacker.")
  (wait)
  (text-reset 14)
  (text-delay 0)
  (str "「Katou」" 'br)
  (text-delay 5)
  (str "The last one is Mitsuko...... she's pure Japanese.")
  (wait)
  (text-reset 14)
  (text-delay 0)
  (str "「Kiyomi」" 'br)
  (text-delay 5)
  (str "Hold on")
  (text-delay 15)
  (str "...")
  (text-delay 5)
  (str " that's all you've got?")
  (wait)
  (text-reset 14)
  (text-delay 0)
  (str "「Katou」" 'br)
  (text-delay 5)
  (str "..................")
  (wait)
  (text-reset 14)
  (text-delay 0)
  (str "「Kiyomi」" 'br)
  (text-delay 5)
  (str "Not even a profile or holopic I can study?")
  (wait)
  (text-reset 14)
  ((cmd 209) 0 0)
  (exec-mem 9504 "C gpc¥op_08.gpc,GPC")
  (image-mem 0 3)
  ((cmd 209) 1 0)
  (text-delay 0)
  (str "「Anna」" 'br)
  (text-delay 5)
  (str "It's all gone...... Someone has erased all" 'br)
  (str "the relevant information.")
  (wait)
  (text-reset 14)
  (text-delay 0)
  (str "「Kiyomi」" 'br)
  (text-delay 15)
  (str "...")
  (text-delay 5)
  (str "you're kidding, right?" 'br)
  (str "How could you allow a breach like that?")
  (wait)
  (text-reset 14)
  (text-delay 0)
  (str "「Anna」" 'br)
  (text-delay 5)
  (str "We believe it was Nana's doing. Not many hackers could" 'br)
  (str "break into a secure military server.")
  (wait)
  (text-reset 14)
  (str "This is just another downside of war. Now we have disgraced" 'br)
  (str "\"former experts\" scattered all over the city.")
  (wait)
  (text-reset 14)
  (str "The situation itself is hard enough to deal with, but what I" 'br)
  (str "can't wrap my head around is the fact that our military" 'br)
  (str "database was penetrated by a single hacker." 'br)
  (str "It just doesn't make sense.")
  (wait)
  (text-reset 14)
  (str "That's unbelievable. Even someone low-tech like me" 'br)
  (str "can understand how valuable that woman is.")
  (wait)
  (text-reset 14)
  (text-delay 0)
  (str "「Kiyomi」" 'br)
  (text-delay 5)
  (str "So, how do you expect me to hunt them down without" 'br)
  (str "even having a picture of a face?")
  (wait)
  (text-reset 14)
  (text-delay 0)
  (str "「Anna」" 'br)
  (text-delay 10)
  (str "........................")
  (wait)
  (text-reset 14)
  (text-delay 0)
  (str "「Kiyomi」" 'br)
  (text-delay 5)
  (str "Don't give me that face, you won't fool me again. I refuse" 'br)
  (str "to accept this mission!")
  (wait)
  (text-reset 14)
  (text-delay 0)
  (str "「Anna」" 'br)
  (text-delay 10)
  (str "....................................")
  (wait)
  (text-reset 14)
  (text-delay 0)
  (str "「Kiyomi」" 'br)
  (text-delay 5)
  (str "Anna, you're always mixing people up in dangerous situations.")
  (str "Don't you feel guilty?" 'br)
  (str "No way am I letting you get me wrapped up in this.")
  (wait)
  (text-reset 14)
  ((cmd 209) 0 0)
  (exec-mem 9504 "C gpc¥op_09.gpc,GPC")
  (image-mem 0 3)
  ((cmd 209) 1 0)
  (text-delay 0)
  (str "「Katou」" 'br)
  (text-delay 5)
  (str "I told you, this is an order.")
  (wait)
  (text-reset 14)
  (text-delay 0)
  (str "「Kiyomi」" 'br)
  (text-delay 5)
  (str "You can't even trust your own people, so don't act" 'br)
  (str "all high and mighty!")
  (wait)
  (text-reset 14)
  (text-delay 0)
  (str "「Kiyomi」" 'br)
  (text-delay 5)
  (str "This is ridiculous")
  (text-delay 15)
  (str "... ")
  (text-delay 5)
  (str "I don't owe you anything. There's no" 'br)
  (str "reason I should be here wiping your asses for you.")
  (wait)
  (text-reset 14)
  (text-delay 0)
  (str "「Katou」" 'br)
  (text-delay 5)
  (str "Your complaints will be recorded and sent to the higher-ups.")
  (wait)
  (text-reset 14)
  (text-delay 0)
  (str "「Kiyomi」" 'br)
  (text-delay 5)
  (str "Great! I'm not scared of them!" 'br)
  (str "Besides, this city has HUNDREDS of places those prisoners" 'br)
  (str "could be hiding!")
  (wait)
  (text-reset 14)
  (text-delay 0)
  (str "「Kiyomi」" 'br)
  (text-delay 5)
  (str "If they decided to hide out in Chinatown or Chiba City," 'br)
  (str "there's no chance we'd ever find them.")
  (wait)
  (text-reset 14)
  (text-delay 0)
  (str "「Katou」" 'br)
  (text-delay 5)
  (str "We WILL find and recapture them. If you fail, it won't just" 'br)
  (str "be your ass on the line, but the Colonel's as well.")
  (wait)
  (text-reset 14)
  (text-delay 0)
  (str "「Kiyomi」" 'br)
  (text-delay 5)
  (str ".........If it comes to that, I'll happily take you" 'br)
  (str "down with me.")
  (wait)
  (text-reset 14)
  (text-delay 0)
  (str "「Anna」" 'br)
  (text-delay 5)
  (str "Kiyomi, please...... Commander Katou, please let me" 'br)
  (str "handle this. We'll come up with a solution.")
  (wait)
  (text-reset 14)
  (text-delay 0)
  (str "「Katou」" 'br)
  (text-delay 10)
  (str "............Good.")
  (wait)
  (text-reset 14)
  (text-delay 0)
  (str "「Katou」" 'br)
  (text-delay 5)
  (str "This mission is completely confidential. You will report" 'br)
  (str "either to me or Colonel Anna. Get to work immediately.")
  (wait)
  (text-reset 14)
  (text-delay 0)
  (str "「Kiyomi」" 'br)
  (text-delay 5)
  (str "........................")
  (wait)
  (text-reset 14)
  ((cmd 209) 0 0)
  (exec-mem 9504 "C gpc¥op_10.gpc,GPC")
  (image-mem 0 3)
  ((cmd 209) 1 0)
  (str "This is ridiculous. It's like trying to catch a cloud." 'br)
  (str "What do they expect me to do?")
  (wait)
  (text-reset 14)
  (text-delay 0)
  (str "「Anna」" 'br)
  (text-delay 5)
  (str "Kiyomi, come see me in my room later.")
  (wait)
  (text-reset 14)
  (text-delay 0)
  (str "「Kiyomi」" 'br)
  (text-delay 5)
  (str "............")
  (wait)
  (text-reset 14)
  (text-delay 0)
  (str "「Anna」" 'br)
  (text-delay 5)
  (str "Kiyomi.")
  (wait)
  (text-reset 14)
  (text-delay 0)
  (str "「Kiyomi」" 'br)
  (text-delay 5)
  (str "Understood, ma'am.")
  (wait)
  (text-reset 14)
  (nop@)
  (set-reg 50 #t)
  (exec-mem 9504 "E")
  (exec-mem 256 "E")
  (exec-mem 256 "I")
  ((cmd 209) 0 10)
  (text-frame 0 0 79 399)
  (text-reset 14)
  (image-file "gpc¥98title.gpc")
  (image-mem 0 3)
  ((cmd 209) 1 10)
  (delay 200)
  (sound 'se 1)
  (nop@)
  (set-reg 1000 #t)
  (flag-save 9)
  (delay 20 0)
  (sound '|| 2)
  (delay 50 0)
  ; If this condition met:
  ; First time playing (L = 0) - After Opening scene finished, go to Kiyomi's room
  ; Else (L = 1) - After Opening scene finished, back to Main Menu
  (if (</>
       (// (? (= L 1)) (sound '|| 0) (mes-jump "mes¥x_menu.mes"))
       (//
        ((cmd 209) 0 5)
        (image-file "gpc¥waku.gpc")
        (image-mem 0 3)
        ((cmd 209) 1 5)
        (sound '|| 0)
        (mes-jump "mes¥MA_A01.MES"))))))
