; X-Girl - Cyberpunk Adventure (PC-98) - OP_01.MES
; Translation by Fuzion
; Script Editing by Tan2000
; Content Revision by OldCorpo
; --Description:--
; Opening introduction (Part 1).
(mes
 (meta (engine 'ADV) (charset "pc98") (extraop #t))
 (seg*
  (sound '|| 0)
  (text-frame 0 0 79 399)
  (text-reset 14)
  (text-color 15)
  (text-frame 0 150 79 399)
  ((cmd 209) 1 5)
  (str "                         It all started 20 years ago.")
  (delay 50)
  ((cmd 209) 0 5)
  (image-file "gpc¥op_01.gpc")
  (image-mem 0 3)
  (if (</>
       (//
        (? (= O 0))
        (sound '|| 0)
        (sound '|| "uso¥xg_01.uso")
        (sound '|| 1)
        (nop@)
        (set-var P 1))
       (//
        (? (= O 1))
        (sound '|| 0)
        (sound '|| "uso¥xg_01v.uso")
        (sound '|| 1)
        (nop@)
        (set-var P 1))))
  (text-frame 10 312 70 383)
  ((cmd 209) 1 5)
  (text-delay 5)
  (str " At that time, I was still a child")
  (text-delay 0)
  (str ",")
  (text-delay 5)
  (str " and knew nothing about")
  (text-delay 0)
  (text 'br)
  (str "       ")
  (text-delay 5)
  (str "the world-changing events happening around me")
  (text-delay 0)
  (str ".")
  (delay 50)
  (text-reset 14)
  (str "             ")
  (text-delay 5)
  (str "It was the start of a long winter")
  (text-delay 0)
  (str ".")
  (delay 50)
  (text-reset 14)
  (str "            ")
  (text-delay 5)
  (str "And now, it's hard to even remember")
  (text-delay 0)
  (text 'br)
  (str "      ")
  (text-delay 5)
  (str "what it was like to look up and see sunlight...")
  (delay 50)
  (text-reset 14)
  (str "             ")
  (text-delay 5)
  ; ref: 123456789012345678901234567890|234567890123456789012345678901, not centred oops
  (str "I only remember the anxious faces")
  (text-delay 0)
  (text 'br)
  (str "               ")
  (text-delay 5)
  (str "of my mom, dad, and neighbors")
  (text-delay 0)
  (str ".")
  (delay 50)
  (text-reset 14)
  (str "          ")
  (text-delay 5)
  (str "After that, more dead animals and birds" 'br)
  (text-delay 0)
  (str "    ")
  (text-delay 5)
  (str "began appearing on the side of the road each day...")
  (delay 50)
  (text-reset 14)
  (str "      ")
  (text-delay 5)
  (str "I didn't understand how these friendly creatures" 'br)
  (text-delay 0)
  (str "                 ")
  (text-delay 5)
  (str "could all die so suddenly")
  (text-delay 0)
  (str ".")
  (delay 50)
  (text-reset 14)
  (str "               ")
  (text-delay 5)
  (str "When I asked my mom, she said" 'br)
  (text-delay 0)
  (str "     ")
  (text-delay 5)
  (str "it must be caused by the poison from our enemies")
  (text-delay 0)
  (str ".")
  (delay 50)
  (text-reset 14)
  (str "  ")
  (text-delay 5)
  (str "I didn't understand what she meant until 10 years later")
  (text-delay 0)
  (str ".")
  (delay 50)
  (text-reset 14)
  (str "          ")
  (text-delay 5)
  (str "Even now, I'm not sure why it happened")
  (text-delay 0)
  (str ".")
  (delay 50)
  (text-reset 14)
  (str "                   ")
  (text-delay 5)
  (str "But Japan declared war" 'br)
  (text-delay 0)
  (str "        ")
  (text-delay 5)
  (str "on the USA, Britain, and other major powers")
  (text-delay 0)
  (str ".")
  (delay 50)
  (text-reset 14)
  (str "   ")
  (text-delay 5)
  (str "It seems like Japan is doing quite well in maintaining" 'br)
  (text-delay 0)
  (str "           ")
  (text-delay 5)
  (str "a battlefront that spans the world...")
  (text-delay 0)
  (delay 50)
  (text-reset 14)
  (str "          ")
  (text-delay 5)
  (str "However, we've had to pay a steep price")
  (text-delay 0)
  (str ".")
  (delay 50)
  (text-reset 14)
  (str "            ")
  (text-delay 5)
  (str "To avoid the constant air raids and")
  (text-delay 0)
  (text 'br)
  (str "  ")
  (text-delay 5)
  (str "deadly germ warfare, people had to evacuate the surface")
  (text-delay 0)
  (text 'br)
  (str "              ")
  (text-delay 5)
  (str "and flee to underground cities")
  (text-delay 0)
  (str ".")
  (delay 50)
  (text-reset 14)
  (str "          ")
  (text-delay 5)
  (str "People can't leave this \"giant eggshell\"")
  (text-delay 0)
  (text 'br)
  (str "               ")
  (text-delay 5)
  (str "that has been built around us")
  (text-delay 0)
  (str ".")
  (delay 50)
  (text-reset 14)
  (str "     ")
  (text-delay 5)
  (str "Therefore, it's rare to find someone who has seen")
  (text-delay 0)
  (text 'br)
  (str "          ")
  (text-delay 5)
  (str "the outside world, regardless of whether")
  (text-delay 0)
  (text 'br)
  (str "           ")
  (text-delay 5)
  (str "they're immigrants or native Japanese")
  (text-delay 0)
  (str ".")
  (delay 50)
  (text-reset 14)
  (str "        ")
  (text-delay 5)
  (str "We will have to continue gazing at this sky")
  (text-delay 0)
  (text 'br)
  (str "    ")
  (text-delay 5)
  (str "made of concrete and chrome for a long time to come")
  (text-delay 0)
  (str ".")
  (delay 50)
  (text-reset 14)
  (str " ")
  (text-delay 5)
  (str "Vapor from the earth's crust forms a mist that covers the")
  (text-delay 0)
  (text 'br)
  (str " ")
  (text-delay 5)
  (str "area and occasionally rains down on the underground city")
  (text-delay 0)
  (str "." 'br)
  (str "        ")
  (text-delay 5)
  (str "But the rain just smells like mud and metal")
  (text-delay 0)
  (str ".")
  (delay 50)
  (text-reset 14)
  (str "     ")
  (text-delay 5)
  (str "The stagnant air crackles with static electricity")
  (text-delay 0)
  (str "." 'br)
  (str "              ")
  (text-delay 5)
  (str "Is this what thunder felt like")
  (text-delay 0)
  (str "?" 'br)
  (str "                    ")
  (text-delay 5)
  (str "I can only imagine")
  (text-delay 0)
  (str ".")
  (delay 50)
  (text-reset 14)
  (str "          ")
  (text-delay 5)
  (str "How can I explain this craving I have...")
  (text-delay 0)
  (delay 50)
  (text-reset 14)
  (str "                    ")
  (text-delay 5)
  (str "Sometimes, I dream")
  (text-delay 0)
  (str "." 'br)
  (str "           ")
  (delay 50)
  (text-delay 5)
  (str "I dream about the feeling of sunlight")
  (text-delay 0)
  (text 'br)
  (str "              ")
  (text-delay 5)
  (str "locked away in my dim memories")
  (text-delay 0)
  (str ".")
  (delay 50)
  (text-reset 14)
  ((cmd 209) 0 5)
  (text-reset 14)
  (image-file "gpc¥op_06.gpc")
  (image-mem 0 3)
  ((cmd 209) 1 5)
  (text-frame 10 312 70 393)
  (text-delay 5)
  (str "My name is Kiyomi")
  (text-delay 0)
  (str ",")
  (text-delay 5)
  (str " and I am a military intelligence officer")
  (text-delay 0)
  (str "." 'br)
  (text-delay 5)
  (str "I'm one of the sharpest people in Tokyo")
  (text-delay 0)
  (str "," 'br)
  (text-delay 5)
  (str "a city full of eccentrics")
  (text-delay 0)
  (str ".")
  (wait)
  (text-reset 14)
  (text-delay 5)
  (str "Once upon a time, my career and position")
  (text-delay 0)
  (text 'br)
  (text-delay 5)
  (str "in the intelligence sector meant everything to me")
  (text-delay 0)
  (str ".")
  (wait)
  (text-reset 14)
  (text-delay 5)
  (str "I had ambition and enthusiasm every day")
  (text-delay 0)
  (str "." 'br)
  (text-delay 5)
  (str "But now, things are different")
  (text-delay 0)
  (str ".")
  (wait)
  (text-reset 14)
  (text-delay 5)
  (str "I'm so sick and tired of the military")
  (text-delay 0)
  (str ".")
  (text-delay 5)
  (str " They walk around with" 'br)
  (str "disgustingly fake smiles on their faces and try to flaunt" 'br)
  (str "their power, even though they're just minor officers")
  (text-delay 0)
  (str ".")
  (wait)
  (text-reset 14)
  (text-delay 5)
  (str "I was not going to let myself turn into one of those" 'br)
  (str "uniformed bastards")
  (text-delay 0)
  (str ".")
  (wait)
  (text-reset 14)
  (text-delay 5)
  (str "When I looked in the mirror and saw that same twisted smile," 'br)
  (str "I made up my mind to leave the army")
  (text-delay 0)
  (str ".")
  (wait)
  (text-reset 14)
  (text-delay 5)
  (str "But they wouldn't let someone talented like me go" 'br)
  (str "so easily...")
  (wait)
  (text-reset 14)
  (text-delay 5)
  (str "The society we live in is terribly small")
  (text-delay 0)
  (str ".")
  (text-delay 5)
  (str " The military and a" 'br)
  (str "few large corporations rule this country now")
  (text-delay 0)
  (str ".")
  (text-delay 5)
  (str " You'd have to" 'br)
  (str "be some type of nutcase to go against them")
  (text-delay 0)
  (str ".")
  (wait)
  (text-reset 14)
  (text-delay 5)
  (str "The only reason I'm even still allowed to live is" 'br)
  (str "because I'm a pure-blooded Japanese citizen")
  (text-delay 0)
  (str ".")
  (wait)
  (text-reset 14)
  (text-delay 5)
  (str "Immigrants, who make up 30\n of this city's population")
  (text-delay 0)
  (str "," 'br)
  (text-delay 5)
  (str "are treated like trash down here")
  (text-delay 0)
  (str "." 'br)
  (text 'br)
  (text-delay 5)
  (str "Above all else, it's important to be born Japanese")
  (text-delay 0)
  (str ".")
  (wait)
  (text-reset 14)
  (text-delay 5)
  (str "This stratified society will never change")
  (text-delay 0)
  (str ",")
  (text-delay 5)
  (str " and the lowest" 'br)
  (str "immigrant will never become more than \"just an immigrant\"" 'br)
  (str "in their whole life")
  (text-delay 0)
  (str ". ")
  (text-delay 5)
  (str "Plus, it's impossible to leave the city")
  (text-delay 0)
  (str ".")
  (wait)
  (text-reset 14)
  (text-delay 5)
  (str "It's no wonder the city is falling apart...")
  (text-delay 0)
  (wait)
  (text-reset 14)
  (text-delay 5)
  (str "If I were an immigrant, I would have been killed long ago")
  (text-delay 0)
  (str "," 'br)
  (text-delay 5)
  (str "deprived of both my credit and military status")
  (text-delay 0)
  (str "." 'br)
  (text-delay 5)
  (str "Honestly, maybe I would be happier that way")
  (text-delay 0)
  (str ".")
  (wait)
  (text-reset 14)
  (text-delay 5)
  (str "I would rather slowly kill my brain cells in a cloud" 'br)
  (str "of purple smoke than face such a painful reality")
  (text-delay 0)
  (str ".")
  (wait)
  (text-reset 14)
  (image-file "gpc¥op_02.gpc")
  (image-mem 0 3)
  (str "「Girl」" 'br)
  (text-delay 5)
  (str "Ma'am...")
  (text-delay 0)
  (wait)
  (text-reset 14)
  (str "「Girl」" 'br)
  (text-delay 5)
  (str "Hey, ma'am")
  (text-delay 0)
  (str "!!!")
  (wait)
  (text-reset 14)
  (str "「Girl」" 'br)
  (text-delay 5)
  (str "If you smoke that much at once, you'll die, okay")
  (text-delay 0)
  (str "?")
  (wait)
  (text-reset 14)
  (str "「Kiyomi」" 'br)
  (text-delay 5)
  (str "Leave me alone")
  (text-delay 0)
  (str ".")
  (text-delay 5)
  (str " You're ruining my vibe")
  (text-delay 0)
  (str ".")
  (wait)
  (text-reset 14)
  (str "「Girl」" 'br)
  (text-delay 5)
  (str "But I...")
  (text-delay 0)
  (wait)
  (text-reset 14)
  (str "「Kiyomi」" 'br)
  (text-delay 5)
  (str "Quiet")
  (text-delay 0)
  (str ".")
  (text-delay 5)
  (str " Pillows aren't supposed to talk")
  (text-delay 0)
  (str ".")
  (wait)
  (text-reset 14)
  (str "「Kiyomi」" 'br)
  (text-delay 5)
  (str "I was so close to becoming the champion of chemicals, too...")
  (text-delay 0)
  (wait)
  (text-reset 14)
  (str "「???」" 'br)
  (text-delay 5)
  (str "I'm afraid your title match will have" 'br)
  (str "to wait until later")
  (text-delay 0)
  (str ".")
  (wait)
  (text-reset 14)
  ((cmd 209) 0 0)
  (image-file "gpc¥op_03.gpc")
  (image-mem 0 3)
  ((cmd 209) 1 0)
  (str "「Uniformed Man」" 'br)
  (text-delay 5)
  (str "We're here to pick you up")
  (text-delay 0)
  (str ",")
  (text-delay 5)
  (str " Major")
  (text-delay 0)
  (str ".")
  (wait)
  (text-reset 14)
  (str "「Kiyomi」" 'br)
  (text-delay 5)
  (str "Hey")
  (text-delay 0)
  (str ",")
  (text-delay 5)
  (str " public servant")
  (text-delay 0)
  (str ".")
  (text-delay 5)
  (str " Been busy serving the people")
  (text-delay 0)
  (str "?")
  (wait)
  (text-reset 14)
  ;; ALL GOOD ABOVE THIS LINE
  (text-delay 5)
  (str "I recognise this guy")
  (text-delay 0)
  (str ".")
  (text-delay 5)
  (str " He's a leg-breaker who specialises in" 'br)
  (str "underground work (= illegal)")
  (text-delay 0)
  (str ",")
  (text-delay 5)
  (str " and he's one of the best guys" 'br)
  (str "in the department")
  (text-delay 0)
  (str ".")
  (wait)
  (text-reset 14)
  (text-delay 5)
  (str "What division was he in, again?......" 'br)
  (str "I know I looked at his profile, but I can't" 'br)
  (str "remember a thing right now")
  (text-delay 0)
  (str ".")
  (wait)
  (text-reset 14)
  (str "「Kiyomi」" 'br)
  (text-delay 5)
  (str "I'm on vacation right now... get lost")
  (text-delay 0)
  (str ".")
  (wait)
  (text-reset 14)
  (str "「Uniformed Man」" 'br)
  (text-delay 5)
  (str "I regret to inform you that your vacation has been cancelled")
  (text-delay 0)
  (str ".")
  (text-delay 5)
  (str "Your mission will begin shortly")
  (text-delay 0)
  (str ".")
  (wait)
  (text-reset 14)
  (str "「Kiyomi」" 'br)
  (text-delay 5)
  (str "You're being so selfish...")
  (text-delay 0)
  (wait)
  (text-reset 14)
  (str "「Uniformed Man」" 'br)
  (text-delay 5)
  (str "Now")
  (text-delay 0)
  (str ",")
  (text-delay 5)
  (str " get rid of that pipe")
  (text-delay 0)
  (str "!")
  (text-delay 5)
  (str " We need a clear" 'br)
  (str "headed agent")
  (text-delay 0)
  (str ",")
  (text-delay 5)
  (str " not some drugged-up idiot")
  (text-delay 0)
  (str "!")
  (wait)
  (text-reset 14)
  (str "「Kiyomi」" 'br)
  (text-delay 5)
  (str "Hm")
  (text-delay 0)
  (str ",")
  (text-delay 5)
  (str " what's the difference between this and your cyber socket")
  (text-delay 0)
  (str "?")
  (text-delay 5)
  (str "Drugs are the only stimulation I'm willing to give" 'br)
  (str "to my bare brain")
  (text-delay 0)
  (str ".")
  (wait)
  (text-reset 14)
  (str "「Uniformed Man」" 'br)
  (text-delay 5)
  (str "......fine")
  (text-delay 0)
  (str ".")
  (text-delay 5)
  (str " It's your funeral")
  (text-delay 0)
  (str ".")
  (wait)
  (text-reset 14)
  (str "「Kiyomi」" 'br)
  (text-delay 5)
  (str "Better to fry my brain than yours")
  (text-delay 0)
  (str "!")
  (text-delay 5)
  (str " Even if it kills me")
  (text-delay 0)
  (str "," 'br)
  (text-delay 5)
  (str "at least I get to choose how I go out")
  (text-delay 0)
  (str ".")
  (wait)
  (text-reset 14)
  (str "「Uniformed Man」" 'br)
  (text-delay 5)
  (str "......It's time to go")
  (text-delay 0)
  (str ".")
  (wait)
  (text-reset 14)
  (str "「Kiyomi」" 'br)
  (text-delay 5)
  (str "You're a nasty son of a bitch")
  (text-delay 0)
  (str ".")
  (text-delay 5)
  (str " I told you I'm not going")
  (text-delay 0)
  (str ".")
  (wait)
  (text-reset 14)
  (str "「Uniformed Man」" 'br)
  (text-delay 5)
  (str "I really hate playing dirty like this, but if you" 'br)
  (str "keep refusing...... I'll have to report it as a failure" 'br)
  (str "to obey orders.")
  (text-delay 0)
  (wait)
  (text-reset 14)
  (str "「Kiyomi」" 'br)
  (text-delay 5)
  (str "............")
  (text-delay 0)
  (wait)
  (text-reset 14)
  (str "「Uniformed Man」" 'br)
  (text-delay 5)
  (str "This is your third violation, isn't it? I read your profile")
  (text-delay 0)
  (str ".")
  (wait)
  (text-reset 14)
  (str "「Kiyomi」" 'br)
  (text-delay 5)
  (str "Are you telling me that I'll be sent to the Siberian front" 'br)
  (str "like you were")
  (text-delay 0)
  (str "?")
  (wait)
  (text-reset 14)
  (str "「Uniformed Man」" 'br)
  (text-delay 5)
  (str "Want me to take off my prosthetic leg and let you see the" 'br)
  (str "stump? Frostbite did this to me")
  (text-delay 0)
  (str ".")
  (wait)
  (text-reset 14)
  (str "「Kiyomi」" 'br)
  (text-delay 5)
  (str "Cut it out")
  (text-delay 0)
  (str ".")
  (text-delay 5)
  (str " I’m not interested in seeing your little trophy")
  (text-delay 0)
  (str ".")
  (wait)
  (text-reset 14)
  (str "「Uniformed Man」" 'br)
  (text-delay 5)
  (str "Otherwise...... if you'd prefer something more tropical, I" 'br)
  (str "can drop you in the \"no-man's land\" of the Arabian Desert")
  (text-delay 0)
  (str ".")
  (wait)
  (text-reset 14)
  (str "「Kiyomi」" 'br)
  (text-delay 5)
  (str "No way")
  (text-delay 0)
  (str "!")
  (text-delay 5)
  (str " I'd rather not be sun-dried OR frozen")
  (text-delay 0)
  (str "," 'br)
  (text-delay 5)
  (str "thank you very much")
  (text-delay 0)
  (str ".")
  (wait)
  (text-reset 14)
  (str "「Uniformed Man」" 'br)
  (text-delay 5)
  (str "Well then")
  (text-delay 0)
  (str ",")
  (text-delay 5)
  (str " let's get going")
  (text-delay 0)
  (str ".")
  (wait)
  (text-reset 14)
  (str "「Kiyomi」" 'br)
  (text-delay 5)
  (str "What a miserable world......" 'br)
  (str "I can't even take the time to enjoy myself")
  (text-delay 0)
  (str ".")
  (wait)
  (text-reset 14)
  (str "「Uniformed Man」" 'br)
  (text-delay 5)
  (str "I agree")
  (text-delay 0)
  (str ".")
  (wait)
  (text-reset 14)
  (mes-jump "mes¥OP_02.MES")))
